### ISSUE TITLE
Not found works page is returned if we click a Code List in Validation Draft Page

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1000]
The issue is that when we click on the Name of a Code List existing in the validation page when we create a draft release, a "Not found works" page is returned.

To reproduce the issue:
1. Create a Code List and move it in Candidate state.
2. Create a Release and click to create a Draft.
3. In the next page where the validation takes place, click on this code list which is in the left pane of the "Releases Assign" page.

At that point, a new tab is opened and a "Not found works" message is displayed.

**Comment by rekuku** [comment]
Now it fixed. 
Please test this @asdimitriadis.

**Comment by asdimitriadis** [comment]
It works good.
