### ISSUE TITLE
The Meaning, Definition and Definition source of an existing Code List Value from the previous revisions cannot be changed

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1001]
The issue is that we cannot change the ShortName, Definition and Definition source of an existing Code List Value from the previous revisions.

To reproduce the issue:
1. Login as a developer
2. Open the Code List "oacl_EngineeringWorkRequestStatusCode"
3. Create a revision
4. Open the code list value "inWork"
5. Try to change the ShortName, Definition and Definition Source fields.

They cannot be changed. 

The expected behavior is that we can change these field. Note that the ShortName field should not be left blank.

**Comment by asdimitriadis** [comment]
Note that the Short Name field has been changed to "Meaning".

In the UI there should be the following 2 changes:
1. In the dialog used for editing a code list value (done)
2. In the table where all the values are listed (**not done yet**)

Please see the attached screenshot

![changedshortname](https://user-images.githubusercontent.com/37205288/101072263-bdfa4380-356b-11eb-994f-967ad47387b4.png)

**Comment by hakjuoh** [comment]
@asdimitriadis `Definition` and `Definition Source` now can be edited when it is in WIP state in revision.

**Comment by kbserm** [comment]
Meaning should be editable too.

**Comment by rekuku** [comment]
Now amended code list value can change the Meaning
![Screen Shot 2020-12-07 at 7 00 34 PM](https://user-images.githubusercontent.com/10194354/101419730-9f26e480-38be-11eb-8df4-a63eabcf0bca.png)

**Comment by hakjuoh** [comment]
@rekuku I guess you forgot to commit it. @asdimitriadis It applied now.

**Comment by rekuku** [comment]
I forgot to commit. thank you @hakjuoh

**Comment by asdimitriadis** [comment]
It works fine.
