### ISSUE TITLE
Integrate the Commonly Used flag into the Type flag on BDT selection page of the BCCP creation

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1002]
related to #975

**Comment by hakjuoh** [comment]
@kbserm Can we close this issue since we have `Commonly Used` filter on BCCP creation page?

<img width="958" alt="Screen Shot 2022-07-28 at 11 19 27 AM" src="https://user-images.githubusercontent.com/16102116/181575209-3564eb3e-a7ed-4b34-94a2-bc62a817684c.png">

**Comment by kbserm** [comment]
Yes

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 28, 2022 at 11:20, Hakju ***@***.***> wrote:   


@kbserm Can we close this issue since we have Commonly Used filter on BCCP creation page?
