### ISSUE TITLE
Code List whose revision number is more than 1 in any state can be deleted

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1003]
The issue is that we can delete a Code List whose revision number is more than 1.

To reproduce the issue:
1. Open an existing Code List (e.g., oacl_UnitCode)
2. Create a new revision
3. Visit the Code List page (Core Component -> View/Edit Code List)
4. Open the menu with 3 dots ("more_vert" element) of the revised code list
5. Click the Delete option and confirm your intension

At this point you can see that the Code list was deleted.

The expected behavior is that we cannot delete a code list whose revision number is greater than 1. 

The same issue exists in end user code list. 
The issue is that we can delete an end user code list whose revision number is more than 1.
To reproduce the issue:
1. Log in as an end user
2. Create a code list and move it to production state
3. Amend the code list.
4. Visit the Code List page (Core Component -> View/Edit Code List)
5. Open the menu with 3 dots ("more_vert" element) of the amended code list
6. Click the Delete option and confirm your intension

At this point you can see that the Code list was deleted.

**Comment by rekuku** [comment]
Fixed. Please test this @asdimitriadis

**Comment by asdimitriadis** [comment]
It works good.
