### ISSUE TITLE
Disable the "Add" and "Save" buttons of the Context Scheme value add/edit dialog

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1004]
The issue/enhancement is that when we add a Context Scheme Value, the "Add" button of the dialog is not disabled if we leave the "Value" field blank. 
Although this does not lead to creating a context scheme value with empty value field, it would be better to disable this "Add" button (this will help me in testing as well). We also followed this approach in 1.x versions.

The same exists when we edit a context scheme value. If we clear the "value" field, the "Save" button remains enabled.

To reproduce this issue/enhancement:
1. Create a Context Scheme
2. Add a value
3. Leave the "value" field empty.
At this point the "Add" button is not disabled.
However, if you click it, no value added.

To reproduce the issue when editing a value:
1. Create a Context Scheme, add some values and save it.
2. Open the Context Scheme and click on a value so that you will edit it.
3. Clear the "value" field.
At this point the "Save" button is not disabled.
However, if you click it, nothing changed and the value is correct.

**Comment by rekuku** [comment]
<img width="452" alt="Screen Shot 2020-11-02 at 11 00 01 PM" src="https://user-images.githubusercontent.com/10194354/97948642-2f718700-1d5f-11eb-8a96-1a5116a7d593.png">

Fixed, Disable save button if the value of ContextSchemeValue is empty. @asdimitriadis

**Comment by asdimitriadis** [comment]
It works good. Thanks.
