### ISSUE TITLE
Change the confirmation button when we delete a code list for consistency reasons

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1005]
The issue is that not all confirmation dialogs used for deleting a code list are the same.
When we delete a code list all confirmation dialogs have the button "Delete anyway" except for the dialog appears when we click the Delete button existing in the Code List page. It has the value "Delete"

To reproduce the issue:
1. Create a code list
2. Visit the code list page
3. Check the corresponding checkbox of the code list created in Step#1
4. Click the Delete button which appears at the top right of the code list page

The confirmation dialog has the button "Delete". All other dialogs use the button "Delete anyway".

**Comment by rekuku** [comment]
Changed.
<img width="542" alt="Screen Shot 2020-11-02 at 11 08 58 PM" src="https://user-images.githubusercontent.com/10194354/97949071-7ca22880-1d60-11eb-8cb0-6f4f70e22205.png">

It is applied to Delete button on Code List detail. it also have "Delete" button

**Comment by asdimitriadis** [comment]
Tested. It is implemented.
