### ISSUE TITLE
fix display of the user extension group ACC 

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1009]
currently when open the UEGACC, the UI shows the tree of the underlying Extension Component and on the detail pane shows details of UEGACC and the underlying Extension ACC. This can be a bit confusing.

Change to simply show the UEGACC in the tree (no need to display the assoc of the Extension ACC), i.e., it will be empty the first the UEGACC is created. And the detail pane then just display the detail of the UEGACC.

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis Now UEGACC has dealt with the same way as the usual ACC. Please test it.

**Comment by asdimitriadis** [comment]
Fixed.
