### ISSUE TITLE
Requiring reuse BIE to be in published state to be reused makes profiling complex BIEs hard

### ISSUE THREAD

**Issue by joshklm** [OAGi/Score#1010]
The existing SCORE requirement, that the reuse BIE needs to be in Published (Released) state to be reused in another profiling, makes the process of profiling complex BIEs convoluted since the new reuse BIEs initially created for reuse might not be ready to be published until number of attempts of reusing them were done to prove the usability of the reuse BIE. 

With the existing SCORE requirement, there will be multiple reuse BIEs in Published state while progressing (for copying, editing, publishing), making it hard to the manage the extraneous reuse BIEs created as byproduct. 

It would be necessary to either 
1. allow reuse BIEs to be reusable when it's in Edit or Candidate state.
2. or allow published BIEs to have certain meta info editable, to mark them to be cleaned up later, and allow certain admin groups to be able to perform deletion. (This feature may be necessary regardless, so create a new issue?)

**Comment by kbserm** [comment]
To help with discussion, let's define the following terms. "Reused BIE" is the top-level BIE that is reused. "Reusing BIE" is the top-level BIE that uses the "Reused BIE". "Reusing BIE Node" is the BIE node within the "Reusing BIE" that uses the "Reused BIE".

@joshklm  **Here is a workaround idea for testing.**
1. In the reusing BIE, enable the reusing BIE Node, but not any other descendant node. Customize cardinality and context definition as needed.
2. Generate the schema of the reusing BIE.
3. Generate the schema of the reused BIE (if owned by a different user, the reused BIE should be in Candidate). Being in candidate, signify readiness for QA.
4. In a text or xml editor, replace the reusing BIE node in the generated schema of the reusing BIE with the generated schema of the reused BIE. The user can try to ensure that the cardinality and context definition specified in (1) are carried forward during editing.

**Discussion about the issue:**
@joshklm please comment to these thoughts.

If you want to allow a BIE to be reusable before published, should we need to block the reusing BIE from advancing its state further than that of the reused BIE? E.g., reusing BIE cannot be candidate b/f reused BIE is candidate. Or the restriction to be only specific to the published state, i.e., reusing BIE cannot be published b/f reused BIE is published? I guess the latter is better?

Keep in mind that if a schema is generated for a reusing BIE, it will take whatever content the reused BIE has at the time of the generation, part of which may be change while the reusing BIE is being generated, unless we implement a read lock. 

While viewing the reusing BIE, if the reused BIE updated, is content won't reflect in the reusing BIE automatically at this time, The user has to refresh the page.

By definition, BIE in editing means it is still a work-in-process, totally unstable. Normally, detail of editing BIE cannot be viewed or expressed by another user. Allowing BIE to be reused while in Editing state kinda violate this definition, although technically it is ok.

If we were to implement change, can this wait until post 2.0?

**Comment by joshklm** [comment]
@kbserm  If you want to allow a BIE to be reusable before published, should we need to block the reusing BIE from advancing its state further than that of the reused BIE? E.g., reusing BIE cannot be candidate b/f reused BIE is candidate. Or the restriction to be only specific to the published state, i.e., reusing BIE cannot be published b/f reused BIE is published? I guess the latter is better? <-- Yes.

**Comment by joshklm** [comment]
@kbserm Keep in mind that if a schema is generated for a reusing BIE, it will take whatever content the reused BIE has at the time of the generation, part of which may be change while the reusing BIE is being generated, unless we implement a read lock.

While viewing the reusing BIE, if the reused BIE updated, is content won't reflect in the reusing BIE automatically at this time, The user has to refresh the page. <-- These I understand. There might be something we can do to make this more obvious for others.

**Comment by joshklm** [comment]
@kbserm By definition, BIE in editing means it is still a work-in-process, totally unstable. Normally, detail of editing BIE cannot be viewed or expressed by another user. Allowing BIE to be reused while in Editing state kinda violate this definition, although technically it is ok. <-- This is somewhat related to the first part of your answer. If Reuse BIE is in Editing State, only the owner is able to reuse that BIE in another BIE. And if the reusing BIE is getting published, or moved to Candidate, the reuse BIE being used should also be published or moved to Candidate as well.

**Comment by joshklm** [comment]
@kbserm If we were to implement change, can this wait until post 2.0? <-- Agreed. This is good to have. But not worth delaying the whole 2.0 release.

**Comment by kbserm** [comment]
@joshklm if I understand you correctly, you mean we can put a constraint that BIE in editing state can only be reused by owner?

**Comment by joshklm** [comment]
@kbserm Yes. With additional constraints to ensure that
1. BIE in editing state that reuses other BIEs in editing state can't move out of the editing state.
2. BIE in editing state that reuses other BIEs in editing state can't have its ownership transferred. 

It would be nice to consider these more advanced option as well, so the new BIE being worked can be reviewed by other users.
3. BIE in editing state can move to Candidate state if all of its reuse BIEs being used inside are in Candidate state or in Published state.
4. a reuse BIE in Candidate state can't move back to Editing state if it's being reused by other BIEs in Candidate state.
5. a reuse BIE in Candidate state can't have its ownership transferred if it's being reused by other BIEs in Candidate or Editing state.

**Comment by kbserm** [comment]
@joshklm In the long run this issue should be addressed by more sophisticated user role. How about in the short term we let the BIE to be reused in any state? Below are some modifications and checking we needs to make to Score.

In Score, we would add the application logic to: 
1. BIE Discard, BIE cannot be discarded if there is a reference to it.
2. Advancing BIE state to Production needs to check that all reused BIEs are in Production.

We need to check to make sure that Express BIE has no issue. Normally, a user who is not the owner cannot express BIE he does not own when it is in WIP state. We have to check that this constraint does not prevent the user from expressing a reusing BIE he owns when it contains reused BIE that is still in WIP.

**Comment by joshklm** [comment]
@kbserm "How about in the short term we let the BIE to be reused in any state? Below are some modifications and checking we needs to make to Score." <-- Yes. This will be good. Agree with two additional logic for discard and advancing BIE states.
Multiple LM SCORE users are having quite amount of usability issues (aka. frustration) for needing to create a new copy from a published reuse BIE when there are minor changes needed in the reuse BIE. This also causes maintenance issues when the reused BIE being updated are already reused in multiple other higher level BIEs, where the higher level BIEs also should take the update from the reuse BIE. LM really hope to see this issue moving forward rather quickly.

**Comment by hakjuoh** [comment]
@asdimitriadis Please review the latest code about this issue. The following is a demo:

https://user-images.githubusercontent.com/16102116/118178237-b59f1200-b401-11eb-9b95-f121f2ed5579.mp4

**Comment by joshklm** [comment]
@kbserm I agree that BIE WIP restriction for non owner is kind of annoying. But not too bothering to have it as long as others are still able to use it as reuse BIE. But reuse BIE in WIP to be only allowed for owner alone should be also okay.

**Comment by kbserm** [comment]
Moving from QA back to WIP need to check for Reuse and block if there is any reuse.

When reusing BIE WIP wants to go to QA and there is a reused BIE, block to transition. 

Generally, the reusing BIE cannot be in more advance state than the reused BIE.

**Comment by kbserm** [comment]
Add a sentence in the error dialog, e.g., when discarding the BIE reused by another BIE, "See the Notification log for error details."

**Comment by asdimitriadis** [comment]
Everything works good.
