### ISSUE TITLE
Extension components may be created without a namespace

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1012]
Because an ACC is created initially w/o a namespace.  If the user invokes the Create OAGIS Extension before specifying a namespace and click Update, the extension ACC and ASCCP are created w/o a namespace, causing them to be invalid. The macro should check that it has all the information necessary to create valid extension components.

**Comment by rekuku** [comment]
![Screen Shot 2020-11-09 at 4 17 50 PM](https://user-images.githubusercontent.com/10194354/98597536-2cb6ea80-22a7-11eb-9d98-9813fe5113c2.png)

Now check the required informations when creating Extension component.
And it also applied to BOD, Verb creation.

**Comment by asdimitriadis** [comment]
Tested, it has been incorporated to test scrips and it works good.
