### ISSUE TITLE
Incorrect extension ASCCP generated from the Create OAGIS Extension

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1014]
The ASCCP should always have the property term "Extension", not "Xyz Extension".

This seems like a regression.

**Comment by kbserm** [comment]
sakis needs to also correct the test script.

**Comment by asdimitriadis** [comment]
Test script has been update to check that the ASCCP is in this format
"Extension. "+ACC.ObjectClassTerm+ " Extension" 

and not in this format
ACC.ObjectClassTerm+"Extension. "+ACC.ObjectClassTerm+ " Extension"

**Comment by kbserm** [comment]
This looks fine on the test instance.
