### ISSUE TITLE
Add the ability to find all ACCs that are based on a specified ACC

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1015]
This filter returns all ACCs that are based on a selected ACC, directly or indirectly.

For example A is based B is based on C is based D. If D is selected, A, B and C are all returned.

One idea is to make this function available on an ACC detail page in the context menu of ACC node that is open. The other idea is to make this function available the context menu of any ACC node in an ACC tree.

This can be used to find, for example, all Verbs, BODs, etc.

**Comment by hakjuoh** [comment]
@kbserm This ability may related with #820

**Comment by asdimitriadis** [comment]
This issue is related to issue #820 
It works well now. You can find the ACC which are based on a specific ACC by using the "Find Usages" function of the context menu of a CC node.
