### ISSUE TITLE
Transfer Ownership Bug with SSO Accounts

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1016]
Users with accounts that use the SSO login(Created via the SSO creation method and users transferred from basic login to SSO) receive an 500 error when attempting to transfer ownership of BIEs.  This error does not occur with Non-SSO accounts.  The transfer ownership menu does not have the prepopulated list of users and the following error immediately shows up:

Server Internal Error: Http failure response for url/api/accounts_list?sortActive=name&sortDirection=asc&pageIndex=0&pageSize=10&status=&excludeRequester=true: 500 OK

Non-SSO accounts can transfer to SSO accounts and Non-SSO accounts.

**Comment by hakjuoh** [comment]
@kbserm @michaelfigura To reproduce this problem, we need a test environment along with Ping Identity settings. Any idea?

**Comment by kbserm** [comment]
@hakjuoh perhaps this is just sql issue. Because the list of users is supposed to pulled up based on the same user role. And old sql before SSO needs to be updated.
