### ISSUE TITLE
Adding metaHeader to expression in JSON Schema is an array, not an object

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1017]
This is happening oagiscore.net.  OpenAPI expresses correctly.
Selected array option for Shipped Item Instance.

JSON Schema:
![image](https://user-images.githubusercontent.com/32434235/98996936-49e2f780-24f9-11eb-98e7-685e636294d9.png)

OpenAPI:
![image](https://user-images.githubusercontent.com/32434235/98997048-7bf45980-24f9-11eb-8d90-5ab912262eb2.png)

**Comment by kbserm** [comment]
@rekuku can you see whether this is an issue and if so see if you want to fix in 2.0. Seem like an easy fix.

**Comment by hakjuoh** [comment]
@kbserm @dubnemo It happened when `Make as an array` option selected. Now, it changed that 'Meta Header' and 'Pagination Response' would always be 'object' whether `Make as an array` option selected or not.

**Comment by asdimitriadis** [comment]
This works good according to the first comment of the issue (now the type is object instead of array).

**Comment by dubnemo** [comment]
This bug has come back in 2.0.0.1.


[Shipped-Item-Instance-oagis-id-5c26c5cf3ae34fdbb8956df23522383c.zip](https://github.com/OAGi/Score/files/6006268/Shipped-Item-Instance-oagis-id-5c26c5cf3ae34fdbb8956df23522383c.zip)

**Comment by rekuku** [comment]
![Screen Shot 2021-02-18 at 8 24 36 PM](https://user-images.githubusercontent.com/10194354/108443799-6c3a8e80-7227-11eb-8c21-c3297827b47b.png)
Perhaps there was a omission during fix.
Now 'Meta Header' and 'Pagination Response' always be "Object" regardless of 'Make as array'.
@asdimitriadis Can you check this one more time? @asdimitriadis
