### ISSUE TITLE
Cannot move BIE to QA state the first time that the "Reused BIE" function is used

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1020]
The issue is that we cannot move the BIE to the QA state **the first time** that we invoke the "Reuse BIE" function and enable the reused node.

To reproduce the issue:
1. Create the BIE "Document Identifier Set", make some changes and then move it to Production State.
2. Create the BIE "Document Reference", open it and expand the root node.
3. On the node "Document Identifier Set" invoke the BIE reuse function.
4. Select the BIE of the Step 1
5. Enable the node
6. Make some changes
7. Update the BIE and try to move the BIE to QA state. The "Move to QA" button is disabled. 

However, if you open the BIE again then everything works fine.

**Comment by rekuku** [comment]
It was a bug that occurred when there was a required item, such as Identifier Set > Identifier.
Now Fixed.
Please check this.

**Comment by asdimitriadis** [comment]
Tested and it works good.
