### ISSUE TITLE
A developer should not be able to reuse a BIE owned by an end user and vice versa

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1021]
The issue is that a developer can reuse a BIE owned by an end user and vice versa.

To reproduce the issue:
1. Login as an end user
2. Create a BIE using the ASCCP "Resource Codes" and move it to Production state
3. Login as a developer
4. Create a BIE using the ASCPP "Change Acknowledge Project Accounting"
5. Extend the BIE (/Change Acknowledge Project Accounting/Data Area/Project Accounting)
6. Reuse the BIE of the Step 2 on the node "Resource codes"

The expected behavior is that a developer can reuse a BIE owned by a developer only. I.e., developer cannot reuse end user BIE.

**Comment by asdimitriadis** [comment]
I would like to note that the **correct behavior is that:**

1. An End user can reuse a BIE owned by a developer or an end user.
2. A developer can reuse a BIE owned by a developer only not by an end user.

**Comment by rekuku** [comment]
Fixed please check this.

**Comment by asdimitriadis** [comment]
@rekuku it works good but now, an end user can reuse a BIE owned by an end user only.

However, an End user should be able to reuse a BIE owned by either a _developer_ **or** an _end user._

See my latest comment as well:
https://github.com/OAGi/Score/issues/1021#issuecomment-732160673

**Comment by rekuku** [comment]
@asdimitriadis It is fixed.
Developer user only reuse the developer's BIE.
End-user able to reuse the BIE of any role of user.
Please test this.

**Comment by asdimitriadis** [comment]
It works fine now.
