### ISSUE TITLE
BIE reused cannot be run again after removing the reused BIE

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1022]
The issue is that if we remove a reused BIE and then try to invoke the Reuse BIE function again on the same node, an error is returned.

To reproduce the issue:
1. Create the BIE "Document Identifier Set", make some changes and then move it to Production State.
2. Create the BIE "Document Reference", open it and expand the root node.
3. On the node "Document Identifier Set" invoke the BIE reuse function.
4. Select the BIE of the Step 1
5. Remove this reused BIE
6. Invoke the BIE reuse function **on the same node.**

An error is returned. However, if you refresh the browser everything is fine.

**Comment by rekuku** [comment]
Fixed.
Now it can reuse-unreuse continuously, please test this.

**Comment by asdimitriadis** [comment]
Tested and it works fine.
