### ISSUE TITLE
BIE node cannot be disabled after setting Min Cardinality to 0. The browser needs to be refreshed.

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1023]
The issue is that if we set the Min Cardinality of a BIE Node to 0, we cannot click the "Used" checkbox. However, if we refresh the browser or if we reopen the BIE again everything works fine.

To reproduce the issue:
1. Create a BIE and set the Min Cardinality of a node to a number greater than 0. (e.g., 19).
2. Update the BIE.
3. Open the BIE again.
4. Visit the node of the Step 1 and set its Min Cardinality back to 0. At this point, the Used checkbox remains disabled. 
Nevertheless, if you refresh the browser, the Used checkbox is ok and you can disable the node (i.e., you can uncheck the Used checkbox). 

The expected behavior is that if the Min Cardinality of a Node is set to 0 then we should be able to Enable/Disable the BIE node.

**Comment by kbserm** [comment]
this is so odd. I does not happen unless you go back to BIE list page first and reopen the BIE as Sakis said. 

I also got sever error a few times before it just magically disappeared. maybe bad internet on my phone

**Comment by rekuku** [comment]
At the first time if user just expand the tree, the used check box is able to change. but as Sakis said, when user click the detail, used check box of tree and detail going to disabled.
Now it is fixed.
Please check this. @asdimitriadis @kbserm
![Screen Shot 2020-11-23 at 7 58 20 PM](https://user-images.githubusercontent.com/10194354/100032545-43406400-2dc6-11eb-949d-9daee68c2dfa.png)

**Comment by asdimitriadis** [comment]
Tested and it works fine now.
