### ISSUE TITLE
Create pop up message warning of specific property conflicts when re-assigning Base ACC to another ACC

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1024]
Run into a conflict where a property (ASCCP, Classification) was defined on the ACC, and when I choose a different Base ACC that already had the same property, it was not added.   A message flashed but was not visible.  Ideally this would be a pop-up, citing the conflicting property that need to be removed.

Resources Base -> Resource Base was the example.

**Comment by dubnemo** [comment]
That should work!  Thanks.

**Comment by kbserm** [comment]
Is the warning a flash up message or a modal dialog? I think the latter is requested and better.

**Comment by dubnemo** [comment]
Modal dialog box, showing the conflicts.
