### ISSUE TITLE
Fix title of the release assignment page

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1026]
Currently it looks like this "Releases Assign 10.8". 

It is better for it to look like "10.8 Release Assignment".

**Comment by rekuku** [comment]
![Screen Shot 2020-11-23 at 8 00 53 PM](https://user-images.githubusercontent.com/10194354/100032716-9c0ffc80-2dc6-11eb-8fc7-d9bee9bd71ff.png)

Applied.

**Comment by asdimitriadis** [comment]
Tested. The title of the page has been changed according to the suggestion.

I am leaving the issue opened because it was created by @kbserm.
