### ISSUE TITLE
Fix menu label on the Release page

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1027]
Change "Back to Initialized" to "Move back to Initialized".
Change "Published" to "Move to Published"

![image](https://user-images.githubusercontent.com/7863166/99916961-6cd09100-2cdb-11eb-840e-efb449b46c2b.png)

**Comment by rekuku** [comment]
![Screen Shot 2020-11-23 at 8 02 59 PM](https://user-images.githubusercontent.com/10194354/100032847-e6917900-2dc6-11eb-8af1-c258fb2ec37d.png)

Applied.

**Comment by asdimitriadis** [comment]
Tested. The above mentioned label has been changed. 
I am leaving the issue opened because it was created by @kbserm.
