### ISSUE TITLE
End users can create CCs if the Release Draft is selected

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1028]
The issue is that an end user can create a Core Component while the Release Draft is Selected.

A simple example to reproduce the issue is:
1. Login as a developer
2. Create a new Release and move it to Draft state
3. Logout and login as an end user
4. Visit the Core Component page and select the Release Draft of the Step 2

At this point you can create a new CC that will belong to the Release Draft.
The expected behavior is that neither an end user nor a developer (it works good for the developers) can create a new CC 
in a release draft.

**Comment by rekuku** [comment]
It is fixed.
Please check this.
![Screen Shot 2020-11-23 at 8 12 42 PM](https://user-images.githubusercontent.com/10194354/100033462-42103680-2dc8-11eb-9448-91875bd77b05.png)

**Comment by asdimitriadis** [comment]
Tested and it works good.
