### ISSUE TITLE
Cannot Make a BIE node reusable if I extend multiple nodes of the BIE tree.

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1029]
The issue is that sometimes I cannot make a BIE node reusable because I have extended some BIE nodes of the BIE tree.

One example to reproduce the issue is:
1. Create a BIE selecting the ASCCP "Cancel Acknowledge Receive Delivery"
2. Visit the BIE List page and click to open it.
3. Expand the following nodes a) Cancel Acknowledge Receive Delivery, b) Data Area, c)Receive Delivery, 
d)Receive Delivery Header, e)Receive Delivery Header, f) Ship Unit Quantity
4. Click to Make reusable the node "Receive Delivery Header". 

At this point an error is returned.

However, if you open the BIE and make the node "Receive Delivery Header" without expanding some of nodes under it then it works fine.

**Comment by rekuku** [comment]
It also same bug with #1020 and #1022 .
When user trying to make reuse node if there has required child then it try to update before make reuse node.
but at this time, the parent node of "required child node" did not exist on server.
Now it fixed. please test this.

**Comment by asdimitriadis** [comment]
Tested and it works fine.
