### ISSUE TITLE
Cannot discard a release if it has been in Draft state in past

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1030]
The issue is that we cannot discard a release if it has been assigned some CCs (or Code Lists) and moved it to draft state in past.

To reproduce the issue:
1. Login as a developer.
2. Create an ACC and move it to Candidate state
3. Create a New release
4. Assigned the ACC of the Step 2 and move the Release to the Draft state
5. Move the release back to Initialized state
6. Discard the release

At that point the release cannot be discarded (maybe it still contains some assigned data/CCs).

**Comment by rekuku** [comment]
@asdimitriadis AGENCY_ID_LIST data not deleted on move back release to initialization
Now it fixed. 
Please test this.

**Comment by asdimitriadis** [comment]
Fixed and tested. It works good.
