### ISSUE TITLE
CCs belogning to a Release Draft should not be listed on the Working branch

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1031]
The issue is that in the Core Components list page if we select the Working branch, we can see CCs belonging to a Release Draft.

A simple example to reproduce the issue:
1. Login as a developer, create an ACC and move it to Candidate state
2. Create a release and include the ACC of the Step 1
3. Make a Release Draft
4. Visit the Core Component List page and select the Working branch.

At this point you can see CCs that belongs to the Release Draft (e.g., the ACC of the Step 1)

**Comment by asdimitriadis** [comment]
The same issue affects Code Lists.
That is to say, Code Lists belogning to a Release Draft should not be listed on the Working branch.

**Comment by kbserm** [comment]
We have discussed this and this is the expected behavior.
