### ISSUE TITLE
Cannot Load Values from an End User Production Code list to a Context Scheme

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1032]
The issue is that a developer cannot choose a Production End User Code List to Load values to a Context Scheme.

To reproduce the issue:
1. Login as an End User
2. Create a Code List and move it to the Production State
3. Logout and Login as a developer
4. Create a Context Scheme and during the creating click the "Load from Code List" button.

At this point you cannot see the Production End User Code List listed.

The expected behavior is that a developer can add to a context scheme code list values from Production End User Code Lists.

**Comment by rekuku** [comment]
<img width="1374" alt="Screen Shot 2020-11-29 at 9 38 47 PM" src="https://user-images.githubusercontent.com/10194354/100563029-6453f980-328b-11eb-84eb-31f03117924e.png">

When i proceed with your scenario, I can see the end-user code list.
Could you check the Branch what you selected?
Or is there any other condition what i missed?

**Comment by asdimitriadis** [comment]
Yes you are right. It works good. 
So, I am closing the issue since I cannot reproduce the issue anymore.
I made a lot of tries even with a new release. It works good.
