### ISSUE TITLE
A developer cannot create a Release Draft if a Code List owned by another developer has been assigned to the release

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1033]
The issue is that a developer cannot create a Release Draft if the Release has a Code List owned by another developer.

To reproduce the issue:
1. Login as a developer, create an Code List and move it to Candidate state
2. Logout and login using a different developer account
3. Create a release and assign the Code List of the Step 1 to the release
3. Make a Release Draft

At this point you will get the error "It only allows to modify the core component by the owner".

The expected behavior is that a developer can create a Release draft having assigned a Code List owned by another developer.

**Comment by rekuku** [comment]
Now it fixed.
Please test this. @asdimitriadis

**Comment by asdimitriadis** [comment]
Tested and it works fine now.
