### ISSUE TITLE
The select box of the "Create Context Scheme" page is limited to 10 values

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1034]
The issue is that the field where you select a Context Category for a Context Scheme is limited to display 10 Context Categories only.  

To reproduce the issue:
1. Create more than 10 Context Categories (e.g., 15)
2. Visit the Context Scheme List page (Context -> View/Edit Context Scheme) and click the "New Context Scheme" button so that you will create a new context scheme.
3. Click on the field (drop list) to select a context category

At this point you will notice that only 10 context categories are listed.

**Comment by rekuku** [comment]
Now it fixed. 
Please test this.

**Comment by asdimitriadis** [comment]
Tested and it works good.
