### ISSUE TITLE
The index of the Context Category List page displays only 10 context categories

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1035]
The issue is that the index (i.e., mat-paginator-range-label) of the Context Category List page (Context -> View/Edit Context Category) displays only 10 Context Categories. 

To reproduce the issue:
1. Create more than 10 context categories
2. Visit the Context Category List page (Context -> View/Edit Context Category)
3. Check that the index (see the screenshot) shows the number 10 although there are many more if you expand it to 50 (via the Items per page) or if you go to the next paginator page.

![indexconcat](https://user-images.githubusercontent.com/37205288/100238089-cca68200-2efd-11eb-81bc-5bc162d4cca5.png)

**Comment by rekuku** [comment]
<img width="512" alt="Screen Shot 2020-11-29 at 10 26 10 PM" src="https://user-images.githubusercontent.com/10194354/100565552-e8a97b00-3291-11eb-9b3c-999f3c71b7a4.png">

It fixed.

Please test this. @asdimitriadis

**Comment by asdimitriadis** [comment]
Tested. It works good.
