### ISSUE TITLE
Cannot reuse a BIE node if I click on a child bbie_sc node

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1038]
The issue is that we cannot reused a BIE if we expand the BIE tree to see a bbie_sc node and just click on it.
I am getting the following stacktrace from the gateway: "Column 'bbie_id' cannot be null"

To reproduce the issue:
1. Create the BIE Resource Codes make some changes and move it to Production state
2. Create the BIE Change Acknowledge Project Accounting
3. Open the Change Acknowledge Project Accounting
4. Expand the nodes: "Change Acknowledge Project Accounting", "Data Area", "Project Accounting", "Employee Identifier" and just click on the node "Scheme Version" (_do not enable it neither do any other change_)
5. Invoke the Reuse BIE function on the Resource Codes node.

At this point an error is returned.

However, if you make some changes on the "Scheme Version" then everything is ok. There is no issue.

I do not know if this issue is similar to #1029 or the other issues mentioned in it.

**Comment by rekuku** [comment]
The problem occurred because the bdt_pri_restri/bdt_sc_pri_restri default value was not loaded in BBIE and BBIE_SC.
Now it works.
Please test this @asdimitriadis .

**Comment by asdimitriadis** [comment]
It works fine.
