### ISSUE TITLE
The history for DT_SC shows nothing

### ISSUE THREAD

**Issue by hakjuoh** [OAGi/Score#1039]
<img width="653" alt="Screen Shot 2020-12-04 at 6 26 52 PM" src="https://user-images.githubusercontent.com/16102116/101225015-5cff6800-365e-11eb-85bb-1a92fa05bfb5.png">

`Show History` menu redirects to `/log/core-component/undefined` page.

**Comment by rekuku** [comment]
Context menu removed for BDT_SC.
Expand/Collapse/Open in new tab is not available for BDT_SC.
Currently, BDT_SC is not changed, so diff also cannot be seen in the history and BDT_SC's logs are remains in sub log in BDT.
It will be implemented in DT management in the future.
@hakjuoh
