### ISSUE TITLE
Allow ACC Object Class Term to be revised

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1040]
In all syntactical expressions that Score current support, this is not causing backwardly incompatible. 

In fact, this is one place GUID plays a good role. As the case when the name needs to change only because misspelled, not semantically.

This is also motivated by OAGIS issues such as https://github.com/OAGi/oagis/issues/284 and https://github.com/OAGi/oagis/issues/279. 

As we can see, this will make BIE uplift more interesting.

**Comment by rekuku** [comment]
![Screen Shot 2020-12-11 at 3 04 02 PM](https://user-images.githubusercontent.com/10194354/101949788-237cae80-3bc2-11eb-8212-4682985751dd.png)

Now revised ACC.objectClassTerm can be changed.
And the Property Term of ASCCP and BCCP is can be change for the same reason and for consistency.

**Comment by kbserm** [comment]
Need discussion with OAGi.

**Comment by rekuku** [comment]
Rollbacked to prevent confusion.

**Comment by kbserm** [comment]
Restrict this functionality to only ACC - Object Class Term.

**Comment by hakjuoh** [comment]
> As we can see, this will make BIE uplift more interesting.

BIE uplifting won't affect anything from this, because ACC is not an object. BIE uplifting only evaluates ASBIE, BBIE, and BBIE_SC.

**Comment by hakjuoh** [comment]
@kbserm Now, the object class term can be editable after revising it.
<img width="723" alt="Screen Shot 2022-07-11 at 11 49 13 PM" src="https://user-images.githubusercontent.com/16102116/178404793-1418f88f-36ac-442f-b0fd-504ddfd8cf9d.png">

**Comment by kbserm** [comment]
This looks good to go from the design perspective.
