### ISSUE TITLE
Some links in the User Extension tab of the Home Page do not work properly

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1042]
The issue is that the links of the tables displaying the number of the UEGs per state do not properly.

To reproduce the issue you need to have 2 releases (e.g., 10.6 and 10.7). Then:
1. Create some BIEs in the latest release and extend them locally or globally
2. Visit the Home Page
3. Click the User Extensions tab
4. There are 2 tables displaying the number of the UEGs per state. Click on a link. For instance on the WIP($number).

At this point the Core Component page is returned. However, the selected release is not the latest one (see the Branch drop-down list) and therefore no core component is listed.

The expected behavior is to show the latest release or let the user pick the release beforehand (maybe on the Home Page).

**Comment by kbserm** [comment]
it should show the release the ueg is on right?

**Comment by asdimitriadis** [comment]
Yes the expected behavior is to show the release that the UEG is related to.

**Comment by rekuku** [comment]
![Screen Shot 2020-12-11 at 2 03 54 PM](https://user-images.githubusercontent.com/10194354/101944078-1eb3fc80-3bba-11eb-84a2-f6e93258c9e7.png)

In order to separate BIE and UEG by Branch, we need add select box to UI.
Please let me know if I can change the UI in this way.
@kbserm @asdimitriadis

**Comment by kbserm** [comment]
Use the drop down to select a branch. Working will not be included. The dropdown can provide a Total choice - but in this case links in inappropriate places should be removed.

**Comment by rekuku** [comment]
@asdimitriadis Now links in homepage works with branch.
link is not active If use select the 'All' branch.
Please test this.

**Comment by asdimitriadis** [comment]
It works good now.
