### ISSUE TITLE
show cardinality in the CC and BIE tree

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1045]

**Comment by kbserm** [comment]
@joshklm As you can see, we have this in our issue log. But this is not super-simple because it has to be synced in real-time with the changes in the detail pane. And our test scripts might need update depending on how the cardinality rendering is associated with the tree node.

**Comment by joshklm** [comment]
@kbserm I see. It would be too complicated to keep the detail pane info synced in real-time with the tree info. I assume the reuse BIE tag is stored at tree level. Maybe it would be beneficial to bring the cardinality info up at the tree level (a bit of redundancy) and update it for changes made in detail pane. Still it wouldn't be that simple. Just a thought.

**Comment by kbserm** [comment]
@joshklm we may do this after we are able to generate the OAGIS Model XML schema. Right now let's allow @rekuku to focus on that. @hakjuoh has his Ph.D. proposal to submit by mid March.

**Comment by joshklm** [comment]
@kbserm Understood/Agreed.
