### ISSUE TITLE
ASCCP/BCCP property term cannot be updated if they are used under an ACC not being in WIP state

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1046]
The issue is that we cannot update the property term of an ASCCP or a BCCP if they are used by an ACC and the ACC is not in WIP state thus their ASCC/BCC is not in WIP state.

To reproduce the issue:
1. Create an ASCCP
2. Create an ACC, append the ASCCP to the ACC and move the ACC to the Draft state
3. Open the ASCCP and try to change its Property term

At this point a message is returned saying that "Only the core component in WIP state can be modified". Therefore, the Property Term cannot be changed. However, all other details of the ASCCP (e.g., definition) can be changed. 

I linked this issue to Score 2.1 milestone as I suggested by @kbserm and that we might need to talk about it.

**Comment by rekuku** [comment]
Fixed.
It is applied to both release/v2.0.0 and develop branch.
Please test this. @asdimitriadis
