### ISSUE TITLE
Add a "OAGIS Entity" filter to CC VIew/Edit page and also ASCCP selection page for BIE creation

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1047]
Possible values of this filter are BOD, Noun, and Verb

Verb is  any ASCCP whose ACC is based on Verb. Details ACC.

BOD is any ASCCP whose ACC is based on Business Object Document. Details ACC.

Noun is retrieved by query for all ASCCP whose property term is "Data Area". Then Noun is the second ASCCP child its ACC. Only return unique ones.  For example a "Data Area" ASCCP has "Process Purchase Order Data Area. Details" ACC. The ACC has "Process" and "Purchase Order" ASCCP. Therefore "Purchase Order" ASCCP is assumed to be a Noun.

This filter is dropdown list where the user can select only one.

**Comment by hakjuoh** [comment]
@kbserm We may be able to use `Module` filter to support this feature.

**Comment by kbserm** [comment]
Yes. Let's hold off on this.

**Comment by hakjuoh** [comment]
@kbserm 

'OAGIS Entity' filter works for ACC or ASCCP.

<img width="492" alt="Screen Shot 2022-06-02 at 5 17 29 PM" src="https://user-images.githubusercontent.com/16102116/171740062-af0d47ff-7b9d-4d62-9704-0aa882e9cffc.png">

For 'Noun' entity, it captures a child of 'Data Area' whose type is not 'Verb'. Since every 'Data Area' has Verb and Noun type ACCs, the remaining one should be 'Noun'.

**Comment by kbserm** [comment]
@hakjuoh this implementation is for temporary, I hope. It is too specific to OAGIS. The tag idea is better. CC's can be tagged and then filtered based on tags like in github Label.

**Comment by kbserm** [comment]
@hakjuoh I looked at this on the UI. It looks pretty much fine. But I think it is more convenient to return only ASCCP (smaller results). After going to ASCCP, he/she can get to ACC.

**Comment by hakjuoh** [comment]
@kbserm I replaced the label 'OAGIS Entity' with 'Tags'. For this change, I added `acc_manifest_tag`, `asccp_manifest_tag`, `bccp_manifest_tag`, and `dt_manifest_tag` tables. Each table is associated with `cc_tag` table, which has 'BOD', 'Noun', and 'Verb' as a tag name.

<img width="1074" alt="Screen Shot 2022-08-04 at 5 57 29 PM" src="https://user-images.githubusercontent.com/16102116/182959873-531614ac-3d62-401a-a4fc-59b2371ff1dc.png">

**Comment by hakjuoh** [comment]
> @kbserm I replaced the label 'OAGIS Entity' with 'Tags'. For this change, I added `acc_manifest_tag`, `asccp_manifest_tag`, `bccp_manifest_tag`, and `dt_manifest_tag` tables. Each table is associated with `cc_tag` table, which has 'BOD', 'Noun', and 'Verb' as a tag name.

Replaced the term 'tag' with 'label'.
