### ISSUE TITLE
Using the Expand All feature creates lag.

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1048]
We were trying out the Expand All feature for the Item Master BIE, when we select Expand All at the Item Master level, the website freezes for around 15-60 seconds.  In some cases the application came back, with the expanded BIE fields, but when it does the app lags when you are scrolling through the fields.   When I try to select fields there is also lag, a click circle will appear for between 5-15 seconds.  The lag also appears when selecting other values on the page, like the Score Logo to return back to the home screen or the BIE menu.  If we exit out of the tab and reopen score it does go away or if we click to another portion of score like the Score logo to go to the home page it disappears. In some cases the expand all caused the open Chrome tab to crash.

**Comment by asdimitriadis** [comment]
It works good now. There is no such delay or lag.
