### ISSUE TITLE
Change the label in the release draft creation page from 'Assign' to 'Assigned'

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1051]

**Comment by rekuku** [comment]
![Screen Shot 2021-06-15 at 10 35 20 AM](https://user-images.githubusercontent.com/10194354/122072617-bd1d5680-cdc5-11eb-8185-7331f40c871f.png)

Updated.

**Comment by asdimitriadis** [comment]
The label has been changed to "Assigned"
