### ISSUE TITLE
Message showed when another user invoke extension while the UEGACC is in QA still use "Candidate state" 

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1053]
The message in the screen shot should be updated from "Candidate" to "QA".

Also, the title of the dialog, "Confirmation", is not good. I would either remove it or change to "Attention!".

![image](https://user-images.githubusercontent.com/7863166/103460320-40992e80-4ce3-11eb-9a5a-138349fd5b8e.png)

**Comment by hakjuoh** [comment]
@kbserm Now it looks like below.
<img width="528" alt="Screen Shot 2021-01-25 at 3 27 22 AM" src="https://user-images.githubusercontent.com/16102116/105680195-63bb9600-5ebd-11eb-9f81-4ee40d70a961.png">

**Comment by asdimitriadis** [comment]
It has been changed correctly.
