### ISSUE TITLE
Is it possible to provide the option to ignore SC nodes in the BIE tree search?

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1054]
This would be the same option as in the CC tree search.

**Comment by rekuku** [comment]
SCs are not rendered when excludeSCs = ture.
Therefore, the initial detail loading speed has been improved by about 30%.

**Comment by asdimitriadis** [comment]
The checkbox to exclude SC nodes from the searching function affects the update function. 
If the exclude SC nodes checkbox is checked (true) then SC nodes cannot be updated. 
To reproduce the issue:
1. Set true the exclude SC nodes option
2. Enable an SC node
3. Change some details
At this point the Update button is disabled and cannot be clicked.

**Comment by rekuku** [comment]
@asdimitriadis 
The SC node's change event was not delivered. now it is fixed.
A warning dialog was added toggling the ExcludeSC button for the unsaved information.
![Screen Shot 2021-07-08 at 11 53 45 AM](https://user-images.githubusercontent.com/10194354/124954083-b8724980-dfe3-11eb-8d30-dbf35ec03196.png)

**Comment by asdimitriadis** [comment]
@rekuku now we can update an SC and the above issue is fixed.
However, there is another issue now. Could you please check the following?
 If we have the Exclude SC checkbox unchecked (False) then the Search BIE function does not work for SCs. 
To reproduce the issue:
1. Open a BIE 
2. Uncheck the Exclude SC
3. Try to find an SC using its path in the Search BIE tree function - there is no result

**Comment by rekuku** [comment]
@asdimitriadis There's a bug that miss delivering between BIE detail page and search module.
Now it fixed. Please test this.

**Comment by asdimitriadis** [comment]
It works well now.

**Comment by rekuku** [comment]
> This would be the same option as in the CC tree search.


@asdimitriadis 
This `excludeSC` is applied to CC details and extension details.
Please test this.

**Comment by asdimitriadis** [comment]
It works well
