### ISSUE TITLE
Add release filter to the BIE copying page

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1055]
At this point it is oblivious to the user which release the BIEs listed belong to, because there is release num in each BIE entry either.

**Comment by dubnemo** [comment]
@kbserm I think the capability to copy to a new release is important for the BIE upgrade process.  I would like this to copy everything as-is including the extensions (perhaps a check box to include the extension or not - perhaps a new issue /enhancement).

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis It now looks like below.
<img width="472" alt="Screen Shot 2021-01-25 at 2 13 18 AM" src="https://user-images.githubusercontent.com/16102116/105672745-ee4ac800-5eb2-11eb-8c3a-dd1466442d79.png">

**Comment by asdimitriadis** [comment]
The filter has been added and it works fine.
