### ISSUE TITLE
The label "Select Expressions" in the BIE Expression should be changed to singular "Select an Expression"

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1056]

**Comment by rekuku** [comment]
![Screen Shot 2021-06-15 at 10 34 34 AM](https://user-images.githubusercontent.com/10194354/122072563-b1319480-cdc5-11eb-9c55-58341c6999f9.png)

Updated

**Comment by asdimitriadis** [comment]
The label has been changed
