### ISSUE TITLE
Simplify the Code List Management

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1057]
refer to the discussion made on the slides here - https://oagiscore.atlassian.net/wiki/spaces/SCORE/pages/970555404/Code+list+changes+for+2.0.

OAGi people agreed to go with no extension in dev. code list.

**Comment by rekuku** [comment]
The migration script that deprecate oacl_{code_list} 
[code_list_migration.sql.zip](https://github.com/OAGi/Score/files/6230080/code_list_migration.sql.zip)

**Comment by asdimitriadis** [comment]
@rekuku  can we please also deprecate/hide the "Extensible" checkbox of developer code lists? This need is based on the slide 12 of the presentation of the first comment of this issue. 

In addition to that, on the BIE side we should display code list versions (see slide 12 of the presentation of the first comment of this issue). That is, when the Value Domain Type is Code the corresponding drop-down list presenting available code list should display their versions as well.

**Comment by rekuku** [comment]
@asdimitriadis The extensible column has hidden, and the versions are showing in BIE details.
Please check this.
![Screen Shot 2021-04-09 at 5 39 33 PM](https://user-images.githubusercontent.com/10194354/114243455-99b7d480-995a-11eb-8d25-d495e4dc97da.png)

**Comment by asdimitriadis** [comment]
@rekuku I cannot see the version of code lists in my local. Could you please verify it again?

**Comment by rekuku** [comment]
@asdimitriadis I'm sorry forgot to push the codes.
Please check this again.

**Comment by asdimitriadis** [comment]
It works good now.
