### ISSUE TITLE
Cardinalities are not enabled when we enable a BIE node

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1059]
The issue is that the Cardinalities fields remain disabled when we enable a BIE node.

To reproduce the issue:
1. Create a BIE
2. Expand the BIE tree
3. Click on a BIE node and enable it
4. Try to change the Cardinalities.

At this point, the Cardinalities of the node are still disabled.

**Comment by hakjuoh** [comment]
@asdimitriadis Done. Please review it again.

**Comment by asdimitriadis** [comment]
It works good now.
