### ISSUE TITLE
Nillable in BCCPs should not be changed if the fixed value was set in a previous revision

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1060]
The issue is that the Nillable field can be changed if we had set a fixed value in a previous revision of a BCCP.

To reproduce the issue:
1. Create a BCCP and set a value to the "Fixed Value" field
2. Make a release
3. Create a Revision of the BCCP.
4. The Nillable can be changed.

However, the expected behavior is that the Nillable should be disabled if we a fixed value was set in a previous BCCP revision.

**Comment by rekuku** [comment]
Now it Fixed. Please test this with latest develop branch.

**Comment by asdimitriadis** [comment]
It works good.
