### ISSUE TITLE
An end user cannot create or view/edit a BIE

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1062]
Some times an end user cannot create a BIE neither view it. 

To reproduce the issue:
1. Create an end user account
2. Login and go to Create BIE page
3. Choose a Business Context
4. Then choose an ASCCP and click create

Some times at this point a circle is displayed in the screen and nothing happens (see the attached screenshot).
Also, the same happens when an end user tries to view a BIE he owns. 

Note in the gateway there is no exception. 

![create](https://user-images.githubusercontent.com/37205288/105529792-e9b8c080-5cb4-11eb-9610-7e492c75d3a9.png)

**Comment by hakjuoh** [comment]
@asdimitriadis It may happened by a bug we already fixed. Please review it again and let me know if you encounter the problem.

**Comment by asdimitriadis** [comment]
It works good now.
