### ISSUE TITLE
CL values derived from another code list should not be changed.

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1063]
The issue is that if a code list value is derived from another code list, its "Code" field can be changed.

To reproduce the issue:
1. Login as an end user
2. Open a Code List and click "Derive Code List based on this" button
3. A new CL is created. Click on a Code List value derived from the previous code list
4. Change its "Code" field.

The issue is that the "Code" field can be changed. The expected behavior is that it should be disabled. Everything else works good.

**Comment by asdimitriadis** [comment]
Please disregard the above comment. The correct issue is the following. 

The issue is that if an end user creates a code list based on another (i.e., uses the "Derive Code List based on this" button), he can change the fields of the inherited code list values.

To reproduce the issue:
1. Login as an end user
2. Open the code list "oacl_TimeZoneCode" and click "Derive Code List based on this" button
3. Click on an inherited code list value

At this point you can change all fields of the inherited code list value.

The expected behavior is that the fields of inherited code list values cannot be changed. They should be locked. 

Note that this also relates and should be fixed in the amendment of a code list that is based on another. That is, the inherited code list values should not be changed in that case as well.

**Comment by hakjuoh** [comment]
@asdimitriadis Just add 'derived' property in Code List Value and the logic as follows,

```If the code list has a based one and there is a same code list value in the base, derived property sets to true.```

Derived code list value's `Code' value cannot be editted.

**Comment by asdimitriadis** [comment]
It works good.
