### ISSUE TITLE
Business Term is not stored in BBIE_SC

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1064]
The issue is that the value of the Business Term field is not stored in BBIE_SC nodes.

To reproduce the issue:
1. Open a BIE
2. Go to a BBIES_SC node and set a value to Business Term field 
3. Click Update
4. Open the BIE again and go to the node of the Step 2
5. The Business Term field is empty.

**Comment by hakjuoh** [comment]
@asdimitriadis Done

**Comment by asdimitriadis** [comment]
It works fine.
