### ISSUE TITLE
A BIE’s state can be changed from WIP to QA if we already made some changes

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1065]
The issue is that we can change BIE’s state from WIP to QA if we have already made some changes. 

To reproduce the issue:
1. Create a BIE
2.  Make some changes
3. Click "Move to QA" button

The BIE is moved to QA state and all changes have stored. 

However, the expected behavior is that we cannot change BIE’s state from WIP to QA if we have already made some changes. BIE has to be updated successfully. Previously, the "Move to QA" button was disabled until we update the BIE.

**Comment by hakjuoh** [comment]
@asdimitriadis Now two buttons, 'Update' and 'Move to QA', mutual-exclusively turned on and off.

**Comment by asdimitriadis** [comment]
It works good.
