### ISSUE TITLE
Business Context assigned to a BIE can still be changed even if it is not owned and not in WIP state

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1066]
The issue is that a user can still change the assigned business context of a BIE even if he does not own the BIE and the BIE is not in WIP state.

A simple example to reproduce the issue is:
1. Create a BIE and move it to QA state
2. Open it and assign new business contexts

The expected behavior is that we can change the BIE business context only if we own the BIE and the BIE is in WIP state.

See also issue #883

**Comment by hakjuoh** [comment]
@asdimitriadis Done.
<img width="338" alt="Screen Shot 2021-01-26 at 8 14 59 AM" src="https://user-images.githubusercontent.com/16102116/105849608-998c7780-5fae-11eb-978f-f4f49642886b.png">

**Comment by asdimitriadis** [comment]
It works good now.
