### ISSUE TITLE
Cannot clear Definition field of an ACC's property and Update the CC

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1069]
The issue is that if a developer (or an end user accordingly) clears the Definition field of a property of an ACC, the Update is disabled.

The expected behavior is that we can update an ACC that there is an empty Definition field. However, a message confirming that the Definition is empty should be returned.

To reproduce the issue:
1. Create an ACC
2. Append a property to the ACC (e.g., a BCCP)
3. Set the Definition of the ACC and the Definition of the BCCP
4. Click Update
5. Click to view the appended BCCP node
6. Empty its Definition
7. Click Update to update the ACC

The Update button is disabled.

**Comment by asdimitriadis** [comment]
This issue is applied to BCCP as well.
To reproduce it:
1. Create a BCCP
2. Set a Definition and click Update button
3. Clear the Definition field and try to Update the BCCP

The Update button is disabled.

**Comment by hakjuoh** [comment]
@asdimitriadis Please review it

**Comment by asdimitriadis** [comment]
It works good.
