### ISSUE TITLE
Descendant deleted CCs are not marked as deleted 

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1070]
The issue is that upon opening a CC that has a descendant deleted CC, the system does not flag it as deleted (e.g., using a text-line-through format) 

A simple case to reproduce the issue:
1. Create the ACC1
2. Create the ACC2 and use ACC1 as a base to ACC2
3. Delete ACC1
4. Open ACC2. 

The deleted ACC1 should be flagged using a text-line-through style. 
Note that there might be cases of deleted CCs in deeper level (e.g., An ACC that uses another ACC which has a deleted ACC as a base)

**Comment by rekuku** [comment]
Now It fixed.
![Screen Shot 2021-01-28 at 5 18 08 PM](https://user-images.githubusercontent.com/10194354/106205644-cf875280-618c-11eb-9a33-ab495eaf12e6.png)

**Comment by asdimitriadis** [comment]
It works good.
