### ISSUE TITLE
Business Term in BBIE_SC nodes is not transferred to the Uplifted BIE.

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1071]
The issue is that the value of the business term field is not transferred to the Uplifted BIE in case of BBIE_SC nodes.

To reproduce the issue:
1. Create the "Enterprise Unit" BIE in 10.6
2. Go to "/Enterprise Unit /Cost Center Identifier /Scheme Agency Identifier" node and set the Business Term field.
3. Uplift the BIE to 10.7

The  "/Enterprise Unit /Cost Center Identifier /Scheme Agency Identifier" node of the uplifted BIE does not have any value in its "Business Term" field.

**Comment by rekuku** [comment]
The biz_term column is missed while uplifting.
Now it fixed.

**Comment by asdimitriadis** [comment]
It works good.
