### ISSUE TITLE
Child node information are not transferred if the parent node is unmatched

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1072]
The issue is that if a map is performed on a descendant node without parent node mapping, the information of the descendant node is not transferred to the uplifted BIE. 

To preproduce the issue:
1. Create the UOM Code Conversion Rate
2. Make some changes to these nodes:  UOM Code Conversion Rate /To UOM Package /UOM Code and to /UOM Code Conversion Rate/To UOM Package/UOM Code/Type Code
3. Go to Uplift page
4. Map the /UOM Code Conversion Rate/To UOM Package/UOM Code/Type Code but not its parent (i.e. UOM Code Conversion Rate /To UOM Package /UOM Code)
5. Uplift the BIE

The uplifted BIE should contain information of the  /UOM Code Conversion Rate/To UOM Package/UOM Code/Type Code but not of the  /UOM Code Conversion Rate/To UOM Package/UOM Code. Both nodes should be enabled. 

Now, the /UOM Code Conversion Rate/To UOM Package/UOM Code/Type Code does not contain any information.

**Comment by rekuku** [comment]
Now it fixed. Please test this. @asdimitriadis 
![Screen Shot 2021-01-28 at 4 20 32 PM](https://user-images.githubusercontent.com/10194354/106200766-7c5dd180-6185-11eb-8504-ab40b5a46257.png)

**Comment by asdimitriadis** [comment]
It works good now. Tested.
