### ISSUE TITLE
end user code list uplifting has to consider a potentially duplicate values if its based developer code list has been revised

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1073]
b/c an end user code list that is based on a developer code list may be extended with add additional code values, some these values might got into the revised based developer code list. This would cause an issue.

**Comment by kbserm** [comment]
When code values are duplication, end user code list needs to take the info from the base. The application just need to let the user knows that the info in the original end user code list has been overridden by the one in the base code list.

**Comment by hakjuoh** [comment]
@asdimitriadis While the CL is uplifting, all CL values derived from a based CL also are copying again. If there is a duplicated value in between a source CL and a target based CL, it will use a latter one in a case insensitive way.

For instance,

1. End user creates oacl_TimeZoneCode_EU derived from oacl_TimeZoneCode in 10.7.1
2. End user adds 'm0010' and 'm0020' code list values onto 'oacl_TimeZoneCode_EU' CL.
3. Developer revises oacl_TimeZoneCode CL, adds 'M0020' and 'M0030', and publishes it.
4. Developer creates new 10.7.2 release including oacl_TimeZoneCode CL.
5. End user tries to uplift oacl_TimeZoneCode_EU with 10.7.2 as a target branch.

The result should has three code list values: 'm0010', 'M0020', 'M0030'.

Please test this and let me know if you have any questions.

**Comment by asdimitriadis** [comment]
It works well. The duplicate values are detected the the developer's ones are used like it is mentioned in the previous comment. 

However, there is no dialog returned to let the user know about the duplicate values and that they have been overridden by the one in the developer's base code list. According to @kbserm 's comment, we need such an information dialog.

**Comment by rekuku** [comment]
<img width="566" alt="Screen Shot 2021-09-01 at 11 21 49 PM" src="https://user-images.githubusercontent.com/10194354/131776892-a7c4ec19-ae0e-4883-87c0-0caf8e7d8fda.png">

Now it shows the list of overwritten values.
Please test this @asdimitriadis

**Comment by asdimitriadis** [comment]
It works well.
