### ISSUE TITLE
Code List creation should not be allowed in a Draft release

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1074]
The issue is the an end user can create a code list in a Draft release.

To reproduce the issue:
1. Create a Release and move it to Draft state.
2. Login as an End User
3. Go to Code List page, choose the Release of Step 1 which is in Draft State.

At this point, you can create a new Code List.

The expected behavior is that no one should be allowed to create the Code List in a Draft release.

**Comment by rekuku** [comment]
Now it is fixed.
![Screen Shot 2021-01-29 at 9 19 24 AM](https://user-images.githubusercontent.com/10194354/106285973-1fa8f800-6213-11eb-8cf4-2a651b97901a.png)

**Comment by asdimitriadis** [comment]
It works good.
