### ISSUE TITLE
If we reused a BIE on a node and enable it, we cannot change its fields

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1075]
The issue is that if you reuse a BIE and enable it (using the Used checkbox), you cannot change its field. You have to refresh the page.

To reproduce the issue:
1. Open a BIE
2. Go to a node and invoke BIE reuse
3. Enable the node (using the "Used" checkbox)

At this point all the field are disabled. You have to refresh the page.

**Comment by rekuku** [comment]
@asdimitriadis Now it fixed. please test this.

**Comment by asdimitriadis** [comment]
It works good.
