### ISSUE TITLE
Violations in Cardinalities of previous appended properties to an ACC

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1076]
The issues described are related to both end user and developer ACCs. When we say "user" we refer to both developer and end user.

Preconditions of the issues:
1. There should be an ACC which has some associations appended (ASCC and BCC) 
2. The revision of the ACC and of its associations (ASCCs, BCCs) is greater than 1.
3. The developer opens the ACC to revise it.

The expected behavior is that the user (developer or end user) can edit the information of existing ASCCs and BCCs (ASCC sand BCCs whose revision > 1) following these rules:
- Cardinality Min should be less than the previous one (i.e.,  0 <= Min <= PreviousMin)
- Cardinality Man should be greater than the previous one (i.e., Max >= PreviousMax)
- Cardinality Min field should be disabled if the previous Min is 0
- Cardinality Max field should be disabled if the previous Max is "Unbounded"

Now the user can make any change to the cardinalities of existing ASCCs and BCCs that leads to this issue.

**Comment by rekuku** [comment]
Now it fixed. 
![Screen Shot 2021-01-30 at 2 24 41 PM](https://user-images.githubusercontent.com/10194354/106366000-1e58f780-6307-11eb-87f2-985164c629fd.png)
Please test this @asdimitriadis

**Comment by asdimitriadis** [comment]
It works good.
