### ISSUE TITLE
No information is transferred when we invoke "Make BIE reusable"

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1077]
The issue is that if we invoke the "Make BIE reusable" to a BIE node, the created BIE is empty. No information is transferred to it.

The expected behavior is that the created BIE has to contain all the information of the BIE node in which we invoked the "Make BIE reusable" function.

**Comment by rekuku** [comment]
Now it fixed. please test this. @asdimitriadis

**Comment by asdimitriadis** [comment]
It works good.
