### ISSUE TITLE
Nested reused BIE nodes does not contain any information

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1078]
The issue is that nested reused BIE nodes does not contain information. 

An example to reproduce the issue is:
1. Create the "Document Identifier Set" BIE, make some changes and move it to Production state.
2. Create the "Document Reference" BIE, make some changes and update it.
3. Reuse the "Document Identifier Set" on the corresponding node of the "Document Reference" and set its Cardinalities and Context Definition.
4. Move "Document Reference" to Production state.
5. Create the BIE ""Change Acknowledge Project Accounting" and reuse the  "Document Reference" on the corresponding node.

At that point you can see that the nested reused BIE "Document Identifier Set" does not contain information.

The expected behavior is that all information of the nested reused BIE should be there.

**Comment by rekuku** [comment]
There has a bug exist on loading the detail information of reused node's.
Now it fixed. please test this. @asdimitriadis 

![Screen Shot 2021-01-30 at 3 03 15 PM](https://user-images.githubusercontent.com/10194354/106366797-531b7d80-630c-11eb-96d9-c9747bc0422f.png)

**Comment by rekuku** [comment]
Now the reused BIE nodes are set used regardless of parent.
Please check @asdimitriadis 
![Screen Shot 2021-01-31 at 11 52 51 AM](https://user-images.githubusercontent.com/10194354/106391374-0478ec80-63bb-11eb-86df-d544ee3a292e.png)

**Comment by asdimitriadis** [comment]
It works good.
