### ISSUE TITLE
Add Value Domain Restriction label

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1079]
On the BBIE and BBIE SC node, there used to be label "Value Domain Restriction" in 1.7. Add this back to 2.0 as the term/label is used in User Guide.

![image](https://user-images.githubusercontent.com/7863166/106400458-7f0e3000-63ec-11eb-86c8-e791ab84d967.png)

**Comment by rekuku** [comment]
![Screen Shot 2021-06-15 at 10 35 54 AM](https://user-images.githubusercontent.com/10194354/122072500-a119b500-cdc5-11eb-9158-b5e2b575aaa3.png)

Updated.

**Comment by asdimitriadis** [comment]
The label has been changed.
