### ISSUE TITLE
Uplift BIE not loading for SSO Accounts

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1084]
When a SSO enabled user tries to use the uplift bie feature the uplift BIE page is stuck in a constant loading screen.  The console returns a 400 error and the site is not accessible. This issue does not occur in non-sso accounts.

**Comment by rekuku** [comment]
This is the bug when the loginId registered in the score and the key received by PingOne were different.
It's occurs in the Uplift side and now fixed.

@asdimitriadis Please test this on test.oagiscore.net

**Comment by asdimitriadis** [comment]
It works good. Tested using an SSO account.
