### ISSUE TITLE
Make Reuse BIE Option Missing for QA and Production State BIEs

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1085]
In version 1.7 we were able to create reuse BIEs from published BIE, i.e Process item master we could create a item master reuse bie.  In version 2.0 the make reuse bie option is not populating for BIEs in the QA or Production state, you can only make a reuse bie in the WIP state.

**Comment by rekuku** [comment]
![Screen Shot 2021-02-10 at 11 57 15 AM](https://user-images.githubusercontent.com/10194354/107543369-29c5e180-6b97-11eb-8829-c64c9cc7121f.png)

User can invoke the "Make BIE Reusable" to a BIE that he owns and is in WIP, QA and Production. He can invoke the "Make BIE Reusable" to a BIE that he does not own and it is in QA and Production.
Please test this @asdimitriadis

**Comment by asdimitriadis** [comment]
It works as above-mentioned.
