### ISSUE TITLE
Uplifting BIEs with a nested BIE.

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1086]
When we try to uplift a BIE that contains a reuse BIE it results in a 500 error.  For example Process Item Master where the reuse BIE was Location Item Master.  The Location Item Master Reuse BIE was uplifted successfully to 10.7 and we select the uplifted Location Item Master Reuse BIE, once the BIE is selected we select the Uplift button and then the error window appears with a 500 error message.  We tried this with the BOM BIE as well which has BOM Item Data field, same result occurred.  We tried the BOM BIE with a BOM Item Data that was created by uplifting from an existing BOM Item Data reuse bie and a newly created BOM Item Data.  Both resulted in a 500 error.

**Comment by rekuku** [comment]
This is the bug when the loginId registered in the score and the key received by PingOne were different.
It's occurs in the Uplift side and now fixed.

@asdimitriadis Please test this on test.oagiscore.net

**Comment by asdimitriadis** [comment]
It works good now.

**Comment by kbserm** [comment]
@smorgan19 encountered 500 error when the same BIE is reused multiple times in the BIE uplifting

@rekuku posted
- Reason: When uplifting an ASBIE, the TO_ASBIEP_ID is used as a key, which is caused the duplicate error.
- Solve: Match ASBIE to LIST format with same ASBIEP_ID (Uplifting architecture is not changed)

**Comment by asdimitriadis** [comment]
It works good and the above scenario included in test scripts.
