### ISSUE TITLE
BIE reuse dialog during the Uplifting should include an ASCCP filtering

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1087]
The issue is related to the BIE Uplifting process. In particular, the dialog that shows BIEs that we can select to reuse under a target node of the target BIE displays all Production BIEs of the target Release.

The expected behavior is that this dialog should only display production top-level BIEs that reference the same ASCCP as the target node. Like it does in BIE reuse.

**Comment by rekuku** [comment]
Now reuse BIE dialog show up only allowed ASCCP based BIEs.
Please test this @asdimitriadis

**Comment by asdimitriadis** [comment]
It works good now.
