### ISSUE TITLE
BIE extension is not working correctly

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1088]
This is a regression occurring after changing BIE rendering using virtual scroll. 

Additional published properties and non-production EUCC added to the non-production UEGACC should not be usable.

**Comment by rekuku** [comment]
Change the node to be only useable in Published or Production state.
![Screen Shot 2021-02-12 at 2 02 42 AM](https://user-images.githubusercontent.com/10194354/107801814-945d5580-6d2e-11eb-86c9-9bf01e863fd1.png)

@asdimitriadis Please test this.

**Comment by kbserm** [comment]
Still not working properly. For example, I had the UEGACC in Production and the containing EUASCCP amended and not in production, the EUASCCP was still usable. The odd thing is the tooltip showed up but the node is still usable (and I think it behaved correctly when the UEGACC is in Production and the EUASCCP is not in Production but still in Rev 1 - not 100% sure about this).

Please re-look at Test Assertion 4 to 8 in TC 6.2 to understand the whole expectation. You might also read my comment on July 14 in #799.  I think you should look at the 2.0 code b/f changing to virtual scroll carefully also. I think those code lines were working correctly.

@asdimitriadis I think you should double check respective test scripts as well. It looks like they couldn't detect the issues particularly for TA 5.

**Comment by rekuku** [comment]
Now it check the state of 
ASCC/ASCCP/ACC for ASBIEP node,
BCC/BCCP/BDT for BBIEP node.

I checked the old code of Score 2.0 and also Score1.7.
It only checking the state is 'Deleted' or not.
Perhaps Test Assertion 4 to 8 in TC 6.2 was not implemented.

Please check this @asdimitriadis.
@kbserm you can check this update on test instance.

**Comment by asdimitriadis** [comment]
@rekuku can you please check again the part that we append an ASCCP to the UEGACC ?
In particular if we append an ASCCP (state does not matter) to the UEGACC which is not is Production, it does not show under the UEGACC. The BCCPs are there.

**Comment by asdimitriadis** [comment]
It works fine now.
