### ISSUE TITLE
Make BIE reusable function hung up in the initializing state.

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1089]
@smorgan19 reported this issue.

@rekuku posted.
- Reason: Copy failed to complete if BBIE_SC exists among Copy targets. This is due to database changes in 2.0 and the copying logic didn't get updated accordingly
- Solve: Modified to copy missing columns in BBIE_SC.

@asdimitriadis Please verify that this in the regular BIE copying as well.

**Comment by asdimitriadis** [comment]
This scenario works good now in making a BIE reusable and in copying a BIE as well.
