### ISSUE TITLE
Score 2.0 spins on some 10.6 BIEs at Land O'Lakes/ on-prem version

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1090]
![image](https://user-images.githubusercontent.com/32434235/107987903-83158280-6f94-11eb-809c-0f21324bff90.png)

This is one 10.6 PurchaseOrder, now assigned to me.
We cannot view many of the BIEs.  
I will gather logs, and a db dump.

**Comment by dubnemo** [comment]
Currently PurchaseOrder BIE owned by vchenna is one that is pressing.
I can open many others including CustomerPartyMaster, etc.


@hakjuoh  I provided to you a dump with that BIE.  I cannot dump the DB anymore.  I currently get this error message for 2.0 backup.  Is this due to the DB upgrade?
mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces

**Comment by dubnemo** [comment]
[Issue1090_LOL.zip](https://github.com/OAGi/Score/files/5989423/Issue1090_LOL.zip)
@hakjuoh the attached zip file contains the docker-compose log output, and the db dmp file.

**Comment by hakjuoh** [comment]
> mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces

New docker image for Score repository is based on MySQL 5.7.31 which has a change that [accessing ‘INFORMATION_SCHEMA.FILES’ table requires the PROCESS privilege](https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-31.html#mysqld-5-7-31-security). In order to avoid the problem, `--no-tablespaces` option should be parameterized onto `mysqldump` command.

**Comment by dubnemo** [comment]
is there an update?  The developer working on this BIE has an urgent need for a project.

**Comment by rekuku** [comment]
Hello, Scott.
I checked issue #1090, and I found out that it is a cycle extension problem.

The cycle extension causes the browser to compute nodes greater than 17400000+ and stop due to memory problems.

These many nodes are due to the two UEGs below.

1. /core_component/extension/20929
Type: Global Extension
Den: All User Extension Group. Details
Problem association: `Classification`
BIE in use:
    1) /profile_bie/edit/52
    /Enterprise Unit/Extension/Classification
    2) /profile_bie/edit/45
    /Customer Party Master/Party/Extension/Classification

Solve: Create local extensions and replace it. after then delete `Classification` from global extension.


2. /core_component/extension/20936
Type: Local Extension
Den: `Location User Extension Group`
Problem association: `Classification`, `Enterprise Unit`
BIE in use: 
    1) /profile_bie/edit/4
    /Location/Extension/Classification
    /Location/Extension/EnterpriseUnit
    This UEG in WIP(rev=1) state, but it is in used even it can not be.

Solve: Replace 'Classification' and 'Enterprise Unit' in Extension with 'Classification' and 'Enterprise Unit' in Location. And then remove the `Classification`, `Enterprise Unit` from Local Extension.

Can I modify it like this in your dump file? @dubnemo

**Comment by dubnemo** [comment]
@rekuku @kbserm 
How can I create a local extension when I cannot even open up the BIE?

**Comment by dubnemo** [comment]
@rekuku I am concerned if any of the global extensions are in use for some BIEs, and how I can identify that.
@kbserm @hakjuoh

**Comment by dubnemo** [comment]
Is that your "BIE in use"?
When I go to 20929, it shows I can 'Amend' the All User Extension Group.  What does that mean?  I do not see any information in Help.

**Comment by dubnemo** [comment]
@rekuku 
Solve: Change the state to Production. 
**Is this changing the state of the extension, or the BIE?**

Can I modify it like this in your dump file? 

**Can this just be a SQL UPDATE Statement to update the status to these specific extensions?**

After this data correction, you can load the BIE normally.

I then want to address these global extensions, and remove them from my DB.

**Comment by rekuku** [comment]
> @rekuku I am concerned if any of the global extensions are in use for some BIEs, and how I can identify that. Is that your "BIE in use"?
> @kbserm @hakjuoh

**Yes "BIE in use" means that case. **



> When I go to 20929, it shows I can 'Amend' the All User Extension Group. What does that mean? I do not see any information in Help.

**Amend means Revise for EndUserCCc.**



> @rekuku
> ---Solve: Change the state to Production.
> **Is this changing the state of the extension, or the BIE?**
> 
> ---Can I modify it like this in your dump file?
> 
> **Can this just be a SQL UPDATE Statement to update the status to these specific extensions?**
> 
> ---After this data correction, you can load the BIE normally.
> 
> I then want to address these global extensions, and remove them from my DB.

**1. Change the state to Production of CC**

**2. I will make a update script for your data."

**Comment by rekuku** [comment]
> Hello, Scott.
> I checked issue #1090, and I found out that it is a cycle extension problem.
> 
> The cycle extension causes the browser to compute nodes greater than 17400000+ and stop due to memory problems.
> 
> These many nodes are due to the two UEGs below.
> 
> 1. /core_component/extension/20929
>    Type: Global Extension
>    Den: All User Extension Group. Details
>    Problem association: `Classification`
>    BIE in use:
>    
>    1. /profile_bie/edit/52
>       /Enterprise Unit/Extension/Classification
>    2. /profile_bie/edit/45
>       /Customer Party Master/Party/Extension/Classification
> 
> Solve: Create local extensions and replace it. after then delete `Classification` from global extension.
> 
> 1. /core_component/extension/20936
>    Type: Local Extension
>    Den: `Location User Extension Group`
>    Problem association: `Classification`, `Enterprise Unit`
>    BIE in use:
>    
>    1. /profile_bie/edit/4
>       /Location/Extension/Classification
>       /Location/Extension/EnterpriseUnit
>       This UEG in WIP(rev=1) state, but it is in used even it can not be.
> 
> Solve: Change the state to Production.
> Can I modify it like this in your dump file? @dubnemo
> After this data correction, you can load the BIE normally.

[issue-1090.sql.zip](https://github.com/OAGi/Score/files/5998215/issue-1090.sql.zip)

@dubnemo Here is the script for case 1.
This script contains the following actions.
Add `Classification` to `Enterprise Unit User Extension` and `Party User Extension Group`.
Update BIE that to reference from global to local.
Delete `Classification` from Global User Extension.

After execute this script, you can normally access the PurchaseOrder or other BIE.

In case of number 2, it can be processed through UI. Please update `Location User Extension Group (ACC)` to Production state for data validation.

**Comment by dubnemo** [comment]
We are now able to open the PurchaseOrder BIE. 
THANK YOU!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
