### ISSUE TITLE
Cache related issues when we revise or amend CCs

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1091]
The following issues are related to cache:

1. In case of amending or revising a CC, the revision number is not increasing. We have to refresh the browser.
2. In case of amending a BCCP, the Deprecated field remains disabled. We have to refresh the browser.

**Comment by rekuku** [comment]
There's a bug that update details of BCCP after amend.
Now it fixed please test this. @asdimitriadis

**Comment by asdimitriadis** [comment]
It works fine now.
