### ISSUE TITLE
Prevent the user from adding ASCCP to global extension

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1092]
Maybe we want to do this because adding an ASCCP to the global extension almost guarantee to create a cyclical structure because most ACCs used by ASCCPs also contain the global extension.

**Comment by dubnemo** [comment]
Only an admin should be able to add a global extension.  Just remove this feature for now, until we get the future roles defined.
@kbserm @hakjuoh

**Comment by kbserm** [comment]
@dubnemo I added a separate issue to limit this capability to a use in admin like role. Right now, we will not allow ASCCP to be added. It  has to be done anyway and will take care of the most dangerous thing that can happen.

**Comment by dubnemo** [comment]
@kbserm I see that the milestone changed.  Will this be available sooner?  Probably add that to the agenda for Thursday.

**Comment by kbserm** [comment]
@dubnemo yes we will try to.

**Comment by rekuku** [comment]
Now only BCCP can be appended to Global Extension. Please test this. @asdimitriadis

**Comment by asdimitriadis** [comment]
It works good. 

The functionality of preventing an ASCCP to be appended to the Global Extension was documented in the user guide as well.
