### ISSUE TITLE
End user code lists in revision greater than 1 should be displayed on BIE Value Domain regardless of their state

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1094]
The issue is that WIP and QA end user code lists whose revision is greater than 1 are not displayed when the Value Domain Type of BBIE is set to “Code”. We only show Production end user code lists.

The expected behavior is that the value domain field should include code lists whose revision is greater than 1 regardless of their state. Note that if they are in WIP or QA state they should be flagged somehow. 

Also, consider that the value domain should display only compatible code lists and end user code list which are derived from that compatible code list.

The expected behavior is detailed in TA 8 of TC 6.2

**Comment by rekuku** [comment]
When the End-user code list Amended/Canceled then BBIE, BBIE_SC’s code_list_id also be updated. 
So, it is always use the newest revision of Code list at the BIE detail and BIE express.

**Comment by rekuku** [comment]
![Screen Shot 2021-02-21 at 12 14 32 AM](https://user-images.githubusercontent.com/10194354/108616336-98e2d780-73da-11eb-9c7f-01d7974f7d92.png)

The BIE is always use last revision of Code list.
The Code List, which is not in Production, Published state, is highlighted.

The value domain also display compatible code lists and end user code list which are derived from that compatible code list.

@asdimitriadis Please check this on release/v2.0.0.2 branch.

**Comment by asdimitriadis** [comment]
It works as above mentioned.
