### ISSUE TITLE
No confirmation dialog if the definition of an association of an ACC is left empty

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1096]
The issue is that if a developer or an end user append a property to an ACC and then is **not** in the panel where the details of the association is displayed, he can update the ACC without confirming that the definition has been left empty.

To reproduce the issue:
1. Create an ACC
2. Set the Definition field.
3. Append a property to the ACC
4. Click the ACC without clicking the property at all.
5. Click the Update button

At this point the definition of the property appended in step 3 is left empty.
If you, however, view the property then everything works good. 
The trick is not to view the property.

**Comment by rekuku** [comment]
@asdimitriadis 
I have a question.
If there is a revised ACC that already has ASCC/BCC with empty definition.
Should we show the confirmation dialog if update this ACC without click those ASCC/BCC?

The current logic is:
Validates only CCs whose details are loaded (= clicked at least once) and contents have been modified.

To check the same case as in step 3.
1. Load all the children of root to client.
2. Include them in the validation check.

**Comment by kbserm** [comment]
"Should we show the confirmation dialog if update this ACC without click those ASCC/BCC?" => from my perspective - No, it is not necessary to validate those.

I don't understand what you said from "To check ...." down.

**Comment by rekuku** [comment]
> To check the same case as in step 3.
> 
> 1. Load all the children of root to client.
> 2. Include them in the validation check.

This is a note about what needs to be worked on. @kbserm

**Comment by asdimitriadis** [comment]
The issue is closed since we do not need such check according to the above comments.
