### ISSUE TITLE
Developers can use end user code lists in value domain of BBIE

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1097]
The issue is that developers can use end user code lists in value domain field of BBIE.

The expected behavior is that developers can select only published and compatible code lists in the value domain field. In addition, these code list should belong to the same release with the BIE.

**Comment by rekuku** [comment]
Now developer user only can use the Published state code list.  
Please test this @asdimitriadis.

**Comment by asdimitriadis** [comment]
It works good.
