### ISSUE TITLE
Message about context definition explaining the Max Cardinality is zero does not disappear

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1098]
The issue is that if we set the Context Definition to explain the reason of setting the max cardinality to zero, the corresponding message is still there.

To reproduce the issue:
1. Create an ACC
2. Append a property
3. Set the Max Cardinality to 0
4. Set the Context Definition 
5. Update the ACC
At this time the message about setting the context definition is still there.

Please see the attached screenshot. 

![maxmessage](https://user-images.githubusercontent.com/37205288/109180449-e489de00-7758-11eb-81c5-446c632e16a0.jpg)

**Comment by asdimitriadis** [comment]
This apply is the BIE side as well.

**Comment by kbserm** [comment]
the message on the CC side is not right either because there is no such thing as 'context definition' in CC. Need to change that to just Definition.

**Comment by hakjuoh** [comment]
@asdimitriadis Now that error message shows only when if the target definition is empty.

**Comment by asdimitriadis** [comment]
It works good now.
