### ISSUE TITLE
Min Cardinality of BIE scenario of losing its previous value

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1100]
The issue is that the Min Cardinality value is "lost" (not empty) if we changed to a value greater than Max Cardinality. 

Generally it works good. But I found the following scenario:
1. Create a BIE
2. Enable a node that its Max Cardinality is unbounded.
3. Change the Max to 55 (do not click update)
4. Change Min to 33.
5. Click update.
6. Click to view the details of another BIE node
7. Go back to view the details of the previous node
8. Change Min to 77 and click update.
9. In the UI it is shown a violation (the Min is 77)
10. Click to view the details of another BIE node
11. Go back to view the details of the previous node
12. Min Cardinality is 7 (no violation but also the Min is changed to a different value rather than to the previous value - i.e. 33)

**Comment by hakjuoh** [comment]
@asdimitriadis Now 'Update' button is disabled if cardinalities violates constraints. The error message will appear when the input text lost a focus.

<img width="895" alt="Screen Shot 2021-03-04 at 3 37 32 PM" src="https://user-images.githubusercontent.com/16102116/110027103-8f713d80-7cff-11eb-9fc8-b0d7ff21baf7.png">

**Comment by asdimitriadis** [comment]
It works good now.

**Comment by asdimitriadis** [comment]
I am reopening the issue since I found out that in some cases it does not work.
For instance in the /Issued Item Instance/Hazardous Material if we set Max to 0, update the BIE, then we can set Min to any value greater than 0.

**Comment by asdimitriadis** [comment]
It works good now according to the new commit.
