### ISSUE TITLE
BIE Expression problem when the same BIE is reused in multiple places

### ISSUE THREAD

**Issue by rekuku** [OAGi/Score#1101]
A BIE(e.g. BOM Item Data) reused multiple locations of BIE(e.g. Process BOM)
![Screen Shot 2021-03-03 at 3 31 05 PM](https://user-images.githubusercontent.com/10194354/109868423-95025100-7c35-11eb-9334-ce57e7703651.png)
The second reused BIE of the generated BIE loses 1 depth.
![Screen Shot 2021-03-03 at 3 01 20 PM](https://user-images.githubusercontent.com/10194354/109868876-3093c180-7c36-11eb-8fc0-80fe95eb0604.png)

```
<xsd:element minOccurs="0" maxOccurs="unbounded" name="BOMOption">
    <xsd:complexType>
        <xsd:attribute name="typeCode" use="optional" type="xsd:token" />
        <xsd:attribute name="typeCode" use="optional" type="xsd:token" />
    </xsd:complexType>
</xsd:element>
```
This part has loses 1 depth of `CustomerItemIdentification` and `ManufacturerItemIdentification`

**Comment by shaildshah** [comment]
Is the reason why there are 2 total typecodes because the Reused BIE only contains 2 attributes containing multiple sub elements (Blue highlighted in SCORE)? Or is it because the BIE is only used twice?

Looking to understand why we have more than 2 typecodes at the bottom, when we only have one BIE Reused twice. Thanks

**Comment by rekuku** [comment]
> Is the reason why there are 2 total typecodes because the Reused BIE only contains 2 attributes containing multiple sub elements (Blue highlighted in SCORE)? Or is it because the BIE is only used twice?
> 
> Looking to understand why we have more than 2 typecodes at the bottom, when we only have one BIE Reused twice. Thanks

It is related to how many times the reused BIE uses the typeCode at the same level.
The typeCode in the example are used in two location.

- /BOM Item Data /Customer Item Identification /Type Code
- /BOM Item Data /Manufacturer Item Identification /Type Code

So it was marked twice.
Your BIE is probably using more typeCodes. @shaildshah

**Comment by smorgan19** [comment]
Thank you for the clarification.

**Comment by hakjuoh** [comment]
@asdimitriadis This issue only happened during expressing in the form of XML. There was a caching mechanism to reuse components already processed. At the time of implementing, it did not take into consideration of BIE reuse. Thus, I temporarily remove it for now and works well. Please review and test a recent commit.

**Comment by asdimitriadis** [comment]
It works good now. A test script for that case also added.
