### ISSUE TITLE
Relayout of Express Page

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1103]
Having the button on the lower left has been challenging.

Consider the following layout as it flows left to right, and will not require a scroll down.

![image](https://user-images.githubusercontent.com/32434235/110031965-34d6e200-7cfd-11eb-8443-99c9fbc7e837.png)

**Comment by dubnemo** [comment]
@kbserm can we discuss this Issue next Thursday.  This is a simple change that will greatly improve easy of use.

**Comment by kbserm** [comment]
Put the generate button right at the bottom of the table.

**Comment by kbserm** [comment]
related to #1152
