### ISSUE TITLE
Uncheck nillable flag (set bcc.is_nillable=false) for all enabled child and descendant BCCs

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1104]
99% of the time I have to uncheck this checkbox.  

editor.swagger.io defaults to not show the example data in the property when enabled.  That should be the test case.

**Comment by kbserm** [comment]
I believe it won't be nillable by default unless it is nillable already in the CC. @asdimitriadis could you double check whether app logic respects this expected behavior.

**Comment by asdimitriadis** [comment]
Nillable works good as Serm mentioned. It reflects the CC.

**Comment by dubnemo** [comment]
As discussed March 12, Architecture team meeting.

This does NOT work in editor.swagger.io

                    name:
                      oneOf:
                      - nullable: true
                      - allOf:
                        - $ref: "#/components/schemas/string"
                        - description: "Customer Name"
                          example: "LargeCustomerA"

This works:
                    name:
                      oneOf:
                      - allOf:
                        - $ref: "#/components/schemas/string"
                        - description: "Customer Name"
                          example: "LargeCustomerA"
                      - nullable: true

**Comment by kbserm** [comment]
Maybe implement this at BIE creation, Context, or User, or Top-level BIE setting.

**Comment by dubnemo** [comment]
@kbserm 
We should limit this to bcc.is_nillable for now.    Let's use the same approach to right click and allow mass update all BCC children and descendants to uncheck nillable at any level.  
![image](https://user-images.githubusercontent.com/32434235/132044379-5df6c709-ed23-46b5-9d9a-ff06bf945564.png)


The oneOf is generating a new class in code generation too.

**Comment by kbserm** [comment]
ok, sounds reasonable. It will affect only used BCC nodes, correct?

**Comment by dubnemo** [comment]
@kbserm yes

**Comment by hakjuoh** [comment]
@kbserm @dubnemo 'Check nillable on Child BCCs' and 'Unheck nillable on Child BCCs' menus are added. These functions are working for BCCP children whose 'used' property values are 'true'.

@kbserm Let's talk `nillable` property issue why it doesn't work.

<img width="668" alt="Screen Shot 2022-06-02 at 11 22 25 AM" src="https://user-images.githubusercontent.com/16102116/171668354-77b36f13-bee2-4e77-b25d-6dcbcfc19957.png">

**Comment by kbserm** [comment]
@hakjuoh I don't understand the issue associated with this statement "@kbserm Let's talk nillable property issue why it doesn't work."

I would change the menu label to "Make child BCCs nillable" and "Make child BCCs non-nillable" instead.

**Comment by hakjuoh** [comment]
> @hakjuoh I don't understand the issue associated with this statement "@kbserm Let's talk nillable property issue why it doesn't work."
> 
> I would change the menu label to "Make child BCCs nillable" and "Make child BCCs non-nillable" instead.

@kbserm Scott left another issue about a nillable property in OAS expression.
```
As discussed March 12, Architecture team meeting.

This does NOT work in editor.swagger.io

                name:
                  oneOf:
                  - nullable: true
                  - allOf:
                    - $ref: "#/components/schemas/string"
                    - description: "Customer Name"
                      example: "LargeCustomerA"
This works:
name:
oneOf:
- allOf:
- $ref: "#/components/schemas/string"
- description: "Customer Name"
example: "LargeCustomerA"
- nullable: true
```

**Comment by kbserm** [comment]
@hakjuoh 

@dubnemo seems to say that the order of the nullable makes a different. If it appear last it doesn't bother the Swagger. Let's confirm this with @dubnemo. But if the nillable false, then the serialization does not have the oneOf . The question is whether we have to move the 'nullable: true' up as a first member of the oneOf. Let's ask @dubnemo in tomorrow call.
