### ISSUE TITLE
The name of Module Set can be empty

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1108]
The issue is that the field "Name" of a Module Set can be left empty when we updating the Module Set (not when creating one).

The expected behavior is that this field should be mandatory.

**Comment by rekuku** [comment]
![Screen Shot 2021-03-11 at 10 13 05 AM](https://user-images.githubusercontent.com/10194354/110809007-87ab1f00-8252-11eb-8327-27ac05208aeb.png)

The update button going to disabled when the name get empty.

**Comment by asdimitriadis** [comment]
@rekuku  Could you please check the creation of a Module set? Yesterday, I thought it worked but I just noticed that an error is returned.
For instance, try to create a new Module Set by leaving the Name empty.

**Comment by rekuku** [comment]
I missed the creation module set page.
now the create button get disabled when the name is empty.

**Comment by asdimitriadis** [comment]
It works good now.
