### ISSUE TITLE
Duplicate modules and directories in a Module Set

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1110]
The issue is that we can create a module or a directory with the same name as an existing one (in the same column - path).

To reproduce the issue related to modules:
1. Open to edit a Module Set
2.  Click add button and create a new module
2. Add the module  e.g. "OAGIS_test"
3. Repeat 1 and 2 again.

At this time there will be duplicate modules.

To reproduce the issue related to directories:
1. Open to edit a Module Set
2.  Click add button and create a new directory
3. Add the name e.g. "OAGIS_test_directory"
4. Repeat 1 and 2 again.

At this time there will be duplicate directories.

As we discussed on our last meeting we can use "_1" or "_(1)" or " (1)" etc.

**Comment by rekuku** [comment]
![Screen Shot 2021-03-11 at 10 02 00 AM](https://user-images.githubusercontent.com/10194354/110807282-de175e00-8250-11eb-85b0-4f0ba7c46bc7.png)
![Screen Shot 2021-03-11 at 9 58 51 AM](https://user-images.githubusercontent.com/10194354/110807286-deaff480-8250-11eb-9abb-44f52f340eec.png)

it's block the to creating/updating Module with duplicate name at same location.
In case of Copy, (4-random-digit) is added as suffix.
This rule applies to both of module and module_dir

@asdimitriadis Please test this.

**Comment by asdimitriadis** [comment]
It works good now.
