### ISSUE TITLE
The name of a module can be left blank

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1111]
The issue is that we can edit a module, left its name empty and update it.

To reproduce the issue:
1. Open a Module set that contains at least one module.
2. Click the pencil button of that module so that you can edit its detail
3. Clear the Name field.
At this point there is indeed a warning message about that it cannot be left black but the Update button is not disabled.
If you click Update the module is left without a name. However, if you reopen the Module Set, the name is there (i.e., it is not updated in the db).

**Comment by rekuku** [comment]
![Screen Shot 2021-03-11 at 9 51 37 AM](https://user-images.githubusercontent.com/10194354/110805762-65fc6880-824f-11eb-9637-6045c583119a.png)

Now it fixed. please test this.

**Comment by asdimitriadis** [comment]
@rekuku the Namespace and Version properties are not transferred in new modules. Somehow they get lost.  Yesterday, I could see them but not now. So I am not creating a new issue. 

For instance, create a new module and set the Name, Namespace and Version. Afterward, click its pencil icon to see its details. There is no namespace and version. 

![testname](https://user-images.githubusercontent.com/37205288/110814258-46693e00-8257-11eb-8a23-c9e260970acd.jpg)

**Comment by asdimitriadis** [comment]
It is a false positive. It works good.

**Comment by asdimitriadis** [comment]
I am reopening the issue. 
My last comment is indeed an issue but it only happens in newly created modules and only the first time you open to see their details.
To reproduce the issue:
1 .Create a module set
2. Add a new module and click create
3. Click on the pencil of this new module you just created.

The Namespace and Version fields are empty.

If you click on an existing module copied from another module set, then you can see its details.

**Comment by rekuku** [comment]
> I am reopening the issue.
> My last comment is indeed an issue but it only happens in newly created modules and only the first time you open to see their details.
> To reproduce the issue:
> 1 .Create a module set
> 2. Add a new module and click create
> 3. Click on the pencil of this new module you just created.
> 
> The Namespace and Version fields are empty.
> 
> If you click on an existing module copied from another module set, then you can see its details.

It is fixed. @asdimitriadis

**Comment by asdimitriadis** [comment]
It works good now.
