### ISSUE TITLE
The Cancel button of the dialog "Add module/directory to "Model"" does not work

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1112]
The issue is that The Cancel button of the dialog "Add module/directory to "Model"" does not work. 

To reproduce the issue:
1. Open a Module Set
2. Click the "+add" button of the first column 
3. Click the "Cancel" button. 

At this point the dialog "Add module/directory to "Model"" remains open. We have to click somewhere else in the page or the Esc keyboard button.

**Comment by rekuku** [comment]
Fixed. please test this @asdimitriadis

**Comment by asdimitriadis** [comment]
It works good.
