### ISSUE TITLE
There is no button used to delete/unassign a module or directory from a Module Set

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1113]
The issue is that in the page where we edit the details of a Module Set, there is no button used to delete/unassign a module or a directory.

**Comment by rekuku** [comment]
![Screen Shot 2021-03-12 at 12 02 29 PM](https://user-images.githubusercontent.com/10194354/110973118-d330fc00-832a-11eb-8f61-7010ba261895.png)

Now the Unassign and delete button available. @asdimitriadis

**Comment by asdimitriadis** [comment]
@rekuku  Can you please check the following scenario:
1. Open a Module Set
2. Click on the pencil icon of a Directory that is not empty (e.g., Model)
3. Click Discard
4. At the new pop up that asks for confirmation click "Cancel"

At this point the page freezes (a mat-spinner is always spinning) and the user has to refresh the browser

**Comment by rekuku** [comment]
> @rekuku Can you please check the following scenario:
> 
> 1. Open a Module Set
> 2. Click on the pencil icon of a Directory that is not empty (e.g., Model)
> 3. Click Discard
> 4. At the new pop up that asks for confirmation click "Cancel"
> 
> At this point the page freezes (a mat-spinner is always spinning) and the user has to refresh the browser

@asdimitriadis Now it fixed.

**Comment by asdimitriadis** [comment]
It works good.
