### ISSUE TITLE
Namespace and Version of a Module should be optional

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1114]
The namespace and version fields of a module are optional. Only the Name field is mandatory.

**Comment by hakjuoh** [comment]
@asdimitriadis Now `namespace` and `version` properties are optional to create new module. If `namespace` is empty during the creation, releases' namespace is overridden.

**Comment by asdimitriadis** [comment]
Although they are optional now, we cannot create a module. An error is returned.
To reproduce the issue, try to create a module and leave Namespace empty. An error is returned. 
Also, we should have an empty option. Now, if I create a module with a namespace, I cannot edit it and clear the Namespace field.

**Comment by asdimitriadis** [comment]
Based on the last updates, now we can create a Module File without setting the Namespace.
However,
1. If you then open to view its details (i.e., by clicking the pencil button), then the Module has a Namespace and it is not empty.
2. You cannot leave it empty; i.e., there is no empty option in the dialog where you Edit the module file.

**Comment by hakjuoh** [comment]
@kbserm This issue was done through Score 2.3 milestone. We can either re-open this issue or post a new issue if we find troubles from the module exporting function.

**Comment by kbserm** [comment]
@hakjuoh I assigned this to 2.3 then.
