### ISSUE TITLE
General comments about Module Set UI

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1116]
1. Have to Scroll down to the bottom to find the Add button.
2. There is no way to resize each folder column.
3. There is no way to delete a module dir or module.
4. When I copied a module, it seems like the whole hierarchy got collapse back.
5. There is no way to copy multiple modules in shot. E.g., for standalone, I want to copy all the BOD modules.
6. When copying a module or module dir, it might be better to select first which Module Set to copy from?
That's all for now.

**Comment by kbserm** [comment]
Terminology.
Module - refers to either directory for file. So use term 'Module File' and 'Module Directory' when needs to differentiate b/w the two.

**Comment by hakjuoh** [comment]
@kbserm 
> Have to Scroll down to the bottom to find the Add button.
- Vertical scrollbar added.

> There is no way to resize each folder column.
- It is currently hard to put dynamic resizing feature. Perhaps it needs to change the entire UI design.

> There is no way to delete a module dir or module.
- It can be removed by 'Discard' buttons.

> When I copied a module, it seems like the whole hierarchy got collapse back.
- Seems like it's fixed, but needs to get reviewed.

> There is no way to copy multiple modules in shot. E.g., for standalone, I want to copy all the BOD modules.
- We already added this function through 'Copy assignements'

> When copying a module or module dir, it might be better to select first which Module Set to copy from?
- Same as above.

Please review current implementations.

**Comment by kbserm** [comment]
>When I copied a module, it seems like the whole hierarchy got collapse back.

>>Seems like it's fixed, but needs to get reviewed.

This is still not fixed.
