### ISSUE TITLE
Empty directories disappear after reopening the Module Set

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1117]
The issue is that if we create a directory without any module inside and then reopen the Module Set (i.e., refresh the page), the directory does not exist.

To reproduce the issue:
1. Open a Module Set
2. Create a directory
3. Refresh the page
4. The directory created in step 2 does not exist anymore.

**Comment by rekuku** [comment]
@asdimitriadis Now it fixed. please test this.

**Comment by asdimitriadis** [comment]
It works good now.
