### ISSUE TITLE
Copy all submodules does not work

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1120]
The issue is that the "Copy all submodules" checkbox does not affect copying. 

To reproduce the issue:
1. Open a Module Set
2. Invoke the "Copy from exist".
3. Choose a Module set and then choose a directory (e.g., "Model")
4. Uncheck the "Copy all submodules". 
5. Click "Copy" button.

At this point everything under the chosen directory is copied. The expected behavior is to copy only the modules of the chosen directory and not all its submodules.

**Comment by rekuku** [comment]
Now it fixed. it only copy module file or directory that user selected if user uncheck the checkbox.
Please test this.
And now it working as overwrite instead of create random four digits.
@asdimitriadis

**Comment by asdimitriadis** [comment]
It works good now. 
Also the copy function as @rekuku mention works good without adding a 4-digit suffix. Based on this I tested and closed the issue #1109 as well.
