### ISSUE TITLE
A module file of a module set can be discarded, although it is used in module set release

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1123]
The issue is that we can discard a module file of a module set even if it is used in module set release and there are some CCs assigned to it.

To reproduce the issue:
1. Create the module set "mset1"
2. Create a module set release
3. Assign some CCs using a specific module file
4. Go back and open "mset1"
5. Discard the module file of step 3.

At this point the module file is discarded. However, there were some CCs using it.

**Comment by rekuku** [comment]
This is Intended for convenience.
When the module file is deleted, the CC assigned to the module is also discarded. 
That CCs are showing on the unassigned list.

**Comment by rekuku** [comment]
Show confirm dialog

**Comment by asdimitriadis** [comment]
It works as mentioned in the previous comments.
We can still discard a module file even if it is used in a module set release. In that case, however, there is a confirmation dialog that the respective assignments will be discarded as well.
