### ISSUE TITLE
The value field of an Agency ID list value should be renamed.

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1124]
The issue is that the field "Value" in the dialog presenting the detail of an Agency ID list value should be changed to code.

Please see the attached screenshot.

![difffields](https://user-images.githubusercontent.com/37205288/114442133-39af7100-9b9a-11eb-96fd-be7d26241122.png)

**Comment by rekuku** [comment]
![Screen Shot 2021-04-14 at 12 48 54 PM](https://user-images.githubusercontent.com/10194354/114748319-cc2d4d00-9d1f-11eb-8c51-6bdce124f364.png)

Changed @asdimitriadis

**Comment by asdimitriadis** [comment]
It is indeed changed.
