### ISSUE TITLE
An end user cannot create an Agency Id list from another Agency Id list

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1125]
The issue is that an end user cannot create an Agency Id list from another Agency Id list.
To reproduce the issue:
1. Login as an end-user
2. Open the "clm63055D16B_AgencyIdentification"
3. Click the "Derive Agency Id List based on this" button

At this point an error is returned.

**Comment by rekuku** [comment]
Now it working, please test this @asdimitriadis

**Comment by asdimitriadis** [comment]
It works good.
