### ISSUE TITLE
Add 'Enable Children' and 'Enable Descendants' menu item to the BIE node

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1128]
Add 'Enable Children' and 'Enable Descendants' to the menu item to the BIE context menu. 

'Enable Children' sets the Used flag of all the child nodes to true.

'Enable Descendants' sets the Used flag of all descendant nodes to true. Need to review performance. Also needs a pop up dialog to confirm as this could take long if invoking on the root node like PO.

**Comment by kbserm** [comment]
The group think that Enable Descendant is too much and too dangerous. So we should implement only Enable Children.

**Comment by dubnemo** [comment]
@kbserm yes, I think we should drop 'Enable Descendants' from scope and title of this issue.  This will be misused, defeating the intent of a BIE.

**Comment by rekuku** [comment]
![Screen Shot 2021-04-26 at 1 38 28 PM](https://user-images.githubusercontent.com/10194354/116126501-b65f4680-a694-11eb-8e02-64ecf54ea983.png)
Add the `Enable Children` to BIE edit context menu. 
Please test this @asdimitriadis

**Comment by asdimitriadis** [comment]
It works good. This "Enable Children" option is also included to the user guide.
