### ISSUE TITLE
Find where a BIE is reused

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1130]
This feature is needed particularly when the reused BIE got updated with a new copy/version. The user needs to go to the parent BIE to update the reused node to point to the new version of the reused BIE.

We may be able to implement as follow. On the View/Edit BIE page, add a menu item 'Find Usages' to the context menu (the ellipsis on the last column). A dialog or a new tab is open listing all the BIEs using the BIE. Note: The user has to invoke this on the older copy/version of the reused BIE.

@joshklm Please review to see if you have any other or better idea.

**Comment by dubnemo** [comment]
@kbserm I believe this is mislabeled.  The Scope we discussed is where an BCCP or ASCCP is Used.  This should be on the Component view page, creating a filterable list of ACC, or ASCCPs (checkbox).

**Comment by joshklm** [comment]
@kbserm Okay with the approach with Find Usage. Maybe 'Find Usages (Reuse)' menu item would be more clear and eliminate confusion. This update will be very helpful!

**Comment by rekuku** [comment]
![Screen Shot 2021-04-23 at 3 44 07 PM](https://user-images.githubusercontent.com/10194354/115924131-51fe7600-a44d-11eb-9ed9-7f747f017be2.png)

"Find Usage" button added to context menu on BIE list page.

Please test this @asdimitriadis

**Comment by kbserm** [comment]
Change the menu name to 'Find Reuses'

Change the Title of the dialog to 'Reuses of "BINE name"'

**Comment by kbserm** [comment]
We can also add a menu under BIE menu like 'Reuse Report'. This would generate a report for the entire release of the current release in the cookies or pop-up a dialog for the user to choose the specific release.

**Comment by rekuku** [comment]
Now the PropertyTerms have links.
And the reuse dialog at the BIE list also has the same UI as the report page.
Please test this. @asdimitriadis

**Comment by asdimitriadis** [comment]
One minor thing that I have noticed is that when I click on a Property Term, I am getting the message "Gateway Unavailable". However, everything works. It opens the BIE on the specific reusing node.

**Comment by asdimitriadis** [comment]
It works good. 

It was due to using prior db before running a new migration script to 2.1.0
