### ISSUE TITLE
Uplifting BIE: Date Time field is changing to token when previously is Date Time

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1131]
When we uplift a BIE from version 10.6 to 10.7 the date time field is changing from date time to token.  If we were to create a new element in 10.7 it would be Date Time and in the original 10.6 version of the date time attribute was set to Date Time.  This is not exclusive to anyone BIE, we are seeing this in purchase order, attachment, item master, and more.

**Comment by rekuku** [comment]
https://github.com/OAGi/Score/issues/808#issuecomment-617335172
This logic was not applied to the Uplift.
Now it applied, please test this on release/v2.0.1 branch on repository @asdimitriadis.

**Comment by kbserm** [comment]
@rekuku I wonder why #808 has to be applied to uplifting. Uplifting is copying existing data. #808 is about when a new BIE data is created with default values.

**Comment by rekuku** [comment]
@kbserm Unlike Copy, Uplift allows users to select matching nodes manually.
In preparation for this case, uplifting uses the default value of the primitive restriction data.

**Comment by asdimitriadis** [comment]
"date time" primitive is transferred good.
However, we should also apply the same rule for the "date" and "time" primitives.
For instance, the "time" primitive of the /Get BOM/Data Area/BOM/BOM Header/Alternate BOM Reference/Status/Effective Time Period/Start Time is not transferred in the uplifted BIE.

**Comment by rekuku** [comment]
@asdimitriadis 
Now it applied to "date" and "time".
Please test this.

**Comment by asdimitriadis** [comment]
It works good.
