### ISSUE TITLE
Update OAGIS 10.7 to OAGIS 10.7.0.1

### ISSUE THREAD

**Issue by rekuku** [OAGi/Score#1132]
Sales Lead Header Base ACC has two associations to the Party ASCCP - one in the CRM Header Base ACC and one in the Sales Lead Header Base ACC itself.  The Party ASCCP in the Sales Lead Header Base has to be removed from the database and docker repository image. This changes results in OAGIS release 10.7.0.1 that replaces OAGIS 10.7 in the Score database. In addition, if there is any BIE depends on the Sales Lead Header Base. Party, it too has to be removed.

**Comment by rekuku** [comment]
This is the script program for detecting and update BIEs.
[migration-10-7-0-1.jar.zip](https://github.com/OAGi/Score/files/6339401/migration-10-7-0-1.jar.zip)

**Comment by kbserm** [comment]
https://github.com/OAGi/oagis/issues/332
