### ISSUE TITLE
Copy BIE function does not open with the same branch from the previous page

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1133]
It looks like the Copy BIE page does not open with the branch based on cookie info.

**Comment by dubnemo** [comment]
@kbserm @hakjuoh I think the current behavior is correct.  We should always copy to the latest OAGIS release branch loaded in the database, as that does eliminate an uplift step and ensures forward progress.   It may be helpful to provide a dialog requiring user acknowledgement showing which branch the copied BIE will be located.

**Comment by kbserm** [comment]
@dubnemo I believe you misunderstood the situation. what happened to you was. You were browsing 10.6. Then you saw a BIE you wanted to copy. You clicked the Copy BIE menu. Score brought up the BC page for you to select. Then the next page list the BIE for you to select, it always list BIEs in the latest release by default. So  you actually copied 10.7 BIE.

The cuurent copying logic cannot copy across branches because of the extension. It would be much more complicated and would be confusing with uplifting.

**Comment by kbserm** [comment]
we can discuss more in the meeting. I think you might refer to your use case where you want to carry the whole thing including extension and any EUCCs used in the BIE to the new branch and clean up your extension later. I would rather has that as a subfunction of the uplifting.

**Comment by rekuku** [comment]
CopyBIE wasn't saving release info. 
Now it fixed to save the copy page's release info to cookie.
@asdimitriadis Please test this on release/v2.0.1 branch.

**Comment by kbserm** [comment]
@rekuku did you mean copy page needs a separate parameter to save release info?

**Comment by rekuku** [comment]
Each "editBIE page", "copyBIE page", and "uploadBIE page" stores its own releases separately.
For instance "editBIE page" keep the 10.6, but "copyBIE page" can be the 10.7.

**Comment by rekuku** [comment]
1. Just use this BIE cookies info for all the BIE pages. This may look a little dumb on the uplifting page when the latest release is in the cookies but it shouldn’t cause mistake/confusion to the user.
2. Use CC cookies for all CC pages. 
3. Code list - if open from the BIE menu use BIE cookies, if open from the CC menu use CC cookies.

Now cookies are following these.

If the user changes the branch on the code list page, each BIE/CC will be overwritten depending on which menu it was opened through.
Please test this @asdimitriadis

**Comment by asdimitriadis** [comment]
It works like it is mention in the previous comment.
