### ISSUE TITLE
Deprecated Agency Id List should remain deprecated in next revisions

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1134]
The issue is that if an agency Id list is deprecated and we revise it, then we can reset it back to non-deprecated status

A simple way to reproduce the issue on developer Agency Id list:
1. Deprecate the existing developer Agency Id list
2. Revise it
3. The deprecated field is not disabled.

A simple way to reproduce the issue on end user Agency Id list:
1. Create a new Agency Id list
2. Move it to Production state
3. Amend it
4. Deprecate it and move it to Production state
5. Amend it again
3. The deprecated field is not disabled.

The expected behavior is that if deprecated was true in the previous revision, the deprecated field should be locked.

**Comment by rekuku** [comment]
The same changes of #1135 are applied to agency id list please test this. @asdimitriadis

**Comment by asdimitriadis** [comment]
It works good
