### ISSUE TITLE
Deprecated Agency Id List value should remain deprecated in next revisions

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1135]
The issue is that if an agency Id list value is deprecated and we revise/amend the Agency Id list, then we can reset this agency id list value back to non-deprecated status

To reproduce the issue from the developer side:
1. Deprecate an Agency Id list value of the existing agency id list
2. Open this Agency Id list
3. Revise it
4. The deprecated field of the deprecated Agency Id list value is not disabled.

To reproduce the issue from the end user side:
1. Create a new Agency Id list, create an Agency Id list value and move the Agency Id list to Production state
2. Amend this Agency Id list and deprecate the  Agency Id list value
3. Move the Agency Id list to Production state again
4. Amend the Agency Id list
5. Open the deprecated Agency Id list value
4. The deprecated field of the deprecated Agency Id list value is not disabled.

The expected behavior is that if deprecated was true in the previous revision, the deprecated field should be locked.

**Comment by rekuku** [comment]
The previous version of deprecated information was not delivered to the client. it is fixed. Please test this. @asdimitriadis

**Comment by asdimitriadis** [comment]
It works good.
