### ISSUE TITLE
Violation of Uniqueness Constraint rule of Agency Id List

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1136]
The issue is that we can create an Agency Id list that violates the uniqueness constraint.

The expected behavior is that no other Agency ID list with same List ID, Agency ID and Version should exist in the selected branch.
That is, the combination of the **List ID, Agency ID, and Version** has to be unique **in the selected branch** (i.e., not in all branches).

**Comment by rekuku** [comment]
![Screen Shot 2021-04-20 at 6 15 25 PM](https://user-images.githubusercontent.com/10194354/115470488-67cd2a80-a204-11eb-95c4-99de157137d7.png)

@asdimitriadis Now it checks the uniqueness of the agency id list, please test this.

**Comment by asdimitriadis** [comment]
It works good.

**Comment by asdimitriadis** [comment]
I am reopening this issue since I have found that it does not work well. 

The combination of the List ID, Agency ID, and Version has to be unique in the selected branch. However, I am able to create a new Agency ID list that has the same List ID, Agency ID, and Version with an existing one. 

The same issue exists when I updating an existing Agency ID list. 

P.S. I moved the issue at 2.3 milestone.

**Comment by hakjuoh** [comment]
The combination of 'Value' and 'Meaning' properties are the uniqueness of the agency ID list value.

**Comment by hakjuoh** [comment]
@asdimitriadis Now it checks the uniqueness using 'Value' and 'Meaning' properties of the assigned agency ID.

**Comment by asdimitriadis** [comment]
@hakjuoh it works but still there is an issue. 

Can you please try to use a slightly difference Value or Meaning? You will not be able to create an Agency ID list. 
For instance, 
If one Agency ID list has a value with Value=testvalue and Meaning=testmeaning
and another Agency ID list has  a value with Value=testvalue1 and Meaning=testmeaning1 you will not be able to create an Agency ID list.

**Comment by hakjuoh** [comment]
@asdimitriadis See commit 138007af at `http-gateway` and commit 9622f60d at `web-app`. Please review it.

**Comment by asdimitriadis** [comment]
It works well now.
