### ISSUE TITLE
Cannot create a new Code List

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1137]
The issue is that we cannot create a new code list. 

I do not know if it is related to issue #1122. This issue was fixed though.

**Comment by rekuku** [comment]
if multiple agency id list exists in database, the code list may not be able to assign a default value for the agency id list value.
So i added a condition that to use developer's agency id list value as the default.

@asdimitriadis Please test this.

**Comment by asdimitriadis** [comment]
It works good.
