### ISSUE TITLE
Issue around the use and export of built-in types that use XSD pattern

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1143]
Currently, the canonical XML Schema export for OAGIS has this behavior.
- The XMLSchemaBuiltinType_1_pattern.xsd is empty.
- The XMLSchemaBuiltinType_1.xsd is populated with the same content as the original schema, i.e., most xbts have no pattern and some of them have patterns.
- The BusinessDataTypes_1.xsd includes the XMLSchemaBuiltinType_1.xsd
The odd thing is it is not clear how can the exporter can generate XMLSchemaBuiltinType_1.xsd because the content in the database only store the xbt definitions with patterns.

I investigate the schemas. I found that none of the BDTs in Fields.xsd relies on any xbt with complicated pattern (i.e., only the ones with simple patterns, like xbt_Boolean, are used and these patterns are also used in the xbts in the XMLSchemaBuiltinType_1.xsd). So it is quite safe to switch the BusinessDataTypes_1.xsd to use XMLSchemaBuiltinType_1_pattern.xsd; and the exporter never generate the XMLSchemaBuiltinType_1.xsd ever again.

**Comment by hakjuoh** [comment]
Now there is only ‘_pattern.xsd’ module under DataTypes.

**Comment by kbserm** [comment]
The module set data in Score generates the canonical schema with XMLSchemaBuiltinType_1 in 10.6 and 10.7.0.1, but with XMLSchemaBuiltinType_1_patterns in 10.7.1. We decided not to spend time and energy to go back and change Module Set data for 10.6 and 10.7.0.1 b/c it is less likely that those will be used again.
