### ISSUE TITLE
Path in the uplift report should have space in the name and some fields has a dot 

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1144]
Current path is output w/o space like this "/Catalog/CatalogHeader/Identifier". This path doesn't work in our search box.

This path shouldn't have a dot. "/Catalog/CatalogHeader/SupplierParty/Location/PostalAddress/CountrySubDivisionCode/Type.Code"

**Comment by rekuku** [comment]
![Screen Shot 2021-05-25 at 10 48 56 AM](https://user-images.githubusercontent.com/10194354/119518802-da22b480-bd46-11eb-94ba-a1e32a867927.png)

Now the paths of the report page are showing same as others.
@asdimitriadis Please check this.

**Comment by asdimitriadis** [comment]
It works well.

Path includes the necessary spaces in names and there is no dot in SCs
