### ISSUE TITLE
Remove dot from the SC label both in the BIE and CC trees

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1145]
This would make it consistent for search and path displays.

**Comment by rekuku** [comment]
![Screen Shot 2021-05-25 at 10 47 05 AM](https://user-images.githubusercontent.com/10194354/119518579-a21b7180-bd46-11eb-8751-80e8aa370f34.png)

The dot removed from BIE and CC trees
@asdimitriadis Please test this.

**Comment by asdimitriadis** [comment]
Dot is removed.
