### ISSUE TITLE
BIE uplift cannot jump a release

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1147]
The issue is that BIE uplifting cannot jump a release. 

For instance, we cannot uplift a BIE from 10.6 to 10.7.1. We have to uplift it to 10.7.0.1 first and then to 10.7.1

BIE uplifting should allow jumping releases. For instance, it should allow a BIE to be uplifted from 10.6 to 10.7.1 without having to uplift the BIE to 10.7.0.1 first.

**Comment by rekuku** [comment]
Now uplift BIE able to jump middle branch. 

Please test this @asdimitriadis

**Comment by asdimitriadis** [comment]
It works good
