### ISSUE TITLE
Modify OAS expression to use OAS extensions to hold the guid, eliminate guid from reference to have cleaner code generation

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1148]
The guid in the schema object reference is causing code generators to create classes that are not developer friendly.

          application/json:
            schema:
              $ref: "#/components/schemas/post-invoice-oagis-id-b67f94df093c4268a063cdce695121ee"

![image](https://user-images.githubusercontent.com/32434235/119711319-03b20d80-be25-11eb-9ce4-4cb392f8fe6c.png)

Considering using OAS extensions to preserve the guid and other OAGIS specific metadata.

To be:
          application/json:
            schema:
              $ref: "#/components/schemas/invoice"

From OAS 3.0.3: 
Allows extensions to the OpenAPI Schema. The field name MUST begin with x-, for example, x-internal-id. The value can be null, a primitive, an array or an object. Can have any valid JSON format value.

**Comment by dubnemo** [comment]
Example C# class...

[Postinvoiceoagisidb67f94df093c4268a063cdce695121eeInvoiceInvoiceHeader.zip](https://github.com/OAGi/Score/files/6548890/Postinvoiceoagisidb67f94df093c4268a063cdce695121eeInvoiceInvoiceHeader.zip)

**Comment by kbserm** [comment]
One of the reasons GUID is in there is because there could be BIE with the same name in the same OAS. There is an example of this in the express pack where different PO BIEs are used in the same OAS to get IDs, to get list, and to get details.

The Open API management feature we were working on might fix this issue. 

The immediate solution would be to do the off-band edit of the OAS doc.

We will have more discussion off-line to see if there is another good short term fix.

**Comment by dubnemo** [comment]
@kbserm if there are duplicate names, can we simply add a suffix, _1 and _2?

I think under paths, these extensions should be considered:
x-oagis-bie-guid:
x-oagis-bie-date-time: $exportTimeStamp

While I am at it, under info:
x-oagis-release:
x-oagis-release-date:
x-oagis-license-declaimer:

**Comment by dubnemo** [comment]
JSON schema is only for one payload, and we need to research how the GUID can be preserved.  OAS is straight-forward.

**Comment by gesch** [comment]
As Scott asked me to add some of my thoughts as well, here we go. I think for something like the GUID which is useless to the consumer, the OAS extensions are the way to go. They seem not interfere with the code generation and they are not visible in the generated code. At least my quick tests with some client and server impls were fine. So there is no trace back in the code. In general I still miss the version for customers who are supposed to implement this interfaces. So even if they keep the OpenAPI document they downloaded, they are not able to match this with there trading partners implementation. If the guid should also help with that, I think it should be minimized to an incremental numbering system and the normal version field should be used. I still worried about the actual use by the trading partners. Especially if you are aiming for a more dynamic release pattern and get new versions out continuously. Especially the medium sized partners might run into issues because they don't run a full blown api management solution but will be forced to connect with older and newer version of the api at the same time.

**Comment by dubnemo** [comment]
@kbserm @hakjuoh 
Changes discussed 2021-07-21, with OAS expression for GUIDs.
We are NOT change the current schema name with the GUID.  This example shows that this was MANUALLY changed, and would continue to be done that way until OpenAPI Authoring and Management is available.

[openapi.yaml.txt](https://github.com/OAGi/Score/files/6903572/openapi.yaml.txt)

**Comment by dubnemo** [comment]
@kbserm 
Please prioritize in Score 2.3

**Comment by kbserm** [comment]
Added to 2.3 milestone and up the priority

**Comment by kbserm** [comment]
info:
  x-oagis-release: 10.7.1
  x-oagis-release-date: "2021-06-01"
  x-oagis-license: "https://oagiscore.atlassian.net/wiki/x/CAAxPg - Do not modify the schema object outside of Score."

paths:
  /moveProductForecast:
    post:
      x-oagis-bie-guid: Move-Product-Forecast-oagis-id-731dc1e7abdd4a77ac3b67f02c3611b6
      x-oagis-bie-date-time: 2021-07-30T12:11:00-05:00
      x-oagis-bie-version: V1

**Comment by hakjuoh** [comment]
@kbserm @dubnemo Here's a sample template.
@kbserm Is there any other place to put this warning message, "Do not modify the schema object outside of Score."?
I put 'x-oagis-bie-*' headers under 'paths', not under each path item to avoid multiple occurrences of the same headers.
```
---
openapi: "3.0.3"
info:
  title: ""
  description: ""
  contact:
    name: ""
    url: ""
    email: "example@example.org"
  version: ""
  x-oagis-release: "10.7.1"
  x-oagis-release-date: "2021-05-27"
  x-oagis-license: "https://oagiscore.atlassian.net/wiki/x/CAAxPg"
paths:
  /moveProduct:
    summary: ""
    description: ""
    x-oagis-bie-guid: "oagis-id-040e6d3a1b644af5a2a67f6c67ac230b"
    x-oagis-bie-date-time: "2022-06-02T10:24:01-0400"
    x-oagis-bie-version: "v1"
    get:
      summary: ""
      description: ""
      tags:
      - "Move Product"
      parameters:
      - name: "id"
        in: "query"
        description: ""
        required: false
        schema:
          type: "integer"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/get-moveProduct"
components:
  schemas:
    get-moveProduct:
      required:
      - "moveProduct"
      additionalProperties: false
      properties:
        moveProduct:
          type: "object"
          additionalProperties: false

```

**Comment by dubnemo** [comment]
You are onto something with multiple BIEs.
It seems every time we have a $ref to a BIE Schema object under a request
or response,  the extensions should with the $ref.

**Comment by kbserm** [comment]
Need to talk about this in Score meeting.

**Comment by dubnemo** [comment]
@kbserm @hakjuoh 
Try this approach

```
openapi: "3.0.3"
info:
  title: ""
  description: ""
  contact:
    name: ""
    url: ""
    email: "example@example.org"
  version: ""
  x-oagis-release: "10.7.1"
  x-oagis-release-date: "2021-05-27"
  x-oagis-license: "https://oagiscore.atlassian.net/wiki/x/CAAxPg"
paths:
  /moveProduct:
    summary: ""
    description: ""
    get:
      summary: ""
      description: ""
      tags:
      - "Move Product"
      parameters:
      - name: "id"
        in: "query"
        description: ""
        required: false
        schema:
          type: "integer"
      responses:
        "200":
          description: ""
          x-oagis-bie-guid: "oagis-id-040e6d3a1b644af5a2a67f6c67ac230b"
          x-oagis-bie-date-time: "2022-06-02T10:24:01-0400"
          x-oagis-bie-version: "v1"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/get-moveProduct"
components:
  schemas:
    get-moveProduct:
      required:
      - "moveProduct"
      additionalProperties: false
      properties:
        moveProduct:
          type: "object"
          additionalProperties: false
```

**Comment by kbserm** [comment]
07/14/2022 Score meeting

This "Do not modify the schema object outside of Score." should go to  x-oagis-usage-note.

We are still wondering what @dubnemo means earlier "You are onto something with multiple BIEs."

**Comment by dubnemo** [comment]
"You are onto something with multiple BIEs."

From May 27th note in this issue:  "One of the reasons GUID is in there is because there could be BIE with the same name in the same OAS. There is an example of this in the express pack where **different PO BIEs** are used in the same OAS to get IDs, to get list, and to get details."

Hence the placement of the the BIE GUID needs to be unique to the reference to the BIE schema object under
components:
  schemas:

**Comment by dubnemo** [comment]
Since we are in this expression code, is it appropriate to also address these?
#1301
#1302

**Comment by dubnemo** [comment]
This works:

```
openapi: "3.0.3"
info:
  title: ""
  description: ""
  contact:
    name: ""
    url: ""
    email: "example@example.org"
  version: ""
  x-oagis-release: "10.7.1"
  x-oagis-release-date: "2021-05-27"
  x-oagis-license: "https://oagiscore.atlassian.net/wiki/x/CAAxPg"
paths:
  /myBusinessContext/v1/moveProduct:
    summary: ""
    description: ""
    get:
      summary: ""
      description: ""
      tags:
      - "Move Product"
      parameters:
      - name: "id"
        in: "query"
        description: ""
        required: false
        schema:
          type: "integer"
      responses:
        "200":
          description: ""
          x-oagis-bie-guid: "oagis-id-040e6d3a1b644af5a2a67f6c67ac230b"
          x-oagis-bie-date-time: "2022-06-02T10:24:01-0400"
          x-oagis-bie-version: "v1"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/moveProduct"
components:
  schemas:
    moveProduct:
      x-oagis-bie-guid: "oagis-id-040e6d3a1b644af5a2a67f6c67ac230b"
      x-oagis-bie-date-time: "2022-06-02T10:24:01-0400"
      x-oagis-bie-version: "v1"
      required:
      - "moveProduct"
      additionalProperties: false
      properties:
        moveProduct:
          type: "object"
          additionalProperties: false
```

**Comment by kbserm** [comment]
This issue is about the placement of the extension only.

**Comment by hakjuoh** [comment]
@dubnemo Here's an example expression after applying the rule for 'Move Product'.

```
---
openapi: "3.0.3"
info:
  title: ""
  description: ""
  contact:
    name: ""
    url: ""
    email: "example@example.org"
  version: ""
  x-oagis-release: "10.8.2"
  x-oagis-release-date: "2022-07-05"
  x-oagis-license: ""
paths:
  /s-series/v1_0/moveProduct:
    summary: ""
    description: ""
    get:
      summary: ""
      description: ""
      tags:
      - "Move Product"
      parameters:
      - name: "id"
        in: "query"
        description: ""
        required: false
        schema:
          type: "integer"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/moveProduct"
    post:
      summary: ""
      description: ""
      tags:
      - "Move Product"
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/moveProduct"
      responses:
        "200":
          description: ""
          content:
            application/json: {}
components:
  schemas:
    moveProduct:
      x-oagis-bie-guid: "oagis-id-30cf5318b9b9426c86e8583c772e0362"
      x-oagis-bie-date-time: "2022-07-22T08:16:04-0400"
      x-oagis-bie-version: "v1.0"
      required:
      - "moveProduct"
```

**Comment by dubnemo** [comment]
@hakjuoh 
Perfect!
