### ISSUE TITLE
 Add features "replace all" primitives, child and descendants for a BIE

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1149]
Our of product teams is having a number of issues with the OAGIS default primitive types when C# code is generated.  
It would be helpful to be able to replace all primitive types from one type to a target type.  For example, from token to string.
This is about 'cleaner' code, and productivity.

**Comment by kbserm** [comment]
Do you still want to keep token in the BIE from the enterprise definition perspective? One can do a replace all using a text editor after the OAS got generated. 

It is not clear with BIE represents an enterprise canonical or API specific. It would depend on the context specify, i.e., how enterprise views the BIE. @dubnemo will check with his team again.

**Comment by dubnemo** [comment]
@kbserm the report from our development team is that our BIEs represent OpenAPIs 90% of the time.  The problem is that even this is generating an unnecessary C# class:
    string:
      type: "string"

**Comment by dubnemo** [comment]
@kbserm @hakjuoh I think the same code that walks the descendent tree to update the cardinality can be leveraged to replace primitives from current primitive to the new JSON primitive.

When we get to the OpenAPI Authoring 'epic' (new tables, wireframes created in the API WG), we will be focusing on APIs specifically.  Even our canonicals are often in JSON Schema now, especially now that IBM Sterling B2B Integrator now supports JSON Schema.

**Comment by dubnemo** [comment]
The challenge here is the ISO 15000-5 has more primitives and we would need to use substitution when expressing JSON schema or OAS; e.g.,  map CCS decimal to JSON number in the expression code.  
The attached is the desired output, with no mappings and $XREF/ AllOf.

[3- DeveloperPreference - BOM - openapi.zip](https://github.com/OAGi/Score/files/6841234/3-.DeveloperPreference.-.BOM.-.openapi.zip)

**Comment by kbserm** [comment]
make another expression for code gen?

**Comment by dubnemo** [comment]
@kbserm @hakjuoh 
I suggest a checkbox on the OpenAPI expression to [X] Substitute Primitives.
The GUID issue is a separate issue. https://github.com/OAGi/Score/issues/1148

**Comment by dubnemo** [comment]
@kbserm 
The OpenAPI point, no checkbox.  Always substitute primitives to the target syntax.  

Most of what we have in OAGIS is XML Schema primitives and our own doing.  I remember working with Jon Bosak and he was so upset with the XML Schema work, declaring that in XML everything is a string and should be left to the interpreting programs that process the data.  

To answer your enterprise question regarding canonical, 'no'.  Our enterprise view does not mean multiple syntaxes, as canonical is only the superset of semantics support multiple views.  

Since Token is derived from String, String provides  **better canonical support** since it is **more flexible** to span the needs of multiple contexts.  I strongly believe that a canonical views should leverage the more general primitives, not the more precise ones.  When one creates the BIE for a specific context, that is when more precise data type constraints need to be applied.  

![image](https://user-images.githubusercontent.com/32434235/127325986-74ae2293-d8e9-40fa-8283-4c3feb09fbc7.png)

**Comment by dubnemo** [comment]
I do appreciate the perspective that we could eliminate this ask the OAS expression approach.
If we can focus on that first, we can revisit if this is needed.
@kbserm @hakjuoh

**Comment by dubnemo** [comment]
Despite the new issue #1162, I don't think we should close at this time.

**Comment by dubnemo** [comment]
@hakjuoh can you post the URL to the Google sheet with the table dump here?
@kbserm

**Comment by kbserm** [comment]
https://docs.google.com/spreadsheets/d/1BOl5Xt32h4fKYQp2B7j9XagN38fy63PgwEqGIcI0KW8/edit?usp=sharing

**Comment by dubnemo** [comment]
We can re-open this later if we need to.
