### ISSUE TITLE
Cannot create a (top-level) BIE from a User defined ASCCP

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1154]
We didn't allow BIE to be created from the user defined ASCCP even in production, caz it needs similar logic in the extension to handle the fact that it can still be changed.

**Comment by kbserm** [comment]
@hakjuoh Think that current BIE logic may be able to handle this already. So we can unlock the restriction to allow top-level BIE to be created from the EU ASCCP. 
@asdimitriadis will write some test scripts to check.

It might worth thinking and checking about when such BIE is used in the BIE reuse.

**Comment by hakjuoh** [comment]
@asdimitriadis 

Now users can create BIE with user-defined ASCCPs whose state is 'Production'.

<img width="701" alt="Screen Shot 2021-08-19 at 11 47 48 AM" src="https://user-images.githubusercontent.com/16102116/130100297-1905d9ac-8dcd-4b91-9caa-541998eca592.png">

**Comment by dubnemo** [comment]
@hakjuoh great news!

**Comment by kbserm** [comment]
@dubnemo In our discussion today, we want to note that a BIE based on a user-defined CC cannot be uplifted with our current uplifting function because the function uses GUID to match the underlying ASCCP. @hakjuoh dissertation will make this better!!

**Comment by rekuku** [comment]
> 1. If the end user ASCCP is amended (i.e., moved to WIP state), the BIE should not be editable. The fields of the BIE nodes should be disabled including the “Used” checkbox.
> 2. If the end user ASCCP is moved to the QA state, the BIE should not be editable. The fields of all BIE nodes (ancestors and descendants) should be disabled including the “Used” checkbox.

If the end user CC is in WIP, QA state, the BIE is not be editable including "Used" checkbox.
A thing is root node can be modified regardless of the status of CC. 

> 3. Currently the ASCCP amendment allows ACC to be changed. This should not be allowed.

Now it is blocked.

> 4. Is there a guard condition for in the case of DEN of the attribute is not properly parsed #3 but the user didn't click refresh? I.e., is there a prevention to when the user might be changing the BIE based on a stale CC data? (need to check this situation in the Extension as well). But perhaps no guard condition is needed because changes to the CC has to be backwardly compatible, so any changes to the BIE cannot be inconsistent with the updated CC.

I also think no guard condition is needed.

> 5. Currently, developer can create a BIE based on an end-user ASCCP. This must not be allowed.

Now it is blocked.
![Screen Shot 2021-09-03 at 2 44 46 PM](https://user-images.githubusercontent.com/10194354/132058380-4019845a-38ff-4de2-8421-25f9c8ec46f7.png)


> - Has the case that an ASCCP/ACC is a group be CONSIDERED? 1) The ASCCP cannot be top level BIE. 2) If any child or descendant properties are from group and the group is amended, those properties have to be locked in the BIE.

ASCCP has group ACC is not showing in ASCCP list of BIE creation.
