### ISSUE TITLE
Improve the real estate of the Code List UI

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1156]
Condense to Eliminate white space,  
All us to see the list and Add button without scrolling down.

![image](https://user-images.githubusercontent.com/32434235/123667487-d11e7a80-d7ff-11eb-97d7-f58bd2ba04e0.png)

**Comment by hakjuoh** [comment]
@dubnemo @kbserm 

Please review the change.

<img width="899" alt="Screen Shot 2022-07-12 at 4 42 26 PM" src="https://user-images.githubusercontent.com/16102116/178591503-28f5699b-db8b-4a7c-adc4-2cac769f3d4c.png">

**Comment by kbserm** [comment]
The new layout looks good. But I think @dubnemo also suggest to move the Add button up to the top. See below.

![image](https://user-images.githubusercontent.com/7863166/178842385-2e21faf5-325e-4854-a7e3-121022793332.png)

**Comment by dubnemo** [comment]
@kbserm good catch!

**Comment by dubnemo** [comment]
Thank you!
