### ISSUE TITLE
Cannot delete a new code list value of a code list

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1158]
The issue is that we cannot delete a new code list value from a code list. 
To reproduce the issue:
1. Create a code list 
2. Add a new code list value
3. Try to delete it. The checkbox in front of the new code list value is disabled.

This applies to both developer and end user code lists.

**Comment by rekuku** [comment]
Now, rev=1 code list value can be deleted. @asdimitriadis

**Comment by asdimitriadis** [comment]
It works well.
