### ISSUE TITLE
Provide Code Generation friendly OpenAPI Specification

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1162]
We need to provide improved code generation based on OpenAPI Specification:
- eliminate type mapping where the property types are strickly OAS primitives,
- eliminate allOf keyword (nillable is not required in JSON),
- improved format specifications for XML primitives and select derived types,
- OAS extensions per Issue #1148

I am providing these sample files, based on another project for our Supply Chain team.

**Original:**
Move-Product-Forecast-oagis-id-731dc1e7abdd4a77ac3b67f02c3611b6.yml
[Move-Product-Forecast-oagis-id-731dc1e7abdd4a77ac3b67f02c3611b6.yml.txt](https://github.com/OAGi/Score/files/6917117/Move-Product-Forecast-oagis-id-731dc1e7abdd4a77ac3b67f02c3611b6.yml.txt)
**Manual edits for the To-Be:**
Move-Product-Forecast-aggateway-implguide-oagis-openapi.yaml
[Move-Product-Forecast-aggateway-implguide-oagis-openapi.yaml.txt](https://github.com/OAGi/Score/files/6917115/Move-Product-Forecast-aggateway-implguide-oagis-openapi.yaml.txt)
**Zip file is aspnetcore code gen off Swagger Editor.**
[Move-Product-Forecast-aspnetcore-server-generated.zip](https://github.com/OAGi/Score/files/6917116/Move-Product-Forecast-aspnetcore-server-generated.zip)

Significant reduction in the number of generated classes.
This is related to #1149.

**Comment by kbserm** [comment]
First bullet can be done. Code List will be defined as Enum locally without the code list name. Or code list name (and other meta-data so chosen) can be appended to the field description? 

The second bullet will be the by product of the first bullet.

The third bullet, please provide input on other format keywords to use.

The fourth bullet, I thought we have agreed to do this in the future as part of the API Management functionality. Please clarify.

**Comment by kbserm** [comment]
This is to be implemented as Code Generation Friendly option of the Open API 3.0 expression. Please also remove "(Early Prototype)" as shown below.

![image](https://user-images.githubusercontent.com/7863166/128287122-ab57e945-ea38-48a7-b94e-784009d0bc81.png)

**Comment by dubnemo** [comment]
@kbserm I believe you are referring to the assembly of more than one BIE in an OAS specification.  
Code Gen friendly needs to eliminate the GUID from the components/schema path, or it is not useable in the IDE.  We can restrict the code gen friendly option to ONE BIE until we have API Authoring and Management.
Can this be accelerated earlier than the milestone indicated, or even a patch release?  This is **_holding up the Express Pack_**, and in my opinion, releasing the Express Pack much more important than BDT management.  
@jim-wilson-kt

**Comment by dubnemo** [comment]
@hakjuoh can you please add the link to the Google sheet here?

It seems that format of normalizedString and token are ignored by the Swagger editor code generator, so I recommend adding it and then working with the Newtonsoft team to leverage it for languages that previously have use these types for XML processing and perceive value to adding this.

Summary:
I tested this:
              properties:
                identifier:
                  type: string
                  format: normalizedString
                  example: 3005640-901
                revisionIdentifier:
                  type: string
                  format: normalizedString
                  example: '0170'
                lastModificationDateTime:
                  type: string
                  format: date-time
                  description: timestamp of last modifiation
                  example: '2020-12-18T13:52:00-05:00'

And the C# class looks good:

       [DataMember(Name="identifier", EmitDefaultValue=false)]
        public string Identifier { get; set; }

        /// <summary>
        /// Gets or Sets RevisionIdentifier
        /// </summary>
        [DataMember(Name="revisionIdentifier", EmitDefaultValue=false)]
        public string RevisionIdentifier { get; set; }

        /// <summary>
        /// timestamp of last modifiation
        /// </summary>
        /// <value>timestamp of last modifiation</value>
        [DataMember(Name="lastModificationDateTime", EmitDefaultValue=false)]
        public DateTime? LastModificationDateTime { get; set; }

        /// <summary>
        /// Gets or Sets ManufacturingParty
        /// </summary>
        [DataMember(Name="manufacturingParty", EmitDefaultValue=false)]
        public BomBomBomHeaderManufacturingParty ManufacturingParty { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BomBomBomHeader {\n");
            sb.Append("  Identifier: ").Append(Identifier).Append("\n");
            sb.Append("  RevisionIdentifier: ").Append(RevisionIdentifier).Append("\n");
            sb.Append("  LastModificationDateTime: ").Append(LastModificationDateTime).Append("\n");
            sb.Append("  ManufacturingParty: ").Append(ManufacturingParty).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
Then this:
                  properties:
                    identifier:
                      type: string
                      format: token
                      description: Manufacturer's Party Identifier
                      example: '123232'
                    name:
                      type: string
                      format: normalizeString
                      description: Name of the Manufacturer
                      example: ProTrition

And the following:
        public BomBomBomHeaderManufacturingParty(string identifier = default(string), string name = default(string))
        {
            this.Identifier = identifier;
            this.Name = name;
        }
        
        /// <summary>
        /// Manufacturer&#x27;s Party Identifier
        /// </summary>
        /// <value>Manufacturer&#x27;s Party Identifier</value>
        [DataMember(Name="identifier", EmitDefaultValue=false)]
        public string Identifier { get; set; }

        /// <summary>
        /// Name of the Manufacturer
        /// </summary>
        /// <value>Name of the Manufacturer</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BomBomBomHeaderManufacturingParty {\n");
            sb.Append("  Identifier: ").Append(Identifier).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

**Comment by dubnemo** [comment]
New OAS file
[3- DeveloperPreference - BOM - openapi.yaml.txt](https://github.com/OAGi/Score/files/6986544/3-.DeveloperPreference.-.BOM.-.openapi.yaml.txt)
Generated Java (looks good)
[java-client-generated.zip](https://github.com/OAGi/Score/files/6986545/java-client-generated.zip)
Generate C# (looks good)
[csharp-client-generated.zip](https://github.com/OAGi/Score/files/6986546/csharp-client-generated.zip)

**Comment by dubnemo** [comment]
Instead of completely scratch out (Early Prototype), lets call it "OpenAPI 3.0 (Template)" -- that gives people a feeling that there is more to come, which there is.

> This is to be implemented as Code Generation Friendly option of the Open API 3.0 expression. Please also remove "(Early Prototype)" as shown below.
> 
> ![image](https://user-images.githubusercontent.com/7863166/128287122-ab57e945-ea38-48a7-b94e-784009d0bc81.png)

**Comment by kbserm** [comment]
Mapping spreadsheet https://docs.google.com/spreadsheets/d/1BOl5Xt32h4fKYQp2B7j9XagN38fy63PgwEqGIcI0KW8/edit?usp=sharing

**Comment by dubnemo** [comment]
@kbserm 
This seems like a good regex tool: https://www.regextester.com/104044
All the OAS patterns should be using Javascript REGEX.  
I added Time REGEX to the mapping.
Entries that have been changed have been highlighted with blue as a good map, and yellow as need to review.
All the other patterns should be reviewed, perhaps we eliminate all OAGIS xbts

**Comment by kbserm** [comment]
@dubnemo Do we want to specify the OpenAPI version to 3.0.3?

**Comment by dubnemo** [comment]
@kbserm 
Sure.  Although there likely isn't any differences in the data type sections.
At some point we need to tackle 3.1, which supposedly is the harmonization of data types between OAS and JSON Schema.

**Comment by kbserm** [comment]
@dubnemo Are you done with the type mapping?

**Comment by hakjuoh** [comment]
@dubnemo Here's a sample of generated expression file.
[Move-Product-Forecast-oagis-id-a7883fb0d125444f904822b220e6da6a.yml.txt](https://github.com/OAGi/Score/files/7093682/Move-Product-Forecast-oagis-id-a7883fb0d125444f904822b220e6da6a.yml.txt)

@kbserm Would you want to put extension headers(or properties) in `info` and `paths` properties like what Scott added in the example as below
```
info:
  x-oagis-release: 10.7.1
  x-oagis-release-date: "2021-06-01"
  x-oagis-license-declaimer: "This OpenAPI Specification was generated by the NIST / OAGi Score tool, and modifications to include metadata and removal of type mappings"

paths:
  /moveProductForecast:
    post:
      x-oagis-bie-guid: Move-Product-Forecast-oagis-id-731dc1e7abdd4a77ac3b67f02c3611b6
      x-oagis-bie-date-time: 2021-07-30T12:11:00-05:00
      x-oagis-bie-version: V1
```

**Comment by kbserm** [comment]
@dubnemo I thought those extensions @hakjuoh asked is for when there is an API Management.

**Comment by dubnemo** [comment]
@kbserm no, we need those extensions in this release.

**Comment by kbserm** [comment]
@rekuku Include this behind or underneath (whichever looks better) the code gen option "(Multiple BIEs of the same Property Term is not supported)". 

@asdimitriadis Please add slightly more detail documentation to the user guide like "Multiple BIEs of the same Property Term is not supported in the Code Generation Friendly option. If multiple BIEs of the same Property Term are selected, only the one created last would be expressed."

I think @dubnemo suggested to move the whole thing underneath "Select Expression" to the third column. You can do it now if you want.

**Comment by rekuku** [comment]
Description message for "Code Generation Friendly" added.

Option box UI changed to three columns layout.
![Screen Shot 2021-09-15 at 8 38 22 PM](https://user-images.githubusercontent.com/10194354/133530945-7e44e580-8c70-4350-8b42-de1ac345c400.png)

**Comment by kbserm** [comment]
Can you move the Generate button to the bottom of the Schema Package Option group.

**Comment by rekuku** [comment]
![Screen Shot 2021-09-15 at 9 08 43 PM](https://user-images.githubusercontent.com/10194354/133533101-ccd5fcc8-fd37-41eb-b866-b20af90adae9.png)

Generate button moved.

**Comment by dubnemo** [comment]
I see we did NOT implement #1148 
@kbserm can we get that prioritized in Score 2.3 scope?
