### ISSUE TITLE
Uplifted Operation component in Production Order not expressed in either XSD or OpenAPI

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1174]
See:
https://oagiscore.net/profile_bie/edit/237
Operation was previously an Extension.  
Operation and child components are enabled, but not expressed.

![image](https://user-images.githubusercontent.com/32434235/129078674-3443ba79-6ac6-4583-8725-ffa86897605b.png)

**Comment by dubnemo** [comment]
[Production-Order-oagis-id-313b3023406d46a8b2abf5845ecade3f.zip](https://github.com/OAGi/Score/files/6970453/Production-Order-oagis-id-313b3023406d46a8b2abf5845ecade3f.zip)

**Comment by rekuku** [comment]
@dubnemo 
This is the misconnection bug between ABIE and ASBIE that occurs when the Extension subnode(Extension>Operation) is mapped to the upper node(Production Order Line>Operation).

I've updated the data, so you can normally express it now.

The fundamental resolution will be resolved in the next release or hotfix.

<img width="1090" alt="Screen Shot 2021-08-11 at 4 34 14 PM" src="https://user-images.githubusercontent.com/10194354/129099361-a4ffb4f1-fd26-4351-9cea-715463bcc26b.png">
