### ISSUE TITLE
When Creating ASCCP off ellipse, the word Details is automatically appended to the Object Term Class name

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1175]
I will record a video of this when I next create a complex ACC that requires an ASCCP.

**Comment by hakjuoh** [comment]
@asdimitriadis You could reproduce this issue as follows:

1. Create ACC. At this point, this ACC's DEN must be 'Object Class Term. Details'.
2. Click vertical ellipse over 'Object Class Term. Details' node on the tree. It shows a context menu.
3. Click 'Create ASCCP from this' menu, and click 'Create' button to confirm.

Previously, it used ACC's DEN as an initial property term of the created ASCCP. Just made a commit to fix on `develop` branch.

**Comment by asdimitriadis** [comment]
The Property Term of the ASCCP is now "Object Class Term". 
Could we please change the Property Term of the ASCCP to "Property Term"?
This will ensure consistency since when we create an ASCCP the Property Term field is "Property Term".

**Comment by dubnemo** [comment]
@asdimitriadis 
Agreed.  Double check CCTS, but I believe all properties have a Property Term.

**Comment by asdimitriadis** [comment]
It works well now.
