### ISSUE TITLE
Add number of files and directories on the Edit Module Set page

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1178]
Somewhere on the page, could we have this total? In addition to serving as a good analytics, t will be used for testing.

![image](https://user-images.githubusercontent.com/7863166/129826687-d85b3077-d4b8-453f-93aa-7f658409892f.png)

**Comment by hakjuoh** [comment]
@kbserm Now it displays total number of directories and files for the module set.

<img width="569" alt="Screen Shot 2022-06-02 at 2 00 14 PM" src="https://user-images.githubusercontent.com/16102116/171696319-b9f04a59-16e6-413c-9a84-192efcc67b59.png">
