### ISSUE TITLE
Add the number of assigned CCs to the CC assignment page

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1179]
Somewhere on the CC Assignment page, report the number of CCs already assigned to the selected module. Also fix some labels according to the image below.

![image](https://user-images.githubusercontent.com/7863166/129832379-ddb0eb8f-56ce-4be2-a835-0d1b6bf7f90b.png)

**Comment by kbserm** [comment]
The total CCs will also be used for testing. Maybe it should be shown in a separate web page component so that test script can pick up easily.

**Comment by hakjuoh** [comment]
@kbserm 

1. We've changed the title to 'Core Component Assignment' through Score 2.3 milestone.

<img width="655" alt="Screen Shot 2022-06-02 at 2 07 08 PM" src="https://user-images.githubusercontent.com/16102116/171697450-9730878d-b255-47db-9ebb-29a4f517e879.png">

2. The user can see the number of assigned components at the bottom of the data table.

<img width="1378" alt="Screen Shot 2022-06-02 at 2 07 22 PM" src="https://user-images.githubusercontent.com/16102116/171697630-68d245c4-8337-438d-b563-2d3c1b3803cb.png">

Let me know if you also want to see the total number of components right after the subtitles.

**Comment by kbserm** [comment]
@hakjuoh only fix some labels.

![image](https://user-images.githubusercontent.com/7863166/178812213-a822cff2-129f-4d4f-99f1-b0897e3465a4.png)
