### ISSUE TITLE
The BCCP root node disappears when the BDT is changed

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1182]
The issue is that the BCCP root node disappears when the BDT is changed. If I refresh the browser everything is fine.

To reproduce the issue:
1. Create a BCCP
2. Make some changes and Update it
3. Change the BDT of the BCCP
4. At this point you cannot see the root node (neither the BCCP tree)

If you refresh the browser everything works well.

**Comment by hakjuoh** [comment]
@asdimitriadis Previous logic was too carefully considered several situations to improve drawing the tree. Now it simply reloads the tree after changing the BDT and works fine.

**Comment by asdimitriadis** [comment]
It works well now.
