### ISSUE TITLE
The Property Term Field of a new ASCCP should be the same as Object Class Term

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1184]
When we create a new ASCCP its property term should be the same with the Object Class Term of its ACC. 

For instance, if we create the ASCCP by selecting the "Customer Credit. Details" then Property Term field of the new ASCCP should be "Customer Credit". 

Now, the Property Term field of any new ASCCP is "Property Term" which according to the @kbserm 's comment on issue #1175 is not correct.

**Comment by kbserm** [comment]
It is not that it is not correct. It seems to be better that way - default the property term to object class term of the ACC. My original thought was to make it "Property Term" to make sure that the user go and make change.

**Comment by kbserm** [comment]
We don't have to fix this in 2.2, if there are many places to fix.

**Comment by asdimitriadis** [comment]
it works well.
