### ISSUE TITLE
Compare in history showed incorrect content

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1185]
@hakjuoh Please take a look in the development instance right now in the Catalog Line Base. Details. Compare the latest change with the last published revision showed this.

![image](https://user-images.githubusercontent.com/7863166/131193180-9a0eacfe-be70-4508-8e3f-b068f470e489.png)

You can see that it showed "Instructions. Instruction Set" in the DEN. But the current ASCCP DEN is currently "Instructions. Instructions" if you just browse the Catalog Line Base. Details tree, you can see that. It looks like the Compare function is looking at an older revision.

**Comment by kbserm** [comment]
This is because the snapshot of the Catalog Line Base was taken before the Instruction Set changes its object class term from Instruction Set to Instructions.

We may improve/avoid this confusion by adding the current record to the top of the list. I.e., if the user select the top of the list, the compare function should pull data from the current record rather than the snapshot/history table.

**Comment by hakjuoh** [comment]
@kbserm I can't find 'Catalog Base. Details' component in a develop instance.

**Comment by kbserm** [comment]
We did some tests. Currently, the logic insert a new log record to the affected ACC's log when there is a property term change to one of its ASCCP. But it turned out this when the underlying ACC of the ASCCP changes, a new log record is not inserted to the affected ACC's log.

@hakjuoh will take out this current logic. We will try changing the behavior by adding an option to use the latest information at the top of history page of CC. When the user select this to compare with another log entry, the system dynamically generate the current info the CC using current info of dependent CCs as well. In this way, we have a more consistent logic that does not violate UoC.

**Comment by hakjuoh** [comment]
@kbserm Dynamically generating the latest information (log) for the CC will happen when the component is in WIP state. For other states, there are already generated log record by changing the state.

**Comment by hakjuoh** [comment]
@kbserm If the component is in WIP state, the log list shows 'Current' record, which is dynamically generated for the latest information.

<img width="828" alt="Screen Shot 2022-07-12 at 11 51 07 AM" src="https://user-images.githubusercontent.com/16102116/178534923-a38be619-25bf-4878-b56a-94c482010f48.png">

**Comment by kbserm** [comment]
@hakjuoh I just tried this on the test instance and did not see that Current row. 

I don't understand why showing the current row has to depends on the state of the entity in focus. This issue is more about changes in the related entities.
