### ISSUE TITLE
Express BIE function crashing when multiple users attempt to express the same BIE

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1187]
Multiple users attempted to express a 10.6 Change Item Master BIE at the same time.  The site became really slow and eventually the request timed out and an error message was shown to users.  In addition the file did not download.  When looking in the logs the following error message was present:

Each user received an error message and the logs are showing the following:
o.s.b.w.servlet.support.ErrorPageFilter  : Forwarding to error page from request [/profile_bie/generate] due to exception [Error creating bean with name 'generationContext' defined in file [/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/org/oagi/score/gateway/http/api/bie_management/service/generate_expression/GenerationContext.class]: Invocation of init method failed; nested exception is java.lang.OutOfMemoryError: Java heap space]

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'generationContext' defined in file [/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/org/oagi/score/gateway/http/api/bie_management/service/generate_expression/GenerationContext.class]: Invocation of init method failed; nested exception is java.lang.OutOfMemoryError: Java heap space

**Comment by kbserm** [comment]
@smorgan19 Could the BIE still be generated, if there is only a single user attempting?

**Comment by smorgan19** [comment]
Yes if a single user tried to download it with no other user trying it would generate at that time.  When multiple users tried in one test it crashed the container and forced a restart of the pod.  In another test it didn't crash the container, but users could still access the site.

**Comment by hakjuoh** [comment]
@kbserm We have two options; 1) increasing JVM memory in the docker container or 2) queuing requests for generating expressions. I'd like to apply the latter option because the memory consumption will always be determined by the number of concurrent users and we won't know how many users will use Score simultaneously.

**Comment by hakjuoh** [comment]
@smorgan19 We tested an issued problem and figured out that it could be tackled by allocating more memory resources onto `srt-http-gateway` container as below:
```
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 2048M
```

This setting sets the memory allocation of `srt-http-gateway` to a maximum 4G.

Please see updating instructions at [Score 2.2.0 Release Note](https://github.com/OAGi/Score/wiki/Release-Detail#upgrade) page.

**Comment by hakjuoh** [comment]
@smorgan19 Have you had the same issue after increasing the memory size?

**Comment by smorgan19** [comment]
We are no longer experiencing that issue as we switched away from the environment that the issue was present on.

**Comment by hakjuoh** [comment]
@smorgan19 Thank you for your response. I close this issue, and reopen it later if necessary.
