### ISSUE TITLE
Error when trying to view "ASCC" and "BCC" CCs in the CC list

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1189]
The issue is that when we try to view only ASCCs and BCCs in the CC list an error is returned. 
To reproduce the issue:

1. Use our migration 2.2.0 script, otherwise the issue will not happen
2. Visit the CC list page
3. Check only "ASCC" and "BCC" in the Type search field
4. Click search button

An error is returned and no CC is listed.

**Comment by rekuku** [comment]
@asdimitriadis There's a mismatch on ASCC's column. Now it fixed.

**Comment by asdimitriadis** [comment]
It works well.
