### ISSUE TITLE
End users cannot uplift a BIE that has been extended locally

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1190]
The issue is that an end user cannot uplift a BIE that has been extended locally. 
When an end user tries to uplift the BIE the page is freeze at a spinning arrow. Browser's console also returns "ERROR TypeError: Cannot read property 'path' of undefined".

**Comment by rekuku** [comment]
There's a exception handling is missed.
Now it fixed.

**Comment by asdimitriadis** [comment]
It works well.
