### ISSUE TITLE
Release Draft is not in the status drop list to filter Core Components

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1191]
Screen shot to be provide once 10.7.2 is back in Release Draft status.

**Comment by hakjuoh** [comment]
@dubnemo Could you elaborate this issue?

**Comment by dubnemo** [comment]
I flagged this for research.
The issue was created a while ago.
Scott

**Comment by dubnemo** [comment]
You clearly fixed this since 9/14/21, as the drop list now has Release Draft.  I suspect someone created a similar or overarching issue, and didn't close this one out. 

![image](https://user-images.githubusercontent.com/32434235/182454922-24a8e32a-ed3e-4e72-92e8-31c0bca9ced9.png)

I am now closing this specific issue.
