### ISSUE TITLE
Duplication property check needs enhancement

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1192]
When the user add a property to the ACC, current the application only checks whether its based ACC already has the property. However, derived ACCs need to be checked for duplicate as well. 

For example, in 10.7.2, @michaelfigura added Name to the Document Reference Base. But Online Document Reference Base already has the Name BCCP. An the Online Document Reference Base is based on the Document Reference Base. The application shouldn't allow Michael to add the Name BCCP to the Document Reference Base.

Score should report where the duplicate occurs.

![image](https://user-images.githubusercontent.com/7863166/134067615-6eb4aae6-a4cb-46a3-b0a2-ce5569031cd8.png)

**Comment by hakjuoh** [comment]
@kbserm Now the logic checks the existence of conflicts in forward/backward directions (i.e., going forward to the base / backward to children.)

Case 1) When it tries to append BCCP 'Name. Name' onto 'Document Reference Base. Details',

<img width="515" alt="Screen Shot 2022-06-02 at 10 11 14 PM" src="https://user-images.githubusercontent.com/16102116/171773372-7c44b9e8-da03-4e27-8471-c1e4795efa1a.png">

Case 2) When it tries to append ASCCP 'Sample Measure Range. Sample Measure Range' onto 'Document Reference Base. Details',

<img width="537" alt="Screen Shot 2022-06-02 at 10 10 50 PM" src="https://user-images.githubusercontent.com/16102116/171773382-91fe4066-6069-474a-a784-a46d72e4aa1c.png">
