### ISSUE TITLE
Refactor a property to a based ACC

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1193]
See https://oagiscore.atlassian.net/wiki/spaces/SCORE/pages/4189126657/Refactoring+Association.

**Comment by asdimitriadis** [comment]
It works well.

**Comment by dubnemo** [comment]
@kbserm @hakjuoh 
It is not possible to refactor a supplemental component to a based abstract ACC.

**Comment by michaelfigura** [comment]
Discussed on 2023-05-05 with @dubnemo @kbserm @hakjuoh @sfohn and we need to update the Score code to allow for the removal of associated components, or enhance the refactoring logic to allow for rebasing existing components that contain identical attributes that match the new base.
