### ISSUE TITLE
Ungroup properties

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1195]
This function is about changing a content model of some properties of an (owner) ACC. The idea is this function is available on an association to a group ASCCP in the owner ACC. Ungrouping the association to the ASCCP means refactoring to create associations  from the owner ACC directly to properties within the group.

This function was motivated by the refactoring property to based ACC use case. See issue #1193. This function can be used to resolve duplicate property from a group (without changing the underlying group ACC) when refactoring.

**Comment by kbserm** [comment]
I would put this menu item as a sub menu of Refactor. The Refactor to Base would be a sub menu as well.

I am wondering how is this shown in history.

Would canceling the revision bring the ACC back to the original state?

**Comment by asdimitriadis** [comment]
It works well
