### ISSUE TITLE
Change 'Semantic Group` type to 'Semantic' type for Group ACCs which have a base

### ISSUE THREAD

**Issue by hakjuoh** [OAGi/Score#1196]
Some ACCs in current records in Score such as `UOM Group` and `Operation Group` is mistakenly assigned as a `Semantic Group` type which initially intented to refer to <xsd:group> compositor. These components should be changed to point a `Semantic` type. The following is a list of these ACCs:

- Acknowledge UOM Group
- UOM Group
- Process UOM Group
- Cancel Acknowledge UOM Group
- Sync UOM Group
- Cancel UOM Group
- Change Acknowledge UOM Group
- Notify UOM Group
- Sync Response UOM Group
- Change UOM Group
- Show UOM Group
- Get UOM Group
- Operation Group

**Comment by hakjuoh** [comment]
@kbserm Do you think this change needs to leave a log to track an audit? If not, we can directly update records through all releases, and it makes sense to me because `Component Type` hasn't affected to any functions in Score so far. Otherwise, we need to create new release like `10.7.3` and put these changes into it.

**Comment by kbserm** [comment]
Issue file in oagis repo. https://github.com/OAGi/oagis/issues/507

**Comment by hakjuoh** [comment]
@kbserm Those are manually updated on `develop` instance using the following query:
```
UPDATE `acc` SET `oagis_component_type` = 1 
WHERE `oagis_component_type` = 3 AND `object_class_term` LIKE '%UOM Group';
UPDATE `acc` SET `oagis_component_type` = 1 
WHERE `oagis_component_type` = 3 AND `object_class_term` LIKE '%Operation Group';
```

This change will be contained in the next OAGIS release.

**Comment by hakjuoh** [comment]
@kbserm Changes applied to OAGIS 10.7.4.
