### ISSUE TITLE
Need an ability to use an end user agency ID list in the Agency ID field of the End User Code List

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1200]
There should be a button behind the Agency ID field that can pop up end user Agency ID list in the same branch to choose from. 

This button shall not appear in the end user code list amendment.

**Comment by kbserm** [comment]
There is a difficulty associated with the fact that the end user Agency ID list may be undergo amendment. To deal with this.
1. Only end user agency ID list in Production state can be selected.
2. When the user clicks the drop down menu, check to whether the agency ID list is in Production state. If not, shows a message that the user cannot change the value at this time b/c the agency ID list is being amended, i.e., not in Production state.
3. When discarding an agency ID while editing an agency ID list, references to the ID should be checked. If exist, shows an error message. If we program (1) & (2) correctly, (3) should never be reached.

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis Now there is a filter for the agency ID list in the code list editing page as below,
<img width="569" alt="Screen Shot 2022-01-31 at 2 30 33 PM" src="https://user-images.githubusercontent.com/16102116/151859856-33d262dc-0475-4b36-af8a-7f54777326d1.png">

In this example, I created 'Hakju Agency Identification' agency ID List and it has three values: "Hakju 1", "Hakju 2", and "Hakju 3". If the selected agency ID List is going to be amended, the selection will be blocked with a message as below,

<img width="628" alt="Screen Shot 2022-01-31 at 2 28 08 PM" src="https://user-images.githubusercontent.com/16102116/151860111-aaeb5ea6-7e0a-4f57-8f12-285815931b15.png">

**Comment by asdimitriadis** [comment]
It works well.
