### ISSUE TITLE
Additional qualifier should be defaulted to the front when creating a new BDT

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1201]
When creating a new BDT, qualifier should be on the front. For example, create a DT based on Tax_ Code. Type. The Qualifier field is currently defaulted to "Tax_ Qualifier". It should be "Qualifier_ Tax"

**Comment by rekuku** [comment]
![Screen Shot 2021-11-15 at 2 35 59 PM](https://user-images.githubusercontent.com/10194354/141844338-ecd162ca-89da-4d30-95a0-b6f69575de1c.png)
Fixed

**Comment by asdimitriadis** [comment]
The Qualifier was removed and there is no such defaulted term. 
Now the Qualifier field is 
[Qualifier of Based DT] (the system tokenizes qualifiers) if any, otherwise the field is empty.
