### ISSUE TITLE
Add CDT or BDT filter when selecting a base for new DT

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1202]

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis Added the following filter on the new DT creation dialog

<img width="272" alt="Screen Shot 2022-01-31 at 11 26 55 AM" src="https://user-images.githubusercontent.com/16102116/151832676-757066ca-44ef-4ba1-9a64-7676ffa87d14.png">

**Comment by asdimitriadis** [comment]
It works well
