### ISSUE TITLE
Add 'Value Domain' title to the DT detail pane

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1204]
![image](https://user-images.githubusercontent.com/7863166/141717066-5db98cf1-1fc1-4a13-b207-c514efbfefdf.png)

**Comment by kbserm** [comment]
Also where it says 'XSD Primitive' change it to 'XSD Expression'.

**Comment by kbserm** [comment]
Also in the primitive entry page where it says "XML Expression' change it to 'XSD Expression'.

**Comment by rekuku** [comment]
Changed.

<img width="961" alt="Screen Shot 2021-12-09 at 11 54 20 AM" src="https://user-images.githubusercontent.com/10194354/145440769-26f48852-6fdb-49a1-8985-00ed057b29b1.png">

**Comment by asdimitriadis** [comment]
The UI changed according to the above comments. 
So, I am closing the issues.
