### ISSUE TITLE
The ACC of an ASCCP cannot be changed. 

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1205]
The issue is that the ACC of an ASCCP cannot be changed. 
When we try to do this, nothing happens and in the gateway there is no error.

To reproduce the issue:
1. Create an ASCCP
2. Make some changes
3. Open again the ASCCP
3. Try to change the ACC. 

This issue happens to developer and end user ASCCPs
It also happens when we revise an ASCCP. That is, we cannot change the ACC of a revised ASCCP.

**Comment by rekuku** [comment]
Now it fixed. @asdimitriadis

**Comment by asdimitriadis** [comment]
It works well.
