### ISSUE TITLE
Cannot cancel a revision or an amendment of a code list

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1206]
The issue is that if we revise or amend a code list we cannot cancel it. 

To reproduce the issue
1. login in as a developer
2. revise a code list
3. make a change 
4. try to cancel the revision 

The same applies to end user code list. To reproduce the issue:
1. login in as an end user
2. create a code list and move it to Production state
2. amend the code list
3. make a change 
4. try to cancel the amendment

**Comment by rekuku** [comment]
Now it fixed.

**Comment by asdimitriadis** [comment]
It works well.
