### ISSUE TITLE
End user cannot open the Invoice BIE - 

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1208]
hangs since v2.2 Score upgrade in our on-prem instance.

![image](https://user-images.githubusercontent.com/32434235/142047870-b576572f-069a-408f-8316-51756969e8dc.png)

**Comment by dubnemo** [comment]
[oagi_LOL_2021-11-12-v2.1.zip](https://github.com/OAGi/Score/files/7549350/oagi_LOL_2021-11-12-v2.1.zip)

**Comment by DimitrijeM** [comment]
We realized that the cause of this issue is that the Invoice at **10.7.1.** has the connection to the BCCP “Payment Means Code” which doesn’t exist at this release, but at **Working** release. Given that the user is not able to add a property from different releases using UI, so far we are not sure how it happened. Currently, the assumption is that it happened during the migration from 2.1.0 to 2.2.0, but it needs to be confirmed.
Nevertheless, the following is important:
1. The same issue can’t happen at other BIEs, since the user can’t choose BCCP from different releases.
2. We confirmed that the use case when the user chooses to add property from the correct release works fine and doesn’t cause any issue.
3. This issue can’t be fixed easily because the BCCP that needs to be part of the Invoice actually doesn’t exist at this release.

I’ll talk with the development team about the possible approaches and will keep you informed.

**Comment by kbserm** [comment]
@DimitrijeM 

How did you know the problematic BIE is in 10.7.1?

Could it be that the BCCP "Payment Means Code" in 10.7.1 an end user BCCP (same name with the one in 10.7.2)?

**Comment by kbserm** [comment]
Did you investigate to whether this (the spilling of content across release) might occur during uplift?

I should note that I see Payment Means Code in 10.7.2 release.

**Comment by dubnemo** [comment]
Is it possible that I can manually delete the association via SQL, and then allow me to uplift to 10.7.2?  
or

Would it hang if I tried to uplift it without trying to open it, or would the query to retrieve its detail have the same problem?

**Comment by DimitrijeM** [comment]
@kbserm  Here are the answers on your questions:
1. How did you know the problematic BIE is in 10.7.1?
The bellow is the screenshot during my debugging, this Invoice has the same link as first screenshot that @dubnemo has posted:  `profile_bie/edit/66`
<img width="716" alt="Screen Shot 2021-11-19 at 9 45 50 AM" src="https://user-images.githubusercontent.com/22545797/142641704-12d522df-ea7d-43bc-94ba-226b5d368d91.png">

2. Could it be that the BCCP "Payment Means Code" in 10.7.1 an end user BCCP (same name with the one in 10.7.2)?
According to the database dump that @dubnemo attached, "Payment Means Code" doesn't exist at 10.7.2. Find below the query from that database that confirms it: 
<img width="453" alt="Screen Shot 2021-11-19 at 9 55 07 AM" src="https://user-images.githubusercontent.com/22545797/142643048-26b2a779-3829-487c-897a-ae77a81600c0.png">

3. Did you investigate to whether this (the spilling of content across release) might occur during uplift? I should note that I see Payment Means Code in 10.7.2 release.
Let's revisit it when I manage to find the code in that release, so far I don't see it based on this database. Please correct me if I'm wrong in the previous responses.

**Comment by dubnemo** [comment]
@kbserm @DimitrijeM could it be that there is an ownership issue bug? If I created the component  with my developer account (considering its in the working branch), and Venkat associated it, that the query to display the BIE would not allow the return of the associated components?
Or is the an end user component created in a prior version of Score?

I can going to have Venkat transfer ownership to me, and try opening it.

Either way can you try to delete the BIE association on your end, and if it opens after removal, send me the SQL to DELETE.

Keep in mind @DimitrijeM you can always reimport the DB image on your end, whereas its not on my end due to multiple users.  
I am going to be on our Thanksgiving holiday next week, but monitoring this issue, so I can update Venkat or fix it on our end.

**Comment by kbserm** [comment]
@dubnemo

@rekuku found that there were issues during upgrades that some EUCC didn't partitioned as intended. He is trying to identify the extent of the affects and coming up with a solution. We have to spend time implementing separate db schemas soon.

**Comment by dubnemo** [comment]
dump prior to Score upgrade
[oagi_LOL_2021-02-01-v2.0.zip](https://github.com/OAGi/Score/files/7626414/oagi_LOL_2021-02-01-v2.0.zip)

**Comment by dubnemo** [comment]
@kbserm @hakjuoh thank you for providing the script to recover the UDCCs.  Venkat is now able to access the Invoice BIE.
Is the removal of those UDCC a separate issue?

**Comment by kbserm** [comment]
Thanks @hakjuoh @rekuku and @DimitrijeM. 

@dubnemo you mean the loss of those UDCC? There was a flaw in the update script from 2.1 to 2.2. @hakjuoh will fix that. Also, we start investing in multiple database schemas which will make data upgrade much easier and it is also important for CI/CD.

**Comment by dubnemo** [comment]
@kbserm yes, that is was my concern. Thank you.
