### ISSUE TITLE
Branch in the Agency ID list does not follow the branch selected in CC-related pages

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1209]
The issue is that when we visit the Agency ID list page, Score does not open the page using the branch selected in another CC-related page. 

To reproduce the issue:
1. Login as a developer
2. Visit the Agency ID list page. Verify that the Working branch is selected
3. Visit the CC list page and select the 10.7.2 branch
4. Visit the Agency ID list page
5. The Working branch is selected instead of the 10.7.2 branch.

See also issue #1133

**Comment by DimitrijeM** [comment]
@asdimitriadis It should be fixed now, please test it.

**Comment by asdimitriadis** [comment]
The Agency ID list page follows the branch selected in CC-related pages. 

@DimitrijeM can you please check the opposite scenario as well?

To reproduce the issue:

1.Login as a developer
2.Visit the Agency ID list page. Verify that the Working branch is selected. Choose 10.7.2 branch
3.Visit the CC list page
5.The Working branch is selected instead of the 10.7.2 branch.

**Comment by DimitrijeM** [comment]
@asdimitriadis Now it should be fixed for the opposite direction as well, please test it.

**Comment by asdimitriadis** [comment]
It works well now
