### ISSUE TITLE
We should not be able to discard derived Agency Id list values

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1211]
The issue is that we can discard a derived Agency Id list value. 

To reproduce the issue:
1. Login in as an end user
2. Open the Agency Id list clm63055D16B_AgencyIdentification in a non-working branch (e.g., 10.7.2)
3. Create an Agency Id list based on this
4. Remove the CCC (Customs Co-operation Council) Agency Id list value

At this point, we will realize that the value is discarded. 

The expected behavior is that we should not be able to discard the derived Agency Id list values. We can use or unuse them. 
Only new values added to the Agency Id list can be discarded.

**Comment by asdimitriadis** [comment]
Also the details of the derived Agency Id list values should be locked and cannot be changed.

**Comment by rekuku** [comment]
> 3. Finally, when we create an Agency Id list based on another, there should be a "Based Agency Id list" field but is should be locked.

![Screen Shot 2021-12-07 at 12 12 37 PM](https://user-images.githubusercontent.com/10194354/145075179-b6eda2a1-5edd-448a-86c1-2c2365cf547c.png)

@asdimitriadis A field for based agency id list added.
Derived values are working the same as the codelist, so should we change the codelist side too?

**Comment by hakjuoh** [comment]
@asdimitriadis In order to tackle this issue, I added `based_agency_id_list_value_id` on `agency_id_list_value` table. Now, the agency ID list value cannot be discarded if `based_agency_id_list_value_id` is not null. Please re-import data before testing this.

**Comment by asdimitriadis** [comment]
It works well
