### ISSUE TITLE
Data too long for column 'version_id' of the Agency Id list

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1212]
The issue is that if the version field of an Agency Id list is consists of more than 11 characters and error is returned. 

To reproduce the issue:
1. Create a new Agency Id list 
2. Give an 11 character string in the version field

An backend error is returned. 

The same issue applies to both developer and end user Agency Id lists as well as when we create an Agency Id list based on another.

**Comment by rekuku** [comment]
Altering the version_id column from vachar 10 to 100, now it is same with code list's version id.
I updated the SQL in gateway repo so that you can execute the altering query in last of mig_2.2.0_to_2.3.0.sql or load oagi_2.3.0.sql.
@asdimitriadis
