### ISSUE TITLE
A deleted Agency ID list cannot be restored by another end user

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1213]
The issue is that an end user cannot restore a deleted Agency Id list that he does not own

To reproduce the issue:
1. Login as enduser1
2. Create an Agency Id list and delete it
3. Logout and login as enduser2 
4. Open the deleted Agency Id list
5. Try to delete it

The expected behavior is that any end user can restore any deleted Agency Id list onwed by a different end user. The user that restores the Agency Id list takes the ownership as well.

**Comment by hakjuoh** [comment]
@asdimitriadis Now deleted agency ID list can be restored by another user whose role is the same as the owner's role.

**Comment by asdimitriadis** [comment]
It works well
