### ISSUE TITLE
The label of the button for deleting the value domain should be changed from Delete to Discard.

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1214]
![image](https://user-images.githubusercontent.com/7863166/143893504-ebf6c12f-836d-40a9-8304-57144f97032b.png)

**Comment by rekuku** [comment]
![Screen Shot 2021-12-07 at 12 19 05 PM](https://user-images.githubusercontent.com/10194354/145075957-4c3c0e83-0260-4c23-9239-5ad824b4c831.png)

Changed.

**Comment by asdimitriadis** [comment]
I confirm that the button was changed. So, I am closing the issue.
