### ISSUE TITLE
The Qualifier field is editable regardless of the DT state and owner

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1215]
The issue is that anyone can change the Qualifier field of a DT. 

To reproduce the issue:
1. Login as a developer
2. Open a DT owned by a different user/developer (e.g., the published "Numeric. Type" DT)
3. Add a new qualifier 

The expected behavior is that the Qualifier field should be editable only by the owner and when the DT is in the WIP state

**Comment by hakjuoh** [comment]
@asdimitriadis A checking condition was missed. Now it's disabled when it is in WIP state or it doesn't have a right ownership.

**Comment by asdimitriadis** [comment]
It works well
