### ISSUE TITLE
Commenting functionality on new DTs does not work

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1216]
The issue is that one cannot leave a comment on newly created DTs but only on Published ones. 

To reproduce the issue:
1. Login as devx
2. Create the DT1
3. Logout
4. Login as devy
5. Open DT1
6. Try to add a comment

**Comment by hakjuoh** [comment]
@asdimitriadis There was a wrong explicit casting in codes and fixed it.

**Comment by asdimitriadis** [comment]
It works well.
