### ISSUE TITLE
Cannot add more than one value domain to a DT

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1218]
The issue is that in a newly created DT we cannot add a second value domain. 
To reproduce the issue:

1. Login as a developer
2. Create a DT
3. Click Add button
4. Choose CodeList as Value Domain Type and select a code list from the list of the Name column
5. Click Update
6. Click Add button

At this point, although a second value domain is added the Update button does not work. Therefore, the second value domain cannot be added.

**Comment by hakjuoh** [comment]
@asdimitriadis You mean you choose the code list that already added? Like adding two same code lists?

**Comment by asdimitriadis** [comment]
The issue is that we cannot add two or more different value domains to a DT.
For instance, two different code lists. 

To reproduce the issue:

1. Login as a developer
2. Create a DT
3. Click Add button
4. Choose CodeList as Value Domain Type and select a code list from the list of the Name column
5. Click Update
6. Click Add button again
7.  Choose CodeList as Value Domain Type and select a code list that is different to the one of step 4
6. Try to click Update button. 

The Update button is disabled. 
If you make a change to another field (e.g., definition) the Update button becomes enabled. Click it. It seems that the second code list of Step 7 is added. However, if you reopen the DT, the code list added at Step 7 is not there.

**Comment by hakjuoh** [comment]
@asdimitriadis There was a bug that updates value domains only added at first. Please review it again.

**Comment by asdimitriadis** [comment]
@hakjuoh now it works well and I can add a second value domain

However, I cannot change it. To reproduce the issue:
1. Add one or two value domain to a DT
2. Click Update button
3. Reopen the DT
4. Make a change to a value domain (e.g., select a different code list)
5. Click Update button
6. Reopen the DT
At this point the change is not stored

**Comment by asdimitriadis** [comment]
Also I just noticed that we can add two exactly same value domains like you mentioned in you comment above. 

> You mean you choose the code list that already added? Like adding two same code lists?

**Comment by asdimitriadis** [comment]
It works well.
