### ISSUE TITLE
Qualifier field of the DT does not work well

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1222]
Taking for example when I create a new DT based on Tax_ Code, the default qualifiers are `Qualifier` and `Tax`. I had to delete `Qualifier` in order to add a qualifier. A new qualifier added can be added only after the `Tax` qualifier, while it should be in front - this is the problem.

**Comment by hakjuoh** [comment]
@kbserm I changed the field to a typical input field, but one thing that the user must know about CCTS DEN rule that all tokens should be separated by '_ ' (underscore and a blank char).

<img width="206" alt="Screen Shot 2022-01-31 at 11 01 27 AM" src="https://user-images.githubusercontent.com/16102116/151828370-8c8481fc-38d1-4839-ac0d-76a5503c2144.png">

**Comment by asdimitriadis** [comment]
It works well.
