### ISSUE TITLE
Derived code lists values can be removed

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1224]
The issue is that code list values that are derived from the base code list can be removed. 

The expected behavior is that we cannot removed derived code list values.

**Comment by dubnemo** [comment]
Why do you believe that is the expected behavior?   If this relates to user
defined code list derived from existing code lists, I expect to be able to
define a subset of the list.  No different than profiling a BIE,
specifically related to a business context.

**Comment by kbserm** [comment]
You can't delete but you can restrict

**Comment by dubnemo** [comment]
Not sure what the difference is. And I have not seen the current UI.

I envision a shuttle control, where the base code list is on the left, and
I can shuttle those I need in my copy to the right.  If it is based on an
agency such as UN/CEFACT, and if I need more code entries that UN/CEFACT
does not cover AND I want to submit my codes to  UN/CEFACT in the future, I
should be able to add my own and discern which would be pending submission
likely through own agencyIdentifier.
Food for thought.

**Comment by hakjuoh** [comment]
@asdimitriadis Now checkboxes for derived code list values are disabled to block to be removed.
<img width="181" alt="Screen Shot 2022-01-31 at 10 51 34 AM" src="https://user-images.githubusercontent.com/16102116/151826534-a5ee4290-a1a7-4bf2-8349-ee66bbb12b88.png">

**Comment by asdimitriadis** [comment]
It works well.
