### ISSUE TITLE
When we restore a deleted DT the owner does not change and we have to reopen it

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1225]
The issue is that when we restore a deleted DT the owner field does not change and we have to reopen the DT

To reproduce the issue:
1. Login as devx
2. Create a DT
3. Delete it
4. Login as devy
5. Open the deleted DT and restore it

At this point, the owner field is devx and not devy
If you reopen the DT the owner field becomes devy

**Comment by rekuku** [comment]
Now it reloads the details after restoring it.

**Comment by asdimitriadis** [comment]
It works well.
