### ISSUE TITLE
The Namespace and Content Component Definition are not derived from the based DT

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1226]
The issue is that Namespace and Content Component Definition fields of a brand-new DT are always blank. 

The expected behavior is these fields of a brand-new DT should be the same as the based DT. 
We should be able to change them though. 

One example to reproduce the issue related to namespace is the following:
1. Login either as a developer or as end user
2. Create a DT selecting the "Sales Activity_ Code. Type" BDT

At this point the namespace field of the new DT is blank. It should be the same with "Sales Activity_ Code. Type" BDT's namespace. 
The field should be also enabled.

**Comment by rekuku** [comment]
Now ContentComponentDefinition is copied from based DT.

But for the namespace, If the end-user create a bdt based on developer's bdt that bdt must have a standard namespace.
And this standard namespace can not be used for end-user bdt.
What do you think about it? @asdimitriadis

**Comment by asdimitriadis** [comment]
The expected behavior is:
1. For the developers: The Namespace should be the namespace of the based DT
2. For the end users: The Namespace should be empty.

**Comment by hakjuoh** [comment]
@asdimitriadis Now the new BDT will have the same namespace with the base DT.

**Comment by asdimitriadis** [comment]
It works well.
