### ISSUE TITLE
The Property Term field of a newly added SC to a DT is not unique 

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1227]
The issue is that the Property Term field of a newly added SC to a DT is not unique 

The Property Term field should be “Property Term” + [a number]. 
The number ensures the Property Term is unique. 

The Property Term field should be mandatory, namely, it cannot be left blank. 
Now, if I remove the value of this field, my browser freezes. I tried to clear the cache, but if it happens again.

**Comment by hakjuoh** [comment]
@asdimitriadis The property term for new SCs now have assigned an unique property term value like 'Property Term 1', 'Property Term 2', so on. It also fixes the freezing problem when the property term changed to the empty.

**Comment by asdimitriadis** [comment]
It works well
