### ISSUE TITLE
Qualifier cannot be left empty if the base DT does not have a qualifier

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1228]
The issue is that the Qualifier field cannot be left empty if the base DT does not have a qualifier.

To reproduce the issue:
1. Create a new DT based on the "Amount. Type" which has qualifier=null
2. Make some changes but leave qualifier empty
3. Try to update it

At this point an error is returned saying that the qualifier cannot be left empty

The expected behavior is:

- if the base DT already has a qualifier the new DT must have at least one qualifier. In this case, Score works well. 
- if the base DT does not have any qualifier, the qualifier field can be left empty. In this case, Score does not work as expected.

**Comment by hakjuoh** [comment]
@asdimitriadis Now it is working as expected.

**Comment by asdimitriadis** [comment]
It works as expected. The qualifier can be left empty if the base DT does not have a qualifier. 

However, in the Core Component list page I can see a "null" value in the DEN column. 

![image](https://user-images.githubusercontent.com/37205288/152444206-f91a2b25-08d8-49ca-910b-81841580da3e.png)

@hakjuoh could you please check it?

**Comment by hakjuoh** [comment]
@asdimitriadis It was putting a 'null' value into the qualifier column when it has an empty string. Now it fixed. Please review it again.

**Comment by asdimitriadis** [comment]
It works well.
