### ISSUE TITLE
Representation Term field of a SC can be left blank

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1229]
The issue is that the Representation Term field of a SC can be left blank.

To reproduce the issue:
1. Create a new DT
2. Add a SC to it
3. Select a representation term (e.g., Binary Object)
4. Update the DT
5. Change the representation term field to empty (there is an empty option in the list)
6. Update the DT

At this point the Representation Term field of the SC is empty. 

The expected behavior is that this field should not be empty. 
To ensure that when we add a new SC to the DT we can also set the Representation Term field to a default selected value (e.g., to Amount).

**Comment by hakjuoh** [comment]
@asdimitriadis Now you could see the representation term including corresponding value domains.

**Comment by asdimitriadis** [comment]
It works well
