### ISSUE TITLE
Cannot discard a brand new SC from a DT

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1230]
The issue is that cannot discard a brand new SC from a DT.

To reproduce the issue:
1. Create a DT
2. Add a SC
3. Update the DT
4. Try to discard it

An error is returned.

**Comment by hakjuoh** [comment]
@asdimitriadis It happened when the DT has derived ones. Now it has fixed.

**Comment by asdimitriadis** [comment]
It works well.
