### ISSUE TITLE
The Default value of a SC is not propagated to DTs 

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1233]
The issue is that the Default value of a SC of a DT (e.g., DT1) is not propagated to other DTs that are based on DT (i.e., DT1)

To reproduce the issue:
1. Create a DT (e.g., DT1)
2. Add a SC (e.g., SC1)
3. Change the Default value of SC1
4. Create a DT (e.g., DT2) based on the DT1
5. Click at SC1 to view its details

At this point there is no Default value in the SC1.

The same issue applies to both developer and end user DTs

**Comment by hakjuoh** [comment]
@asdimitriadis Please check this function again. I tried to the following steps, but it works well.

1) Create new DT using a based DT 'Open_ Amount. Type'.
2) Create new SC.
3) Change the property term of the new SC to 'Date'.
4) Change the representation term of the new SC to 'Date Time'.
5) Change the value constraint of the new SC to 'Default - a'
6) Create new DT using a based DT created in 2)
7) Click 'Amount. Date. Date Time' SC.

**Comment by asdimitriadis** [comment]
@hakjuoh the value constraint work well. 

Can you please try change the default value of the value domain?

**Comment by asdimitriadis** [comment]
@hakjuoh, they both work well. I am closing the issue.

**Comment by asdimitriadis** [comment]
I am reopening the issue since the default value of the value domain is not propagated to the derived DT.

To reproduce the issue :

1. Create DT1 using a based DT 'Open_ Amount. Type'.
2. Add a new SC.
3. Change the representation term of the new SC to 'Date Time'.
5. Change the default value domain of the new SC to 'TimePoint - time'
6. Create DT2 using a based DT created in 1 (i.e., DT1)
7. At this point the default value domain of SC of step 2 is 'TimePoint - time'
8. Open DT1 again
9. Open the SC of step 2 and change the default value domain to "TimePoint - gregorian year month"
10. Update it
11. Open DT2
12. At this point the default value domain of SC of step 2 is 'TimePoint - time'. It should be "TimePoint - gregorian year month"

**Comment by hakjuoh** [comment]
@asdimitriadis Just updated a relevant logic. Please review this issue again.

**Comment by asdimitriadis** [comment]
It works well
