### ISSUE TITLE
If a BCCP has a value constraint defined, it is not shown in the BIE side

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1234]
The issue is that if a BCCP has a value constraint (e.g., Default value) defined then in the BIE it is not shown. However, it correctly says that the value constraint cannot be modified.

One example to reproduce the issue:
1. Login as developer
2. Open the BCCP "Scenario Identifier" and revise it
3. Change the Value Constraint to Default and set a value (e.g., 9)
4. Move the BCCP to the Candidate state
5. Create a new release (e.g., 10.99) and include the "Scenario Identifier"
6. Create a BIE from this release (10.99) (e.g., Get BOM)
7. Expand the BIE tree and visit the  "Scenario Identifier"

At this point the Value Constraint is disabled (correct) but the Default value (e.g., 9) is not shown in the field.

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis Found a structural issue. We now have a default value and a fixed value properties in both BCC and BCCP, and we've used it for only BBIE, not BBIEP.

Take a look at this:
![Screenshot 2022-01-05 132541](https://user-images.githubusercontent.com/16102116/148269131-9e93d796-ac10-4285-a724-155066ef71f7.png)

After revising the component through the example steps, 'Scenario Identifier' BCCP now has a default value '9', but 'Application Area Base. Scenario Identifier. Identifier' BCC does not have it.

**Comment by hakjuoh** [comment]
@asdimitriadis Now, if the BCCP has either a 'Default Value' or a 'Fixed Value' constraint, it will apply to BBIE even if the BCC doesn't have it. Please review it.

<img width="925" alt="Screen Shot 2022-02-21 at 10 21 11 AM" src="https://user-images.githubusercontent.com/16102116/154983657-a6b13dcb-86b5-41fd-bb6f-f01fd9cf258b.png">

**Comment by asdimitriadis** [comment]
It works well.
