### ISSUE TITLE
Changes in an inherited SC of a DT are not allowed

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1235]
The issue is that the following changes in an inherited SC are not allowed:

1. We cannot add a Value Domain even if there is a Token CDT Primitive in the existing value domain. The Add button is disabled. The expected behavior is that we can add a Value Domain to an inherited SC when there is a Token CDT Primitive in the existing value domain. Such locally-added Value Domain can be discarded. 
2. We cannot change the Default Value Domain. The expected behavior is that it can be changed. 
3. Value Constraint, Definition, and Definition Source cannot be edited. The expected behavior is that they can be edited.

Note that the above-mentioned changes, _except Definition and Definition Source_, must also be made to the corresponding SC in all DTs derived from this DT. Note that any restriction put upon this SC in the derived DT would be lost. There should be a confirmation dialog indicating this when the Update button was clicked – “Extensions and restrictions applied to this SC in all DT derived from this DT will be lost”.    
Definition and Definition Source shall be propagated only if they were the same before the change. In other words, if the Definition and Definition Source have been altered in the derived DTs before the change in this DT, leave the one altered alone

**Comment by hakjuoh** [comment]
@asdimitriadis
Now, 'Add' / 'Remove' buttons on 'Value Domain' panel show up only if it has 'Token' primitive. Also, other properties such as Value Constraint, Definition, Definition Source can be changed.

**Comment by asdimitriadis** [comment]
It works well.
