### ISSUE TITLE
Invalid Certificate Errors on oagiscore.net

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1237]
HTTPS is being disabled due to invalid cert.

"This server could not prove that it is oagiscore.net; its security certificate expired 2 days ago."

**Comment by dubnemo** [comment]
Gateway Connection Errors too.  CTRL-SHFT-R cache refresh does not help.

**Comment by hakjuoh** [comment]
@dubnemo Thanks for your feedback. It happened because of expired SSL certificates for `oagiscore.net` and `develop.oagiscore.net` instances. I just renewed and worked well.
