### ISSUE TITLE
Code Lists and Agency ID lists are not included in a new release

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1239]
The issue is that if we create a new release, the code lists and agency ID lists are not included. 

One example to reproduce the issue is the following:
1. Create a new release
2. Move the release to Draft state
3. Go to Core Component-> View/Edit Code List
4. Select the new release

At this point there is no code list listed in the new release

**Comment by hakjuoh** [comment]
@asdimitriadis It's happened by a wrong data dump file. Please re-import 2.3.0 data into your DB and try it again.
