### ISSUE TITLE
A DT can have SCs with same DENs 

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1240]
The issue is that we can have multiple SCs with same DENs if those SCs are derived from the based DT.

To reproduce the issue:
1. Create DT1
2. Create DT2 using DT1
3. Add a SC to DT2 with the DEN "Code. Unique Derived SC. Date Time"
4. Open DT1 again and add a SC with  the DEN "Code. Unique Derived SC. Date Time"
5. Open DT2 again

At this point the DT2 has 2 SCs with same DEN

**Comment by hakjuoh** [comment]
@asdimitriadis Now when it tries to create a duplicated SC, it shows the following error message:
<img width="544" alt="Screen Shot 2022-01-24 at 2 37 26 PM" src="https://user-images.githubusercontent.com/16102116/150852194-9b321f36-40e9-42e4-b22b-007e0e509e7f.png">

**Comment by asdimitriadis** [comment]
@Hakju sorry but I just realized that we need the Property Term of the SC to be unique. 

The test assertion is that the Property Term should be unique across all DT derived from this DT as well as within the DT itself. That is why we have this number added in the Property Term in issue #1227. 

So the Property Term of an SC should be unique across all DT derived from this DT as well as within the DT itself.

**Comment by hakjuoh** [comment]
@asdimitriadis I don't know how we can make duplicated property terms along with breaking DEN uniqueness.

**Comment by asdimitriadis** [comment]
@hakjuoh can you try to add in a DT these two SCs?
- Code. Property Term 1. Amount
- Code. Property Term 1. Date Time

The SC's property terms are the same. 

The property term shall be unique across all DT derived from this DT as well as within the DT itself

**Comment by hakjuoh** [comment]
@asdimitriadis Now it shows an error message when there is duplicated property terms in SCs as below,
<img width="512" alt="Screen Shot 2022-02-01 at 12 03 10 AM" src="https://user-images.githubusercontent.com/16102116/151915285-18fadeeb-2e27-4b4d-bdf8-1ccac6a64a41.png">
