### ISSUE TITLE
A default value domain of an SC can be deleted

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1242]
The issue is that we can delete a value domain if it is selected as the Default value domain

To reproduce the issue:
1. Add an SC to a DT
2. Add a new value domain - VD1
3. Update the DT
3. Set VD1 as the default value domain
4. Update the DT
5. Delete the VD1

At this point the VD1 is deleted. The expected behavior is that we cannot delete a value domain if it is selected as the Default value domain.

Note that the Steps 3 and 4 are important to reproduce the issue.

**Comment by hakjuoh** [comment]
@asdimitriadis Now, deleting the default value domain is blocked.

<img width="461" alt="Screen Shot 2022-01-24 at 11 29 50 AM" src="https://user-images.githubusercontent.com/16102116/150823717-e6eeebb6-3ffc-4e9a-a0d6-37b3d25585e6.png">

**Comment by asdimitriadis** [comment]
It works well.
