### ISSUE TITLE
The Qualifier, Six Hexadecimal Value and Namespace of a revised DT can be changed

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1244]
The issue is that the Qualifier, Six Hexadecimal Value and Namespace fields of a revised DT are editabled. 

To reproduce the issue:
1. Login as a developer
2. Open a published DT in the Working branch
3. Revise the DT
4. Change the Qualifier or the Six Hexadecimal Value or the Namespace fields.

At this point the Qualifier, Six Hexadecimal Value and Namespace fields are editable. 

The expected behavior is that the QQualifier, Six Hexadecimal Value and Namespace fields of a revised DT cannot be changed. These fields 
should be disabled.

**Comment by hakjuoh** [comment]
@asdimitriadis Now namespace, qualifier, and six hexadecimal digits are disabled if the DT has revised.

**Comment by asdimitriadis** [comment]
It works well
