### ISSUE TITLE
Interval Server Error 500 Updating context scheme with new value

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1245]
https://oagiscore.net/context_management/context_scheme/11

Cannot add a new Context Scheme Value to an existing context scheme

**Comment by kbserm** [comment]
@dubnemo can u try again, maybe session timeout or certificate expired. I tried added a value it was fine. you can see "serm test" value and can remove it.

**Comment by dubnemo** [comment]
@kbserm 
I tried it on the same scheme 11 on a different computer, and got the same error.
Server Internal Error: Http failure response for https://oagiscore.net/api/context_scheme/11: 500 OK

**Comment by dubnemo** [comment]
![2022-01-09-090330_1920x1080_scrot](https://user-images.githubusercontent.com/32434235/151665175-64821d4b-0a17-44e4-a532-c9478faeaa8f.png)

**Comment by dubnemo** [comment]
![2022-01-29-083805_1920x1080_scrot](https://user-images.githubusercontent.com/32434235/151665194-21678a4a-f49c-48a8-aafe-203809dbcd8e.png)

**Comment by dubnemo** [comment]
@kbserm @hakjuoh 
Can you see why there are multiple scheme values listed for Receive Work Order and others?  
Is this somehow related to uplifted BIEs?  There should be **only one reference** to the same value across BIEs in any release.  Business Context is completely independent of the BIE instances.

**Comment by hakjuoh** [comment]
@dubnemo Thank you for your reporting! We found a bug that it showed multiple scheme values if the value has used in multiple business contexts. Fortunately, it's only a SQL query issue, so the data in DB are clean. We're working on it now.

**Comment by DimitrijeM** [comment]
@dubnemo  The issue is fixed and an update will come with the 2.3 version. @asdimitriadis  Please test it.

**Comment by asdimitriadis** [comment]
It works well.
