### ISSUE TITLE
Cannot remove a brand new Agency ID list value

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1250]
The issue is that once we cannot an Agency ID list value that it was just added.

To reproduce the issue:
1. Login as an end user
2. Create a new Agency ID list
3. Add a new value
4. Click update button
5. Remove the value

At this point the Agency ID list value cannot be removed. 
This issue applies to developers as well. To reproduce it:
1. Login as a developer
2. Open the existing Agency ID list in the Working branch
3. Revise it
4. Add a new value
5. Click Update
6. Try to remove it. 

At this point the checkbox and the Remove button are disabled. 

Note that if the value is used in the Agency ID field, it should not be able to be removed. In that case, the checkbox in front
of the value should be disabled.

**Comment by hakjuoh** [comment]
@asdimitriadis Now both developers and end-users can delete the agency ID list value. Please review it.

**Comment by asdimitriadis** [comment]
A brand-new agency ID value can be removed now. 
However, we can remove an agency ID value even if it is used in the Agency ID field of the Agency ID list. 

To reproduce the issue:
1. Login as an end user
2. Create an Agency ID list
3. Add a value
4. Update the Agency ID list
5. Select the value added in Step 3 in the Agency ID field
6. Remove it

At this point the value is removed from the UI. If you refresh the browser, it is shown again. 
The expected behavior is that if a new value is used in the Agency ID field, it cannot be removed. For instance, we can disable the checkbox in front of the value.

**Comment by hakjuoh** [comment]
@asdimitriadis This happened in only UI. If you clicked the 'Update' button, it would show the following message,
<img width="408" alt="Screen Shot 2022-03-14 at 10 15 31 AM" src="https://user-images.githubusercontent.com/16102116/158190713-195858d4-b894-4917-9a6f-f7ec95d24776.png">

Nevertheless, the selection box is disabled if the row is used in 'Agency ID' field.

**Comment by asdimitriadis** [comment]
It works well
