### ISSUE TITLE
Cannot discard a newly added value domain from an SC of a DT

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1252]
The issue is that we cannot discard a value domain from an SC of a DT. 

To reproduce the issue:
1. Login as developer
2. Create a new DT
3. Add a new SC to the DT
4. Add a value domain value to that SC
5. Click Update
6. Try to Discard the value of Step 4

At this point the Discard button does not work. 

Note that this issue applies to end users as well.

**Comment by hakjuoh** [comment]
@asdimitriadis There was a wrong statement for testing, and removed it now. Please review it again.

**Comment by asdimitriadis** [comment]
It works well
