### ISSUE TITLE
'OAGIS10 Nouns' filter for the component type field in the CC list page is showing 14k results.

### ISSUE THREAD

**Issue by hakjuoh** [OAGi/Score#1255]
@michaelfigura reported this:

In order to search 'Noun' components, 'OAGIS10 Nouns' filter was used for the component type field in the CC list page. But it showed 14k results.

<img width="931" alt="Screen Shot 2022-03-10 at 10 04 31 AM" src="https://user-images.githubusercontent.com/16102116/157690348-cc086bec-9c41-44f9-a979-8a92687e9e6b.png">

- It's because we used the component type field as an additional filter for the 'ACC' type, and it does not apply to the results if there is no 'ACC' type filter. @kbserm Do we need to change the behavior of the component type field in filters? But the real problem was that there's no function to search 'Noun' components.

**Comment by kbserm** [comment]
When the Tagging function is there, it will be possible.

**Comment by hakjuoh** [comment]
#1047
