### ISSUE TITLE
Restricting a derived Agency ID list

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1256]
The issue is that the values inherited from the based Agency ID list cannot be restricted. 

To reproduce the issue:
1. Login as an end user
2. Create an Agency ID list from the existing developer Agency ID list
3. Try to Use/Unuse a value

At this point there is no such option. 

The expected behavior is that we should Use/Unuse the values inherited from the based Agency ID list should based on the following rules:
1. If the value was Used, then we can Unuse it.
2. If the value was Unused, then we cannot Use it.

Note that we have a Use/Unuse flag in Code Lists. Also note that **the above-mentioned behavior is for derived Agency ID lists** only. That is, the Revise/Amend functionalities works well.

**Comment by hakjuoh** [comment]
If the agency ID list value is checked as a non-used, it MUST not be shown on the 'Agency ID' field in the agency ID list editing page, the 'Agency ID List Value' field in the code list editing page, and schema expressions.

**Comment by asdimitriadis** [comment]
We handle derived values as new ones, so I am closing this issue.

The expected behavior is:

"For the Agency ID List Value inherited from the based Agency ID List,
the values can be removed and changed if revision = 1"

"For the Agency ID List Value inherited from the based Agency ID List,
the values cannot be removed if revision > 1)
However, their Meaning, Definition, and Definition Source fields can be changed."
