### ISSUE TITLE
Create a code list based on a deprecated code list is flagged as deprecated 

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1257]
The issue is that when we create a code list based on a deprecated code list is flagged as deprecated. 

Expected behavior:
Since it is a new code list it should not be flagged as deprecated even if it is derived from a deprecated code list.

**Comment by hakjuoh** [comment]
@asdimitriadis The `deprecated` property won't be forwarded to the derived one.

**Comment by asdimitriadis** [comment]
It works well
