### ISSUE TITLE
Module Set Release Uniqueness

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1259]
Right now a Module Set Release with duplicate Module Set and Release can be created. I am not sure if this should be allowed. If it is allowed, Module Set Release should have its own Name column. I looked at the DB schema and there is Name column. Right now the UI shows the name of Module Set as if it is the Name of the Module Set Release.

I think I might have said that duplicate Module Set and Release entries are allowed. Or at least I don't see technically the need to restrict it. So if we go this route, the Module Set Release should have a required name column. Without that it will be confusing on the UI. See below.

![image](https://user-images.githubusercontent.com/7863166/158597386-15ba0525-6262-4a22-8b24-3631d0feb862.png)

**Comment by hakjuoh** [comment]
@asdimitriadis Now, the module set release has the `name` field. When the `name` field is empty during creation, it copied from the `module_set`.`name`.

<img width="395" alt="Screen Shot 2022-04-05 at 1 38 50 PM" src="https://user-images.githubusercontent.com/16102116/161816875-16ec2731-f8c4-4630-8201-d2e757ebfd6f.png">

**Comment by kbserm** [comment]
@hakjuoh this approach seems a bit unnatural. The Name field is required in general. If we want to default the Name field to the Module Set name, we should but the Name field after the Release field and populate it after the Module Set is selected. Plus I would default the name to [Module Set Name] + "Module Set Release" with the truncation of if the end of the Module Set Name overlaps with the "Module Set Release" string.

**Comment by asdimitriadis** [comment]
The name of a Module Set Release works as described in the above comment and in issues #1276  and #1277.

However, we are still able to create 2 module set releases with the same name. Should we allowed or not?

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis Please review the following messages.

<img width="730" alt="Screen Shot 2022-04-20 at 11 12 39 AM" src="https://user-images.githubusercontent.com/16102116/164264598-c52ad4a8-5b5a-4fdb-950d-677bc8e8d568.png">

<img width="729" alt="Screen Shot 2022-04-20 at 11 15 40 AM" src="https://user-images.githubusercontent.com/16102116/164264608-1cc925c8-5ba9-4571-b426-676ce18ff174.png">

**Comment by hakjuoh** [comment]
@asdimitriadis Please see dbd2964d commit, and test it.

**Comment by asdimitriadis** [comment]
It works well.
