### ISSUE TITLE
There is no confirmation dialog when discarding a Module Directory that contains a Module Set assigned to a CC 

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1261]
The issue is that there is no confirmation dialog when discarding a Module Directory that contains a Module Set assigned to a CC. 

To reproduce that issue:
1. Create a Module Set that contains the Module Directory "Nouns"
2. Add the Module File "BOM" to the Module Directory "Nouns"
3. Create a Module Set Release and assign a CC to the Module File "BOM"
4. Go back to the Module Set and discard the Module Directory "Nouns"

At this point there is a dialog asking to confirm our intension for discarding the Module Directory "Nouns". However, there is no information saying that the assignments to the CCs will be discarded as well since the Module Directory "Nouns" contains the Module File "BOM" which has an assigned CC. 
The same applies to the scenario of discarding a Module Directory that contains a Module Directory that contains a Module Set assigned to a CC 

This dialog exists if you try to discard the Module File "BOM". Please see the attached figure. 

![module](https://user-images.githubusercontent.com/37205288/158847597-030019ac-6071-4885-9148-7fc5733527c9.png)

**Comment by hakjuoh** [comment]
@asdimitriadis When I attempt to discard 'Nouns' module directory, the following dialog displays:
<img width="735" alt="Screen Shot 2022-03-22 at 9 34 43 PM" src="https://user-images.githubusercontent.com/16102116/159604428-766c75c0-8791-4154-be70-8732d56ba965.png">

It seems like we need to update messages that appear in all dialogs in regard to Module management.

**Comment by asdimitriadis** [comment]
It works well.
