### ISSUE TITLE
Unable to use a reuse BIE for Document Reference component 

### ISSUE THREAD

**Issue by joshklm** [OAGi/Score#1262]
There's a Document Reference BIE profile created and reused in several BIEs (Some are Item Master, some are BOM). 

Try to use the same Document Reference BIE as a reuse BIE for Document Reference component under Item Instance. When select Reuse BIE under Document Reference, the existing Document Reference BIE profile doesn't show up as a selection in the available BIEs list for Document Reference component even those the BIE is available and in Production state for the same OAGIS release.

**Comment by kbserm** [comment]
@joshklm are you saying that the issue is present only for Item Instance? I. E., Document Reference showed up fine when you are reusing it in another BIE?

**Comment by joshklm** [comment]
@asdimitriadis Checked the BIE and it was owned by an end user. The BIE that it was going to reuse was owned by the same end user.

**Comment by joshklm** [comment]
@kbserm For now, it was the Item Instance trying to reuse the Document Reference BIE that was reused under Item Master and BOM.

**Comment by joshklm** [comment]
@asdimitriadis @kbserm I have tried reusing the BIE created by end user, within a BIE being worked by end user. And it seems to be working correctly. So unless there's a good way to make developer user and end user BIEs to be able to reuse BIEs from the other side, we can close this issue. But, in order to minimize future confusion, it would be better to show a BIE property with some flags to indicate the characteristics that affect the reuse compatibility. And some info in the Help documentation would be helpful for users as well.

**Comment by hakjuoh** [comment]
> [B]ut, in order to minimize future confusion, it would be better to show a BIE property with some flags to indicate the characteristics that affect the reuse compatibility. And some info in the Help documentation would be helpful for users as well.

@kbserm Please let me know if you have any idea about this.

**Comment by kbserm** [comment]
@hakjuoh @elena-jelisic @joshklm I emphasized this constraint on the BIE Reuse section in the user guide and also added more clarification. In fact, a general understanding about sharing/accessing End User and Developer content should already help Score users guess/understand this behavior.
