### ISSUE TITLE
Cannot deprecate Code List and agency ID list values from previous revision

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1263]
The issue is that we cannot deprecate Code List and agency ID list values from previous revision

To reproduce the issue (this is an example in code list but the same logic applies to agency ID list):
1. Login as end user
2. Create a code list and add a new value
3. Move the code list to production state
4. Amend the code list
5. Try to deprecate the value added in the previous revision

At this point the deprecated checkbox is disabled 

The expected behavior is:
"If the Deprecated was already True in the previous revision,
 the field should be locked. 
If it was False before the amendment/revision the checkbox shall be enabled."

The same applies to developer code lists. 
To reproduce it:
1. Login as developer
2. Open a code list in Published state in Working branch
3. Revise it
4. Try to deprecate a value of the previous revision

At this point the deprecated checkbox is disabled 

The same issue applies to agency ID lists since the logic is the same.

**Comment by hakjuoh** [comment]
@asdimitriadis 
`Deprecated` property should be enabled only if the rev # is greater than 1 and the previous value was False.
Just applied this logic. Please review it.

**Comment by asdimitriadis** [comment]
it works well
