### ISSUE TITLE
Disappearing 'Create Extension component' menu after setting a base to ACC

### ISSUE THREAD

**Issue by hakjuoh** [OAGi/Score#1268]

**Comment by hakjuoh** [comment]
@asdimitriadis Previously, the logic checked the existence of 'Extension' component in a recursive manner. When the user set a base ACC, it mostly had an 'Extension' component in its hierarchy. That's the reason 'Create Extension component' menu was disappeared after setting the base. Now, the recursive searching is removed to check the existence of the 'Extension' component.

**Comment by asdimitriadis** [comment]
It works well
