### ISSUE TITLE
If the developer Agency ID list is being revised, developers cannot choose Agency ID list values in their Code Lists

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1270]
Now we have only one Agency ID list and developers cannot create a new Agency ID list. Considering that, if the developer Agency ID list is being revised, developers cannot choose Agency ID list values in their Code Lists.
The Agency ID list field is blocked in the UI, and it can be enabled only if the Agency ID list is in Published state. However, if the Agency ID list is being revised it cannot be moved to Published state. 
Please see the attached screenshot. 

This behavior works for end users because an End User Agency ID list can be move to the Production state. When an Agency ID list is in Production state, end users can use this Agency ID list in their Code lists. 

![code list agency id list issue](https://user-images.githubusercontent.com/37205288/161629817-03476ff2-f271-40b6-ada8-650873d3ffdf.png)

**Comment by hakjuoh** [comment]
@asdimitriadis Now it allows to select an agency ID list which is being revised/amended.

**Comment by sakisdimt** [comment]
Now we can select an Agency ID in any state. However, the following expected behavior is not implemented:

1. The developer/end user cannot discard an Agency ID list value from the Agency ID list if it is used in a Code List. (the checkbox in front of the Agency ID list value should be disabled)
2. If the developer/end user changes the Meaning field of an Agency ID list value, the Code List that uses this Agency ID list value should be updated accordingly.

**Comment by asdimitriadis** [comment]
Now we can select an Agency ID in any state. However, the following expected behavior is not implemented:

1. The developer/end user cannot discard an Agency ID list value from the Agency ID list if it is used in a Code List. (the checkbox in front of the Agency ID list value should be disabled)
2. If the developer/end user changes the Meaning field of an Agency ID list value, the Code List that uses this Agency ID list value should be updated accordingly.

**Comment by asdimitriadis** [comment]
To reproduce the above mentioned behavior
For the "The developer/end user cannot discard an Agency ID list value from the Agency ID list if it is used in a Code List."
1. Login as a developer
2. Create a code list and choose the existing developer Agency ID list
3. Revise the Agency ID list
4. Add a new value to the Agency ID list
5. Open the code list of step 2
6. Select the Agency ID list value of Step 4
7. Update the code list
8. Open the revised developer Agency ID list of Step 3
9. Remove the value of step 4.
At this point in the UI is removed. But not in db. Also in the UI there is a blackbox returned.
At this point you can remove the value in the UI. However, this should not be possible since it is used in the code list.
Maybe the checkbox in front of the Agency ID list value should be disabled?
The same applies to end user code list. You can follow the same steps using end user code list and angency id list though.
For the "If the developer/end user changes the Meaning field of an Agency ID list value, the Code List that uses this Agency ID list value should be updated accordingly."
1. Login as a developer
2. Create a code list and choose the existing developer Agency ID list
3. Revise the Agency ID list
4. Add a new value to the Agency ID list
5. Open the code list of step 2
6. Select the Agency ID list value of Step 4
7. Update the code list
8. Open the revised developer Agency ID list of Step 3
9. Try to change the meaning field of the value of step 4.
At this point a blackbox is returned and the value is not changed neither in the Agency Id list nor in the Agency ID value field in the code list.
The same applies to end user code list. You can follow the same steps using end user code list and angency id list though.

**Comment by hakjuoh** [comment]
@asdimitriadis I added `code_list_manifest`.`agency_id_list_value_manifest_id` column to support the use of values. Now, the checkbox is disabled if the value is used in either a code list or an agency ID list. A lot of logic has been changed for this issue. Please test entire agency ID list logics along with the code list.

**Comment by asdimitriadis** [comment]
It works well.
