### ISSUE TITLE
Change the page title of the CC assignment page

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1272]
![image](https://user-images.githubusercontent.com/7863166/162280388-c6ae9705-500e-4c39-a619-e5e1ed792696.png)

The name of this page should be changed to "Core Component Assignment"

**Comment by hakjuoh** [comment]
@asdimitriadis Please check this change.
<img width="488" alt="Screen Shot 2022-04-08 at 10 35 58 AM" src="https://user-images.githubusercontent.com/16102116/162458563-aa0231b3-fb88-42ea-981c-cb7db7ca7ddb.png">

**Comment by asdimitriadis** [comment]
The page title has been changed.
