### ISSUE TITLE
Improve UI on CC Assignment

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1273]
The UI on the CC Assignment section does not work well. First, right now the top part (red mark in the screenshot below) where the filters are also scroll, it shouldn't. Seconding, I cannot use the Ctrl key to check multiple entities. This make the selection harder. It looks like the UI components used in the Release Management page might be better. We don't have to change this in 2.3. You can refactor this as an issue in a later release. The third issue is, filtering sometime take long while there is no hour glass like the View/Edit CC page.

![image](https://user-images.githubusercontent.com/7863166/162280758-acd8f153-11e5-4554-9d63-5a0f8bc5a53f.png)

**Comment by asdimitriadis** [comment]
The UI was improved as depicted in the Figure of the above comment. It works well.
