### ISSUE TITLE
Indicate current signed-in role on the banner: End User or Dev User Role

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1275]
I think the End User role retains the current light grey banner. The developer role has black banner and the menu font has to be changed to white. Score logo needs to be changed to white too. This is similar to Git banner. 

![image](https://user-images.githubusercontent.com/7863166/162573977-78c67f90-692d-4c0c-ad9c-deec719e731d.png)

@michaelfigura can you give @hakjuoh SCORE logo with white foreground.

**Comment by kbserm** [comment]
@hakjuoh Not sure if this can done in 2.3.

@asdimitriadis Can this be tested?

**Comment by kbserm** [comment]
@joshklm @michaelfigura I am thinking, in the short term, whether it is better that when the user has logged in a dialog pops up right away to tell the user whether he is in the End User or Developer role. The reason is the user may not know anyway what the grey vs. black banner means. And approach is much easier to implement. Thoughts?

**Comment by kbserm** [comment]
We agreed to have both the pop up diaglog at the log in and also the parenthesis behind or under the user name in the top banner '(dev)' or '(end user)'.

**Comment by hakjuoh** [comment]
@asdimitriadis Now the role appears in both a dialog and a menu as below.

<img width="364" alt="Screen Shot 2022-04-15 at 11 16 14 AM" src="https://user-images.githubusercontent.com/16102116/163588531-4f48933a-9dd4-4d77-b550-cdbddcd708ec.png">

<img width="211" alt="Screen Shot 2022-04-15 at 11 16 22 AM" src="https://user-images.githubusercontent.com/16102116/163588537-9251a5ce-9c23-48e3-8ad2-06383770f5fc.png">

**Comment by asdimitriadis** [comment]
It works well

**Comment by kbserm** [comment]
Can I see the screenshot of the whole banner please.

**Comment by asdimitriadis** [comment]
This is the banner. When the user clicks on its name, he can see his role next to the name
![image](https://user-images.githubusercontent.com/37205288/164222720-af2cc0e6-1d9a-47a2-a68b-279f47cd756f.png)

This is the message when the user logins
![image](https://user-images.githubusercontent.com/37205288/164222950-cd0165a0-41e1-48bd-b0d0-c08fa7d9f800.png)

**Comment by kbserm** [comment]
I would rather have the role shown without clicking.

**Comment by asdimitriadis** [comment]
I am reopening this issue based on the above comment.

**Comment by hakjuoh** [comment]
@asdimitriadis Changed the position of the role parenthesis. The drawback is that the menu name would be too long for some users whose username is already lengthy.
<img width="160" alt="Screen Shot 2022-04-21 at 12 42 20 AM" src="https://user-images.githubusercontent.com/16102116/164373688-765d6d3e-3dd9-4be7-8236-ff6abbd45aae.png">

**Comment by asdimitriadis** [comment]
![image](https://user-images.githubusercontent.com/37205288/164705657-a4f4a51c-4c55-45a7-9cbf-3a024466daf3.png)

Attached I have included the whole banner. 
This is fixed so I am closing the issue
