### ISSUE TITLE
The Name of a Module Set Release is not defaulted to "[Module Set] Module Set Release"

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1276]
The Name field of a Module Set Release can be a string value but if it is left blank it should be defaulted. 

The Name field should be defaulted to "[Name of the selected Module Set] suffixed with “Module Set Release”, trailing and leading duplicate truncation.

Below are provided some examples:
1. If name of the Module Set is “OAGIS 10.8”, the default name of the Module Set Release should be “OAGIS 10.8 Module Set Release”.
2. If name of the Module Set is “OAGIS 10.8 Module Set”, the default name of the Module Set Release should be “OAGIS 10.8 Module Set Release”. (duplicate truncation)
3. If name of the Module Set is “OAGIS 10.8 Modules”, the default name of the Module Set Release should be “OAGIS 10.8 Modules Module Set Release”
4. If name of the Module Set is “OAGIS 10.8 Canonical XML Schema", the default name of the Module Set Release should be “OAGIS 10.8 Canonical XML Schema Module Set Release”

This issue applies when a developer creates
1. a new Module Set Release via the "Create Module Set Release"
2. a new Module Set with the Create Module Set Release option. The default name of the created Module Set Release should be the name of the Module Set suffixed with “Module Set Release” but truncated with any duplication as shown in the example 2 above.

**Comment by hakjuoh** [comment]
@asdimitriadis The new rule for the default module set release name is applied. Please test this.

**Comment by asdimitriadis** [comment]
It works well as described above

**Comment by hakjuoh** [comment]
The following algorithm is used to truncate duplicates.
```
function (str1, str2) {
    string[] str2Tokens = tokenize(str2, " ");
    string partialStr2 = "";
    for (i = 0; i < str2Tokens.length; ++i) {
        partialStr2partialStr2 += ((i == 0) ? " " : "") + str2Tokens[i];
        if (str1.endsWith(partialStr2)) {
            return str1 + " " + join(str2Tokens.range(i + 1, len), " ");
        }
    }
    return str1 + " " + str2;
}
```
