### ISSUE TITLE
CCs belogning to Working branch are not displayed in a Module Set Release

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1278]
To reproduce the issue:
1. Login as a developer
2. New some new CCs. 
3. Create a new Module Set with the Create Module Set Release option. 
4. Select the Working release that has some new CCs. 
5. Select a Module Set Release. 
6. Open the Module Set Release created. 
7. Click the "Assign CCs" button.

At this point the new CCs of step 2 that belong to the Working branch are not displayed. They should be displayed as Unassigned CCs.

**Comment by hakjuoh** [comment]
@asdimitriadis Is new CC's state `Published`?

**Comment by asdimitriadis** [comment]
@hakjuoh  I do not believe that the CCs should be in Published state since the expected behavior related to a module set release that is associated with the Working branch.
1. If a CC is deleted, its CC assignment in the module set release must be also discarded.
2. Deleted CC cannot be assigned in the module set release (_maybe its checkbox is disabled?_)

**Comment by kbserm** [comment]
We went with that b/c it is simpler. Only when the deleted component is purged then module assignment is deleted from the database. We still need to change the expression logic to ignore deleted components.

**Comment by hakjuoh** [comment]
@asdimitriadis Now we can see all CCs in any state. I also added a 'State' filter.

<img width="686" alt="Screen Shot 2022-04-19 at 3 39 52 PM" src="https://user-images.githubusercontent.com/16102116/164082649-ab1c3901-b9af-4935-9151-d52c3b311c3b.png">

**Comment by asdimitriadis** [comment]
They are now displayed and can be used. It works well.
