### ISSUE TITLE
Namespace and Version Number of a module should be optional

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1281]
To reproduce the issue:
1. Login as developer
2. Create a Module Set
3. Click the +Add button of a column to add a module
4. Click the option "create a new module file". At this point the Namespace and version are optional (this is the expected behavior)
5. Populate the Name field and click "Create" button
6. Click on the pencil icon next to the new module you created

At this point, there is a namespace selected in the Namespace field and this field is not optional. The expected behavior is 
that the Namespace and Version fields should be optional

**Comment by hakjuoh** [comment]
@kbserm If we plan to use the `namespace` field for a `targetNamespace` in XML, it should be required. Otherwise, we can make it optional or remove it from the module if it is useless.

**Comment by kbserm** [comment]
I think namespace can be required or optional. If it is optional and it is not specified; and then if a particular expression needs it, the serialization will have to catch that exception. If it is required, it may not be used in a particular expression. 

I can go either way but would prefer optional.

**Comment by hakjuoh** [comment]
@asdimitriadis Now there is a '-' option to make it NULL.

<img width="355" alt="Screen Shot 2022-04-18 at 10 52 40 AM" src="https://user-images.githubusercontent.com/16102116/163826408-ecbbc188-3835-415f-9ac2-7c5d7b493417.png">

**Comment by asdimitriadis** [comment]
It works well
