### ISSUE TITLE
Load from Code List does not work in Context Scheme

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1282]
The issue is that the Load from Code List does not work in Context Scheme

To reproduce the issue:
1. Create a Code List
2. Click on the "Load from Code List"
3. Select the "oacl_CurrencyCode"

At this point there is no values added to the Context Scheme

**Comment by hakjuoh** [comment]
@asdimitriadis Please see c1282298 commit, and test it again.

**Comment by asdimitriadis** [comment]
It works well
