### ISSUE TITLE
The Used flag of reused BIE nodes does not work

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1284]
The issue is that the Used flag of reused BIE nodes does not work

To reproduce the issue:
1. Create the BIE "From UOM Package", make some changes and move it to Production
2. Create the BIE "UOM Code Conversion Rate"
3. Reuse the "From UOM Package". 
4. Enable the "From UOM Package" node.
5. Update the BIE
6. Reopen the BIE

At this point the  "From UOM Package" is not used. The Used checkbox is unchecked.

**Comment by hakjuoh** [comment]
@asdimitriadis Please see da23f05b commit, and test it again.

**Comment by asdimitriadis** [comment]
It works well.
