### ISSUE TITLE
Add multi-select option to the left "verb" side of the interface

### ISSUE THREAD

**Issue by michaelfigura** [OAGi/Score#1286]
It took me half a day of effort to create the BODs for 5 new nouns. Can we make this faster?

![image](https://user-images.githubusercontent.com/36652082/165307126-74d8a70e-abe2-4e05-b12c-91b780abc786.png)

**Comment by hakjuoh** [comment]
@asdimitriadis Now the dialog supports a multiple selection of both verb and noun components.

<img width="1388" alt="Screen Shot 2022-04-27 at 10 05 49 AM" src="https://user-images.githubusercontent.com/16102116/165537633-ddaddadc-af76-4d5e-817d-e448e49cd827.png">

**Comment by asdimitriadis** [comment]
It works well
