### ISSUE TITLE
Change labels 'OAGIS Developer' to 'Standard Developer'

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1288]
This is to make Score more usable with other standards..

**Comment by hakjuoh** [comment]
@kbserm <img width="412" alt="Screen Shot 2022-06-02 at 10 05 46 AM" src="https://user-images.githubusercontent.com/16102116/171647798-37893d64-0745-4893-9b63-6e52668e730b.png">

**Comment by DimitrijeM** [comment]
OAGiS Developer is renamed to Standard Developer in test cases. Adding data for test cases is working properly.
