### ISSUE TITLE
OpenAPI Expression issue: Eliminate duplicate schema object in OAS yaml when the same BIE is referenced 

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1302]
**Feedback from AgGateway Product Catalog WG03:**
We are seeing large yaml files due to the duplication of the schema object of the same BIE.  We are manually edited the yaml to remove the duplicated schema object, and the appropriate reference to the schema object.

    get:
      summary: ""
      description: ""
      tags:
      - "Catalog"
      parameters:
      - name: "id"
        in: "query"
        description: ""
        required: false
        schema:
          type: "integer"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/get-catalog"
    post:
      summary: ""
      description: ""
      tags:
      - "Catalog"
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/post-catalog"
      responses:
        "200":
          description: ""
          content:
            application/json: {}

**Comment by dubnemo** [comment]
What we do:

    get:
      summary: ""
      description: ""
      tags:
      - "Catalog"
      parameters:
      - name: "id"
        in: "query"
        description: ""
        required: false
        schema:
          type: "integer"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/catalog"
    post:
      summary: ""
      description: ""
      tags:
      - "Catalog"
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/catalog"
      responses:
        "200":
          description: ""
          content:
            application/json: {}

**Comment by hakjuoh** [comment]
@dubnemo @kbserm

Because 'Get' and 'Post' operations could be different by options.

<img width="379" alt="Screen Shot 2022-07-18 at 4 22 17 PM" src="https://user-images.githubusercontent.com/16102116/179610557-487234aa-104e-471c-8392-2e2d4e35a89a.png">

**Comment by dubnemo** [comment]
Correct, the rule should be IF the same bie-guid AND no other selections are enabled for meta header, array or pagination.

**Comment by hakjuoh** [comment]
@dubnemo Here's an example expression after applying the rule for 'Move Product'.
```
    get:
      summary: ""
      description: ""
      tags:
      - "Move Product"
      parameters:
      - name: "id"
        in: "query"
        description: ""
        required: false
        schema:
          type: "integer"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/moveProduct"
    post:
      summary: ""
      description: ""
      tags:
      - "Move Product"
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/moveProduct"
      responses:
        "200":
          description: ""
          content:
            application/json: {}
components:
  schemas:
    moveProduct:
```
