### ISSUE TITLE
Allow support of plurals in OpenAPI Expression

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1303]
Developers have a non-specified de facto standard where plurals are desired for arrays of a object.  It was proposed that the business term be used for these scenarios when an ASCCP is unbounded in a BIE.  This could be enabled with a checkbox on the business term workstream on the primary business term.  This also avoids plural scenarios like 'boundaries' and 'addresses' vs. simpler plurals such as 'items'.

It should be noted that the OAGi RESTful Web API guidelines does recommend the use of plurals in the schema object and resource paths.

**Comment by hakjuoh** [comment]
@dubnemo Is this issue related to #1483?

**Comment by dubnemo** [comment]
Yes.
