### ISSUE TITLE
Release Notes text box doesn't save unless it loses focus

### ISSUE THREAD

**Issue by michaelfigura** [OAGi/Score#1304]
I just created the OAGIS 10.8.2 release and typed in a solid description into the release notes text box and then I grabbed the mouse and clicked the publish button without tabbing out of, or clicking out of the release notes text box. It did not save my description text, as a result.

**Comment by hakjuoh** [comment]
@kbserm I changed the behavior that developers can update 'Release Note' and 'Release License' fields even if the release is in 'Published' state.

<img width="371" alt="Screen Shot 2022-07-27 at 10 00 29 PM" src="https://user-images.githubusercontent.com/16102116/181404047-832443be-7d2d-4bf3-82b6-0095d1b0db07.png">
