### ISSUE TITLE
Developer account cannot create a Code list

### ISSUE THREAD

**Issue by elenajelisic** [OAGi/Score#1321]
A developer account cannot create a Code list. The ‘New Code List’ button is not visible.

![image](https://user-images.githubusercontent.com/103444540/190312117-445e82e4-2a13-4a2c-b084-3cf00aa5a0f1.png)

**Comment by hakjuoh** [comment]
@elenajelisic As same as the issue #1320, please check this again with MySQL 5.7 and let me know if you have the same problem.

**Comment by elenajelisic** [comment]
@hakjuoh yes, it was the same problem. It works with MySQL 5.7
