### ISSUE TITLE
Update button is disabled when creating ABIE extension locally

### ISSUE THREAD

**Issue by elenajelisic** [OAGi/Score#1322]
If an end-user tries to define the namespace for ACC **after** creating ABIE extension locally, the 'Update' button will be disabled. The button will be enabled, only if additional changes are made (e.g., Definition Source field).

1. The end-user creates a new ABIE

![image](https://user-images.githubusercontent.com/103444540/190318380-94e298fd-1b71-4057-8302-bd03737d9252.png)

2. The end-user Creates ABIE extension locally

![image](https://user-images.githubusercontent.com/103444540/190318647-d9865bf4-8be6-4614-8aba-bfedf35f62f2.png)

3. After defining the namespace, the 'Update' button remains disabled

![image](https://user-images.githubusercontent.com/103444540/190318780-a2bff917-4adc-4d02-b931-3a70b99181f6.png)

4. The 'Update' button will be enabled only if additional changes are made

![image](https://user-images.githubusercontent.com/103444540/190319161-dc307121-6542-433c-bf4e-7f48b83507ba.png)

**Comment by hakjuoh** [comment]
@elenajelisic I couldn't reproduce this issue on my local. It would be much appreciated if you can provide the detail about this behavior like what you did before you saw this problem.

**Comment by elenajelisic** [comment]
@hakjuoh It works now.
