### ISSUE TITLE
Reusing BIE expands the BIE tree

### ISSUE THREAD

**Issue by elenajelisic** [OAGi/Score#1324]
When an end-user reuses a BIE, the BIE-tree gets expanded and focus is lost.

1. End-user reuses BIE for Document Reference

![image](https://user-images.githubusercontent.com/103444540/190461166-0f78f216-2c77-4ff4-b4d6-a1692f03577c.png)

2. After reusing BIE, the BIE-tree gets expanded (look at the 'Common Time Reporting' component) and focus is not on the 'Document Reference' component anymore

![image](https://user-images.githubusercontent.com/103444540/190461823-7a6e66c6-a7fe-4361-bc3d-ff4467de50f4.png)

**Comment by hakjuoh** [comment]
@elenajelisic Just made an update to fix this. Now when the tree reloads, the focus will be on the target node, in this case it's 'Document Reference'.

**Comment by elenajelisic** [comment]
@hakjuoh It works fine now.
