### ISSUE TITLE
10.6 BIEs are stuck in a loading state

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1326]
Existing 10.6 BIEs are stuck in a loading loop, when attempting to view their contents.  We tried copying the BIEs to see if we could see a copied version.  The tool will create the BIE, but we are unable to open it, as its also stuck in a infinite loop.  Creating a fresh 10.6 BIE results in the created message showing and the BIEs does not load and is stuck in a loading loop.  Attempting to uplift a 10.6 BIE results in it also being stuck in a load state.

**Comment by smorgan19** [comment]
To add we are able to express the 10.6 BIEs.

**Comment by kbserm** [comment]
@smorgan19 are the code lists generated correctly in other releases? We could not reproduce this issue. Please schedule a conference call if you would like us to address this in 2.4 release which we hope to finish in a week or two.

@dubnemo could you see if you can open 10.6  and express BIEs fine.

**Comment by smorgan19** [comment]
The codelists are generating in the cl0, like the 10.6 BIE currently is.  We compared the 10.6 expressed output that was freshly generated with a previously generated version of the same profile.  The only different is the cl402 in the original has now changed in the newly expressed BIE to cl0.

**Comment by hakjuoh** [comment]
@smorgan19 Currently, the code list naming begins with the prefix 'cl' and the agency ID list value ID like 'cl402'. However, the code list could have no agency ID list value and it makes the code list name like 'cl0'. Did you assign the agency ID list value to that code list? @kbserm We need to talk about this naming rule in case of the absence of the agency ID list value in the code list. I would suggest that it should follow the agency ID list `value`, not `ID`. For example, the agency ID list value ID '402' has 'ZZZ' value. In this case, the code list name should begin with 'clZZZ'. If it doesn't have the agency ID list value, it would start with just 'cl'.

**Comment by smorgan19** [comment]
The agency id list value is populated with the clm...agencyid and set to mutually defined in the 10.6 and in another version.  We are still able to open the codelists for 10.6, just not the BIEs.  In a prior expressed copy that was expressed long before we discovered this issue has the cl402 and we have not changed this BIE or codelist since the prior expressed copy was expressed.

**Comment by hakjuoh** [comment]
> @hakjuoh The agency id list value is populated with the clm...agencyid and set to mutually defined in the 10.6 and in another version. We are still able to open the codelists for 10.6, just not the BIEs. We have not changed this BIE or codelist in a long time, which is interesting considering the older copy generated with the cl402 and the new copy when the issue is present did not.

Sounds like it lost the agency ID list value while it's copying. Could you give me more details about your copying experience? Did you use 'Uplift Code List' function to do that, or anything else?

**Comment by smorgan19** [comment]
Since uplifting was introduced, we uplift codelists.  Copying a BIE, it says its in WIP, but does not load.  I will send you all an email shortly regarding meeting times.
