### ISSUE TITLE
Assign New Business Term button should not be displayed if BIE is not editable

### ISSUE THREAD

**Issue by elenajelisic** [OAGi/Score#1327]
1. An end-user opens BIE created by another user

![image](https://user-images.githubusercontent.com/103444540/191560602-0a02d8c7-de7e-45d6-8f10-4b80d0f60664.png)

2. An end-user clicks on component Identifier Set. The user cannot edit any information about this component, so 'Assign New Business Term' button should not be displayed.

![image](https://user-images.githubusercontent.com/103444540/191560774-05d8ca76-d8d6-41f9-bf13-97bfec714351.png)

**Comment by DimitrijeM** [comment]
It should be fixed now. If the user opens a non-editable BIE, the "Assign Business Term" button is not visible. @elenajelisic Please test and let me know if it's ok now.
