### ISSUE TITLE
Have 'Code Generation Friendly' feature become the default behavior and eliminate the {x} option from the UI

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1338]
It was agreed 10/6/22 that Code Generation Friendly 'option box' is awkward and is **always** used.  It should be the normal behavior for OpenAPI specification expression.  
Ideally this would be released in conjunction with #1301 and #1308. 

@joshklm @jim-wilson-kt @michaelfigura @sfohn @dubnemo @hakjuoh @kbserm @lmkennethburnett 
+ Nikola Stojanovic

![image](https://user-images.githubusercontent.com/32434235/194416484-31bd6cb2-52bb-448b-8146-982e94d9095d.png)

**Comment by hakjuoh** [comment]
@dubnemo @kbserm 'Code Generation Friendly' option has been discarded from UI, and it becomes the default behavior.
<img width="338" alt="Screen Shot 2022-10-06 at 10 54 55 PM" src="https://user-images.githubusercontent.com/16102116/194458248-2c549e56-acf1-41f7-85de-42e0c5fbf5c7.png">

**Comment by dubnemo** [comment]
Thank you!!

**Comment by jim-wilson-kt** [comment]
Can we have a "Code-generation unfriendly" checkbox? :-)

**Comment by dubnemo** [comment]
hehe...

I'd pass on that one, Jim.   ;-)
