### ISSUE TITLE
Unable to logout using the logout drop down menu option.

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1344]
When an end user or developer accounts attempts to use the logout option under drop down menu the page loads for an extended period of time and then the page is not working appears.  When you refresh or revisit the tool, you are still logged in as your account. The menu bar also disappears while it stuck loading.  We are able to directly use the url/logout link to log out and successfully are logged out of the tool.  This is in the 2.4.0 version, and is not present in the later version.

**Comment by hakjuoh** [comment]
We worked for supporting OpenID Connect RP-Initiated Logout 1.0 mechanism in 2.4, and seems like it does not work in LM environment. Would you let me know the logout endpoint of your PingIdentity provider? That is an endpoint you can sign off the current account from your browser. Perhaps you have to set up the path in the configuration https://docs.pingidentity.com/bundle/solution-guides/page/brr1601053457752.html.

**Comment by smorgan19** [comment]
We can logout through the url directly(i.e www.abcd.com/logout).  The UI crashes when we attempt to logout using the menu option.  If you click the button, the menu completely disappears and the page freezes, before crashing entirely.  You are still logged in if you revisit the site.  This issue is not SSO account specific, it does the same is accounts created from the tool, that are not linked to an sso provider.

**Comment by smorgan19** [comment]
Based on the article you posted, is the tool attempting to globally log users off their ping identity source or a single logout only to the application.

**Comment by hakjuoh** [comment]
When users tried to log out through the UI 'Logout' button, the session (the authentication token) in SSO provider wasn't cleared. This causes a problem that once the user logged in Score, one can't switch to another user in the same browser. You may have encountered this problem when you click the logout link on the screen with the user pending warning message.

PingIdentity provides an logout endpoint for only single application, and if you provide it to me, you can add it to DB by the following query:

```sql
UPDATE `oagi`.`oauth2_app` SET `end_session_endpoint` = <pingidentity_logout_endpoint>;
```

and you need to register `https://<score_domain>/logout` for the logout redirect path to the PingIdentity configuration.

This setting makes a flow that when you click 'Logout' button, the browser sends the logout request to PingIdentity first, and PingIdentity calls the redirect path back to the browser. As a result, user sessions in Score and PingIdentity will successfully be discarded.

Now, the trial account has been expired, and we are trying to obtain PingIdentity account for testing again. I'll inform you the instruction for this after that.

**Comment by hakjuoh** [comment]
@smorgan19 Could you give me any clue about this issue through the browser's developer tool? When the user hits 'Logout' button, you would be able to capture the following exchanges in 'Network' tab if everything's fine.

<img width="603" alt="Screen Shot 2022-11-30 at 1 13 00 PM" src="https://user-images.githubusercontent.com/16102116/204876456-3dd1ef58-f8ed-4279-a5ac-7f199697cdc4.png">
<img width="607" alt="Screen Shot 2022-11-30 at 1 14 08 PM" src="https://user-images.githubusercontent.com/16102116/204876480-afb8881a-c58b-422d-95e2-ae0134c6b2d2.png">

**Comment by smorgan19** [comment]
I will try to gather that info for you in the next few days, but I think it was a 504 or 403 error code.  How does this logout mechanism work if ping isn't or cant be configured for a logout endpoint.  In some authentication schemes, a logout isn't necessary or redundant.  Requiring a logout endpoint isn't always universally available or allowed on enterprise systems.

**Comment by smorgan19** [comment]
@hakjuoh The inspector is showing a 302, where it attempts to redirect as in your first screenshot.  The second response is failed net err_empty_response.  The page shows a "This page isn’t working" in the ui.

**Comment by smorgan19** [comment]
Just to add, before now we had no issue switching between accounts.  I regularly switch between a sso based account and a non-sso account.

**Comment by hakjuoh** [comment]
> @hakjuoh The inspector is showing a 302, where it attempts to redirect as in your first screenshot. The second response is failed net err_empty_response. The page shows a "This page isn’t working" in the ui. Before now we had no issue switching between accounts. I regularly switch between a sso based account and a non-sso account.

The first response would have 'Location' header, which is the URL to redirect the request to IdP services if the `end_session_endpoint` is assigned in `oauth2_app` table. Otherwise, it should be the score http-gateway logout endpoint; e.g., `https://<score hostname>/logout`.

I guess the `Location` header may have an incorrect endpoint by some reason, probably by the web server configuration. If you're okay without IdP logout service, One possible solution is to update `end_session_endpoint` value to the score http-gateway logout endpoint as follows:

```sql
UPDATE `oauth2_app` SET `end_session_endpoint` = 'https://<score_hostname>/logout`;
```

Please let me know if you need any help to do this. Moreover, I'll update this if we can have PingIdentity trial account.

**Comment by smorgan19** [comment]
Hi @hakjuoh I didn't catch this at first, but it does try to do the url/logout redirect next which is what is causing the err_empty response.  It looks like it tries at least twice, but both status are reading as cancelled.  The order of the is the first redirect which returns a 302.  The next logout is the failed network empty error response.  Then it continuously attempts to go to the score url/logout, which is cancelled each time.

**Comment by smorgan19** [comment]
@hakjuoh Requiring a logout end point is a huge limitation for individuals trying to use ping with the score tool.  For certain ping configurations, log out end points aren't accessible or available at an organizational level.

**Comment by hakjuoh** [comment]
@smorgan19 Two logout requests are to close both IdP and Score sessions like [IdP logout endpoint with 302 -> IdP session closing, and Score logout endpoint with 302 -> Score session closing].

If you update `end_session_endpoint` value in `oauth2_app` to Score /logout endpoint, which is the same url as you use to log-out manually, the second flow (IdP session closing, which is the case you got failure) will be skipped. Does the cancelled request have the same url that you use to log out?

**Comment by smorgan19** [comment]
We will try to updated the end_session_endpoint in the db on Monday.  Cancelled request has the url: www.url.com/logout

**Comment by smorgan19** [comment]
We ran the sql command and are still experiencing the same issue.

**Comment by hakjuoh** [comment]
We will reopen this issue if it happens again.
