### ISSUE TITLE
oagiscore.net throwing an exception while expressing BIEs

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1345]
Duplicate key 24 (attempted merging values BdtPriRestri(bdtPriRestriId=18811, bdtManifestId=24, cdtAwdPriXpsTypeMapId=13, codeListManifestId=null, agencyIdListManifestId=null, defaulted=true) and BdtPriRestri(bdtPriRestriId=1000037, bdtManifestId=24, cdtAwdPriXpsTypeMapId=13, codeListManifestId=null, agencyIdListManifestId=null, defaulted=true))

**Comment by dubnemo** [comment]
I tried this for multiple BIEs and in different branches.  Same error message.

**Comment by hakjuoh** [comment]
The migration script for Score 2.4 generated duplicate records to `bdt_pri_restri` and `bdt_sc_pri_restri` tables. I have updated all data of *.oagiscore.net instances using [the patch script](https://github.com/OAGi/Score/files/10026370/issue_1345.zip), and also have patched the migration script. If your on-prem instance have already updated to Score 2.4 with the prior migration script, you must execute the patch script. I noted this on the release wiki too.

**Comment by dubnemo** [comment]
V2.4 for our on-prem environment without 10.8.4 did not have a problem expressing BIEs.

**Comment by dubnemo** [comment]
After applying 10.8.4 with 

Execute processes...
        Executing mig_10_8_3_to_10_8_4.sql
        Executing c:\temp\mig_10_8_3_to_10_8_4.sql as a SQL script
        Executing issue_1345.sql
        Executing c:\temp\issue_1345.sql as a SQL script
Completed.

Now experience this exception while express BIEs
Http failure response for http://ahdap3522:8880/api/profile_bie/generate?data=dG9wTGV2ZWxBc2JpZXBJZHM9MTM1JmZpbGVuYW1lcyU1QjEzNSU1RD1EYXRhc2V0TWV0YWRhdGEmYml6Q3R4SWRzJTVCMTM1JTVEPTcyJm9wZW5BUElDb2RlR2VuZXJhdGlvbkZyaWVuZGx5PXRydWUmYmllRGVmaW5pdGlvbj10cnVlJmV4cHJlc3Npb25PcHRpb249T3BlbkFQSTMwJnBhY2thZ2VPcHRpb249QUxMJm9wZW5BUElFeHByZXNzaW9uRm9ybWF0PVlBTUwmb2RmRXhwcmVzc2lvbkZvcm1hdD1PRFMmb3BlbkFQSTMwUG9zdFRlbXBsYXRlPXRydWU=: 500 OK

Provide DB dmp to @hakjuoh over Slack.

**Comment by dubnemo** [comment]
From @hakjuoh  in Slack.
===============
```

UPDATE bbie, (SELECT t.bbie_id, bdt_pri_restri.bdt_pri_restri_id
              FROM (SELECT bbie.*
                    FROM bbie
                    LEFT JOIN bdt_pri_restri ON bbie.bdt_pri_restri_id = bdt_pri_restri.bdt_pri_restri_id
                    WHERE bbie.bdt_pri_restri_id IS NOT NULL
                      AND bdt_pri_restri.bdt_pri_restri_id IS NULL) t
                    JOIN bcc_manifest ON t.based_bcc_manifest_id = bcc_manifest.bcc_manifest_id
                    JOIN bccp_manifest ON bcc_manifest.to_bccp_manifest_id = bccp_manifest.bccp_manifest_id
                    JOIN dt_manifest ON bccp_manifest.bdt_manifest_id = dt_manifest.dt_manifest_id
                    JOIN bdt_pri_restri ON dt_manifest.dt_manifest_id = bdt_pri_restri.bdt_manifest_id AND bdt_pri_restri.is_default = 1) t
SET bbie.bdt_pri_restri_id = t.bdt_pri_restri_id
WHERE bbie.bbie_id = t.bbie_id;

UPDATE bbie_sc, (SELECT t.bbie_sc_id, bdt_sc_pri_restri.bdt_sc_pri_restri_id
              FROM (SELECT bbie_sc.*
                    FROM bbie_sc
                    LEFT JOIN bdt_sc_pri_restri ON bbie_sc.dt_sc_pri_restri_id = bdt_sc_pri_restri.bdt_sc_pri_restri_id
                    WHERE bbie_sc.dt_sc_pri_restri_id IS NOT NULL
                      AND bdt_sc_pri_restri.bdt_sc_pri_restri_id IS NULL) t
                    JOIN dt_sc_manifest ON t.based_dt_sc_manifest_id = dt_sc_manifest.dt_sc_manifest_id
                    JOIN bdt_sc_pri_restri ON dt_sc_manifest.dt_sc_manifest_id = bdt_sc_pri_restri.bdt_sc_manifest_id AND bdt_sc_pri_restri.is_default = 1) t
SET bbie_sc.dt_sc_pri_restri_id = t.bdt_sc_pri_restri_id
WHERE bbie_sc.bbie_sc_id = t.bbie_sc_id;
```

**Comment by dubnemo** [comment]
This patch worked.
