### ISSUE TITLE
Update database and BIE retrieval to support multi-tenancy

### ISSUE THREAD

**Issue by georgiyolovski** [OAGi/Score#1346]

**Comment by dubnemo** [comment]
@georgiyolovski there isn't a description of the requirements here.  

- Will multi-tenancy allow support of tenants that would be able to access their own component library, or an empty component library, while other tenants would be able to access the OAGIS component library?  
- If not, will the existing design allow a transition to multiple component libraries and tenants are granted access to these libraries?

Also the Milestone should be a 3.0 release as that would be classified as a major release. 
@kbserm @jim-wilson-kt @michaelfigura @joshklm

**Comment by kbserm** [comment]
The scope is only BIE multi-tenancy at this point.
