### ISSUE TITLE
Update the release process to change owner_user_id to the OAGi user.

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1349]
Once released/ Published, the submitter has contributed to the OAGi core component library with a full release of all IP.   

- The owner_user_id should point to the OAGi user, not the original content submitter.  
- The created_by should still be the original submitter.
- The last_updated_by column should be the user who last revised the component.  This could be different than the created_by.

I prefer not to see my username on these Published components.

**Comment by hakjuoh** [comment]
@dubnemo @kbserm If it could update `owner_user_id`, `created_by`, and `last_updated_by` to OAGi user (i.e., `oagis`) through the migration data, we don't need to change anything on UI. By this approach, we could also eliminate all developer accounts from on-prem instances.

**Comment by dubnemo** [comment]
@hakjuoh @kbserm 
Yes, doing this in the publishing steps is what I hoped.  Keeping the name references is helpful, and if there was a way to see that via the UI, I would appreciate it.  Perhaps as simple as a hover-over somewhere in the component detail view.

**Comment by kbserm** [comment]
@hakjuoh I think we are only talking about changing the owner user id to a designated account, created by and last updated by are left as is. I there there is no point in going back to prior release and change this. Eliminating those accounts in release data is, I think, unnecessarily add more work and data inconsistency. 

So the question is what is the designated account to use for publishing. I would like to avoid hard coding to oagis account b/c Score is not supposed to be specific to only OAGIS. Maybe we would rather assume that the staff or the architect of the SDO is the one who publishes the release and that we change the owner to that particular user that publish the release. In the case of OAGIS, we can see that the assumption holds as it is now Michael who does that.

On a separate question, I looked that Answer. Text BCCP and its history in 10.8.5 release. It shows ScottNeimanOAGISDev and the last updater. But when I open its history, I see mfiguradev as the last person who modified, I guess b/c he published the release, and that info does go into the CC table. But there is also hakju.oh b/f ScottNeimanOAGISDev, so I'm wondering how ScottNeimanOAGISDev still appears as last updater on the CC list page.

**Comment by dubnemo** [comment]
@kbserm
Would you agree that oagis is the account which is the owner of the
component library?
I would suggest each library would have a similar account.

**Comment by hakjuoh** [comment]
> On a separate question, I looked that Answer. Text BCCP and its history in 10.8.5 release. It shows ScottNeimanOAGISDev and the last updater. But when I open its history, I see mfiguradev as the last person who modified, I guess b/c he published the release, and that info does go into the CC table. But there is also hakju.oh b/f ScottNeimanOAGISDev, so I'm wondering how ScottNeimanOAGISDev still appears as last updater on the CC list page.

@kbserm Because it hasn't updated the who column `last_updated_by` during release creation, but only made logs for it.
