### ISSUE TITLE
Uplifting BIE needs warning message under verification when reused BIEs need to be mapped, and other potential issues.

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1350]
@hakjuoh you may want to review the logs:

Http failure response for https://oagiscore.net/api/profile_bie/451/uplifting: 500 OK

**Comment by dubnemo** [comment]
Maybe this is related to #1345 ?

**Comment by dubnemo** [comment]
The problem is there isn't a message that states 'There is an issue mapping the content.'  It states 'All contents are mapped', without an expansion of the tree on the right.  It is NOT obvious.
![image](https://user-images.githubusercontent.com/32434235/204845404-1b1f72b3-5500-4350-bcdb-e0bec3218e6e.png)

Expanding the tree on the right shows that Substance needs to be assigned to the reused BIE, but the previous UI implied that everything mapped perfectly.

![image](https://user-images.githubusercontent.com/32434235/204845238-1787895b-7a26-432c-8480-70de092b6198.png)

**Comment by hakjuoh** [comment]
<img width="983" alt="Screen Shot 2022-12-01 at 10 54 11 AM" src="https://user-images.githubusercontent.com/16102116/205099020-28ee146e-ed0e-4457-a7db-04f5da208046.png">

It fixed. Now it shows the number of components that need to be mapped on the top of the screen as it worked in prior releases.
