### ISSUE TITLE
Uplifting BIE feature is not uplifting attached Code lists

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1356]
Uplifting BIEs is partially working.  It detects a problem with certain fields, but it isnt uplifting non-issue fields.  I had originally thought this issue was present in only the application area, but its doing it elsewhere.  The codelists do exist in the version that the bie is being uplifted too, there is no indication that these code lists are causing an issue.  When we express the bie or look at the ui, they arent there in the uplifted bie.

**Comment by hakjuoh** [comment]
The following example is a report page to indicate the restriction of the code list uplifting.

<img width="1259" alt="Screen Shot 2022-12-14 at 8 35 04 PM" src="https://user-images.githubusercontent.com/16102116/207751932-6dded2f4-f598-43f6-aabd-d53a312e1980.png">

Currently, Score does not support the code list uplifting in BIE uplifting because Score differently treated two code lists in two releases. @kbserm Please support this issue.

**Comment by smorgan19** [comment]
Before we even attempt to uplift the BIE to a new version.  We used the separate uplift code list process.  The code lists do exist in the new version as they were uplifted prior to attempting to uplift the BIE.  Based on this the exact match code list is now in the target release.  We then attempt to uplift the BIE to the new target release.  There is no indication that there is a problem like in the above screenshot or any indication that the code lists were selected by the system.

**Comment by dubnemo** [comment]
@hakjuoh @kbserm @smorgan19 @jim-wilson-kt @michaelfigura 
This is the fundamental reason WHY I have been advocating for a _separate database_ (schema) for code-lists, context, business terms, and other objects that have their own **independent lifecycle**.

**Comment by dubnemo** [comment]
#1358 has been created

**Comment by smorgan19** [comment]
@hakjuoh Was this issue ever fixed?

**Comment by kbserm** [comment]
@smorgan19 It looks like this function was broken along the way. Hakju will look into fixing this and release a patch for release 3.0.

@bingqi2045 Could you look whether there are test assertions covering various scenarios about uplifting BIEs with standard and end user code lists.

**Comment by bingqi2045** [comment]
@elena-jelisic  Since you are currently working on test scripts on code lists, can you answer @kbserm
's question: whether there are test assertions covering various scenarios about uplifting BIEs with standard and end user code lists.

**Comment by hakjuoh** [comment]
@bingqi2045 @elena-jelisic Please review the PR https://github.com/OAGi/Score/pull/1454, especially the line 1567-1580 in [BieUpliftingService.java](https://github.com/OAGi/Score/pull/1454/files#diff-42543a102cb7befaccb3cd7ec914ed35fe0e21cb86b517f5b9829941065717cf)

**Comment by dubnemo** [comment]
I really don't believe this was the solution.  Codelists should be a shared
concept no different than business context and business terms.

**Comment by kbserm** [comment]
@dubnemo @jim-wilson-kt Let's put the code list up as an architectural issue discussion.

**Comment by dubnemo** [comment]
> #1358 has been created

@kbserm @jim-wilson-kt @sfohn @hakjuoh @smorgan19 @joshklm 

Scroll up, I previously created this issue:
https://github.com/OAGi/Score/issues/1358 

I will bring #1358 as an Architectural Issue for review in the Score meeting or next Architecture meeting.  I advocate that we distance ourselves from maintaining code lists as part of an OAGIS release.  Code lists have their own release lifecycle.
