### ISSUE TITLE
Hide unused should not be checked during the creation of a new BIE

### ISSUE THREAD

**Issue by michaelfigura** [OAGi/Score#1366]
It appears that this functionality of having hide-unused checked carries over from any other BIE session so that when you create a new BIE nothing is checkable until hide-unused is disabled.

**Comment by hakjuoh** [comment]
There are some options to solve this issue:

1. Separately keep 'Hide Unused' option settings for each BIE.
2. Turn the option off during the new BIE creation if it was enabled.

One drawback is that the user should click the 'Hide Unused' checkbox again after the new BIE is created.

**Comment by jim-wilson-kt** [comment]
@hakjuoh regarding your point 2, this is what we want. There is no drawback to the user for new BIEs since the user would have to uncheck "hide unused" in order to see/do anything useful.

**Comment by hakjuoh** [comment]
@jim-wilson-kt Thanks for your feedback. 'Hide Unused' option will be turned off after BIE creation processes, such as 'Create BIE', 'Copy BIE', and 'Uplift BIE'.
