### ISSUE TITLE
External Reference URI should be marked as required in "Create Business Term" page

### ISSUE THREAD

**Issue by bingqi2045** [OAGi/Score#1368]
The "Create" button is disabled without the input for External Reference URI.

Please see the attached. 

<img width="575" alt="business term required" src="https://user-images.githubusercontent.com/117864643/211668261-5b383d5c-0f54-45f1-984a-f97da089b497.png">

**Comment by hakjuoh** [comment]
@bingqi2045 Now the 'External Reference URI' field is required in both 'Create/Edit Business Term' pages.

<img width="305" alt="Screen Shot 2023-01-11 at 11 42 34 AM" src="https://user-images.githubusercontent.com/16102116/211865018-85132c04-1dfa-4a77-b48d-02dbaaccf4b5.png">

**Comment by bingqi2045** [comment]
Fix verified
