### ISSUE TITLE
Layout BIE selection page for the BT Assignment needs some improvements

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1375]
At least the DEN, Top Level BIE, Version, Status and Remark column width should be adjustable.

It should be possible to assign BT to top-level BIE too. @dubnemo @joshklm @sfohn what do you think?

**Comment by kbserm** [comment]
Also, I think assigning BT by the BT Assignment page is not practical. If BTs need to be assigned to ASBIE or BBIE with the same DEN in different locations of the top-level BIE, it is impossible to know which one to pick. See the first and the last Identifier in the screen cap below.

![image](https://user-images.githubusercontent.com/7863166/213036429-ef7af514-8ffc-4bb4-b138-8f13ac3c42fa.png)

**Comment by hakjuoh** [comment]
This page has been discarded.
