### ISSUE TITLE
Type Code shouldn't be required in the Select Business Term of the BT assignment

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1376]

**Comment by hakjuoh** [comment]
@kbserm Now, the 'Create' button is enabled without the type code. @bingqi2045 Please update the test document with this behavior.

<img width="546" alt="Screen Shot 2023-01-18 at 10 21 52 AM" src="https://user-images.githubusercontent.com/16102116/213211895-a22ee3bc-cb74-4044-87a7-3ae35d305578.png">

**Comment by bingqi2045** [comment]
the test document TestSuite42.md has been updated without the requirement of Type  Code.
