### ISSUE TITLE
Change the button name "Assign New Business Term" to "Assign Business Term"

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1377]

**Comment by hakjuoh** [comment]
@kbserm Changed. @bingqi2045 You can use this button name on your test script when it searches the button.

<img width="562" alt="Screen Shot 2023-01-18 at 10 09 23 AM" src="https://user-images.githubusercontent.com/16102116/213208083-c0b78bc1-3fd7-4d65-a2a1-0cb681c568a4.png">

**Comment by bingqi2045** [comment]
I can see that the button name is changed to "Assign Business Term"
