### ISSUE TITLE
Only one preferred business term is allowed for each BIE

### ISSUE THREAD

**Issue by bingqi2045** [OAGi/Score#1381]
On the "Business Term Assignment" page, click on the "Search by Selected BIE" button, I see two "True" value for the selected BIE. 

<img width="1004" alt="Screenshot 2023-01-19 at 12 50 05 PM" src="https://user-images.githubusercontent.com/117864643/213522097-7434e193-0b31-4b38-8146-9ac9778c8533.png">

**Comment by hakjuoh** [comment]
@bingqi2045 Updated fixes. Please test this function again.

**Comment by bingqi2045** [comment]
Function tested.  Only one true value allowed for each selected BIE.

The test cases have been updated too.
