### ISSUE TITLE
missing format check for the external csv file upload 

### ISSUE THREAD

**Issue by bingqi2045** [OAGi/Score#1383]
No format check on the external csv file upload. 

I can upload the following csv file with extra columns, and wrong URI format in the second column. 

![Screenshot 2023-01-20 at 10 18 50 AM](https://user-images.githubusercontent.com/117864643/213734276-5128b6e3-7d3a-421d-a820-66bbe996b0b3.png)

**Comment by hakjuoh** [comment]
@kbserm @bingqi2045 What's the correct behavior when the csv file has invalid data? In my opinion, the page should report the result with error messages. If
- `businessTerm` is invalid: Error. e.g., `The business term 'XYZ' is invalid`
- `externalReferenceUri` is invalid: Error. e.g., `The external reference URI 'XYZ' is invalid`
- Unknown column(s) (`test` in the screenshot) found: Pass/Ignore

Can we put 'Type Code' and 'Preferred' tag into the upload template?

**Comment by kbserm** [comment]
- `businessTerm` is invalid: Error. e.g., `The business term 'XYZ' is invalid`
  - <serm>I'm not sure what are the conditions we can say that the term is invalid. 
- `externalReferenceUri` is invalid: Error. e.g., `The external reference URI 'XYZ' is invalid`
  - <serm>Sure. See if there is already a library that is readily validate https://www.rfc-editor.org/rfc/rfc3986 
- Unknown column(s) (`test` in the screenshot) found: Pass/Ignore
  - <serm>Sure

**Comment by hakjuoh** [comment]
> `businessTerm` is invalid: Error. e.g., `The business term 'XYZ' is invalid`
> * I'm not sure what are the conditions we can say that the term is invalid.

We may have a character and a length constraints; e.g., a maximum length of 100 alphanumeric, underscore, at sign, or hyphen characters.

**Comment by bingqi2045** [comment]
Currently, the length limit is 255, maybe this is the only constraint?
