### ISSUE TITLE
Unbounded association cannot be changed back to 0..1 while in WIP state in the working branch

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1386]
@hakjuoh In the mean time, could you go into the developed instance database to fix the cardinality of the Primary UOM back to 0..1.

@elena-jelisic Please add this test assertion.

FYI @michaelfigura

**Comment by hakjuoh** [comment]
@kbserm Did you mean 'Item Base. Primary UOM' needs to be changed back to 0..1? Item Base is in Candidate state. Please confirm it.
<img width="1432" alt="Screen Shot 2023-01-27 at 10 10 25 AM" src="https://user-images.githubusercontent.com/16102116/215119782-81c985b9-fdfb-4841-b907-979e209f66ba.png">

**Comment by kbserm** [comment]
Yes. @michaelfigura  tried to do that during the oagis review session but it didn't work.

**Comment by hakjuoh** [comment]
@kbserm @michaelfigura Updated it to 0..1.
<img width="1213" alt="Screen Shot 2023-01-31 at 10 46 12 AM" src="https://user-images.githubusercontent.com/16102116/215808033-492534c2-bf19-4437-94c1-fbc2ac35ad8f.png">
