### ISSUE TITLE
The EU should not be allowed to edit BIE if the end user ASCCP is amended

### ISSUE THREAD

**Issue by elena-jelisic** [OAGi/Score#1387]
1. The EU_A creates a BIE  from an ASCCP which is in the Production state and created by the EU_B.
![image](https://user-images.githubusercontent.com/71283987/214613109-1e297fe5-2356-42a3-8603-6c5990e8210a.png)

2. The EU_B opens an ASCCP that was previously in the Production state.
![image](https://user-images.githubusercontent.com/71283987/214613618-cdb679b7-677a-42ea-a08b-293324764b23.png)

3. The EU_B Amends the ASCCP.
![image](https://user-images.githubusercontent.com/71283987/214613731-5135ebe4-55ff-4a21-88a1-b5793cea7486.png)

4. The EU_A open previously created BIE and tries to edit it.
![image](https://user-images.githubusercontent.com/71283987/214614077-c8dd6b79-ae8a-4989-ad66-8bf2ef767c1b.png)
![image](https://user-images.githubusercontent.com/71283987/214614214-e6732e2e-e2ad-4a08-b72f-92bd197288d6.png)

**Comment by hakjuoh** [comment]
@elena-jelisic @kbserm we can solve this by making the BIE to be inaccessible if the ASCCP has being revising/amending.
<img width="496" alt="Screen Shot 2023-01-25 at 11 28 17 AM" src="https://user-images.githubusercontent.com/16102116/214626644-0fbd84ce-031b-4043-9f78-feb683790288.png">

Let me know if it's okay.

**Comment by hakjuoh** [comment]
@elena-jelisic According to [TC 15.12.5](https://github.com/OAGi/Score/blob/develop/docs/test_cases/TestSuite15.md#test-assertion-15125), the end-user cannot change the base ACC to another one during ASCCP amending. Thus, we decide that the system allows the top-level BIE to get updated even if the base ASCCP is amending. No need to change Sakis' test scripts.
