### ISSUE TITLE
If the code list is in Deleted state it should be displayed using Strikethrough font for the code list selection

### ISSUE THREAD

**Issue by elena-jelisic** [OAGi/Score#1393]
1. There is the "oacl_CountryCode_derived" code list created by the EU_A which is in "Deleted" state
![image](https://user-images.githubusercontent.com/71283987/215586120-4bb07bfb-f280-41e1-aea0-9d488e50a52f.png)

2. When an EU_B creates a BIE, the "oacl_CountryCode_derived" code list should show up for the code list selection (since it is in the same release as the BIE), but with Strikethrough font because it is "Deleted".
![image](https://user-images.githubusercontent.com/71283987/215587032-b06c717c-6b25-47cd-a607-5eb588afa6fc.png)

**Comment by hakjuoh** [comment]
@elena-jelisic Changed the text with a strike-through for deleted code list/agency ID list
<img width="527" alt="Screen Shot 2023-01-30 at 3 33 28 PM" src="https://user-images.githubusercontent.com/16102116/215589397-3edce9d2-9ab3-4f86-b900-73f936760ba9.png">

**Comment by elena-jelisic** [comment]
@hakjuoh I have tested again, and it works properly now.
