### ISSUE TITLE
"hover" over "Show business terms" button not working 

### ISSUE THREAD

**Issue by bingqi2045** [OAGi/Score#1398]
"hover" over "Show Business Terms" button without clicking not working. 

<img width="1136" alt="Screenshot 2023-02-06 at 3 36 08 PM" src="https://user-images.githubusercontent.com/117864643/217079894-d0e7b3d5-7013-4aeb-9cb8-770ace00d7b9.png">
<img width="673" alt="Screenshot 2023-02-06 at 3 35 06 PM" src="https://user-images.githubusercontent.com/117864643/217079923-81dd4d3c-936e-49d5-a8eb-a4087026a99f.png">

I have one business term assigned to the selected BIE, but when I hover over the "Show Business Terms" button, and it displays: "no business term assigned yet".

**Comment by bingqi2045** [comment]
When "hover" over "Show Business Terms" buttons, there should be up to 5 business terms displayed

**Comment by hakjuoh** [comment]
It used the polling approach to retrieve the list of assigned business terms for the BIE node, but costs heavy resources by several requests. Thus, we decided to take this feature off.
