### ISSUE TITLE
BIE Expression → Open Document Spreadsheet fails for all types (ODS, FDOS, XLSX)

### ISSUE THREAD

**Issue by jim-wilson-kt** [OAGi/Score#1400]
<img width="1876" alt="image" src="https://user-images.githubusercontent.com/2702530/217393059-9e7150fb-78c5-41e4-a1b7-e3bc874de4e2.png">

**Comment by jim-wilson-kt** [comment]
This occurred at https://oagiscore.net/profile_bie/express?q=c29ydEFjdGl2ZT1sYXN0VXBkYXRlVGltZXN0YW1wJnNvcnREaXJlY3Rpb249ZGVzYyZwYWdlSW5kZXg9MCZwYWdlU2l6ZT0xMCZyZWxlYXNlSWQ9MTMmZXhjbHVkZVByb3BlcnR5VGVybXM9TWV0YSUyMEhlYWRlcixQYWdpbmF0aW9uJTIwUmVzcG9uc2UmYWNjZXNzPUNhblZpZXcmYnVzaW5lc3NDb250ZXh0PUJpb3BoYXJtYWNldXRpY2Fs

**Comment by hakjuoh** [comment]
@jim-wilson-kt Thanks for reporting. This problem's happening only if 'Put each schema in an individual file' option is chosen.
![Annotation 2023-02-08 094707](https://user-images.githubusercontent.com/16102116/217564164-4fe3e85f-cca7-4f6f-89f4-2e09e5b1c8e7.png)

I'll remove 'Put all schemas in the same file' option for the ODS.

**Comment by hakjuoh** [comment]
@elena-jelisic @bingqi2045 I made a fix for this issue, and please review it.
