### ISSUE TITLE
Data too long for column 'business_term'

### ISSUE THREAD

**Issue by hakjuoh** [OAGi/Score#1401]
Tested 'Create Business Term' page with randomly generated long texts. 'Edit Business Term' page may also have the same problem.

![Annotation 2023-02-08 104839](https://user-images.githubusercontent.com/16102116/217579923-94c35b9b-4ffe-4c71-a084-ad77b5268445.png)

**Comment by bingqi2045** [comment]
Current allowed maxlength = 255, what is the length limit for business term?
