### ISSUE TITLE
OpenAPI expression - default example keyword to empty string or null

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1405]
It would be a good practice to always populate the **example** keyword in the OAS expression for components.schemas object, as Swagger Editor will generate data if not present in some cases, or output the data type.  Currently the **example** keyword is suppressed if there isn't any content in the associated x.example field in the repo tables (e.g., x=bbie).

Rules:
if string or date, then empty string  (`example: ""`)
else null value if integer or numeric  (`example: null`)
else false for boolean (`example: false`)

**Comment by hakjuoh** [comment]
@dubnemo Rules are applied. Here's sample result:
[WarehouseShippingOrder.yml](https://github.com/OAGi/Score/files/10797876/WarehouseShippingOrder.txt)

**Comment by dubnemo** [comment]
Verified.   Can you now add example data and re-upload the yml?

**Comment by hakjuoh** [comment]
> @hakjuoh Verified. Exactly what the doctor ordered. Can you now add example data to the BIE and then reupload the yml? String, date, boolean, numeric should be fine. Thank you.

Here's the same BIE with example data.

[WarehouseShippingOrder_with_examples.txt](https://github.com/OAGi/Score/files/10806961/WarehouseShippingOrder_with_examples.txt)

**Comment by dubnemo** [comment]
@hakjuoh Great!  Done!
