### ISSUE TITLE
changing BCCP entity type to Element won't give user warning

### ISSUE THREAD

**Issue by bingqi2045** [OAGi/Score#1406]
<img width="1281" alt="Screenshot 2023-02-21 at 3 24 47 PM" src="https://user-images.githubusercontent.com/117864643/220450851-11023916-04d3-4935-af49-ba3916ef7fe0.png">

When changing entity type to Element, the system shall warn the user that the Default and Fixed Value will be cleared.

**Comment by hakjuoh** [comment]
@bingqi2045 Users will see the following message when it tries to change the entity type to 'Element' and the value constraint (the default value or the fixed value) is not empty.

![Annotation 2023-02-21 163849](https://user-images.githubusercontent.com/16102116/220464846-4e5f0673-fcb6-4ece-9ad5-b48a685f61d6.png)

**Comment by bingqi2045** [comment]
warning added.
