### ISSUE TITLE
Set Base ACC - make Conflicts a dialog box that forces me to either click OK or Copy to Clipboard

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1424]
Developer Role
==========
There simply isn't enough time to capture the text displayed.  

If we were provided a dialog box that has two buttons, that would be very helpful:

Button 1 : OK
Button 2: Copy to clipboard

I need to know what I have to do to resolve adding a base ACC to Party Identification.  It should be based off Named Identification Base ACC.
@kbserm

**Comment by hakjuoh** [comment]
@dubnemo @kbserm Here's an example of the changed dialog box:

![Annotation 2023-03-29 181608](https://user-images.githubusercontent.com/16102116/228680472-da99be98-d7d0-43a3-9446-5eb372ca580b.png)

**Comment by dubnemo** [comment]
Exactly what we need!  Thank you!
