### ISSUE TITLE
"Update" button unexpectedly disabled when editing BIE

### ISSUE THREAD

**Issue by jim-wilson-kt** [OAGi/Score#1431]
Steps to reproduce on https://test.oagiscore.net:

1. Create a new BIE.
2. Click the check box for a child component of the root component.
3. Click the link of another child component of the root component. Note that the `Update` button is enabled.
4. Click the root component's link. Note that the `Update` button is unexpectedly disabled.

**Comment by jim-wilson-kt** [comment]
By the way, the workaround for this is to just click on any of the root component's child components again and the click the `Update` button.

**Comment by hakjuoh** [comment]
@jim-wilson-kt Thanks! I created [a new PR](https://github.com/OAGi/Score/pull/1433) for this issue. @elena-jelisic @bingqi2045 Please review/close it if it solved.

**Comment by bingqi2045** [comment]
I just tested after pulling the latest commits. The"update" issue is fixed.
