### ISSUE TITLE
Create Business Term: cannot paste the full length of a URI 

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1458]
![image](https://user-images.githubusercontent.com/32434235/227573693-37735b5c-0557-4b8b-969f-163a24a2baad.png)

**Comment by bingqi2045** [comment]
External Reference URI's maxlength is set at 45 previously, just updated it to 1000

**Comment by bingqi2045** [comment]
Test with long URI (> 1000) passed after the update.
