### ISSUE TITLE
Allow BCCs referencing BCCPs based on Open Identifier to be selected as an integer (override feature)

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1469]
From a code generation point of view, and UI behavior point of view, some identifiers need to be specified as integer.

1) DB unique identifiers in most relational databases are integers or have the option to be set as an integer.  If the API layer specifies a string in JSON, then a type casting must be performed in a mapper class or edit of the yml to correct the data type for all id and *Id properties.  

2) UI tools like React.js may need a sorted list, and developers have stated using a string is problematic.

![image](https://user-images.githubusercontent.com/32434235/230907117-ee0e17d1-4970-4a0c-99ab-09a87d7dff3e.png)

**Comment by hakjuoh** [comment]
The value domain of the 'Identifier. Type' in CCTS data type catalog is defined by 'String', 'Normalized String', and 'Token' allowed primitive types, and we mapped each primitives to 'string'-ish data types based on the XML data types in Score. @kbserm Should we relax this mapping with any data types (or at least numeric types) for this issue?

**Comment by dubnemo** [comment]
@hakjuoh @kbserm
Should this be an override feature on the BCC; i.e., it overrides the BCCP?  I complained about this in the past, and I thought I created an issue in the past.  I believe the reference to ISO 15000 core data types came up -- hence why I called this an override.

**Comment by dubnemo** [comment]
@kbserm @hakjuoh 
What is interesting is that the OpenAPI standard id query parameter is expressed as an integer.

`      parameters:
      - name: "id"
        in: "query"
        description: ""
        required: false
        schema:
          type: "integer"
`

**Comment by hakjuoh** [comment]
@kbserm Added 'integer' primitive to all Identifier DTs and DT_SCs.
![Annotation 2023-04-17 141310](https://user-images.githubusercontent.com/16102116/232573955-582a5a7b-ddf3-40f9-9ba3-8cc66ecfe883.png)

**Comment by dubnemo** [comment]
This is more than I requested but it is a good idea.
