### ISSUE TITLE
Allow mass status update of BIEs from WIP -> QA -> Production similar to Core Components

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1473]
When creating a microservice we may have upwards to 20 BIEs that are referenced in a final OpenAPI definition (multiple OpenAPI files merged into one).  It would be great to be able to update all at once, very going into each one individually.

**Comment by hakjuoh** [comment]
@bingqi2045 Like the CC page, users now can update multiple BIEs at once. Please test it.

![Annotation 2023-04-18 140227](https://user-images.githubusercontent.com/16102116/232864617-20b76e19-8fd9-4a09-8ac6-8ac3a890787f.png)

**Comment by bingqi2045** [comment]
just tested it, the end user can batch update the status of BIEs from WIP to QA back and forth. also batch update the status of BIEs from QA to Production

**Comment by dubnemo** [comment]
Excellent thank you!
