### ISSUE TITLE
Confirm Verb tagged as Noun

### ISSUE THREAD

**Issue by lmkennethburnett** [OAGi/Score#1476]
The confirm verb is being returned with a noun tag

**Comment by hakjuoh** [comment]
@lmkennethburnett Thanks for your reporting. I missed the fact that 'Confirm' had not based on 'Verb. Details' unlike other verbs. Although this issue will be fixed in Score 3.0.2, you could run the following query to fix DB records if needed.
```
UPDATE `asccp_manifest_tag`, `tag`, (
    SELECT `asccp_manifest`.`asccp_manifest_id` FROM `asccp_manifest`
    JOIN `asccp` ON `asccp_manifest`.`asccp_id` = `asccp`.`asccp_id`
    WHERE `asccp`.`property_term` = 'Confirm') t
SET `asccp_manifest_tag`.`tag_id` = `tag`.`tag_id`
WHERE `tag`.`name` = 'Verb' AND `asccp_manifest_tag`.`asccp_manifest_id` = t.`asccp_manifest_id`;
```
