### ISSUE TITLE
Cannot update the description of a Context Schema Value

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1488]
![image](https://github.com/OAGi/Score/assets/32434235/29c057b5-10d2-4fda-8ddb-5278ea227e8a)

![image](https://github.com/OAGi/Score/assets/32434235/8f347c0d-7942-4b8e-91ad-f9e8053d63f0)
 
Message flashes stating that Manage Milk Production already exists.

![image](https://github.com/OAGi/Score/assets/32434235/edaeac97-9253-4fb8-9e5e-624039cdd951)

**Comment by hakjuoh** [comment]
@bingqi2045 Please review [the PR](https://github.com/OAGi/Score/pull/1489)

**Comment by bingqi2045** [comment]
just tested.  I can update the meaning in the following context scheme value example. 

<img width="1229" alt="Screenshot 2023-05-09 at 4 39 54 PM" src="https://github.com/OAGi/Score/assets/117864643/11c18624-45a4-4547-9d0a-73858fb770c8">
