### ISSUE TITLE
Use a different background color for each role.

### ISSUE THREAD

**Issue by hakjuoh** [OAGi/Score#1491]
@michaelfigura Light red for admin, Light yellow for developers, and Light green or gray for regular users.

**Comment by hakjuoh** [comment]
@michaelfigura Please review colors.

- Light red for Admin
<img width="1303" alt="Screenshot 2023-05-10 at 1 09 39 PM" src="https://github.com/OAGi/Score/assets/16102116/f73bf125-f786-42bb-828b-f20dd87c4b90">

- Light yellow for developers
<img width="1301" alt="Screenshot 2023-05-10 at 1 09 54 PM" src="https://github.com/OAGi/Score/assets/16102116/ae4e11e3-a258-4e8c-af95-721666b10a4e">

- Light green for end-users
<img width="1298" alt="Screenshot 2023-05-10 at 1 10 02 PM" src="https://github.com/OAGi/Score/assets/16102116/1303d26f-cae6-47e9-a692-38652437b667">

**Comment by michaelfigura** [comment]
Looks great!

**Comment by hakjuoh** [comment]
@bingqi2045 Please review [the change](https://github.com/OAGi/Score/commit/46f3c90d466cdb858b4af9c7d17cbc14a844a06e) and test it.

**Comment by bingqi2045** [comment]
The background is correctly changed to a different color  depending on the role of the user.


<img width="919" alt="Screenshot 2023-05-11 at 10 31 26 AM" src="https://github.com/OAGi/Score/assets/117864643/b06f7e3b-846a-4754-a837-89be8e2ede1e">
<img width="919" alt="Screenshot 2023-05-11 at 10 31 26 AM" src="https://github.com/OAGi/Score/assets/117864643/b4c76702-f5c4-4516-8f68-067c15bc1602">
<img width="919" alt="Screenshot 2023-05-11 at 10 31 26 AM" src="https://github.com/OAGi/Score/assets/117864643/5c7ce31e-b86d-4171-aad7-7e473321746f">

**Comment by hakjuoh** [comment]
@michaelfigura @bingqi2045 Decided using a gray color for regular users.
