### ISSUE TITLE
Consider an interim approach to generate and merge multiple OpenAPI YML files into one file

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1492]
#862 has been open for years.
@sfohn @kbserm @hakjuoh @bingqi2045 
This proposal allows a simple jumpstart to build upon for the future.

Use Case:
Select Express BIEs as OpenAPI
Display empty grid
Select Business Context (required) - this is the name of the microservice
Display BIEs assigned to that business context
Enable the following edits on the BIE list
- Verb (droplist values : `POST, PATCH, PUT, GET, DELETE`)
- Array (checkbox)
- Suppress Root Property (**default as enabled**): checkbox
- resource path (editable);default `'/{BizContext}/{version}/{BIE_Name}LIST | /{id}| ''' -- rule: 'List' if array, /{id} if PUT, PATCH, GET, DELETE (no array, '' if POST`
- tag (editable); default }`{BIE_Name}`
- operationId (editable); `'{Action}{BIE_Name}'`, we have a mapping from {Verb} to {Action} in old close issue

Persist above fields into tables proposed by OpenAPI working group.  The commit would after navigation from one row to the next in the grid.

We would express all BIEs in a specific <business_context> (pre-filtered) into a single yml in an asynchronous manner.

**Comment by dubnemo** [comment]
![OpenAPI_GridView](https://github.com/OAGi/Score/assets/32434235/f1e5634e-c3ce-4118-a6db-be93e73b6179)

**Comment by bingqi2045** [comment]
Hi Scott, Please review the attached Schema and let me know anything need to be changed.

**Comment by dubnemo** [comment]
@bingqi2045 I am trying to perform a DIFF on the last know SQL in #862 vs this one you provided.  Of course these DIFF tools are not that great, and its hard to discern.
I don't recommend paring down the tables to MVP, but the UI would have simpler features over the agreed upon ERD from our work group.  Did you change anything?
@hakjuoh @kbserm

**Comment by dubnemo** [comment]
@bingqi2045 @hakjuoh 
here is the sample yml for the fixed asset:
[FixedAsset-ProgramManagement (all).zip](https://github.com/OAGi/Score/files/11910374/FixedAsset-ProgramManagement.all.zip)

**Comment by dubnemo** [comment]
Existing rules in place for resource path and operation id default values.
As stated in the description, these are editable.
If two BIEs have the same resource path and verb combination, they should be considered paired like the Fixed Asset example above.  If there are more than one, display a message and stop the process.
![image](https://github.com/OAGi/Score/assets/32434235/3c7b690d-acd3-4cff-9025-48353bc170fe)

**Comment by bingqi2045** [comment]
@dubnemo 
Application Logic

The user specifies a Business Context for the Open API Doc. This will be used as the microservice name.

When the user click on Add BIE, the pop-up dialog default the Business Context filter to the one specified in the Open API Doc page, but the user can change it to what he wants. In other words, the application does not put a rigid restriction that all BIEs in a single Open API must share a common business context associated with the Doc. This is to simplify application logic and allow for flexibility.

A Validation button will be added to the Open API Doc page, which can include checking that all BIEs in the Doc share the same business context.

The Discard Business Context function needs to be updated to check for referential integrity associated with the Open API Doc. 

Will this application logic follow your requirements?

**Comment by bingqi2045** [comment]
@dubnemo  

You mentioned that two BIEs are linked if they share the same resource path, like in the following screenshot:
<img width="395" alt="Screenshot 2023-07-05 at 9 34 50 AM" src="https://github.com/OAGi/Score/assets/117864643/f690319d-9903-4198-8bb4-6037aa60990c">
Can you elaborate on this scenario?

**Comment by dubnemo** [comment]
Well the PATCH and the GET are NOT likely scenarios.  

On a POST /program-management/v1/fixed-asset, there will be two BIEs; 1) a requestBody, and 2) a responseBody.  Therefore these two with the same verb-resourcePath combination need to be 'linked'.

**Comment by dubnemo** [comment]
@bingqi2045 related to the business context, it is only a filtering mechanism to help narrow which BIEs will be added.

**Comment by dubnemo** [comment]
@bingqi2045  did you look at #1519 ?  

Also please update your local machine with a current state backup of oagiscore.net, specifically to capture the 10.9 Express Pack.  You will then have realistic example BIEs, which the Remark field is capturing Verb - Resource Path details.

**Comment by dubnemo** [comment]
@bingqi2045 @hakjuoh @kbserm @ekwallace 

Just so you know how valuable this issue is for everyone.  I tried to merge three BIEs expressed as OpenAPI into one yml file during an AgGateway call, and ran into an indentation problem that was not easily handled.  Copy and paste from one file into another file does not always work, and too often this is while I am presenting.

![image](https://github.com/OAGi/Score/assets/32434235/425ef070-8d3e-4817-8c93-c2e8862f2d69)

**Comment by bingqi2045** [comment]
@dubnemo  Thanks for the motivation, I am still working on it.

**Comment by dubnemo** [comment]
No worries @bingqi2045.
Let's think this through properly.
The value proposition is big.

I suggest taking a copy of oagiscore.net repo, and look at all the
interrelated BIEs.
There are a lot of reuse for global properties/code generation reasons.
I will send you the AgGateway yml when I finish documenting the
resource/verb combinations.

**Comment by dubnemo** [comment]
@bingqi2045 

Here is a good example merging three BIEs for Scale Ticket:
[AgGateway-ScaleTicket.zip](https://github.com/OAGi/Score/files/12100347/AgGateway-ScaleTicket.zip)

And here is one for the SME Manufacturing connectKit I have been upllifting:
[SME-Manufacturing-connectKit(ExpressPack).zip](https://github.com/OAGi/Score/files/12100360/SME-Manufacturing-connectKit.ExpressPack.zip)

**Comment by bingqi2045** [comment]
@dubnemo 
I just checked them in the Swagger Editor. 

I see how the array references are handled. 

I also see how the resource paths and operationIds are used:

resource path for one of the BIEs:

/bulk-delivery/direct/v1-1/scale-ticket/{id}

the operationId for it is:

operationId: "scaleTicket_getScaleTicketDirect"

**Comment by dubnemo** [comment]
Includes both v2 of Dataset Metadata and v1.1 of Scale Ticket yml files:

[AgGateway-YML.zip](https://github.com/OAGi/Score/files/12553225/AgGateway-YML.zip)

**Comment by dubnemo** [comment]
Recommendations for defaulting operationId:
```
<operationId> ::=<business-context>_<operation-definition>
<operation-definition> ::= <operation-enum><BIE_Name><opt-list>
<operation-enum> ::="create" | "query" | "update" | "delete" | "replace"
<opt-list> ::= "list" | ""
```

Recommendations for defaulting schema object root property:
```
<schema_object_root> :: = <operation-definition><opt-entry>
<opt-entry> ::= "Entry" | ""
```

**Comment by dubnemo** [comment]
@bingqi2045 
Also you have enough real estate to expand the description too.

![image](https://github.com/OAGi/Score/assets/32434235/49f1c42b-2972-4513-be9e-d3257e709e1f)

**Comment by dubnemo** [comment]
@bingqi2045 if you think the grid is tight, State, Version, Array Indicator, and Suppress Root sizes can be reduced quite a bit.
It may make sense to have the following order:
DEN
Owner
Remark
State 
Version
Verb
Message Body -  shorten to Body
===== slack message ====

Not sure if there is value to set Verb and Message Body values up front vs the next screen (which I have not even got to).  Personally I have used the Remark field to guide me during BIE editing but not all users may use that approach.

Bingqi Cheng
  [12:00 PM](https://oagi.slack.com/archives/D0621EKRN5A/p1697821211346239)
ok, I will try it


ScottNieman
  [12:03 PM](https://oagi.slack.com/archives/D0621EKRN5A/p1697821392914859)
Also the Remark is more important than the Owner on the BIE List.  Scratch the Owner, and maybe reduce the DEN size (eliminate the GUID as it has limited business value).
![image](https://github.com/OAGi/Score/assets/32434235/014207d8-8d80-428d-8ad4-b5fd5b610dd3)

**Comment by bingqi2045** [comment]
@dubnemo  new docker image is deployed to test instance to address all the UI comments above. 
Please check it.

**Comment by dubnemo** [comment]
Test Case:
Adding 6-7 BIEs only persisted for four BIEs.
Added others one by one.

**Comment by dubnemo** [comment]
Test Case:
Updating Tag Name on all BIEs caused java.lang.IllegalArgumentException
![image](https://github.com/OAGi/Score/assets/32434235/49cbead9-1dee-444b-90af-0211a2a223be)
First BIE Tag Name persisted.
Next one continues to throw exception.
![image](https://github.com/OAGi/Score/assets/32434235/d493b880-c302-4170-a116-8c675fce2752)

**Comment by dubnemo** [comment]
@bingqi2045  the same is happening on enabling the Suppress Root checkbox.  The first time I check a BIE row and Update, it works fine.  The second time, I check the next BIE, it throws an exception.  

![2023-10-23-065336_1920x1080_scrot](https://github.com/OAGi/Score/assets/32434235/8b2e892a-1576-4727-afdf-52e3c24d509f)

**Comment by dubnemo** [comment]
@bingqi2045 
I think we need 1) to default Suppress Root =  true when Adding BIE (as stated in May 10 comment) and 2) add back the Array Checkbox.  The Updated On and Owner columns are not need in this dialog box.

![2023-10-23-070403_1920x1080_scrot](https://github.com/OAGi/Score/assets/32434235/9e9148e4-a1d6-4f84-8163-cea5f5027d7c)

**Comment by dubnemo** [comment]
@bingqi2045 the filename of the generated yaml should be <Title>_<Document_Version>_<Timestamp_now>.yml

**Comment by dubnemo** [comment]
@bingqi2045  resource id in the UI should map to the yaml
For example, this setup on the PATCH
/as-planted/V1/container/{id}/container-state 
![2023-10-23-090627_1920x1080_scrot](https://github.com/OAGi/Score/assets/32434235/61bca149-6da5-49d2-8f62-33f082e3fa28)
But does not appear in the yaml

![2023-10-23-090649_1920x1080_scrot](https://github.com/OAGi/Score/assets/32434235/0e298079-764a-42f5-8379-021d2b6aae6b)

Again, this will be in a test case.

**Comment by dubnemo** [comment]
[Traceability-API_V1_2023-10-23T09:27-05:00.yml.zip](https://github.com/OAGi/Score/files/13072147/Traceability-API_V1_2023-10-23T09.27-05.00.yml.zip)

Opening the attached in editor.swagger.io reveals this error due to the POST response addition, reusing the GET by id response in Containers, TRUs, and CTEs:
 
Semantic error at paths./as-planted/V1/container/{id}
Declared path parameter "id" needs to be defined within every operation in the path (missing in "post"), or moved to the path-level parameters object
Jump to line 43
Semantic error at paths./as-planted/V1/traceable-resource-unit/{id}
Declared path parameter "id" needs to be defined within every operation in the path (missing in "post"), or moved to the path-level parameters object
Jump to line 187
Semantic error at paths./as-planted/V1/traceable-resource-unit/{id}.post.operationId
Operations must have unique operationIds.
Jump to line 221
Semantic error at paths./as-planted/V1/container.post.operationId
Operations must have unique operationIds.
Jump to line 246
Semantic error at paths./as-planted/V1/critical-tracking-event/{id}
Declared path parameter "id" needs to be defined within every operation in the path (missing in "post"), or moved to the path-level parameters object
Jump to line 256
Semantic error at paths./as-planted/V1/critical-tracking-event/{id}.post.operationId
Operations must have unique operationIds.
Jump to line 290

**Comment by dubnemo** [comment]
@bingqi2045 correct yaml is attached.  Removing the duplicated POSTs under the /{id} paths worked.

[(edited)Traceability-API_V1_2023-10-23T09:27-05:00.yml.zip](https://github.com/OAGi/Score/files/13072626/edited.Traceability-API_V1_2023-10-23T09.27-05.00.yml.zip)

**Comment by dubnemo** [comment]
@hakjuoh @kbserm @jim-wilson-kt @michaelfigura 
This is a Slack note sent to @bingqi2045 .
========================
FYI -- this feature just saved me about 6-8 hours of work for AgGateway. I still need to add query parameters on my -list endpoints, but this is a GREAT.  I was able to refine the OpenAPI document in about 10minutes. Seriously great.

**Comment by dubnemo** [comment]
@bingqi2045 
One final ask for v3.2 is remove the Update On sorting of this grid, and to have a default row sorting by Tag (increasing alpha) and then by OperationId (increasing alpha).  When a BIE is Added, and it should appear on the top of the list, and after update the grid is refreshed with the proper sorting.  This helps when BIEs are paired together in an operation as request and response message bodies.  

User defined sorting or filtering is NOT needed for v3.2.

![2023-10-29-075837_1920x1080_scrot](https://github.com/OAGi/Score/assets/32434235/bccdcd03-c522-43f4-981b-70877c697bd4)

Lastly, is there Owner based security to restrict editing of the BIE list by others?  If not, we can add that in v3.3.

**Comment by dubnemo** [comment]
@hakjuoh @bingqi2045 @kbserm 
I would like to keep test.oagiscore content in place for awhile until I replicate the Traceability API to oagiscore.net.  Please give me a few days to complete that.
@jim-wilson-kt
