### ISSUE TITLE
Add a "Components" tab to the home screen dashboard for displaying Component related work

### ISSUE THREAD

**Issue by michaelfigura** [OAGi/Score#1494]
For some of us (namely me and Scott N) we spend equal or greater time in Score developing new components and editing existing ones. It would be extremely helpful to see a dashboard view of our efforts. This new tab should be the default view when logged in as a developer. It should show both your component activity, as well as work of others. In other words, the behavior should be similar to the BIE tab view, but for component work occurring in the working branch.

**Comment by hakjuoh** [comment]
@michaelfigura 

Added 'Core Components' tab to the home dashboard.
<img width="1203" alt="Screenshot 2023-05-12 at 1 54 49 PM" src="https://github.com/OAGi/Score/assets/16102116/bda723fb-340d-4f5f-9d62-d9291155b1ab">

It shows components in only 'WIP', 'Draft', and 'Candidate' states, and the 'My recent core components' panel shows the most 5 recent core components.

**Comment by michaelfigura** [comment]
@hakjuoh this is AMAZING work! Bravo. I didn't think you could do it so fast. Or maybe you just made the screen mockup? Either way, this is way more progress than I expected! Take a bow!

**Comment by hakjuoh** [comment]
@michaelfigura Thanks! You could see that on test.oagiscore.net now. It'll be in 3.0.3.
