### ISSUE TITLE
Add control-S/command-S hotkey functionality for saving when on the BIE edit screen and component edit screen

### ISSUE THREAD

**Issue by michaelfigura** [OAGi/Score#1495]
This is a big time saver for folks like me who don't want to continuously grab the mouse.

**Comment by dubnemo** [comment]
Funny thing is that I often find myself typing Ctrl-S by mistake, expecting
it to work.

**Comment by hakjuoh** [comment]
@bingqi2045 Please review [this commit](https://github.com/OAGi/Score/commit/84d8093daee736a7f471c48f11451c8b6b20a75d), and test functions.
