### ISSUE TITLE
Addition of AVSC/AVRO as an Expressable Schema Format

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1500]
Avro is used in various processes for data serialization.  It has rich data structures, is compact, fast, and is commonly used with Kafka, Hadoop, AWS and more.  AVRO data serialization requires AVSC Schema Format which is fairly similar to JSON, but has a different data type.

**Comment by dubnemo** [comment]
Perhaps references to the schema definition would be helpful, as this is a
meta-model mapping exercise.   It seems the schema is expressed in JSON
(not JSON) schema.
Are you willing to help define this?  It will take a lot of time and effort.

We were using Hadoop for a while, then moved away from it.  So we have very
limited interest.   We have much more interest in expanding / completing
OpenAPI capabilities as a priority, as we have not completed the features
that had been defined by the API Work Group.

**Comment by smorgan19** [comment]
From a format comparison by data type:
![image](https://github.com/OAGi/Score/assets/56837736/18c6c490-6b76-4c43-861a-d995c1731191)

**Comment by hakjuoh** [comment]
@smorgan19 I wonder how you're dealing with a `namespace` property, a naming convention, an optional field declaration, nesting schemas, etc. Is there an example set of schema/instance?

**Comment by smorgan19** [comment]
@hakjuoh
{
    "namespace": "openapplications.org",
    "type": "record",
    "name": "GetPartyMaster",
    "fields": [
        {
            "name": "ApplicationArea",
            "type": {
                "type": "record",
                "name": "ApplicationArea",
                "fields": [
                    {
                        "name": "CreationDateTime",
                        "type": [
                            "null",
                            "string"
                        ]
                    }
                ]
            }
        },
        {
            "name": "DataArea",
            "type": {
                "type": "record",
                "name": "DataArea",
                "fields": [
                    {
                        "name": "Get",
                        "type": [
                            "null",
                            {
                                "type": "record",
                                "name": "Get",
                                "fields": [
                                    {
                                        "name": "GetUniqueIndicator",
                                        "type": [
                                            "null",
                                            "int"
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "name": "PartyMaster",
                        "type": {
                            "type": "array",
                            "name": "PartyMaster",
                            "items": {
                                "type": "record",
                                "name": "PartyMaster",
                                "fields": [
                                    {
                                        "name": "LastModificationDateTime",
                                        "type": [
                                            {
                                                "type": "record",
                                                "name": "PartyMasterLastModificationDateTime",
                                                "fields": [
                                                    {
                                                        "name": "content",
                                                        "type": [
                                                            "null",
                                                            "DateTime"
                                                        ]
                                                    },
                                                    {
                                                        "name": "typeCode",
                                                        "type": [
                                                            "null",
                                                            "string"
                                                        ]
                                                    }
                                                ]
                                            },
                                            "null"
                                        ]
                                    },
                                    {
                                        "name": "Party",
                                        "type": [
                                            {
                                                "type": "array",
                                                "name": "Party",
                                                "items": [
                                                    {
                                                        "name": "PartyMasterParty",
                                                        "type": "record",
                                                        "fields": [
                                                            {
                                                                "name": "typeCode",
                                                                "type": [
                                                                    "string",
                                                                    "null"
                                                                ]
                                                            },
                                                            {
                                                                "name": "ID",
                                                                "type": [
                                                                    "null",
                                                                    {
                                                                        "type": "array",
                                                                        "name": "ID",
                                                                        "items": {
                                                                            "name": "PartyMasterPartyID",
                                                                            "type": "record",
                                                                            "fields": [
                                                                                {
                                                                                    "name": "typeCode",
                                                                                    "type": [
                                                                                        "string",
                                                                                        "null"
                                                                                    ]
                                                                                },
                                                                                {
                                                                                    "name": "content",
                                                                                    "type": [
                                                                                        "string",
                                                                                        "null"
                                                                                    ]
                                                                                }
                                                                            ]
                                                                        }
                                                                    }
                                                                ]
                                                            },
                                                            {
                                                                "name": "Contact",
                                                                "type": [
                                                                    "null",
                                                                    {
                                                                        "type": "array",
                                                                        "name": "Contact",
                                                                        "items": {
                                                                            "name": "PartyMasterPartyContact",
                                                                            "type": "record",
                                                                            "fields": [
                                                                                {
                                                                                    "name": "typeCode",
                                                                                    "type": [
                                                                                        "string",
                                                                                        "null"
                                                                                    ]
                                                                                },
                                                                                {
                                                                                    "name": "PersonName",
                                                                                    "type": [
                                                                                        "null",
                                                                                        {
                                                                                            "type": "array",
                                                                                            "name": "PersonName",
                                                                                            "items": {
                                                                                                "name": "PartyMasterPartyContactPersonName",
                                                                                                "type": "record",
                                                                                                "fields": [
                                                                                                    {
                                                                                                        "name": "typeCode",
                                                                                                        "type": [
                                                                                                            "string",
                                                                                                            "null"
                                                                                                        ]
                                                                                                    },
                                                                                                    {
                                                                                                        "name": "FormattedName",
                                                                                                        "type": [
                                                                                                            {
                                                                                                                "name": "PartyMasterPartyContactPersonNameFormattedName",
                                                                                                                "type": "record",
                                                                                                                "fields": [
                                                                                                                    {
                                                                                                                        "name": "typeCode",
                                                                                                                        "type": [
                                                                                                                            "string",
                                                                                                                            "null"
                                                                                                                        ]
                                                                                                                    },
                                                                                                                    {
                                                                                                                        "name": "content",
                                                                                                                        "type": [
                                                                                                                            "string",
                                                                                                                            "null"
                                                                                                                        ]
                                                                                                                    }
                                                                                                                ]
                                                                                                            },
                                                                                                            "null"
                                                                                                        ]
                                                                                                    }
                                                                                                ]
                                                                                            }
                                                                                        }
                                                                                    ]
                                                                                }
                                                                            ]
                                                                        }
                                                                    }
                                                                ]
                                                            }
                                                        ]
                                                    }
                                                ]
                                            },
                                            "null"
                                        ]
                                    }
                                ]
                            }
                        }
                    }
                ]
            }
        }
    ]
}

**Comment by hakjuoh** [comment]
@smorgan19 This is an example BIE used for testing
<img width="228" alt="Screenshot 2023-06-14 at 2 34 30 PM" src="https://github.com/OAGi/Score/assets/16102116/5a9ca457-7957-4c43-bf93-325a97ce5dbc">

and the generated AVRO expression file, 'GetPartyMaster.avsc'
```json
{
  "namespace" : "org.openapplications",
  "type" : "record",
  "name" : "GetPartyMaster",
  "fields" : [ {
    "type" : "string",
    "name" : "releaseID"
  }, {
    "name" : "ApplicationArea",
    "type" : {
      "type" : "record",
      "name" : "ApplicationArea",
      "fields" : [ {
        "type" : "string",
        "name" : "CreationDateTime"
      } ]
    }
  }, {
    "name" : "DataArea",
    "type" : {
      "type" : "record",
      "name" : "DataArea",
      "fields" : [ {
        "name" : "Get",
        "type" : {
          "type" : "record",
          "name" : "Get",
          "fields" : [ {
            "name" : "Expression",
            "type" : {
              "type" : "array",
              "name" : "Expression",
              "items" : {
                "type" : "string",
                "name" : "Expression"
              }
            }
          }, {
            "type" : [ "null", "boolean" ],
            "name" : "uniqueIndicator"
          } ]
        }
      }, {
        "name" : "PartyMaster",
        "type" : {
          "type" : "array",
          "name" : "PartyMaster",
          "items" : {
            "type" : "record",
            "name" : "PartyMaster",
            "fields" : [ {
              "name" : "FinancialParty",
              "type" : [ "null", {
                "type" : "record",
                "name" : "FinancialParty",
                "fields" : [ {
                  "name" : "ID",
                  "type" : [ "null", {
                    "type" : "array",
                    "name" : "ID",
                    "items" : {
                      "type" : "record",
                      "name" : "FinancialPartyID",
                      "fields" : [ {
                        "type" : "string",
                        "name" : "content"
                      }, {
                        "type" : [ "null", "string" ],
                        "name" : "typeCode"
                      } ]
                    }
                  } ]
                }, {
                  "name" : "Contact",
                  "type" : [ "null", {
                    "type" : "array",
                    "name" : "Contact",
                    "items" : {
                      "type" : "record",
                      "name" : "FinancialPartyContact",
                      "fields" : [ {
                        "type" : [ "null", "string" ],
                        "name" : "typeCode"
                      }, {
                        "name" : "ID",
                        "type" : [ "null", {
                          "type" : "array",
                          "name" : "ID",
                          "items" : {
                            "type" : "record",
                            "name" : "ContactID",
                            "fields" : [ {
                              "type" : "string",
                              "name" : "content"
                            }, {
                              "type" : [ "null", "string" ],
                              "name" : "typeCode"
                            } ]
                          }
                        } ]
                      }, {
                        "name" : "PersonName",
                        "type" : [ "null", {
                          "type" : "array",
                          "name" : "PersonName",
                          "items" : {
                            "type" : "record",
                            "name" : "FinancialPartyContactPersonName",
                            "fields" : [ {
                              "type" : [ "null", "string" ],
                              "name" : "typeCode"
                            }, {
                              "name" : "FormattedName",
                              "type" : [ "null", {
                                "type" : "record",
                                "name" : "FinancialPartyContactPersonNameFormattedName",
                                "fields" : [ {
                                  "type" : "string",
                                  "name" : "content"
                                }, {
                                  "type" : [ "null", "string" ],
                                  "name" : "typeCode"
                                } ]
                              } ]
                            } ]
                          }
                        } ]
                      } ]
                    }
                  } ]
                } ]
              } ]
            }, {
              "name" : "LastModificationDateTime",
              "type" : [ "null", {
                "type" : "record",
                "name" : "LastModificationDateTime",
                "fields" : [ {
                  "type" : "string",
                  "name" : "content"
                }, {
                  "type" : [ "null", "string" ],
                  "name" : "typeCode"
                } ]
              } ]
            }, {
              "name" : "Party",
              "type" : [ "null", {
                "type" : "array",
                "name" : "Party",
                "items" : {
                  "type" : "record",
                  "name" : "Party",
                  "fields" : [ {
                    "type" : [ "null", "string" ],
                    "name" : "typeCode"
                  }, {
                    "name" : "ID",
                    "type" : [ "null", {
                      "type" : "array",
                      "name" : "ID",
                      "items" : {
                        "type" : "record",
                        "name" : "PartyID",
                        "fields" : [ {
                          "type" : "string",
                          "name" : "content"
                        }, {
                          "type" : [ "null", "string" ],
                          "name" : "typeCode"
                        } ]
                      }
                    } ]
                  }, {
                    "name" : "Contact",
                    "type" : [ "null", {
                      "type" : "array",
                      "name" : "Contact",
                      "items" : {
                        "type" : "record",
                        "name" : "PartyContact",
                        "fields" : [ {
                          "type" : [ "null", "string" ],
                          "name" : "typeCode"
                        }, {
                          "name" : "PersonName",
                          "type" : [ "null", {
                            "type" : "array",
                            "name" : "PersonName",
                            "items" : {
                              "type" : "record",
                              "name" : "PartyContactPersonName",
                              "fields" : [ {
                                "type" : [ "null", "string" ],
                                "name" : "typeCode"
                              }, {
                                "name" : "FormattedName",
                                "type" : [ "null", {
                                  "type" : "record",
                                  "name" : "PartyContactPersonNameFormattedName",
                                  "fields" : [ {
                                    "type" : "string",
                                    "name" : "content"
                                  }, {
                                    "type" : [ "null", "string" ],
                                    "name" : "typeCode"
                                  } ]
                                } ]
                              } ]
                            }
                          } ]
                        } ]
                      }
                    } ]
                  } ]
                }
              } ]
            } ]
          }
        }
      } ]
    }
  } ]
}
```

and the java source files generated by `avro-maven-plugin`.
[generate-sources.zip](https://github.com/OAGi/Score/files/11749512/generate-sources.zip)

Please review this and let me know if you find any issues.

**Comment by smorgan19** [comment]
@hakjuoh, I should be able to review everything on Monday

**Comment by smorgan19** [comment]
@hakjuoh it looks good.  I generated a sample as well.
{"releaseID": "0.1", "ApplicationArea": {"CreationDateTime": "6-19-2023"}, "DataArea": {"Get": {"Expression": ["TestExpression"], "uniqueIndicator": null}, "PartyMaster": [{"FinancialParty": null, "LastModificationDateTime": null, "Party": [{"typeCode": "YellowCar", "ID": [{"content": "John Doe", "typeCode": "Driver"}, {"content": "Jane Doe", "typeCode": "PassengerOne"}], "Contact": null}, {"typeCode": null, "ID": [{"content": "Jimmy John", "typeCode": "Driver"}, {"content": "James John", "typeCode": "PassengerOne"}, {"content": "Carter John", "typeCode": "PassengerOne"}], "Contact": [{"typeCode": "DriverContact", "PersonName": [{"typeCode": null, "FormattedName": {"content": "James John", "typeCode": "CarContactPerson"}}]}]}]}]}}

**Comment by hakjuoh** [comment]
@smorgan19 Thanks! I tested a validation for the sample using [avro python package](https://pypi.org/project/avro/) and found no errors.
```python
import avro.schema
from avro.io import validate

schema = avro.schema.parse(avsc)
validate(schema, sample)
```

**Comment by joshklm** [comment]
@smorgan19 The avro schema has some inconsistency in certain names that are nested under a parent component. Which creates inconsistency, incompatibility or problem in mapping when this AVRO schema based format is used along with XSD or JSON Schema based format. The example is 'PartyContactPersonNameFormattedName' instead of just 'FormattedName'.

**Comment by hakjuoh** [comment]
@smorgan19 Changed the logic using the full path, and it works well. The name of records are pretty lengthy though.
```json
{
  "namespace" : "org.openapplications",
  "type" : "record",
  "name" : "GetPartyMaster",
  "fields" : [ {
    "type" : "string",
    "name" : "releaseID"
  }, {
    "name" : "ApplicationArea",
    "type" : {
      "type" : "record",
      "name" : "GetPartyMasterApplicationArea",
      "fields" : [ {
        "type" : "string",
        "name" : "CreationDateTime"
      } ]
    }
  }, {
    "name" : "DataArea",
    "type" : {
      "type" : "record",
      "name" : "GetPartyMasterDataArea",
      "fields" : [ {
        "name" : "Get",
        "type" : {
          "type" : "record",
          "name" : "GetPartyMasterDataAreaGet",
          "fields" : [ {
            "name" : "Expression",
            "type" : {
              "type" : "array",
              "name" : "Expression",
              "items" : {
                "type" : "string",
                "name" : "Expression"
              }
            }
          }, {
            "type" : [ "null", "boolean" ],
            "name" : "uniqueIndicator"
          } ]
        }
      }, {
        "name" : "PartyMaster",
        "type" : {
          "type" : "array",
          "name" : "PartyMaster",
          "items" : {
            "type" : "record",
            "name" : "GetPartyMasterDataAreaPartyMaster",
            "fields" : [ {
              "name" : "FinancialParty",
              "type" : [ "null", {
                "type" : "record",
                "name" : "GetPartyMasterDataAreaPartyMasterFinancialParty",
                "fields" : [ {
                  "name" : "ID",
                  "type" : [ "null", {
                    "type" : "array",
                    "name" : "ID",
                    "items" : {
                      "type" : "record",
                      "name" : "GetPartyMasterDataAreaPartyMasterFinancialPartyID",
                      "fields" : [ {
                        "type" : "string",
                        "name" : "content"
                      }, {
                        "type" : [ "null", "string" ],
                        "name" : "typeCode"
                      } ]
                    }
                  } ]
                }, {
                  "name" : "Contact",
                  "type" : [ "null", {
                    "type" : "array",
                    "name" : "Contact",
                    "items" : {
                      "type" : "record",
                      "name" : "GetPartyMasterDataAreaPartyMasterFinancialPartyContact",
                      "fields" : [ {
                        "type" : [ "null", "string" ],
                        "name" : "typeCode"
                      }, {
                        "name" : "PersonName",
                        "type" : [ "null", {
                          "type" : "array",
                          "name" : "PersonName",
                          "items" : {
                            "type" : "record",
                            "name" : "GetPartyMasterDataAreaPartyMasterFinancialPartyContactPersonName",
                            "fields" : [ {
                              "type" : [ "null", "string" ],
                              "name" : "typeCode"
                            }, {
                              "name" : "FormattedName",
                              "type" : [ "null", {
                                "type" : "record",
                                "name" : "GetPartyMasterDataAreaPartyMasterFinancialPartyContactPersonNameFormattedName",
                                "fields" : [ {
                                  "type" : "string",
                                  "name" : "content"
                                }, {
                                  "type" : [ "null", "string" ],
                                  "name" : "typeCode"
                                } ]
                              } ]
                            } ]
                          }
                        } ]
                      } ]
                    }
                  } ]
                } ]
              } ]
            }, {
              "type" : [ "null", "string" ],
              "name" : "LastModificationDateTime"
            }, {
              "name" : "Party",
              "type" : [ "null", {
                "type" : "array",
                "name" : "Party",
                "items" : {
                  "type" : "record",
                  "name" : "GetPartyMasterDataAreaPartyMasterParty",
                  "fields" : [ {
                    "type" : [ "null", "string" ],
                    "name" : "typeCode"
                  }, {
                    "name" : "ID",
                    "type" : [ "null", {
                      "type" : "array",
                      "name" : "ID",
                      "items" : {
                        "type" : "record",
                        "name" : "GetPartyMasterDataAreaPartyMasterPartyID",
                        "fields" : [ {
                          "type" : "string",
                          "name" : "content"
                        }, {
                          "type" : [ "null", "string" ],
                          "name" : "typeCode"
                        } ]
                      }
                    } ]
                  }, {
                    "name" : "Contact",
                    "type" : [ "null", {
                      "type" : "array",
                      "name" : "Contact",
                      "items" : {
                        "type" : "record",
                        "name" : "GetPartyMasterDataAreaPartyMasterPartyContact",
                        "fields" : [ {
                          "type" : [ "null", "string" ],
                          "name" : "typeCode"
                        }, {
                          "name" : "PersonName",
                          "type" : [ "null", {
                            "type" : "array",
                            "name" : "PersonName",
                            "items" : {
                              "type" : "record",
                              "name" : "GetPartyMasterDataAreaPartyMasterPartyContactPersonName",
                              "fields" : [ {
                                "type" : [ "null", "string" ],
                                "name" : "typeCode"
                              }, {
                                "name" : "FormattedName",
                                "type" : [ "null", {
                                  "type" : "record",
                                  "name" : "GetPartyMasterDataAreaPartyMasterPartyContactPersonNameFormattedName",
                                  "fields" : [ {
                                    "type" : "string",
                                    "name" : "content"
                                  }, {
                                    "type" : [ "null", "string" ],
                                    "name" : "typeCode"
                                  } ]
                                } ]
                              } ]
                            }
                          } ]
                        } ]
                      }
                    } ]
                  } ]
                }
              } ]
            } ]
          }
        }
      } ]
    }
  } ]
}
```
