### ISSUE TITLE
Change the structure of the BCCP DEN with the DT DEN

### ISSUE THREAD

**Issue by hakjuoh** [OAGi/Score#1506]
Related to oagis Issue [#798](https://github.com/OAGi/oagis/issues/798).

All BCCP DENs now consist of its property term and DT DEN except ". Type".

Format Code. Code b2d744c9062544f0b36aebdd671ba484
-> Format Code. Open_ Code

Format Code. Code ac3bd3b7d41d4626a196da0dd7b6dfb1
-> Format Code. Code (* Not changed)

Language Code. Code 4419527f02ca4a90bd139c20e084b562
-> Language Code. Language_ Code

Language Code. Code b3a87b15f4814a369262dbdaab1bc8d5
-> Language Code. Language Code Content_ Code

Response Code. Code bf4b792eac454c9db04df29878f6377e
-> Response Code. Response Code Content_ Code

Response Code. Code e09fef05fbd440b9ac980b56d97c4116
-> Response Code. Open_ Code

Also, all associated BCC DENs are changed with regard to the change of the BCCP DEN.

**Comment by bingqi2045** [comment]
Tested with Score 3.0.4.

Any change in DT DEN will be reflected in the derived BCCP DEN. The associated BCC DEN will be changed with respect to the derived BCCP DEN.
