### ISSUE TITLE
Update BIE root view to include Open API options

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1519]
Currently I have been using Remark to capture Open API information since it display nice on the BIE list view.

_Perhaps_ this is the appropriate UI to capture the following, as there seems to be enough real estate on the screen, and these parameters are directly related 1:1 to the BIE:

- Resource Path
- Verb
- Operation Id
- requestBody | responseBody
- Array
- Suppress Root element

Replace Remark with real OpenAPI fields
![2023-07-02-091232_1920x1080_scrot](https://github.com/OAGi/Score/assets/32434235/5fc86468-0723-49fc-bcf4-7826318598af)

Here is how I historically have used Remark to have a logical list of related BIEs.  The new issue #1492 is similar type of view:
![2023-07-02-091825_1920x1080_scrot](https://github.com/OAGi/Score/assets/32434235/3bcf4a16-84bd-42a4-828e-73fb498e2fa2)

**Comment by dubnemo** [comment]
@bingqi2045 @hakjuoh 
I think this is the way to go.  Define these parameters on the BIE root itself, and which would help the merge into the single yml

**Comment by bingqi2045** [comment]
<img width="395" alt="Screenshot 2023-07-05 at 9 34 50 AM" src="https://github.com/OAGi/Score/assets/117864643/23d34488-967c-48dc-b90d-d3d1e19855c1">

In this example, two different verbs are assigned to the same BIE, so it is not possible to directly related 1:1 to BIE.

**Comment by hakjuoh** [comment]
@bingqi2045 The OpenAPI information will appear if the BIE has a relationship with the OpenAPI document as below.
<img width="1498" alt="Screenshot 2023-07-14 at 11 10 49 AM" src="https://github.com/OAGi/Score/assets/16102116/38ea215c-267b-42cd-b27d-06c3a9c9cffd">

**Comment by dubnemo** [comment]
@hakjuoh @bingqi2045 yes, that is exactly what I was envisioning.

**Comment by dubnemo** [comment]
Note the relationship to a single OpenAPI doc, and the ability to add a BIE relationship to the doc.

![MultipleBIEs_mapping_operationId](https://github.com/OAGi/Score/assets/32434235/4ccace41-d955-4fa5-ae74-542acf823315)

We should also review the logic to generated the OperationId.  I am showing the reference type, and the verb mapping we did for securitySchema reference with create, etc. prefixed to the BIE name.
<operation_id>::= <referenceType>_<crudVerb><BIEName>
<referenceType> ::= 'response' | 'requestBody' | 'parameters'

**Comment by bingqi2045** [comment]
@dubnemo @hakjuoh 
Regarding the question: Are these editable? If you choose Response Body, is it stored the corresponding table for response? Or are the tables (response, request, parameters) now collapsed into one table?

Yes, They are editable. the response, request and parameters tables are separate and stored  in the corresponding table in the database.

**Comment by dubnemo** [comment]
@hakjuoh  what ever happened to this work?
