### ISSUE TITLE
View BIE - Search BIEs across any Branch

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1520]
Searching across any branch would provide the same listing, but with the branch in a column, and sorting by age where the latest is on top.   

Rationale:
The Express Pack has been uplifted numerous times, and it would be great to understand the history and what can be cleaned up.  
I am not clear if we are maintaining UUID linkage such as the 'from BIE UUID" on the new BIE -- and I am not sure if that is needed as 'dead end BIEs' can be deleted.  Or if there is value, perhaps these can manually associated (another feature ).

**Comment by hakjuoh** [comment]
@dubnemo The searching result would display BIEs in any branch.
<img width="1511" alt="Screenshot 2023-07-06 at 2 01 02 PM" src="https://github.com/OAGi/Score/assets/16102116/10fd99cd-83f0-4633-aba4-c32dc32fbdd2">
