### ISSUE TITLE
New User Banner or Help Area on the Login Page

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1524]
The current login page can be confusing for new users who are trying to create an account.  It would be helpful for new users if there  dedicated button that prompts a new user creation process or a help page link for the steps to create an account.

**Comment by bingqi2045** [comment]
@kbserm @smorgan19  There is "Create a User" section in the current User guide  [https://test.oagiscore.net/docs/ScoreUserGuide.html#create-a-user](url)
Should we add a link in the current login page for this "Create a User" section.

**Comment by hakjuoh** [comment]
The login page will show the configurable statement to inform the account creation information.

**Comment by hakjuoh** [comment]
@smorgan19 @joshklm 

I added a new configuration, 'Sign-in Page Statement' in the application settings. Only administrators can access this page. Click on 'Update' button after you fill the 'textarea' out. Note that the text can be formatted in [Markdown](https://www.markdownguide.org/basic-syntax/).
<img width="1027" alt="Screenshot 2023-10-11 at 2 44 28 PM" src="https://github.com/OAGi/Score/assets/16102116/562e765b-cefb-42c2-b95e-1771fbdbc46f">

Then, the text will show up on the sign-in page.
<img width="511" alt="Screenshot 2023-10-11 at 2 44 41 PM" src="https://github.com/OAGi/Score/assets/16102116/8a8dd606-66e0-40fa-b05d-732534f66404">

Please let me know what you think.

**Comment by smorgan19** [comment]
@hakjuoh This looks great
