### ISSUE TITLE
Notifications for admins when there is a pending account

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1525]
Would it be possible to have some sort of a notification or visual ui method for showing that there are pending accounts ready to be enabled?  In current admin window area, the user request can get lost if you are not constantly checking to see if there are new accounts.

**Comment by hakjuoh** [comment]
@smorgan19 I would like to propose the following approach to implement the feature:

1. Notification on New Account Creation:
Whenever a new account is created and remains in a pending state, all administrators will receive a notification. The notification will provide relevant information about the newly created account.

<img width="469" alt="Screenshot 2023-07-27 at 12 03 01 PM" src="https://github.com/OAGi/Score/assets/16102116/e40a422d-3013-4e5a-84ab-f498b7c91677">

2. Notification Icon Interaction:
Upon receiving the notification, administrators can click on the notification icon. Clicking on the icon will seamlessly direct them to the message list.

<img width="857" alt="Screenshot 2023-07-27 at 12 03 15 PM" src="https://github.com/OAGi/Score/assets/16102116/91b1cbb4-89d5-464a-b60b-867b66964d28">

3. Account Approval Link:
Within the notification message, administrators will find a convenient link. This link will be directly associated with the pending account and will lead them to an account approval page.

<img width="551" alt="Screenshot 2023-07-27 at 12 03 31 PM" src="https://github.com/OAGi/Score/assets/16102116/783e7e11-2387-499c-936d-1f34e9b18584">

4. Review Pending Account Page:
Upon clicking the provided link, administrators will be redirected to the "Review Pending Account" page.

<img width="535" alt="Screenshot 2023-07-27 at 12 03 40 PM" src="https://github.com/OAGi/Score/assets/16102116/82aa8cdd-cc8a-4075-a9bc-e648ca6231b1">

**Comment by smorgan19** [comment]
That looks great.

**Comment by bingqi2045** [comment]
Tested with three admin accounts. 

The pending account is created through SSO with auth0 as the provider. 

All three admin accounts receive the message for awaiting approval of pending accounts. 

Once the pending account is approved by one admin account, the other admin accounts will see the status for the pending account is changed to "linked".
