### ISSUE TITLE
Error expressing JSON Schema in demo.oagiscore.ent

### ISSUE THREAD

**Issue by jim-wilson-kt** [OAGi/Score#1538]
When attempting to express a JSON Schema in demo.oagiscore.net, @sfohn and I get the following error:

Duplicate key 100000001 (attempted merging values BdtPriRestri(bdtPriRestriId=100000004, bdtManifestId=100000001, cdtAwdPriXpsTypeMapId=13, codeListManifestId=null, agencyIdListManifestId=null, defaulted=true) and BdtPriRestri(bdtPriRestriId=100000005, bdtManifestId=100000001, cdtAwdPriXpsTypeMapId=14, codeListManifestId=null, agencyIdListManifestId=null, defaulted=true))

**Comment by hakjuoh** [comment]
@jim-wilson-kt Thank you for reporting this. I found out that there are invalid records in `bdt_pri_restri` table as below
<img width="748" alt="Screenshot 2023-08-23 at 9 50 40 AM" src="https://github.com/OAGi/Score/assets/16102116/9fe1d928-10f1-4e2b-abab-e3464f2261b8">

Both records whose ID values are 100000004 and 100000005 are indicated as a default (`is_default` = 1), that should haven't happened. In Score design, only one restriction record in the same DT must be a default. For now, I manually changed the `is_default` value of the record 100000005 to 0 (non-default), and the JSON schema expression works well.

@bingqi2045 I think it happened when the user attempted to change the default value of the DT. Please test DT restriction functions.

**Comment by bingqi2045** [comment]
@hakjuoh @jim-wilson-kt  I just tested the  bdt_pri_restri  restriction function after the latest commit. 

1) Create DT and choose 'Code. Type' CDT as a base.
2) Check bdt_pri_restri table in the MySQL workbench. 
There is no duplicate is_default = 1 in bdt_pri_restri for the new DT_Manifest_Id.
