### ISSUE TITLE
AVSC schema generates an invalid schema when a component has no children attributes

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1543]
In the case of components like extension, if you do no have any children enabled under extension the schema generates without the required fields value.

https://avro.apache.org/docs/1.11.1/specification/#schema-record
![image](https://github.com/OAGi/Score/assets/56837736/d9deb7cf-400c-4039-841a-940bb8eafc2d)

**Comment by hakjuoh** [comment]
@smorgan19 I was trying to add 'fields' with an empty list as below
```json
"name" : "Extension",
"items" : {
   "type" : "record",
   "name" : "...Extension",
   "fields": []
}
```

and the one of the Avro schema validator showed this error message: ```Record type must have at least one field```. Do you have an idea to express an empty field?

**Comment by smorgan19** [comment]
@hakjuoh Thank you, this was a very interesting edge case to handle.
