### ISSUE TITLE
Uplifting throws this exception: Unable to find the target ASCCP.

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1544]
Throws error
![image](https://github.com/OAGi/Score/assets/32434235/3d30603d-86c1-4409-89a7-ccc9f4244c99)

then hangs spinning
![image](https://github.com/OAGi/Score/assets/32434235/f5e73c29-0b6a-4e41-a1f6-1cf5598c04b5)

**Comment by jim-wilson-kt** [comment]
I suspect that this is a consequence of #1545.
