### ISSUE TITLE
Error when updating BIE with new code lists

### ISSUE THREAD

**Issue by jim-wilson-kt** [OAGi/Score#1546]
connectCenter instance: https://demo.oagiscore.net
User: oagis
Branch: HR Open 5.1
BIE: Person
Video: https://app.screencast.com/93GTO02z0cJ1i

I have created a Person BIE using components I created in the HR Open Standards namespace. I have also created code lists, which three of the components use. When I check any of them for the BIE and then click the "Update" button, I immediately get non-user-friendly errors (see video link above). However, when I click on the link for the component first, I get user-friendly messages when I click on the "Update" button.

<img width="632" alt="image" src="https://github.com/OAGi/Score/assets/2702530/c21e795f-e7f1-4296-9b68-e2eba11fa955">

**Comment by hakjuoh** [comment]
@jim-wilson-kt If a base data type has a default value that is a code list or agency ID list, the empty BBIE/BBIE_SC should show the default value on the value domain restriction in the BIE page.

Currently, `Gender_ Code. Type` has `Gender Code List` as a default value domain as below.
<img width="978" alt="Screenshot 2023-10-05 at 8 55 51 AM" src="https://github.com/OAGi/Score/assets/16102116/4a0b7697-b843-442d-be70-7db8e7630af5">

In this case, it should shows `Gender Code List` on the value domain restriction when the user opens the BBIE whose base data type is `Gender_ Code. Type`, but currently it shows empty primitives.
<img width="1236" alt="Screenshot 2023-10-05 at 8 54 49 AM" src="https://github.com/OAGi/Score/assets/16102116/295f8d7d-e598-4524-8fd2-08399d4f8c17">

I fixed this behavior and uploaded [the PR](https://github.com/OAGi/Score/pull/1548) for this. Now it shows correctly.
<img width="1183" alt="Screenshot 2023-10-05 at 9 34 43 AM" src="https://github.com/OAGi/Score/assets/16102116/7b9884dd-c9f7-4a93-ab99-8aa19e9970c5">

@bingqi2045 Please review the PR and test it.

**Comment by kbserm** [comment]
@jim-wilson-kt just a little tip, you don't have to click Update on every node on which you made changes before you leave and move to another node. Might help you reduce the # of clicks!
