### ISSUE TITLE
Provide ability to delete multiple notification messages

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1553]
I should not have to double click each one of these to delete them.  I know what they are.

![image](https://github.com/OAGi/Score/assets/32434235/88425e30-3cdd-4bf5-b56f-2cd2d7529be1)

**Comment by hakjuoh** [comment]
@dubnemo Now, users can delete multiple messages.
<img width="1052" alt="Screenshot 2023-10-19 at 3 47 23 PM" src="https://github.com/OAGi/Score/assets/16102116/5df91758-8758-4e7d-88a5-ee4c2e2b777f">

**Comment by bingqi2045** [comment]
Verified that multiple messages can be discarded all at once. 

<img width="580" alt="Screenshot 2023-10-25 at 3 49 42 PM" src="https://github.com/OAGi/Score/assets/117864643/84a3dc26-c5a0-4b0b-8f8d-3c91b625c458">
<img width="1146" alt="Screenshot 2023-10-25 at 3 49 55 PM" src="https://github.com/OAGi/Score/assets/117864643/e6ad61b2-9bb4-4f92-a2e2-8fa8b3856cc1">
