### ISSUE TITLE
When Deleting a BIE, check to see if the BIE is referenced in an OpenAPI document.

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1569]
Currently, a BIE can be deleted and OpenAPI document may have orphaned records.  @bingqi2045 check to see if there are still records related to container BIEs in test.oagiscore.net.

It would be best to throw an exception when trying to delete the BIE, and delete the references to the BIE in the OpenAPI document first.

**Comment by bingqi2045** [comment]
@dubnemo   reference to OpenAPI document is checked before a BIE is removed.   An exception will be thrown if the BIE is assigned to an OpenAPI doc. 

test instance is updated with the changes, you can test it out.
