### ISSUE TITLE
Add BIE Release to Edit OpenAPI Document  view

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1570]
It is not clear how to identify which release the BIE is associated to in the current view.  Users must click on the BIE DEN name to open a new tab.  This was not apparent until the BIEs were uplifted.

Options to  Place Release Id:

1. As a grid column, replacing Updated On column if multiple releases are permissible for an OpenAPI document, or,
2. On the header view if there is a desire to constrain the OpenAPI document to a specific connectSpec Release. 

Option 1 is easy, but requires users to be careful which release they are linking to the OpenAPI document.
Option 2 likely requires a DB table ALTER as that is not part of the OpenAPI specification and is unique to OAGi implementation with connectCenter.

![2023-11-05-084811_1920x1080_scrot](https://github.com/OAGi/Score/assets/32434235/c0e8966f-250c-467f-bf77-80db120d9366)

@sfohn @kbserm @jim-wilson-kt @hakjuoh @bingqi2045 
Do we want to constrain the OpenAPI documents to a specific release?

**Comment by bingqi2045** [comment]
just add 'Branch' in between 'DEN' and 'Remark'

![Screenshot 2023-11-07 at 9 56 30 AM](https://github.com/OAGi/Score/assets/117864643/883518a5-0a19-46bc-99d3-b07b7e2d8877)

**Comment by dubnemo** [comment]
@bingqi2045 this is perfect step forward.  I prefer no changes to the database tables at the OpenAPI doc level at this time.

**Comment by bingqi2045** [comment]
@dubnemo  test instance is updated with the changes. You can test it out.
