### ISSUE TITLE
OpenAPI Document Generated YML  - PATCH request and response are swapped

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1571]
When viewing in Swagger Editor, the PATCH container-state BIE is reference in the response, not the request as configured.  See `asPlanted_updateContainerState` operation.
YML is attached below.
@bingqi2045 

![2023-11-05-091201_1920x1080_scrot](https://github.com/OAGi/Score/assets/32434235/ab3dc5c3-7ff4-47fa-b27f-141ec13ce785)

![2023-11-05-091526_1920x1080_scrot](https://github.com/OAGi/Score/assets/32434235/4d8f7c5b-b6cc-4ee4-821a-7a6916e764f8)

[Traceability API-V1-1699196798411.yml.zip](https://github.com/OAGi/Score/files/13259976/Traceability.API-V1-1699196798411.yml.zip)

**Comment by dubnemo** [comment]
Today, it seems to be working

![image](https://github.com/OAGi/Score/assets/32434235/7d24edf0-ebbd-4ec9-99ff-7fb449d3d616)

**Comment by dubnemo** [comment]
Nothing changed in the BIE assignment
![image](https://github.com/OAGi/Score/assets/32434235/0fed88c0-bf6b-4ce9-943f-17c0b638b665)

**Comment by dubnemo** [comment]
I will close and re-open if this re-occurs.

**Comment by bingqi2045** [comment]
The test database might be corrupted.

I re-imported my backup today.

Binqqi

From: Scott T Nieman ***@***.***>
Date: Monday, November 6, 2023 at 2:48 PM
To: OAGi/Score ***@***.***>
Cc: Cheng, Bingqi (Fed) ***@***.***>, Assign ***@***.***>
Subject: Re: [OAGi/Score] OpenAPI Document Generated YML - PATCH request and response are swapped (Issue #1571)

Nothing changed in the BIE assignment
[Image removed by sender. image]<https://user-images.githubusercontent.com/32434235/280830243-0fed88c0-bf6b-4ce9-943f-17c0b638b665.png>

**Comment by dubnemo** [comment]
@bingqi2045 this is oagiscore.net, not test.oagiscore.net
