### ISSUE TITLE
Admin capability to transfer WIP BIEs owned by any users

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1576]
As an Admin there are cases when we need the capability to transfer a BIE from one user to another.  When a SSO enabled account is no longer able to be accessed, the users WIP content is no longer accessible by any user.  Adding this capability would enable an Admin in this example to transfer the WIP state content to another end user or assume the content themselves.  The capability would be a last resort mechanism for when a account cannot be used anymore, i.e a person leaving a company.

This was mentioned before in 2022 with ticket 1314.

**Comment by hakjuoh** [comment]
@smorgan19 @kbserm Currently, the ownership of a BIE can only be transferred for BIEs in WIP state, and can only be transferred to another user with the same roles as the owner (i.e., End-User to End-User / Developer to Developer). 
Should the same rules be applied to administrators in this change, or do they need to be relaxed? 
We should also consider whether administrators might want to modify or remove items.

| Role/Action | Move to QA | Move to Production | Back to WIP | Transfer Ownership | Discard |
| ---- | -------- | --------- | ------ | ---------- | ------ |
| Owner | Yes if the BIE is in WIP | Yes if the BIE is in QA | Yes if the BIE is in QA or Production | Yes if the BIE is in WIP (only to users who have the same role (i.e., EU to EU / Dev to Dev) | Yes |
| Admin | ? | ? | ? | Yes (in any states? or only WIP state?) (to any roles? or the same role as the owner?) | ? |

**Comment by smorgan19** [comment]
If its not going to break anything, then relaxing the rules seems like the better option.  The admins wouldn't need to worry about having a developer admin account and an end user admin account to maintain, but at the same time having two accounts doesn't seem like a large issue either.  Additionally, adding the ability to modify or remove content as an admin would be beneficial in a number of ways.  It enhances overall security by giving admins the capability to potentially remove malicious content.  Additionally, stale BIEs can be removed which reduces the amount resources needed for the application with a large user base.

**Comment by kbserm** [comment]
I don't think it is plausible to allow transfer ownership between End-user and Developer.

We can allow Admin to do the same thing as Owner as in the second row of the table above @hakjuoh.

**Comment by hakjuoh** [comment]
@smorgan19 @kbserm I made changes as below,

- The administrator can change the status of BIE regardless of ownership
- The administrator can transfer ownership of BIE to another user with the same role
- The administrator can discard the BIE regardless of its status and ownership.

@elena-jelisic Please review the PR for this issue. https://github.com/OAGi/Score/pull/1608
