### ISSUE TITLE
Ability to disassociate SSO with an account or to merge to account together

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1577]
The ability to disassociate SSO from an account would allow us to reassign the SSO login to an account or turn the account into a non-SSO account when needed.  An alternative would be a way to merge an SSO account that was created newly with a Non-SSO account, allowing the admin to chose which username would be the new merged account username.  Example for where this feature is needed, includes when an admin makes a mistake when creating the account(i.e username is 123456 and is created as 12345) or not seeing the existing Non-SSO account in the account list for it to be linked.  We currently are experiencing this issue where an Non SSO account has the correct username and the SSO account has the typo username associated with it.  We would like to either combine these accounts or be able to reassign the SSO to the Non-SSO, if possible.

Similar solution was proposed before in ticket 1315 as an alternative to deleting accounts.

**Comment by hakjuoh** [comment]
@smorgan19 @kbserm

I've added the 'Disassociate SSO' button. To view it, click on the 'Admin > Accounts' menu and select the account. To address any mistakenly created username issues, the admin can now update the login ID.

<img width="531" alt="Screenshot 2024-03-06 at 2 22 50 PM" src="https://github.com/OAGi/Score/assets/16102116/ec4ab7c1-e8fa-466d-aac6-9c4c78d06b01">

@elena-jelisic Please review the PR for this issue https://github.com/OAGi/Score/pull/1609
