### ISSUE TITLE
Releases Details What's Changed Feature/Button available for End User Accounts

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1579]
Enabling the What's Changed Button on the Releases Details page for each release is helpful for all users.  This will give users a quick way to check if they need to uplift their BIEs or change existing mappings.

**Comment by hakjuoh** [comment]
@smorgan19 Thanks for reporting this. I made a change to allow all users to access the button. I'll apply the change to version 3.2.1.
@elena-jelisic I made the [PR](https://github.com/OAGi/Score/pull/1580) for this. Please review it.

**Comment by elena-jelisic** [comment]
@hakjuoh, I have reviewed it. It works now for End Users as well.

![image](https://github.com/OAGi/Score/assets/71283987/0886ed14-6b0c-4e86-9e29-497a32ce0ee2)

![image](https://github.com/OAGi/Score/assets/71283987/03714584-491f-4290-9692-7d0b0ca35919)
