### ISSUE TITLE
BIE Editability Restriction When EUACC is WIP and EUASCCP is Production

### ISSUE THREAD

**Issue by hakjuoh** [OAGi/Score#1587]
If ASCCP is in Production status, but ACC is in WIP status, BIE should not be able to be modified even if it is created.

**Comment by dubnemo** [comment]
@hakjuoh Unclear of the problem statement.

If the underlying ACC referenced by the ASCCP was previously released, the BIE can be created and modified. 
There are numerous time we have an ACC in WIP status as there are unresolved discussions that may carry over to a subsequent release.

**Comment by kbserm** [comment]
@dubnemo I modified the title. It is about end user CC (EUCC).

**Comment by hakjuoh** [comment]
@elena-jelisic I uploaded [the PR](https://github.com/OAGi/Score/pull/1593) for this. Please review and test it.
