### ISSUE TITLE
OpenAPI document, suppressing root property no longer working 

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1590]
Reviewing the POST operation:

![image](https://github.com/OAGi/Score/assets/32434235/4ca7064f-2a98-4dbf-8294-3349aa0c4385)

The shippedItemInstance {} root property is present:

![image](https://github.com/OAGi/Score/assets/32434235/3f5726dd-b70d-4865-981e-2c3842abd5d4)

**Comment by dubnemo** [comment]
Current OpenAPI document as of 2023-12-27
![image](https://github.com/OAGi/Score/assets/32434235/8d39841a-d4f4-439e-b0b9-016f2293c23a)

yaml attached as a zip file: 
[In-Field Product Id-V4-1703693859142.zip](https://github.com/OAGi/Score/files/13779859/In-Field.Product.Id-V4-1703693859142.zip)

**Comment by dubnemo** [comment]
Let's use this one GOOD yml as the test.  It was created with the previous release of Score, and is in the AgGateway github.

[AgGateway-Traceability API.yml.zip](https://github.com/OAGi/Score/files/13850132/AgGateway-Traceability.API.yml.zip)

**Comment by hakjuoh** [comment]
> @hakjuoh can you add in the link to which Java file(s) Bingqi created for the OpenAPI document expression? I think you pasted into Wednesday's G2M call chat window, but that goes away after the session.

@dubnemo Here's a link: https://github.com/OAGi/Score/blob/master/score-http/score-http/src/main/java/org/oagi/score/gateway/http/api/oas_management/service/generate_openapi_expression/OpenAPIGenerateExpression.java

**Comment by hakjuoh** [comment]
@elena-jelisic [BieOpenAPIGenerateExpression](https://github.com/OAGi/Score/blob/master/score-http/score-http/src/main/java/org/oagi/score/gateway/http/api/bie_management/service/generate_expression/BieOpenAPIGenerateExpression.java) has been used for generating OpenAPI expressions. Bingqi copied it to implement OpenAPIGenerateExpression and made some changes to it. You may need to check both to investigate this issue.

**Comment by dubnemo** [comment]
@elena-jelisic I just tested in test.oagiscore.net, and I still see the same issues:

![image](https://github.com/OAGi/Score/assets/32434235/e5079e72-fe4d-41fa-84a0-ae7cc8b9bb40)
I am available today 2pm Central.

@hakjuoh

**Comment by dubnemo** [comment]
@elena-jelisic 
I have checked test.oagiscore.net, and it is working now.
