### ISSUE TITLE
OpenAPI generated expression: Extra schemas created, two unused, same referenced BIE should not have be duplicated but set as global property

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1591]
**This was previously working.**

![image](https://github.com/OAGi/Score/assets/32434235/eb9b2f24-6cff-4b3c-8e6c-7497eb7aca4e)

Since the _same BIE was referenced_ across both GET response and POST request, only shippedItemInstanceArray and shippedItemInstanceArrayEntry should have been created.
![image](https://github.com/OAGi/Score/assets/32434235/41c06544-4e39-47f1-b55f-db8fe548fa1e)

Interestingly, the createShippedItemInstance and queryShippedItemInstance have the root property suppressed.

**Comment by dubnemo** [comment]
Let's use this one GOOD yml as the test.  It was created with the previous release of Score, and is in the AgGateway github.

[AgGateway-Traceability API.yml.zip](https://github.com/OAGi/Score/files/13850132/AgGateway-Traceability.API.yml.zip)

**Comment by elena-jelisic** [comment]
@dubnemo @hakjuoh @kbserm I have reverted changes made OpenAPI functionality, and here are the results.

1. The Open API document content for "AgGateway In-Field Product Id" on the oagiscore instance looks like this:

<img width="1713" alt="Screenshot 2024-01-11 at 11 17 54 PM" src="https://github.com/OAGi/Score/assets/71283987/f0f8f623-a45a-4f0e-bf90-249c4e875ee1">

2. Next is the .yml file generated from the current oagiscore instance:

[after_x-oagis-* properties_changes_AgGateway In-Field Product Id-V4-1705032079871.yml.zip](https://github.com/OAGi/Score/files/13914542/after_x-oagis-.properties_changes_AgGateway.In-Field.Product.Id-V4-1705032079871.yml.zip)

3. Next is the .yml file generated on my local instance after I have reverted all changes previously made (according to issue #1574):

[before_x-oagis-* properties_changes_AgGateway In-Field Product Id-V4-1705032041734.yml.zip](https://github.com/OAGi/Score/files/13914548/before_x-oagis-.properties_changes_AgGateway.In-Field.Product.Id-V4-1705032041734.yml.zip)

**Comment by dubnemo** [comment]
I cannot unzip the attached file.  Either way, if the file looks the same as we looked at the other day, it is NOT properly generated and something is wrong.

![image](https://github.com/OAGi/Score/assets/32434235/c48aa0d0-0f13-4db5-b387-5bcd1e1912ee)

**Comment by elena-jelisic** [comment]
@dubnemo I am uploading the files again. Let me know if it works for you.

[before_x-oagis-_ properties_changes_AgGateway In-Field Product Id-V4-1705032041734.zip](https://github.com/OAGi/Score/files/13951697/before_x-oagis-_.properties_changes_AgGateway.In-Field.Product.Id-V4-1705032041734.zip)

[after_x-oagis-_ properties_changes_AgGateway In-Field Product Id-V4-1705032079871.zip](https://github.com/OAGi/Score/files/13951698/after_x-oagis-_.properties_changes_AgGateway.In-Field.Product.Id-V4-1705032079871.zip)

**Comment by dubnemo** [comment]
@elena-jelisic  
The zips are OK this time.   As you state, other than the extension, the files are relatively the same.  

So there must be something in the data that is causing this behavior or other code changes in that release.  Have you looked at Bingqi's older issues related to the requirements on what the yml should look like?  It may seem a bit daunting.

Perhaps you can review the DB records for [Traceability API (Original)](https://oagiscore.net/profile_bie/express/oas_doc/1) vs. [In-Field Product Id](https://oagiscore.net/profile_bie/express/oas_doc/4).  The Traceability API express well.  Are there columns that are not populated in the In-Field Product ID API that are populated in the Traceability API?

Lastly did you see my comment prior to the correct zip comment?

**Comment by dubnemo** [comment]
I will try to find key Slack messages like this:

![image](https://github.com/OAGi/Score/assets/32434235/5323ca38-b09f-4829-b441-736306aafd8c)

**Comment by elena-jelisic** [comment]
> Can you explain what guid is displayed here?
> 
> ![image](https://private-user-images.githubusercontent.com/32434235/297224727-a036f371-6fd3-4bfe-80a9-bff5829a4f3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NDUyNzksIm5iZiI6MTcwNTk0NDk3OSwicGF0aCI6Ii8zMjQzNDIzNS8yOTcyMjQ3MjctYTAzNmYzNzEtNmZkMy00YmZlLTgwYTktYmZmNTgyOWE0ZjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDE3MzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmYzAxZmYwMDdlMWI5ZjlkYTUxYzk2YTE0ZDg2YWJhZWUyMzdkZTZjMzQ0NjEyNmFlM2M3Y2RhNjhhM2Y3NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ca2mavo1phAoX3wwWYiS6GPVwrZkWeQI6PqGyali9dY)
> 
> I cannot find it in the yaml: ![image](https://private-user-images.githubusercontent.com/32434235/297224894-4ef9fe0b-e8c4-4e4e-b44f-2106660dcd5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NDUyNzksIm5iZiI6MTcwNTk0NDk3OSwicGF0aCI6Ii8zMjQzNDIzNS8yOTcyMjQ4OTQtNGVmOWZlMGItZThjNC00ZTRlLWI0NGYtMjEwNjY2MGRjZDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDE3MzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZDlkOGY4MDJjMDViYmJlMzg0ODNjNGIxNWNkM2Q5ODdmYjA4ZTkwNDE2YmFlMjgxM2Q0NzRkOGExYjNlNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LdbTP6Y02eqn3ncP6nkA54fHIPVfvv0jdCcPr55aTis)
> 
> I previously suggest to Bingqi to display the URI to the BIE; e..g, https://oagiscore.net/profile_bie/860


@dubnemo @hakjuoh @kbserm I found out that the GUID of the ASCCP is displayed on the UI. Meanwhile, the GUID of the associated ABIE is shown in the YAML file. That is odd. Was there a reason to display ASCCP/ABIE GUIDs instead of ASBIEP GUID?

**Comment by dubnemo** [comment]
@elena-jelisic I just tested in test.oagiscore.net, and I still see the same issues:

![image](https://github.com/OAGi/Score/assets/32434235/e5079e72-fe4d-41fa-84a0-ae7cc8b9bb40)
I am available today 2pm Central.

@hakjuoh

**Comment by elena-jelisic** [comment]
@dubnemo Sorry, Scott, I just saw you message. It turned out that the test instance didn't have the latest code. @hakjuoh  just uploaded the latest version. Can you please test it again? We apologize for this.

This is a screenshot how it looks like on my local.

![Screenshot 2024-01-26 at 2 51 57 PM](https://github.com/OAGi/Score/assets/71283987/de45b2bc-0545-42a6-b07a-5ca0d33f4cd8)

**Comment by elena-jelisic** [comment]
@dubnemo We have another question. As you can see in the generated Open API document there is the following error message:

![Screenshot 2024-01-26 at 3 10 52 PM](https://github.com/OAGi/Score/assets/71283987/227ed24d-b2ef-4401-b640-860e4a0d4a8c)

The current logic works with either the 'sinceLastDateTime' or 'id' parameter when the array indicator is checked or not, respectively. And as you can see in the data:

![Screenshot 2024-01-26 at 3 06 45 PM](https://github.com/OAGi/Score/assets/71283987/fa17d11a-b6f2-40b0-ba8a-91fa0745a4e7)

The array indicators for these shipped item instances are checked and it has '{id}' path parameter in the resource name.

Can you please confirm if the current logic is fine or we need to fix it? 

@hakjuoh

**Comment by hakjuoh** [comment]
> The array indicators for these shipped item instances are checked and it has '{id}' path parameter in the resource name.
> 
> Can you please confirm if the current logic is fine or we need to fix it?
> 
> @hakjuoh

@elena-jelisic @dubnemo Previously, the logic takes either the 'sinceLastDateTime' query parameter if the array indicator is checked or the 'id' path parameter if the resource name has the 'id' parameter in its path. I fixed this behavior, now the path can have both parameters.

<img width="687" alt="Screenshot 2024-01-26 at 3 52 26 PM" src="https://github.com/OAGi/Score/assets/16102116/cb0cd414-fff9-4bdb-b02d-6827af4b9c24">

I'm unsure whether we'll use the array Indicator and id parameter together in practice, though.

**Comment by dubnemo** [comment]
- Parameters
I told @bingqi2045  that the query and path logic would be enhanced when we revisit #862.
@hakjuoh yes, it is related to the array selection, AND it was intended only when BIE selections are HTTP verb = GET and the Message Body = response body.  Perhaps that is a simple fix just to check those values and suppress sinceLastDateTime for all other verb-combinations.   

I LIKE the check to see if the {id} is in the resource path.

- Duplicate schema objects
@elena-jelisic 
I have checked test.oagiscore.net, and it is _generally_ working now.   If you recall in the meeting, I thought it may be valuable to cache or use a hashtable to the top level bie id value to check if the specific BIE has already been expressed.  Here is a duplicate:

    replaceShippedItemInstanceListEntry:
      x-oagis-bie-guid: "db527237f0f14307bf0ba0f5935cd94d"
      x-oagis-bie-date-time: "2023-12-26T20:24:28+0000"
      x-oagis-bie-version: "4.0"
      **x-oagis-bie-uri: "https://test.oagiscore.net/profile_bie/896"**
      x-oagis-release: "10.10.2"
      x-oagis-release-date: "2023-12-18"
      type: "object"
      additionalProperties: false

    queryShippedItemInstanceListEntry:
      x-oagis-bie-guid: "db527237f0f14307bf0ba0f5935cd94d"
      x-oagis-bie-date-time: "2023-12-26T20:24:28+0000"
      x-oagis-bie-version: "4.0"
      **x-oagis-bie-uri: "https://test.oagiscore.net/profile_bie/896"**
      x-oagis-release: "10.10.2"
      x-oagis-release-date: "2023-12-18"
      type: "object"
      additionalProperties: false

**Comment by hakjuoh** [comment]
> @hakjuoh yes, it is related to the array selection, AND it was intended only when BIE selections are HTTP verb = GET and the Message Body = response body. I am not sure why sinceLastDateTime was a path parameter, but perhaps a simple fix is to check those values and suppress sinceLastDateTime for all other verb-combinations.

@elena-jelisic The 'sinceLastDateTime' query parameter is allowed for only the 'GET' verb.
https://github.com/OAGi/Score/blob/97157b100587db9656d22128cbe4f6d1e5c60b7e/score-http/score-http/src/main/java/org/oagi/score/gateway/http/api/oas_management/service/generate_openapi_expression/OpenAPIGenerateExpression.java#L171-L185

**Comment by dubnemo** [comment]
@elena-jelisic 
While you are in there, please default line 187 
`.put("description", "Returns resources that have been updated since the last time the endpoint has been called")`
@hakjuoh

**Comment by dubnemo** [comment]
@hakjuoh @elena-jelisic 
I remember talking with Bingqi about the ORDER BY when retrieve the BIE list when generating.  It does not seem there is an order by at all or not the best approach.  Using the Tag Name ASC and Operation ID ASC will provide the best results for ordering in the YML file.  For example, the BOM schema objects would be next to each other where they are not today.
![image](https://github.com/OAGi/Score/assets/32434235/a392fcad-76ac-4cec-b805-13bd05fbfef4)


Second I think it would helpful to have a simpler naming convention for the schema objects, and not use the DEN.
`<schemaObject Name> ::= <resourceName>-<messageBodyType>-[entry] // entry is optional as the reference schema object for a list`

 The DEN be part of an extension (x-oagis-bie-den):
```
      x-oagis-bie-guid: "bce7462b32d549e48a4f029c4e46f102"
      x-oagis-bie-date-time: "2023-11-15T22:54:29+0000"
      x-oagis-bie-version: "V2"
      x-oagis-bie-den: "WIP Status"
      x-oagis-bie-uri: "https://test.oagiscore.net/profile_bie/883"
      x-oagis-release: "10.10.1"
      x-oagis-release-date: "2023-11-01"

```
So outside the ASCCPs that reused with in the selected BIEs, of the six displayed BIEs there should only be eight schema objects:

1. bom-list-response
2. bom-list-response-entry
3. bom-response
4. production-order-list-response
5. production-order-list-response-entry
6. production-order-response
7. wip-status-request
8. wip-status-response
9
