### ISSUE TITLE
BIE referenced but not expressed in OpenAPI document

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1592]
The PATCH response body should be 
https://oagiscore.net/profile_bie/896

![image](https://github.com/OAGi/Score/assets/32434235/7ca4127f-b0bb-4d60-bfe0-bb43c9d56c93)

However it is not found in the expressed yaml.  Should be in this property:
      x-oagis-bie-uri:

![image](https://github.com/OAGi/Score/assets/32434235/674102af-8568-49d5-b99e-6a1c0e7925e4)

**Comment by dubnemo** [comment]
@hakjuoh @elena-jelisic 
Did the movement of OpenAPI extensions to under the schema obhject change the logic that @bingqi2045 and I worked on?

**Comment by dubnemo** [comment]
With my modications to this OpenAPI document, it is now appearing.   We do need to revert never-the-less.

![image](https://github.com/OAGi/Score/assets/32434235/4dc47982-3d00-46e3-846a-797126c36d93)

**Comment by dubnemo** [comment]
Let's use this one GOOD yml as the test.  It was created with the previous release of Score, and is in the AgGateway github.

[AgGateway-Traceability API.yml.zip](https://github.com/OAGi/Score/files/13850132/AgGateway-Traceability.API.yml.zip)

**Comment by hakjuoh** [comment]
@elena-jelisic Check if the GUID corresponding to the BIE pointed to by the ID at the end of the URI (e.g., 896) matches the GUID (e.g., "x-oagis-bie-guid": "bdaf07b470e44b3b9342c45b22dcac70") included in the generated schema. If they are different, identify the reason. If they are the same, investigate why an unintended BIE has been included in the schema.
