### ISSUE TITLE
No longer can discard an OpenAPI document - Discard's forbidden! The OpenAPI Doc is used.

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1601]
I tried this in both test.oagiscore.net (no assigned BIEs) and oagiscore.net (assigned BIEs) for the Express Pack / connectKit. 
Same error message regardless of BIE assignment: Discard's forbidden! The OpenAPI Doc is used.

This connectKit enables small manufacturing businesses to digitize their BOM and production order processes.

**Comment by hakjuoh** [comment]
@elena-jelisic I made [a commit](https://github.com/OAGi/Score/commit/6f621c462dd42de432c3452494fb76ec310b20fe) for this issue. Please review it. Records in the `oas_resource_tag` and `oas_tag` tables needed to be wiped out to discard the document.

**Comment by dubnemo** [comment]
@hakjuoh To clarify, the records _associated_ to the OpenAPI document are not being deleted, and must be.  
In test.oagiscore.net, I removed the BIEs first.  It may be worthwhile to see if that leaves orphan records.
