### ISSUE TITLE
OpenAPI - refine naming convention and check for duplicate topLevelBIE by id

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1603]
## Naming Convention
This naming convention is based on Enhanced Bachus Naur Form (EBNF) which has been used to express programming languages and syntax and semantics for decades. There are specific notational semanticssuch as `[ ]` means 'optional'.

The OpenAPI Document Expression should follow this naming convention:

```
<SchemaObject Name> ::= <UniqueTopLevelBIEName>[List][<MessageBodyType>][<ActionVerb>][Entry]

<UniqueTopLevelBIEName> ::= <BIEName> when a DEN only has one distinct BIEId in the list of usages  
[List] ::= **conditional** name; only used when the outer schema object represents an array or if the BIE has few properties selected in an inner array typically on a GET operation
[<MessageBodyType>] ::= 'Request' | 'Response'; **optional** name, only used to distinguish distinct BIEs, across different message bodies
[<ActionVerb>] :: = 'Update' | 'Delete' | 'Create' | 'Replace' | 'Read'; **optional** name used to further assist in unique DEN when multiple BIE ids exist for the same DEN.
[Entry] ::= **optional** name; used for the inner schema object of an array -- seldom used.
```

If there are multiple BIE ids for the same DEN, then expand to additional naming options until distinct (similar logic to how we named the columns in CSV).   For example, if there to two BIE id references for the same DEN, expanding to <MessageBodyType> will help make the BIE name distinct.  This will cover use cases where a requestBody of a DEN will not have an id or uuid until store in a database, and a responseBody will have the id and uuid after the database auto-creates the identifier onInsert().

If more distinction is required, then add <ActionVerb>.

### Expression Logic

-get list of BIE usages in OpenAPI document
-for the BIEs that list, generate all reused BIEs (does not currently duplicate)
-place reused BIEid, DEN in hashtable
-count(BIEId), DEN and for-each BIEid where count(BIEid)=1 and if not an already generated reused BIE, then generated the Schema Object as `<UniqueTopLevelBIEName>`
-if its usage is an array, then create another Schema object with `<List> `appended, and reference `<UniqueTopLevelBIEName>`.
-Create Path entries for these; add references to the Schema Objects either `<UniqueTopLevelBIEName><List> `or `<UniqueTopLevelBIEName>` ; keep track of what has been serialized.
-for-each DENs where count(BIEId) > 1, determine if the conflict can be differentiated by adding `<MessageType>`
-Create Path entries for these, add references to the Schema Objects `<UniqueTopLevelBIEName><List><MessageType>` or `<UniqueTopLevelBIEName><MessageType>`
-if it still cannot be differentiated, then add `<ActionVerb>` and so forth.
- `<Entry>` is the worst case scenario where conflicts need to be differentiated.

### Moving DEN to the Extensions:
 The DEN be part of an extension (x-oagis-bie-den):
```
      x-oagis-bie-guid: "bce7462b32d549e48a4f029c4e46f102"
      x-oagis-bie-date-time: "2023-11-15T22:54:29+0000"
      x-oagis-bie-version: "V2"
      x-oagis-bie-den: "WIP Status"
      x-oagis-bie-uri: "https://test.oagiscore.net/profile_bie/883"
      x-oagis-release: "10.10.1"
      x-oagis-release-date: "2023-11-01"

```

### Example schema objects:
So ignoring the ASCCPs that reused with in the selected BIEs, **instead of the fourteen (14) I see in the yml**, of the six (6) displayed BIEs below, there should _only be eight (8)_ schema objects appearing in this sequence:

- **bomResponse** //same DEN name, therefore add <MessageBodyType>
- **bomResponseListEntry**; // same DEN name, therefore add <MessageBodyType>, [List]  for array, and [Entry] added for inner array object
- **bomResponseList** // same DEN name, add <MessageBodyType>, since the resource specifies an array, this is the outer wrapper, therefore [List], 
- **wipStatusRequest** // same DEN name, therefore add <MessageBodyType>
- **wipStatusResponse** // same DEN name, therefore add <MessageBodyType>
- **productionOrderResponse** // same DEN name, therefore add <MessageBodyType>
- **productionOrderResponseListEntry** // same DEN name, therefore add <MessageBodyType>, [List]  for array, and [Entry] added for inner array object
- **productionOrderResponseList** // this is the array therefore [List], same DEN name, therefore add <MessageBodyType>

List of BIEs for the OpenAPI document:
![image](https://github.com/OAGi/Score/assets/32434235/38c3544f-5763-40a2-96fb-3c4c6dc653b3)

@hakjuoh @elena-jelisic

**Comment by dubnemo** [comment]
This may need to be refined.

If the same BIE is across multiple verbs and message types, it may make sense to suppress the message type.

ShippedItemInstance in InFieldProductID API may be another good example.

**Comment by elena-jelisic** [comment]
@dubnemo @hakjuoh 

Scott, please review the current content of the OAS document. 

[AgGateway In-Field Product Id-V4-1709651453849.yml.zip](https://github.com/OAGi/Score/files/14497694/AgGateway.In-Field.Product.Id-V4-1709651453849.yml.zip)

I made the following changes:

1. Order statements are added,
2. The naming convention is changed,
3. DEN is moved to the Extensions,
4. ASCCPs that are reused within the selected BIEs are ignored.

I have the following questions:

1. Where can I see the SME Manufacturing Connect Kit example you used?
2. What should I do with reusable ASCCPs that are arrays? They are now represented as global schemas (e.g., Substance List in the file I sent). Do you think I should change this as well?
3. You don’t want to see ASCCPs used as Request/Response message bodies as global schemas. Am I correct? 
4. Also, if I remember well, you said that you don’t need to distinguish between two BIEs that profile the same ASCCP (e.g., Shipped Item Instance with IDs 896 and 893) because they are the same, just use different examples. Am I correct?

**Comment by dubnemo** [comment]
@elena-jelisic 
Recreated SME Manufacturing connectKit in oagiscore.net.

![image](https://github.com/OAGi/Score/assets/32434235/35dc22d1-e971-4409-9cc0-49cee2a328e1)

**Comment by hakjuoh** [comment]
> @elena-jelisic Recreated SME Manufacturing connectKit in oagiscore.net.
> 
> ![image](https://private-user-images.githubusercontent.com/32434235/310695146-35dc22d1-e971-4409-9cc0-49cee2a328e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MTAwMDUsIm5iZiI6MTcwOTkwOTcwNSwicGF0aCI6Ii8zMjQzNDIzNS8zMTA2OTUxNDYtMzVkYzIyZDEtZTk3MS00NDA5LTljYzAtNDljZWUyYTMyOGUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDE0NTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwYzZiZDRjYWI4NDczYWFjODYyZGIxYTg4MDE5NWZmNzIxOGY2NGNmMmUyYTcyNDhkY2Y5NTI5YjIzZjhiMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FzwPQaikcibRgs6y8ZszKuxbHEfwz7qAT3d4BTbUzkk)

[SME Manufacturing Express Pack-V1-1709915050415.yml.zip](https://github.com/OAGi/Score/files/14540689/SME.Manufacturing.Express.Pack-V1-1709915050415.yml.zip)

- I have added the 'x-oagis-bie-den' header. However, this is not the DEN but the 'Property Term'. I wonder if this is okay as it is. If it were DEN, the value of 'x-oagis-bie-den' in the example below would be "WIP Status. WIP Status".

```yml
    wipStatus:
      x-oagis-bie-guid: "462f05ad0bf74ae283ef5cb786042556"
      x-oagis-bie-date-time: "2023-11-15T23:01:52-0500"
      x-oagis-bie-version: "V2"
      x-oagis-bie-den: "WIP Status"
      x-oagis-bie-uri: "http://localhost:4200/profile_bie/884"
      x-oagis-release: "10.10.1"
      x-oagis-release-date: "2023-11-01"
```

- I have modified the elements of the schemas component to be inserted in the order determined by the sorting conditions set in the UI. For example, when the sorting values in the UI are set to Tag Name ASC, Operation ID ASC, pressing the 'Generate' button will construct the schemas component with Top-Level ASBIEPs loaded in the corresponding order.

<img width="344" alt="Screenshot 2024-03-08 at 11 26 31 AM" src="https://github.com/OAGi/Score/assets/16102116/07176e58-9a06-4f6b-a6a6-f86eb879ece4">

**Comment by dubnemo** [comment]
See the naming convention, to have resourceName first, then messageBodyType.

Plus we are back to where we were,  which we have too many schema objects created.   For example,  WIP Status would only have two, versus four shown. S/b:
WipStatusRequest
WipStatusResponse

**Comment by hakjuoh** [comment]
> See the naming convention, to have resourceName first, then messageBodyType.
> 
> Plus we are back to where we were, which we have too many schema objects created. For example, WIP Status would only have two, versus four shown. S/b: WipStatusRequest WipStatusResponse

@dubnemo 
[SME Manufacturing Express Pack-V1-1709923045827.yml.zip](https://github.com/OAGi/Score/files/14541979/SME.Manufacturing.Express.Pack-V1-1709923045827.yml.zip)

This is the result written according to the new naming convention, excluding the creation of reused BIEs as global schemas.

<img width="838" alt="Screenshot 2024-03-08 at 1 38 29 PM" src="https://github.com/OAGi/Score/assets/16102116/16482f8c-2cb5-4d85-ae81-2f8ac4c8f9a9">

There are eight (8) schema objects appearing in this schema:
 - bomResponse
 - bomHeaderListResponse // this is the array
 - bomHeaderListResponseEntry
 - productionOrderResponse
 - productionOrderHeaderListResponse // this is the array
 - productionOrderHeaderListResponseEntry
 - wipStatusRequest
 - wipStatusResponse

@elena-jelisic Here's a commit for this: https://github.com/OAGi/Score/commit/f0ed4b50405027a10a87b238395a55ad180f3141

**Comment by dubnemo** [comment]
@hakjuoh 
When you say excluding the reuse BIEs, are you still planning to make those global schemas?  That would be great.
The rest of it is looking good, thank you.
@elena-jelisic

**Comment by dubnemo** [comment]
@hakjuoh 
@elena-jelisic and I met, and we did a code review, and I think it is good enough for now.  I changed the title of this Issue.  Let's get 3.2.2 out as soon as possible.

We also talked about the remaining items to complete OpenAPI, and populate other aspects of the model including other request and response details.  I will create other issues for incremental releases, such as 

- http headers (request/response), 
- parameters (request), 
- HTTP status (response),
- examples (request/response) eliminating the examples table, placing example as [JSON data type](https://mariadb.com/kb/en/json-data-type/) in request, response tables, and string for parameters.

**Comment by dubnemo** [comment]
@hakjuoh 
Hate to inform you that we still have some work to do on this one.
I still see multiple schema objects for the same BIE id (scope of this issue).  For example this BIE in In-Field Product Id has two schema objects for https://oagiscore.net/profile_bie/909

I have refined the 'naming convention' above to hopefully provide additional clarity.    It has been difficult to articulate.  Please note that BNF has additional semantics with the square bracket notation.  That meant we only use the feature as needed when further uniqueness is required.

![Screenshot from 2024-03-17 18-49-38](https://github.com/OAGi/Score/assets/32434235/a4a35e35-e344-4c6f-aae5-672f0fbc96ca)

**Comment by dubnemo** [comment]
You may have missed my comment @hakjuoh.  
We are still creating too many schema objects with the same BIE id.    See my comment of last week, and more importanly yesterday when I tested In-Field Product Id.  
I edited the title last week to capture the too many schema objects for the same BIE id.  This issue was to consolidate the prior issue(s) related to the multiple schema objects for the same BIE id.

**Comment by hakjuoh** [comment]
@dubnemo @kbserm @elena-jelisic 
I missed your comment. I hadn't noticed the changes regarding this issue.

```
<SchemaObject Name> ::= <UniqueTopLevelBIEName>[List]][<MessageBodyType>][<ActionVerb>][Entry]

<UniqueTopLevelBIEName> ::= <BIEName> when a DEN only has one BIE Id.  
[List] ::= optional name; used when the outer schema object represents an array
[<MessageBodyType>] ::= optional name, used to distinguish distinct BIEs, across different message bodies
[<ActionVerb>] :: = 'Update' | 'Delete' | 'Create' | 'Replace'; optional name used to further assist in unique DEN when multiple BIE ids exist for the same DEN.
[Entry] ::= optional name; used for the inner schema object of an array
```

When applying this new naming rules, the SchemaObjectName will be determined as follows.

| BIE DEN | Verb | Message Type | SchemaObjectName |
| -------- | ---- | --------------- | --------------------- |
| BOM. BOM | GET | Request | `Unsupported` |
| BOM. BOM | GET | Response | bom(List)Response(Entry) |
| BOM. BOM | PUT | Request | bom(List)RequestReplace(Entry) |
| BOM. BOM | PUT | Response | bom(List)ResponseReplace(Entry) |
| BOM. BOM | POST | Request | bom(List)RequestCreate(Entry) |
| BOM. BOM | POST | Response | bom(List)ResponseCreate(Entry) |
| BOM. BOM | DELETE | Request | `Unsupported` |
| BOM. BOM | DELETE | Response | bom(List)ResponseDelete(Entry) |
| BOM. BOM | PATCH | Request | bom(List)RequestUpdate(Entry) |
| BOM. BOM | PATCH | Response | bom(List)ResponseUpdate(Entry) |

To completely eliminate duplicate names, however, the 'Operation Name' should also be considered. Otherwise, it will make duplicate names as follows.

| BIE DEN | Verb | Message Type | Operation Name | SchemaObjectName |
| -------- | ---- | --------------- | ---------------- | --------------------- | 
| BOM. BOM | GET | Response | /manufacturing | **bom(List)Response(Entry)** |
| BOM. BOM | GET | Response | /engineering | **bom(List)Response(Entry)** |

Alternatively, allowing users to modify the schema object name for each operation on the UI would be another option. Please let me know what you think.

**Comment by dubnemo** [comment]
Hakju
The optional values should only be added to the name ONLY AS-NEEDED to
avoid duplicates.  If you look across the unique DEN list, and there is
only one id for a DEN, you know the schema object name can be the DEN.

I attached in my response an edited In-Field Product ID yml as an example,
minus the <ActionVerb> that I am recommending.
-shippedItemInstance DEN is that unique BIE id example.

However there are multiple <List> references to that single DEN / BIE Id,
and they all point to the same BIE id.  Therefore there should be separate
schema objects for each pattern
-shippedItemInstanceListRequest  (applicable for Replace - PUT, and Create
- POST)
-shippedItemInstanceListResponse (applicable for Read - GET, Replace - PUT,
and Create - POST)
Therefore the wrapper schema objects do NOT have the <ActionVerb> since
they both point to the same BIE id.  If the GET, PUT or the POST pointed to
a different BIE id, then the <ActionVerb> rule would kick in.

This naming convention keeps the schema object and class names shorter.

The operation id is explicitly mapped to the controller name in both NSwag
and CodeGen.  Not sure how that matters from a schema object naming.  It is
not a path as you show.   I do try to ensure the operation ids are named
the same for pairs of requests and responses.

@kbserm <https://github.com/kbserm> @elena-jelisic
<https://github.com/elena-jelisic>

**Comment by hakjuoh** [comment]
@dubnemo 

The following are the results of generating OpenAPI documents for three items worked on oagiscore.net, applying the updates you provided. Please review them.

[SME Manufacturing Express Pack-V1-1713970117116.yml.zip](https://github.com/OAGi/Score/files/15096156/SME.Manufacturing.Express.Pack-V1-1713970117116.yml.zip)
[AgGateway In-Field Product Id-V4-1713970053102.yml.zip](https://github.com/OAGi/Score/files/15096157/AgGateway.In-Field.Product.Id-V4-1713970053102.yml.zip)
[Traceability API-V1-1713969959147.yml.zip](https://github.com/OAGi/Score/files/15096158/Traceability.API-V1-1713969959147.yml.zip)

In 'Traceability API,' there is duplication occurring as it reuses Container [ID=862] from Critical Event [ID=873] BIE, which is not defined within the corresponding OpenAPI Document. As a result, an object named 'container862' is generated.

@kbserm @elena-jelisic

**Comment by dubnemo** [comment]
You will want to see the version we have edited down for AgGateway In-Field
Product Id.  It follows the convention.  There is a shippedItemInstance
schema object for the profiled BIE, and a shippedItemInstanceList schema
object.  All the verb-request and verb-response combinations that use that
BIE, all reference the ShippedItemInstanceList.  No Response or Request
required.

I am getting close to completion of the state machine, but may not be
completely ready by the time of the meeting.  But we can go through the
first layer of it, before we get to verb/message type details.  I really
follows how I manually edit the connectCenter output today.

**Comment by hakjuoh** [comment]
@dubnemo 

Here's a fixed one. All schema object names are referred to shippedItemInstanceList. I uploaded this version of the connectCenter to the test instance with the prod instance's data.

[AgGateway In-Field Product Id-V4-1714062510597.yml.zip](https://github.com/OAGi/Score/files/15112994/AgGateway.In-Field.Product.Id-V4-1714062510597.yml.zip)

**Comment by hakjuoh** [comment]
@dubnemo 

The following is the result of applying the modified logic discussed in the last meeting. You can also test it on the test instance.

[SME Manufacturing Express Pack-V1-1714654264466.yml.zip](https://github.com/OAGi/Score/files/15188545/SME.Manufacturing.Express.Pack-V1-1714654264466.yml.zip)
[AgGateway In-Field Product Id-V4-1714654245755.yml.zip](https://github.com/OAGi/Score/files/15188546/AgGateway.In-Field.Product.Id-V4-1714654245755.yml.zip)
[Traceability API-V1-1714654223071.yml.zip](https://github.com/OAGi/Score/files/15188547/Traceability.API-V1-1714654223071.yml.zip)
