### ISSUE TITLE
Linking Existing Accounts option for SSO missing developer accounts in the list

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1616]
When a existing user with a developer account requests SSO, the account does not appear in the Link to existing account's list.  Only non developer accounts are showing in the list to link with an existing account.

**Comment by hakjuoh** [comment]
By the current design, Developer accounts are users who develop Core Components and should not be SSO users. Could you please explain in what scenarios Developer users are necessary?
@kbserm

**Comment by smorgan19** [comment]
We have users who develop Core Components before presenting them to OAGIs for approval or our own internal testing.  Additionally, we have users who have had developer accounts for years and we are unable to switch them to end user accounts.  Since the addition of SSO we have always had developer accounts that are linked to SSO and this is a safer security practice to use SSO then basic auth.  Currently, non-sso accounts don't have any restrictions on password types(length, character vs special character), expiration/mandatory cycling, etc, to make it a safer alternative.

**Comment by hakjuoh** [comment]
Now, the 'Link to Existing Account' dialog allows SSO users to link to both developers and end-users.

<img width="1142" alt="Screenshot 2024-06-10 at 1 51 58 PM" src="https://github.com/OAGi/Score/assets/16102116/453a4ce0-9691-4722-9529-612521c27fe8">
