### ISSUE TITLE
Version Info no longer appearing in BIE expression (.XSD)

### ISSUE THREAD

**Issue by tekratz** [OAGi/Score#1617]
When expressing a BIE that contains a version value, the attribute does not appear in the .XSD schema

**Comment by hakjuoh** [comment]
Was the BIE BOD? Every BOD has 'Version Identifier'.
<img width="1308" alt="Screenshot 2024-03-25 at 11 02 51 AM" src="https://github.com/OAGi/Score/assets/16102116/e13bab50-dec3-4b58-ab69-26b036c38a72">

If the BIE is not a BOD, the version attribute does not appear even if the Top-Level ASBIEP has a version value.

**Comment by tekratz** [comment]
I think the functionality we are requesting is that the version information would be added to the expressed BIE in all cases.  
![image](https://github.com/OAGi/Score/assets/14177869/636fbe56-7437-4f7c-a4c6-7217ad6872e0)

Not sure the best way to resolve a BOD with a version value and a versionID attribute fixed value. Originally we this was part of the BIE packaging request, but after talking it over with Michael, we thought that this should just be the standard for how BIEs are expressed, regardless if it is in a package or not.

**Comment by hakjuoh** [comment]
@tekratz Version ID would be expressed through 'appinfo' in the same way as with the BIE Package, as follows.
```xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.openapplications.org/oagis/10" targetNamespace="http://www.openapplications.org/oagis/10" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:element name="ItemMaster">
		<xsd:annotation>
			<xsd:documentation>Below is the 'appinfo' element containing BIE version information in beta format.</xsd:documentation>
			<xsd:appinfo>Version ID = 7.3</xsd:appinfo>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				...
```
