### ISSUE TITLE
Transfer Ownership UI Issue, if you click on a username in the transfer ownership list it shows a not-found works message.  

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1622]
If you click on a username in the transfer ownership list it shows a not-found works message.

Steps to replicate:
1. View the Transfer Ownership List
2. Click on any of the usernames

![image](https://github.com/OAGi/Score/assets/56837736/02771ac7-af77-4a98-9860-d19810018d96)

**Comment by hakjuoh** [comment]
@smorgan19 It would be helpful if you could provide more details about which screen, which user, and which button was pressed when the issue occurred.

**Comment by smorgan19** [comment]
@hakjuoh It is the Transfer Ownership Page, if you click on any of the user ids it brings up the not-found works.
Steps: 
1.Admin Menu->Transfer Ownership
2. Transfer Ownership Page thats lists all of the usersnames, click on the username
3. The not found works will appear

**Comment by hakjuoh** [comment]
@smorgan19 Thank you for your feedback. I have identified the issue. When the user clicks on a username, the checkbox on the left should be activated. This is happening due to an unnecessary link on the username. We will address this issue in the upcoming version.

@kbserm
