### ISSUE TITLE
BIE Uplifting Issue:  Users unable to uplift BIE's that the user owns, but can uplift other users BIEs

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1623]
When a user tries to uplift a BIE owned by their account, a 400 error appears on the uplift menu.  Users are able to uplift BIEs owned by other user accounts.

Steps to replicate:
1. Uplift BIE Area
2. Any Src and Target Version, BIE Selected that the user owns
3. Error 400 should appear

**Comment by hakjuoh** [comment]
@smorgan19 I tried to set up and test the SSO environment using Auth0, but I couldn't reproduce the issue. If possible, could you please provide a screenshot or more detailed information?

**Comment by smorgan19** [comment]
@hakjuoh, @lmkennethburnett and I have done more testing.  The issue is present only in WIP State BIEs that have existing SSO.  If we create a new account and attach it with SSO we can uplift the BIE in WIP State.  If we Disassociate SSO with an existing and re-enable it, the issue is still present.  Additionally, an account not tied to SSO can uplift BIEs in WIP State.

**Comment by hakjuoh** [comment]
@smorgan19 @lmkennethburnett Could you send me a stack trace when you got that 400 error message from the docker containers?

**Comment by smorgan19** [comment]
@hakjuoh we will work on this.  I think the only way to replicate this will be to start from version 3.2.2 and set up SSO accounts in that version.  Then do the upgrade to 3.3.0, the issue is only present on existing accounts before the upgrade.  We created a new account and attached it to SSO and we were able to uplift.

**Comment by hakjuoh** [comment]
@smorgan19 We identified the cause of the problem and fixed it. https://github.com/OAGi/Score/commit/55d25f0659e609143e37be02af8f092e005cd196
