### ISSUE TITLE
prepopulate definition on new component

### ISSUE THREAD

**Issue by crakerb-ship-it** [OAGi/Score#1626]
When reusing an existing components it would be helpful if the definition is populated from the source element by default. In many cases the same component may have the same definition in multiple contexts. This would automatically fill the definition box with the base element definition, if it is not accurate the user could replace. 

Alternatively, there could be a button to reuse the definition instead of prepopulating by default, that would still be more efficient than scrolling down to copy then paste the definition.

**Comment by dubnemo** [comment]
I fully support this on the BIE context definitions, copying **all property term definitions** from the ASCCP and BCCP properties,  and also during the component library development and maintenance; e.g., from ACC to ASCCP (careful not to override existing definitions).
Thanks, @crakerb-ship-it

**Comment by kbserm** [comment]
For BIE , case if you just want the CC definition to display on the UI , I think it's better to logically does it and show it in a distinguished way from the customed created one, unless the user clicks the button to copy. This will save BIE object size which is oftentimes already huge and also keep informed that there is no real context definition. Keep in mind that in the BIE Expression, there is an option to include CC definition. We can change the logic to copy CC definition to BIE if BIE definition is empty. 

For Asccp, I would advocate a copy button. I prefer not to make user too complacent about giving definition. Maybe we can add some validations when changing CC state from WIP to draft. One validation would be if Asccp property term is same as ACC object class term but definition is no difference then it's a violation.

**Comment by dubnemo** [comment]
@kbserm should this be broken up into two features?  One BIE feature and the other on the component library?

@crakerb-ship-it  is your request for a component library feature, considering this may have been driven by the ADAPT experience, working  with @knelson-farmbeltnorth ?  If so, I can create the issue for the BIE feature.

**Comment by crakerb-ship-it** [comment]
That was my only hesitation on if it is too easy for users to reuse a definition they might not change it when they really should. I like the copy button option for that reason, then it is at least a conscious decision to copy it over and some sort of validation/conformation that the user really wants it to be the same makes sense.

**Comment by crakerb-ship-it** [comment]
It was in ADAPT so on the component library since until very recently BIEs were not an option but I think it applies to both use cases but up to you guys if that should be separate issues
