### ISSUE TITLE
Annotation is appearing twice in expressed xsd bies

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1630]
Annotation is appearing twice and is generating an invalid schema.  This happens on regardless of the BIE type or method of creations(new creation vs uplift).  To replicate this issue, the express conditions are BIE Definition Selected, XSD as the Expression, Put all Schemas in One File for Schema File options.
![image](https://github.com/user-attachments/assets/c1c2a186-2a40-4d02-8afa-9104b02cac2e)

**Comment by hakjuoh** [comment]
@joshklm @tekratz @kbserm This issue follows the issue #1617. One way to solve this issue is to move the documentation tag for the context definition into the first annotation tag.

```xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.openapplications.org/oagis/10" targetNamespace="http://www.openapplications.org/oagis/10" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xsd:element name="Process">
        <xsd:annotation>
            <xsd:documentation>Below is the 'appinfo' element containing BIE version information in beta format.</xsd:documentation>
            <xsd:appinfo>Version ID = abc</xsd:appinfo>
            <xsd:documentation source="http://www.openapplications.org/oagis/10">Context Definition Info</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType />
    </xsd:element>
</xsd:schema>
```
