### ISSUE TITLE
BIE Uplift

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#454]
Here are initial requirements:
1. The user can choose which OAGIS release the profile BOD will be based on.
2. When a new minor release is made, there is an automatic functionality to upgrade the profile BOD to the new release (i think this should create a copy and point to the new release, the old profile BOD will remain). A question is can the upgrade jump across releases, e.g., current profile BOD is based on 10.1, the user didn't upgrade the profile BOD to 10.2 release, can the user just jump from 10.1 to 10.3 release? Is this possible?
3. What can the tool do to help if there is a major release?

**Comment by kbserm** [comment]
when all nodes in the source BIE are automatically map, the tree in left pane currently only shows root node.

**Comment by dubnemo** [comment]
@kbserm let review this Thursday as well.  After going through a few of the them, I do see that 
1) if there is a direct component to component map, when the extension appears in ASCCP view, an ACC or its base ACC, then the **three primary context attributes** (context definition, example and max cardinality) are current not carried over, and that would be ideal (OK for 2.1)
2) I think it would great to be able to edit the target BIE, perhaps allowing copy / paste the **three primary context attributes** from the source to the target, one attribute at a time, as needed.  
3) if there isn't a direct component to component map (e.g., sequenceNumber in standard extension, to Sequence Code BCCP), then the copy/ paste of the **three primary context attributes** would be possible.
4) the Report was not working on oagiscore.net.  Perhaps this simply copies to clipboard the paths, and I paste in Notepad.
