### ISSUE TITLE
ACC's associations reordering affects all revisions

### ISSUE THREAD

**Issue by ljmshiki** [OAGi/Score#460]
As reordering of associations within an ACC revision is not tracked by history records (kept only within current records), all previous revisions will lose their ordering of associations and use the latest one.

Probable fix: we should create history records for this case and review if ACC tree view pulls up correct snapshot of history records for ACC's associations

NOTE: it is not possible to differentiate new associations based on the release, as the problem occurs between revisions (example: add new assoc to ACC rev2, then create new revision and add new assoc to ACC rev3, without including ACC revs into new release => both new associations have null release, so difference cannot be made on that basis)

**Comment by kbserm** [comment]
@asdimitriadis I want to use this issue to track that there is a test case to make sure that changes in ordering of associations are properly kept and displayed across ACC revisions.

**Comment by kbserm** [comment]
This issue is addressed in the ACC association management. @hakjuoh implemented history record. Changed the association ordering to linked list. There is also a constraint that new association cannot be moved before existing associations.
