### ISSUE TITLE
Validate release content selection

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#471]
While making a release, the system should at least validate that all the selections are connected and connected with the other part of the model. E.g. No BCCP is dangling, no BCC without a connected BCCP.

**Comment by kbserm** [comment]
In 2.0 we will validate references. @kbserm will think more about unused CC entities.

**Comment by kbserm** [comment]
The following verbiage is added to the test case doc about release validation for the references.

The developer can click on Validate References. The system ensures that those new and revised CCs reference CCs that are included in the release and that are in Candidate or Published state. The following references should be validated 1) ASCCP to ACC, 2) ACC to ASCCP in its ASCC, 3) ACC to BCCP in its BCC, 4) BCCP to Code List, 5) BCCP to BDT. If the target entity is not in the release or in a wrong state in the release, the validation fails. If the validation fail, the system shall list CCs that have invalid references and list those CCs that are needed to make the release draft valid. Missing CCs and CCs in incorrect states must be listed along with the current state and owner (needed CCs may be in Draft, WIP, or Deleted state or in Candidate state but not included in the release). Optionally, the developer can notify (via email) to the owners of those needed CCs that they need to act upon those CCs so that that release draft can be created.  The developer can open the detail page of a needed CC (in another tab), in which actions can be performed based on his ownership and state of the CC. The system shall also give warnings for ACC, ASCCP, BCCP, Code List, Agency ID List and DT  newly added to the release that is not used/referenced by any other entity.

**Comment by kbserm** [comment]
There seems to be a validation mistake. The system seems to complain when an ASCCP is not included in the release when its ACC is included. This situation should not cause invalidation.

**Comment by kbserm** [comment]
A component has no relevant to the components assigned to the release draft was said to cause invalidity. I don't know why, as there were other irrelvant components also but they don't get error out. I had to delete that ACC to be able to create the release draft.

![image](https://user-images.githubusercontent.com/7863166/95527437-482a8f00-09a3-11eb-9d9d-203b444cb9a8.png)

Another issue is revised CCs not assigned to the release draft cause validation error as well. @asdimitriadis please make sure Test Script covers this.

**Comment by rekuku** [comment]
Implemented
ACC(rev=1) - Based ACC
- If Based ACC is in WIP/Draft/Deleted state : Error
- If Based ACC is in Candidate state but not included: Error

ACC(rev=1) - Associated ASCCP/BCCP
- If ASCCP/BCCP is in WIP/Draft/Deleted state : Error
- If ASCCP/BCCP is in Candidate state but not included: Error

ASCCP(rev=1) - Role of ACC
- If Role of ACC is in WIP/Draft/Deleted state : Error
- If Role of ACC is in Candidate state but not included: Error

ACC(rev>1) - Based ACC
- If Based ACC is in WIP/Draft/Deleted state : Error
- If Based ACC is in Candidate state but not included -> Warning given and use previous revision based ACC

ACC(rev>1) - Associated ASCCP/BCCP
- If ASCCP/BCCP is in WIP/Draft/Deleted state : Error
- If ASCCP/BCCP is in Candidate state but not included: -> Warning given and use previous revision ASCCP/BCCP

ASCCP(rev>1) - Role of ACC
- If Role of ACC is in WIP/Draft/Deleted state : Error
- If Role of ACC is in Candidate state but not included -> Warning given and use previous revision Role of ACC

**Comment by kbserm** [comment]
@rekuku @hakjuoh Please see my questions/comments in the attached slide deck. I also proposed, I think, a simpler/easier to follow algorithm on the deck. Please take a look.
[Release Validation.pptx](https://github.com/OAGi/Score/files/5361191/Release.Validation.pptx)

**Comment by rekuku** [comment]
@kbserm As written in the ppt
I changed the warning conditions and messages.
It is deployed in the test, and examples are as follows:
![Screen Shot 2020-10-11 at 10 03 40 PM](https://user-images.githubusercontent.com/10194354/95699276-0bb09a80-0c12-11eb-8042-819e96a84560.png)
