### ISSUE TITLE
Test multiple releases in the DB

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#487]

**Comment by rekuku** [comment]
Deprecated cannot be set when revision is 1 (first creation).

**Comment by rekuku** [comment]
Developer user only can make new revision CC from the working release to working release.
End user only can change state of CC from ‘Published’ to back to Editing at a specific release.

**Comment by kbserm** [comment]
only two releases, for testing purpose. And we should assume that data from the prior release is playing nice with the current release.
