### ISSUE TITLE
DT Management

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#493]
Need to come up with a functional design.

**Comment by kbserm** [comment]
We decided to defer DT editing to a future milestone.

**Comment by hakjuoh** [comment]
OAGIS doesn't have the following unqualified BDT: "Picture. Type", "Rate. Type", and "Ratio. Type".

**Comment by kbserm** [comment]
I was looking at the UI below. It does not show me that the Payment Method_ Code. Type also has a code list primitive assigned.

![image](https://user-images.githubusercontent.com/7863166/131223687-9dca3ec9-354c-44e2-a5dd-7f083b18f23e.png)

**Comment by rekuku** [comment]
@asdimitriadis DT management is ready to test.
Please check the latest commits and execute the migration script for mig_2.2.0_to_2.3.0.sql.
Implementations are following this assertion.
https://docs.google.com/document/d/1xYnX3j0grpt-uIB9Jim5EgpFtFulqH75037NAidwcg0/edit#heading=h.56uta8gg6m1t

**Comment by rekuku** [comment]
And it deployed to test instance. cc @kbserm

**Comment by asdimitriadis** [comment]
I am closing this issue since DT management works well. 
We have closed all DT management related issues
