### ISSUE TITLE
Extend Release management with modules support

### ISSUE THREAD

**Issue by ljmshiki** [OAGi/Score#495]
Extracted from Issue #472 
> The RELEASE_ID in the module table is assigned as part of the release management. When assigning a module to a CC, the user can use a module from any prior releases or ones with no release yet. If a (draft) release got deleted this RELEASE_ID column should be updated as well. In other words, eventually, it should points to a final release.

**Comment by kbserm** [comment]
duplicate with the new module management issue #801
