### ISSUE TITLE
Make the BCCP GUID static

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#540]
The current import logic uses the GUID of the xsd:attribute for BCC and randomly generate the GUID of the BCCP. This causes inconsistencies when importing a future version of the OAGIS. We need to make GUIDs of these BCCP static.

A few options are:
1. Generate from name.
2. Add explicit BCCPs to OAGIS.

Option 2 is a better way to go. Why don't we list out the affected BCCPs and see if there might be a problem adding them to OAGIS.

**Comment by kbserm** [comment]
OAGi is planning to use Score to develop future standards. This issue may not need fixing. I move this to 2.0 just to keep closer watch.

**Comment by kbserm** [comment]
This issue does not impact the generated Model Schema b/c these BCCP won't be generated.

@hakjuoh @rekuku ohow do we know not to generate these BCCPs as xsd:element?

**Comment by rekuku** [comment]
We have EntityType value in BCC table.
This distinguishes an element from an attribute.
And i checked all the BCCP elements match xml and DB guid.

**Comment by kbserm** [comment]
This issue does not matter once OAGIS development moves to Score.
