### ISSUE TITLE
create Business Term capabilities map to BIE tables and relate to a data catalog

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#602]
It was discussed that Business Term in CCTS is unbounded, and could be a list off the asbiep.

7.9.4.3 Association Business Information Entity Property Business Terms
An ASBIE property may have several business terms. ASBIE property business
terms are synonym terms under which the ASBIE property is commonly known and
used in business.
[B130] Each ASBIE property shall have zero or more business terms.

**Comment by dubnemo** [comment]
@kbserm reviewing this one, and comparing to the data mapping specification, the reference to CCTS business term can be interpreted as a thesaurus or lexicon.  
The data mapping specification is an extension of that or potentially the set sibling tables we discussed in the face-to-face.

![BusinessTerms_Thesaurus](https://user-images.githubusercontent.com/32434235/76879322-18b80780-6844-11ea-8615-b9064790e3e9.png)

**Comment by kbserm** [comment]
related with #790

**Comment by dubnemo** [comment]
Based on today's meeting.  We discussed focusing on bbiep as a starting point. 

I would consider two BIE tables.

![BusinessTerms](https://user-images.githubusercontent.com/32434235/81986269-20eeb200-95fd-11ea-81bb-6329e88f16d5.png)

**Comment by kbserm** [comment]
Also ideas from today meeting are:

Logically, relationship from BIE to business term is 1-n but physically it is n-n because Score cannot support BIE reuse yet; and even if Score supports BIE reuse, building higher-level BIE bottom up from reusable BBIEP may not be practical. A work around is ,at the application level, provide a functionality to check for consistent business term assignment to BIEs that are derived from the same CC and that are in the same context.

Conversely, business terms can be suggested when a new BIE is created based on business terms already assigned to other BIEs that share the same CC.

**Comment by dubnemo** [comment]
I recommend that business_term table have a generic uri instead of catalog_uri, based on Peter's comments yesterday.  It should also include an external_ref_id to enable an import capability leveraging the upsert pattern; the external_ref_id would be used to check if the business_term already exists, and if not INSERT, else UPDATE the definition and/ or uri.

**Comment by dubnemo** [comment]
Update the business_term diagram.  @kbserm 

@hakjuoh is this the complete listing of tables (in white) where biz_term column exists?

![BusinessTerms](https://user-images.githubusercontent.com/32434235/97721289-43836300-1a97-11eb-8f52-727e14ea5123.png)

**Comment by hakjuoh** [comment]
@dubnemo `biz_term` columns only exist on `abie`, `asbiep`, `bbiep`, and `bbie_sc` tables which are all BIE-related tables.

**Comment by dubnemo** [comment]
**From 2021-04-29 Score Meeting**
For consideration, related to business term and synonyms, and associated business context.

![image](https://user-images.githubusercontent.com/32434235/116554415-c65b6e00-a8c0-11eb-9abe-63968af193ef.png)

**Comment by kbserm** [comment]
https://oagiscore.atlassian.net/wiki/spaces/MAP/pages/4094427139/2021-07-21+Mapping+WG+Meeting+Minutes

**Comment by kbserm** [comment]
@dubnemo Can you think about uplift. Is there a special treatment needed related to business term?

**Comment by kbserm** [comment]
From our 10.7 meeting we realized that the business term functionality need to take into account the type code qualification.
