### ISSUE TITLE
BIE Extension Simulation

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#607]
I was able to select Create ABIE Extension Locally, find Manufacture Date Time, and Append it to the Extension area for Inspection Order.

The extension does not 1) appear in the list to be profiled, and 2) does not appear in the JSON Schema.
Going back into the BIE extension, it shows that it is still appended.

I also tried to append globally -- no go.

Seems to be some form of referencing issue at the DB level.

**Comment by dubnemo** [comment]
@kbserm @hakjuoh is this now covered under Core Component management?

**Comment by hakjuoh** [comment]
> @kbserm @hakjuoh is this now covered under Core Component management?

Simple answer is yes. We’ve been planning to use core components in BIEs without a state transition in this milestone.

**Comment by kbserm** [comment]
@dubnemo we talked about various options to enable simulation of extensions a couple of weeks ago. I explaned to you the complication and you said let's keep the current approach and delay this issue.

**Comment by kbserm** [comment]
having said that I did think about this a couple of days ago. One simple solution which I am not sure if it would be acceptable to you is a simulate BIE Extension function would express a schema or API which has all the nodes in the User Extension Group (I.e. , like every node in the extension is enabled). In this way, there is no BIE or BIEs created that could cause issues if the user needs to go back and change the extension or any user defined CC used underneath it. What do you think @dubnemo?

**Comment by dubnemo** [comment]
@kbserm This may be a good topic to discuss next Thursday.  While it think the root issues is resolved (note the global extension attempted that messed with my repo), the simulation aspect is interesting.

**Comment by dubnemo** [comment]
@kbserm we are using UDCC quite a bit now, allowing us to create BIEs that simulate the JSON.

**Comment by kbserm** [comment]
@dubnemo Do you mean your requirement has been satisfied?

**Comment by dubnemo** [comment]
> 

by other means, yes.  UDCC allows me to create a BIE prototype, then decide how to actually build it properly.  I only wish I could delete UDCC once I have done this, added CCs to the OAGi CCL and built the actual BIE using components from the new release that contains those CCs.
