### ISSUE TITLE
In need of duplicate elements in DB for multiple releases.

### ISSUE THREAD

**Issue by hakjuoh** [OAGi/Score#608]
Some components like 'Application Area' would be contained at common components such as 'Meta.xsd'. When new OAGIS release published, however, its location has changed by some naming policy. For example, 'Application Area' for OAGIS 10.4 is located at 'Model\Platform\2_4\Common\Components\Meta' but it's replaced with 'Model\Platform\2_5\Common\Components\Meta' for OAGIS 10.5.
Our database schema for core components directly linked with its module. Thus, if we want to populate to common components for multiple releases, we should create duplicated core component data linked to the newly added module.

**Comment by kbserm** [comment]
This issue will already be addressed under the release and module management issues #801 and #802 and perhaps more.
