### ISSUE TITLE
Open Date Time -- defaulting primitive = token

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#621]
Shouldn't the primitive for Open Date Time be a Date Time type?  I have been manually editing these to date time.

![image](https://user-images.githubusercontent.com/32434235/54307152-f3d9e600-4598-11e9-940d-acd6add83c0d.png)

by default:
        "lastModificationDateTime" : {
          "description" : "This the date the inspection order was  either created or modified.",
          "$ref" : "#/definitions/token"
        },

whereas:
![image](https://user-images.githubusercontent.com/32434235/54307492-d8bba600-4599-11e9-835c-b9fe900b7ad5.png)

**Comment by kbserm** [comment]
duplicate with #808
