### ISSUE TITLE
Core Component Management

### ISSUE THREAD

**Issue by hakjuoh** [OAGi/Score#658]
Write CC Management functions.

**Comment by kbserm** [comment]
![image](https://user-images.githubusercontent.com/7863166/82963991-40d58c80-9f92-11ea-805c-6020f14ec9a0.png)

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis 

There are two changes:
1) Added 'Open in new tab' menu for each tree node on the left side panel except the root node to go to another CC detail page.
2) Replace with tab controls for each detail on the right side panel to display CC DEN, release, revision #, state, and owner.

<img width="1313" alt="Screen Shot 2020-06-14 at 10 03 08 AM" src="https://user-images.githubusercontent.com/16102116/84595566-844f4800-ae26-11ea-8755-0a94440339e6.png">

**Comment by kbserm** [comment]
We need additional business rule regarding the Extension core component type. One option is to have a function that automatically generate the Extension component for a given ACC. Additionally, during the release process, there shall be a business rule to check whether all the new ACCs that is not abstract have appropriate Extension ASCC, ASCCP, and ACC and give a warning if it is not the case.

**Comment by kbserm** [comment]
New detail related to Extension components has been added to the Test Case document.

The menu Component should be changed back to Core Component.

**Comment by kbserm** [comment]
Make sure the terminology related to content removal is use properly on the menu items.

* Score terminology related to content removal. Discard vs. Remove vs. Delete
- Discard = the content is removed permanently, there is no trace or record about the removal and the removed content. 
- Remove = the content is removed from the entity table, but there is a trace or record about the removal and the removed content.
- Delete = the content is marked deleted in the entity table, there is also a trace or record about the deletion and the deleted content. Deleted content can be restored easily by changing the state of the content in the entity table. A deleted entity can be 'restored'.
- Cancel is similar to Remove.  A revision can be cancelled. The information about that revision would be removed from the entity table. Traces can still exist in the history table.

**Comment by kbserm** [comment]
It looks like the ability to flag higher level entity when lower level entity is deleted is not there yet. We can do this in the later release b/c the Release process is also taking care of this as deleted CCs cannot be included in the release draft. This function can be deferred to future version. An issue has been filed #864.
