### ISSUE TITLE
Visibility of an extension issue

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#663]
The issue is that a user can view a BIE’s extension that is in Editing state and created by another user.

The expected behavior is that a user cannot view a BIE’s extension that is in Editing state and created by another user.

**Comment by rekuku** [comment]
- This confirmation message applied.
"Another user is working on the extension. It is in the Candidate state. You can only review the extension. Would you like to open the extension to review?"


- In the case of UEG, 1.3 takes the most recent data from the history to determine if it is the same user's access or not, If it's not the same user, but it's published, then create a new revision.
2.0 always looks up data based on the most recent work history, so the behavior is same as shown in 1.3.

Please let me know if there are any improvements or considerations in this logic.

related with #750, #751
