### ISSUE TITLE
DB LockAcquisitionException -- how to clear a db lock

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#679]
I have never encountered this error before.
Is there a way to clear a lock?

could not execute batch; SQL [update `acc` set `based_acc_id`=?, `current_acc_id`=?, `definition`=?, `definition_source`=?, `den`=?, `is_deprecated`=?, `is_abstract`=?, `last_update_timestamp`=?, `last_updated_by`=?, `module_id`=?, `namespace_id`=?, `oagis_component_type`=?, `object_class_qualifier`=?, `object_class_term`=?, `owner_user_id`=?, `release_id`=?, `revision_action`=?, `revision_num`=?, `revision_tracking_num`=?, `state`=? where `acc_id`=?]; nested exception is org.hibernate.exception.LockAcquisitionException: could not execute batch

**Comment by kbserm** [comment]
Resolved by subsequent Score release.
