### ISSUE TITLE
Add AgencyIDList management

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#7]
Add AgencyIDList management to the BIE management in the design doc.

**Comment by kbserm** [comment]
Can Code List and Agency ID List be managed together.

**Comment by rekuku** [comment]
Add remark column to agency id list.
Set default value of agency_id GUID.

**Comment by asdimitriadis** [comment]
I am closing this issue since we do not have any other issues for the Agency ID list management. 
Everything works well.
