### ISSUE TITLE
An extension should not have two same associations

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#710]
The issue is that we can append an ASCCP or a BCCP to a Local or Global extension even there is an association with the same name as depicted in the attached screenshot.

![issue3](https://user-images.githubusercontent.com/37205288/66223530-b5755700-e6a1-11e9-8ea6-dbfee4ee6cf6.jpg)

**Comment by asdimitriadis** [comment]
According to our last meeting, we found that the issue still exists. For instance one can append a BCCP with the same DEN creating in this way a duplicate node.

**Comment by kbserm** [comment]
@asdimitriadis your comment above reference the case of DEN (perhaps more like Property Term) duplicate with that on the based type.

**Comment by kbserm** [comment]
Don't forget that you need to prune any Group contained within the ACC or based ACC as well.

**Comment by kbserm** [comment]
This business rule applies to any ACC. Leave this open just to make sure that User Extension Group ACC is get tested.

**Comment by kbserm** [comment]
simple logic was implemented but more need to be done and this is logged in #868.
