### ISSUE TITLE
The is_used column of some ancestor nodes don't get recorded

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#747]
The is_used column of some ancestor nodes don't get recorded. This happened when the user keep expanding the BIE tree and enable a node deep down. Some ancestor nodes don't get recorded, even though the UI displayed correctly. When generate the XML schema, the expected descendant nodes don't get generated.

**Comment by rekuku** [comment]
Some ASBIE node has not check correctly ( is_used must be set 1, but it was not ) 
e.g. top_level_bie_id 8, 18.
I try to reproduce this in my local environment, but it works fine. it could be happen at AWS instance environment.

**Comment by rekuku** [comment]
It is not AWS instance environment problem.
This bug occurs when if user using mixes the `used` checkbox in the tree and the checkbox in the detail view.
The bug scenario is as follows:
Create BIE -> 
 Expand tree -> 
 Set used some node using tree’s checkbox -> 
 Load node’s detail by click node -> 
 Set unused node using details’ checkbox ->
 Set used node using detail’s checkbox ->
 Update
Then that node’s used value will be not recorded.

It is the bug at synchronizing data between the server and the client, and is now fixed and merged to the develop branch.

@asdimitriadis test it please.

**Comment by asdimitriadis** [comment]
Got it. I am testing it.

**Comment by kbserm** [comment]
when this error occurred, I actually never use the check box in the details pane.

**Comment by rekuku** [comment]
This bug related to the order of loading details.
It also happens when you only use the tree’s checkbox.

In this case, the scenarios are as follows:
Create BIE ->
Expand tree ->
Set used some node using tree’s checkbox ->
Load detail node what one of checked ->
Update.
@kbserm

**Comment by asdimitriadis** [comment]
Tested.
