### ISSUE TITLE
View/review of an extension in Candidate state

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#750]
The issue is that if a BIE has been extended locally on an extension point and the extension is in candidate state then another user cannot view/review the extension.
The expected behavior is that when a BIE has been extended locally on an extension point then another user can view/review that extension (but he cannot edit it).
To reproduce the issue:
1. Login as a devx
2. Create the BIE "ASN Reference", expand the tree and extend it locally on "ASN Reference/Extension".
3. Set the extension to Candidate state
4. Logout
5. Login as a devy
2. Create the BIE "ASN Reference", expand the tree and extend it locally on "ASN Reference/Extension".
At this point the user2 should be able to view/review the extension but not edit it.
Now, he cannot view/review it as depicted in the Screenshot below

![issue](https://user-images.githubusercontent.com/37205288/72005584-9a912080-3256-11ea-980d-256cc1daa5a5.png)

**Comment by rekuku** [comment]
I add condition to Create Extension logic what checking Extension's State.
So now other users can review Extensions in Candidate, Published state.

**Comment by asdimitriadis** [comment]
Tested.
