### ISSUE TITLE
Extend a BIE locally on an extension point that there is a published local extension

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#751]
The issue is that if a BIE has been extended locally and the extension point is in Published state then another user cannot extend the BIE locally on the same extension point. 
The expected behavior is that the BIE can be extended locally by a user on an extension point even if another user has already extended it locally on this extension point providing that the extension is in Published state.

**Comment by rekuku** [comment]
Extensions are working between each other users as with below.
Editing: other user can NOT  edit/view extension
Candidate: other user only can view extension
Published: other user can edit extension with new revision.
@asdimitriadis You can find this at develop branch.

And we need to think more whether to change the structure for apply rules of TC5.6 - 8.

**Comment by asdimitriadis** [comment]
If an UEGACC has revision number greater than 1, old associations cannot be deleted but they can be deprecated.
Also old associations (ASCCs and BCCs) should follow the following business rules:
1.	Min <= previous_Min
2.	If previous_Max = -1, it cannot be changed. 
3.	If previous_Max != -1 and previous_Max >=0, Max >= previous_Max

**Comment by rekuku** [comment]
@asdimitriadis 
TC5.6's ASCC/BCC rules has applied.
You can found this at release/1.3.0 branch.

Please test this. Thank you.

**Comment by asdimitriadis** [comment]
I have found an issue after the above commit.

The issue is that when I create a BIE, the first time I try to extend it, it returns the error that "Editing Extension already exists.". If I try again, it works and I can extend the BIE. So, the error is returned only at the first time someone tries to extend a BIE. Every next time it works. 

P.S. I have restarted everything as well as the database and prune the docker volumes but I still face the issue.

**Comment by rekuku** [comment]
@asdimitriadis 
In Publishing, there was a code that took a long time ( about 3 seconds) with regard to #714 .
It's faster now because I don't use this time.
Please check this on 1.3.0 branch.

**Comment by asdimitriadis** [comment]
The issue still exists.
To reproduce it.
1) Create the BIE "ASN reference" and leave the Edit BIE page (e.g. visit CC View page).
2) Open the BIE List page (BIE -> View/Edit BIE).
3) Click to open the BIE "ASN reference".
4) Expand it (you need only to expand the parent node).
5) Extend it locally (ASN Reference -> Extension).
**_At this point this message is returned "Editing Extension already exists.".
There is no issue in stacktrace, so it is a logic issue._**

However, if you then:
1) Open BIE List page.
2) Click to open the BIE "ASN reference".
3) Expand it (you need only to expand the parent node).
4) Extend it locally.
**_This time you can extend the BIE and no message is returned._**

**Comment by rekuku** [comment]
@asdimitriadis 
It happen when trying to extend at first time.
Now fixed.

**Comment by asdimitriadis** [comment]
Another new issue is that now I cannot change the fields of olds association (ASCCs and BCCs). 
Once I create a revision of an extension then the fields of _some_ old associations are disabled (they are not interactable).

**Comment by rekuku** [comment]
For cardinality, if it is published as the default value in old revision (0, -1), then the new revision cannot be changed.
Because we got this rules
 - Min <= previous_Min  <= If old cardinality is zero. it means Min can not be changed. isn't it? 
 - If previous_Max = -1, it cannot be changed.

**Comment by rekuku** [comment]
@kbserm @asdimitriadis 
I Apply new Nillable condition to BCC
Once Nillable published as checked, then it can not be unchecked.

**Comment by asdimitriadis** [comment]
Tested.
