### ISSUE TITLE
Fix JSON schema and OAS schema object serialization

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#753]
Fix them according to the recent examples serm created.

**Comment by kbserm** [comment]
[FullBOMBIEExample1.1.json.txt](https://github.com/OAGi/Score/files/4073989/FullBOMBIEExample1.1.json.txt)

[FullBOMBIEExample1.1OASSchemaObject.json.txt](https://github.com/OAGi/Score/files/4073992/FullBOMBIEExample1.1OASSchemaObject.json.txt)


[FullBOMBIEExample1.1OASSDoc.json.txt](https://github.com/OAGi/Score/files/4073994/FullBOMBIEExample1.1OASSDoc.json.txt)

**Comment by kbserm** [comment]
Fixed a mistake oneOf => allOf in one of the subschema as pointed out by Hakju.

[FullBOMBIEExample1.1.json.txt](https://github.com/OAGi/Score/files/4122426/FullBOMBIEExample1.1.json.txt)
[FullBOMBIEExample1.1OASSchemaObject.json.txt](https://github.com/OAGi/Score/files/4122429/FullBOMBIEExample1.1OASSchemaObject.json.txt)
[FullBOMBIEExample1.1OASSDoc.json.txt](https://github.com/OAGi/Score/files/4122432/FullBOMBIEExample1.1OASSDoc.json.txt)

**Comment by hakjuoh** [comment]
@kbserm Please review the generated schemas for both JSON and OAS after applying new rules.

[OAS-BOM-oagis-id-8ba43f95f8ef46719f41cfd929f830a3.json.txt](https://github.com/OAGi/Score/files/4130634/OAS-BOM-oagis-id-8ba43f95f8ef46719f41cfd929f830a3.json.txt)
[JSON-BOM-oagis-id-8ba43f95f8ef46719f41cfd929f830a3.json.txt](https://github.com/OAGi/Score/files/4130635/JSON-BOM-oagis-id-8ba43f95f8ef46719f41cfd929f830a3.json.txt)

**Comment by kbserm** [comment]
A few corrections after talking to @hakjuoh today.

[FullBOMBIEExample1.1OASSDoc.json.txt](https://github.com/OAGi/Score/files/4131685/FullBOMBIEExample1.1OASSDoc.json.txt)
[FullBOMBIEExample1.1.json.txt](https://github.com/OAGi/Score/files/4131686/FullBOMBIEExample1.1.json.txt)
[FullBOMBIEExample1.1OASSchemaObject.json.txt](https://github.com/OAGi/Score/files/4131687/FullBOMBIEExample1.1OASSchemaObject.json.txt)
