### ISSUE TITLE
Block the functionality "Import from Code List" in case a BC uses one value of a CS

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#755]
There is the following scenario:
Assuming that we have the Context Scheme CSa that has the value csva with the name "aValue" and the Business Context BCa that uses the csva.
1. If a changes the name of the csva from "aValue" to "aValueNewName", then the new name should be displayed in both the CSa details page (when we view the CSa) and in the BCa details page (when we view the BCa). This works good.
2.  However, if a user decides to import to CSa values from a code list (that is to say to use the "Import from a code list" functionality) then an error is returned. This is due to the fact that the csva cannot be removed/deleted from the BCa.

Moreover, as @rekuku correctly pointed out that the same error is returned if a Context Scheme imports values from a code list and one of them is used by a Business Context and then we add values manually to the Context Scheme (meaning we decide not to use the "Import from Code List" functionality anymore).

It is suggested therefore to block the "Import from a code list" functionality of a Context Scheme in case there is a Business Context that uses one of its values.

**Comment by rekuku** [comment]
Block `Import from Code list` checkbox when It's Context Scheme Value in use.

**Comment by asdimitriadis** [comment]
Tested.

**Comment by rekuku** [comment]
And also
Change to only a combination of category, scheme, and value need to be unique.

**Comment by kbserm** [comment]
I think you should add the following logic. If a CS value is specied in the CS,  disable the import. If all values are deleted, them import is possible again. If import is used, no value can be specified.

**Comment by asdimitriadis** [comment]
> And also
> Change to only a combination of category, scheme, and value need to be unique.

It is fixed when one is updating a Business Context but not when one is creating a new one. That is to say, when you create a business context, you cannot add a value that has the same name with an existing one but different Context Category and Context Scheme.

**Comment by rekuku** [comment]
> I think you should add the following logic. If a CS value is specied in the CS, disable the import. If all values are deleted, them import is possible again. If import is used, no value can be specified.

I add this rules for Context Scheme create/edit view.



> It is fixed when one is updating a Business Context but not when one is creating a new one. That is to say, when you create a business context, you cannot add a value that has the same name with an existing one but different Context Category and Context Scheme.

And apply same thing to creating view.

@asdimitriadis Please review this on develop branch.

**Comment by asdimitriadis** [comment]
@rekuku I think that now we have to overlapped logics and we should keep only the latest one that Serm suggested, namely "_I think you should add the following logic. If a CS value is specified in the CS, disable the import. If all values are deleted, them import is possible again. If import is used, no value can be specified_"

So we should remove the previous one, wiz "_block the "Import from a code list" functionality of a Context Scheme in case there is a Business Context that uses one of its values_.". Also, the message/tooltip "It cannot be modified if some Context Scheme Values are specified or using by Business Context" should be changed to "It cannot be checked if some Context Scheme Values are specified. To use it, remove all values first."

It will be ok, as we still have the logic that prevents deleting a value from a CS if it is used by a BC.

**Comment by asdimitriadis** [comment]
We keep both logics/rules since they are not totally overlapped. 
In case the user added values manually they are overlapped.
However, in case the user used the "import from code list" functionality, they are not overlapped since the second logic prevents the user from choosing another code list.
