### ISSUE TITLE
UEGASCC should not be shown in the CC page

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#756]
The issue is that the UEG ASCCs are shown in the Core Component page.
The expected behavior is that they must not be shown in the list.

**Comment by rekuku** [comment]
Until now, only UEG ASCC and ASCCP belonging to the Working release have not been shown.
But now not allowed to display all UEG CCs regardless of Release.
@asdimitriadis Please test this.

**Comment by asdimitriadis** [comment]
To sum up, regarding the UEG CCs: 
- If the working release is chosen, no UEG CC is shown
- If a release is chosen, only the UEGACCs (User Extension Group Aggregate Core Components) are shown.

Tested.
