### ISSUE TITLE
On Business Context Detail page, show Context Value Name

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#757]
On Business Context Detail page, Business Context Value list, show Context Value Name.  Currently this is showing the value /code, not the **human readable description** of the code.  

During demos, people are unclear about what these codes mean.

**Comment by hakjuoh** [comment]
@dubnemo Currently, the details of context scheme/value displayed on a tooltip box in editing mode as

<img width="677" alt="Screen Shot 2020-04-03 at 1 58 11 AM" src="https://user-images.githubusercontent.com/16102116/78329126-dfbfa880-754e-11ea-9c70-5e93c44b9110.png">
<img width="660" alt="Screen Shot 2020-04-03 at 1 58 24 AM" src="https://user-images.githubusercontent.com/16102116/78329133-e1896c00-754e-11ea-9d6a-43a3c9f163fb.png">

@kbserm Have any idea?

**Comment by kbserm** [comment]
@hakjuoh Scott mean this page. The last column, instead of showing Context Value, show the Context Value Meaning or show both. Sometimes context values are very short abbreviation.

![image](https://user-images.githubusercontent.com/7863166/78364103-e9670180-758a-11ea-9485-dda19f4e9aeb.png)

**Comment by hakjuoh** [comment]
@kbserm @dubnemo Take a look at this.

<img width="986" alt="Screen Shot 2020-04-03 at 1 20 26 PM" src="https://user-images.githubusercontent.com/16102116/78387797-e7fb0080-75ad-11ea-90cb-7b1120c4e6c0.png">

I don't know how much information it needs to be there. I just added schema value meaning under the value.

**Comment by kbserm** [comment]
Does it display ok if the meaning is long?

**Comment by hakjuoh** [comment]
> Does it display ok if the meaning is long?

<img width="1363" alt="Screen Shot 2020-04-03 at 4 14 06 PM" src="https://user-images.githubusercontent.com/16102116/78401188-2c929600-75c6-11ea-9554-3c43e66bab87.png">

**Comment by dubnemo** [comment]
@hakjuoh @kbserm 
I recommend the description  be hover-over, and just display the context value name.
The principle is that ALL the grids should be **compact**, not show all the detail, but just enough text to want me to click or hover.

I preferred this one:

![image](https://user-images.githubusercontent.com/32434235/78499058-0549df00-7714-11ea-94ce-8ea4b972a971.png)

**Comment by kbserm** [comment]
@dubnemo Hovering over cannot show long text well either because it cannot have a scroll bar. Have to enable clicking to bring up a scrollable dialog box or open up the context scheme & corresponding value on another tab.

**Comment by dubnemo** [comment]
@kbserm @hakjuoh 
I prefer to click.  Compact is better, please. TMI.

**Comment by kbserm** [comment]
@hakjuoh How about either show the Meaning underneath the value like you had earlier or use scroll over dialog with limited space. Shows "......" at the end when the text runs over the space or over a certain length. The user can click to pop up a full text.

**Comment by dubnemo** [comment]
@kbserm, @hakjuoh Is the meaning really needed at this level?  I prefer to click to find more information, as I am looking for compactness.  The context scheme value is more than enough -- it used to show only a **short code** (e.g., 'AB', etc.) when this issue was created and now has expanded scope.

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis 

If 'meaning' property's value is too long, it shrinks with '...' as below

<img width="571" alt="Screen Shot 2020-04-21 at 5 31 54 AM" src="https://user-images.githubusercontent.com/16102116/79850127-771b5d00-8391-11ea-868d-5aae9711867c.png">

When it also clicks, details of each context display as below
<img width="1396" alt="Screen Shot 2020-04-21 at 5 27 15 AM" src="https://user-images.githubusercontent.com/16102116/79850326-be095280-8391-11ea-942e-c03ff5c787a0.png">

**Comment by dubnemo** [comment]
@hakjuoh this looks good.  Thank you.

**Comment by asdimitriadis** [comment]
Tested.
