### ISSUE TITLE
Collapse the View/Edit BIE list page so the page navigation control is at the bottom of the screen without scroll down

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#758]
We need a conversation about this page, as this came up during the demo calls.

The old UI (non-Angular version) was much more collapsed user friendly.  Typically, if you have pagination, the UI Design suggests that the page control is at the bottom of the screen.  Today, in the Angular Score, you have to scroll down to find the control as the page layout is not optimized, and nearly defeats the purpose of the pagination control.

Areas I see improvement...

**Search fields**:
- Don't  stack fields, 
- sequence in the order of importance: term, state, owner, context
- do we need date range, version result sort criteria?

**List box**: 
- reduce the width of Property Name, 
- have Owner as a column "Owner" vs. concatenated string
- have OAGIS release as a column "Release" vs. concatenated string
- Consider assigned contexts next to Property Name
- consider a left/right scroll bar

**Comment by kbserm** [comment]
@dubnemo I think this page layout is a result of my and/or someone else suggestion to have definition on this page. Search for a component that has definition and you will see it.

If there is a definition, then more columns make row height of each CC bigger, i.e., even longer scroll to the bottom to reach pagination buttons. 

One simplification we will definitely do is to remove the definitionSource.
I believe the main purpose of pagination is dynamic/lazy loading. I think these days lazy load can be done w/o pagination but with scrollbar like in web-based email client. Personally, I don't know if I like that either, it is kinda slow.   

I think one interesting thing we could try is listing DEN on the top of the result table, so one can quickly scan. Those DEN are anchor links. And add the pagination buttons on the top as well.

**Comment by hakjuoh** [comment]
@dubnemo How about use 'sticky' attribute on a pagination box?

![NIST_OAGi Score](https://user-images.githubusercontent.com/16102116/74369095-c6964900-4da2-11ea-82de-eb29f9760337.gif)

**Comment by dubnemo** [comment]
@hakjuoh @kbserm still too much real estate.  The old 1.1.1.2d was tighter, and Figura is saying the same thing.  The DEN path is too wide.  Owner and Revision can be separate columns.  The path can be removed has is TMI for a list view.  If we really want description, consider hover overs/ pop up.  

The same holds true for the DEN search.  TMI.

**Comment by dubnemo** [comment]
@kbserm closing
