### ISSUE TITLE
Create functionality to set Max Cardinality to 1 for all children

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#759]
An extraordinary amount of time is spent changing cardinality from unbound to 1.  Even though the standard allows for unbounded occurrences, in most cases except for *Line types, the cardinality is changed.  

This is the biggest complaint we are seeing about OAGIS from developers to date (other than the generic nature if identifiers with typeCodes in cases).

Enabling a right click option to set this cardinality would speed up delivery of a BIE 10 fold if not more.

**Comment by kbserm** [comment]
@dubnemo 

My concern about this is the user won't see the original 'unbounded' possibility. 

But to implement this feature, we might provide a check box on the BIE editing page where the user  has the option to default unbounded max cardinality to 1 once a BIE is checked. This is because BIE descendants are dynamically created as the user click the the check boxes. There is also a question to what we would do with the ancestor nodes as there is a feature to auto-enable those if a descendant is enabled. Are we going to change maxcardinality of those ancestors to 1 as well? This could create surprises. Could you think thru these situations.

**Comment by dubnemo** [comment]
@kbserm My take on this is that I would _first_ go through the selection process of all the BIE types/elements first, and then decide to set the cardinality.  I envision that only be done one time.  Then elements could be set to unbounded.  

Regarding the unbounded po ssibility, if an element is unbounded in the standard but not in the BIE after mass update, would it be possible to color code or some other indicator to show that option is available.  Otherwise, I currently just type 'unbounded', and SRT has an error message pop-up telling me the standard does not support it - I can live with that too.

**Comment by kbserm** [comment]
@dubnemo So you are suggesting more like a button, if clicked, change all the unbounded to 1.

For the color code we could try that.

**Comment by dubnemo** [comment]
@jim-wilson-kt @kbserm as discussed.  There may other ways to address this.

**Comment by kbserm** [comment]
I think in 2.0, @hakjuoh has changed the BIE loading such that this is more feasible. We may do it like this.

Add 'Set children max occur to 1' menu to the BIE context menu.

The question is whether we only allow to 'set children' or 'set descendants'? If we allow the latter case, there should be a confirmation box.

Do we need another menu item to reset the value to original?

**Comment by dubnemo** [comment]
@kbserm 
I agree to a confirmation box for Set to Descendants on **enabled properties** (caveat).    

There should also be an UI indicator that 'Std is Unbounded' or something like that, as you mentioned 1/29/2020, when you have selected a property and looked at the property sheet.

![image](https://user-images.githubusercontent.com/32434235/114935535-eee36280-9e00-11eb-9dfc-283d17b10837.png)

**Comment by dubnemo** [comment]
@kbserm Limited the scope of the Set Max Cardinality to 1 to Descendants to the selected property.  For example, if my scope is Production Order Line ASCCP, then only the enabled descendants max cardinality would be set to 1.

**Comment by kbserm** [comment]
@dubnemo We don't need the 'Set Children' one then?

**Comment by asdimitriadis** [comment]
It works good. 
The option has been changed to "Set Children Max Cardinality to 1".
