### ISSUE TITLE
Cannot update a BIE if I enable a BCCP without viewing its details

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#763]
The issue is that when I create a BIE, and then enable a node without viewing its details (click on it and view it on the detail pane), I cannot update the BIE. However, if I enable an ancestor node, click on it and view its details then I can update the BIE.

This issue might be related to #762 (although it is fixed) and might be similar to #747 (it was fixed).

**Comment by rekuku** [comment]
Server has a rule that least one of `Primitive Restriction(Code, Agency, Bdt)` information should be given for #762 
But update is_used value without load detail(click that node on tree), will not provide to server `Primitive Restriction` information. 
So for this case I remove the exception handling code on server even rule is correct.
May be we separate update API for detail and is_used on tree @hakjuoh 

@asdimitriadis Now update action will be work. please test this.

**Comment by asdimitriadis** [comment]
Tested. It works.
