### ISSUE TITLE
Change the Logo to Score logo

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#765]

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis 
<img width="407" alt="Screen Shot 2020-04-22 at 4 08 51 PM" src="https://user-images.githubusercontent.com/16102116/80028746-94484c80-84b3-11ea-8890-533b00b30f95.png">

**Comment by dubnemo** [comment]
@kbserm @hakjuoh I think the NIST and OAGi logos should be also displayed, merged.

**Comment by hakjuoh** [comment]
@asdimitriadis NIST/OAGi logo will put on the right side of the menu. `Semantic Refinement WG` text on the image will be cropped and it redirects to [NIST page](https://www.nist.gov/services-resources/software/score-standards-life-cycle-management-tool) when it clicks.

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis Please review the following screenshot:

<img width="1041" alt="Screen Shot 2020-04-27 at 10 37 17 PM" src="https://user-images.githubusercontent.com/16102116/80440888-ba1c8980-88d7-11ea-80c8-03ba0903179e.png">

**Comment by dubnemo** [comment]
@kbserm  I like the NIST/OAGi logo position.

Can we consider adding 'API' to the text?  'developer of API/ data exchange standards and contextualized implementation guidelines (profiles) based on the...'

**Comment by kbserm** [comment]
@dubnemo Hakju copied part of the text from NIST web site. If he copies more it will include API.

 Score is a software tool that supports the development of data exchange standards based on the ISO 15000-5 Core Components standard.  Score provides a repository and functionalities for standards developers to create, publish, and maintain data exchange standards with higher precision, quality, and productivity.  Standards are created once in the syntax/platform-independent form and can be published in various implementation-specific languages such as XML Schema, JSON Schema, or Open API specification.  In addition, Score allows the standard users to create (in a syntax/platform-independent form) a standards usage model (also known as implementation guide) for specific integration scenarios, and then serialize each into desired implementation-specific languages.

**Comment by dubnemo** [comment]
@kbserm @hakjuoh excellent.  Thanks.

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis Updated.

<img width="731" alt="Screen Shot 2020-04-28 at 6 35 21 PM" src="https://user-images.githubusercontent.com/16102116/80544430-0c64b580-897f-11ea-852d-46d4bb7ce287.png">

**Comment by asdimitriadis** [comment]
The about page is tested.
