### ISSUE TITLE
Update homepage of the tool

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#766]
Michael Figura will give an idea.

**Comment by dubnemo** [comment]
It would be great to have a summary of 
BIEs
now:
1) number of BIEs in each status, 
2) # BIEs by owner, 
3) recently worked on (favorites), 
future
4) hours spent on each (ha!), and,

Extensions:
now:
5) number of extensions created
6) number extensions created but not enabled (for various reasons)
future:
7) number of extensions submitted to OAGi
8) number of extensions disapproved/approved by OAGi

**Comment by dubnemo** [comment]
Perhaps barcharts...

**Comment by kbserm** [comment]
Core component area.
Have to be able to select the release.
Number of Published ACC, ASCCP, BCCP, Code List, DTs,

For the extension section, it should list the number by state. At this time this will count and display only the User Extension Group ACC.

**Comment by michaelfigura** [comment]
Updated Requirements:
BIEs by State
1. As a Score user I want to view a color-coded progress bar of the number of my current BIEs in 3 different states so that I have a better understanding of the various BIEs being developed by me.
2. As a Score user I want to view a paginated, color-coded progress bar of the number of all current BIEs by owner in 3 different states so that I have a better understanding of the various BIEs being developed by everyone.

**Comment by kbserm** [comment]
For the extension dashboard 
- The number of (UEGACC) extensions by state across the database
- The number of (UEGACC) extensions that has one or more child BIE enabled. If possible, provide the list of the UEGACCs on click and/or the list of top-level BIEs that has such extensions.

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis 

<img width="1194" alt="Screen Shot 2020-04-23 at 1 15 58 AM" src="https://user-images.githubusercontent.com/16102116/80061853-51609600-8500-11ea-877a-b2b946104093.png">

<img width="1154" alt="Screen Shot 2020-04-23 at 1 16 06 AM" src="https://user-images.githubusercontent.com/16102116/80061866-57ef0d80-8500-11ea-816d-f4899e2081f0.png">

**Comment by kbserm** [comment]
The label "Number of BIEs by States" should be changed to "Total BIEs by state". So the bar on the bottom is not a progress bar. You cannot find a progress bar component? There should be another similar graph with label "My BIEs by state". Then, there should be a pagination table that looks like this

![image](https://user-images.githubusercontent.com/7863166/80100093-73c4d480-853d-11ea-887f-fa8090b79fbf.png)

The table may have filter by user name.

"BIEs recently worked on" => "My recent BIEs"

We don't need that circle chart.

Similarly, "Number of User Extension by states" => "Total extensions by states". Then "My extensions by states", and then a similar table.
 
The "User Extensions used in BIEs" => "My extensions used in BIEs".

**Comment by hakjuoh** [comment]
@kbserm @dubnemo @michaelfigura Please review the following mockup.

![Score_Dashboard](https://user-images.githubusercontent.com/16102116/80130220-3fb1d980-8566-11ea-9bf3-fc2a9c7c86b4.png)

**Comment by hakjuoh** [comment]
> Are these User-defined CCs (Core Components)? ...wondering if the "Type" of extension should be noted here.

Yea, it's great catch. I also wonder what 'User extension' means in the dashboard. Since this release has no creating brand new User-defined CCs, it only has user extension groups which is (a kind of) a container generated by a system and its child associations appended by a user.

Anyway, those number are *NOT* user-defined CCs. It's a number of how many original extensions has been tried to expand by users.

**Comment by dubnemo** [comment]
@kbserm  I tend to like the visual controls @hakjuoh selected already. 

I prefer MY recent work on top.

How long does it take to load the page?  Do we have tab controls?
My Work - All Work being -- then a smaller number of queries would be executed.

User Extensions coming soon...

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis Displayed each content using Tab.

<img width="834" alt="Screen Shot 2020-04-27 at 3 31 59 AM" src="https://user-images.githubusercontent.com/16102116/80345804-b76a5780-8837-11ea-9cb5-d2edaa15bdd2.png">
<img width="831" alt="Screen Shot 2020-04-27 at 3 32 06 AM" src="https://user-images.githubusercontent.com/16102116/80345809-b9341b00-8837-11ea-884a-fd56ed5ccae9.png">

One last question is that what content would be good to show the `progress-bar` or `table` if there is no records.

**Comment by hakjuoh** [comment]
> **How long does it take to load the page?** Do we have tab controls?

@dubnemo Not too long, less than 1 second on my local.

**Comment by kbserm** [comment]
For no record, how about show a blank bar with the word None.

**Comment by dubnemo** [comment]
I like this approach .  Is this good enough for this specific issue?
@kbserm @hakjuoh ?

**Comment by kbserm** [comment]
Yes. I think we should be able to close this soon. One thing to change is the label from "My extensions but unused in BIEs" to "My unused extensions in BIEs". @hakju are the columns in tables sortable?

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis Apply changes what we talked today's call.
1. Sortable headers
2. `User` filter
3. `None` bar in case of no records on `progress bar`

<img width="1144" alt="Screen Shot 2020-04-27 at 11 26 58 PM" src="https://user-images.githubusercontent.com/16102116/80444042-a294cf00-88de-11ea-81cf-77d2dd6b140d.png">

**Comment by asdimitriadis** [comment]
Tested and it works.
