### ISSUE TITLE
Unsaved changes are disappeared when check Hide unused box.

### ISSUE THREAD

**Issue by rekuku** [OAGi/Score#767]
Unsaved changes are disappear when toggle hide unused button.

**Comment by kbserm** [comment]
When the user toggle Hide Unused, the client side also sends the update request.

**Comment by kbserm** [comment]
This has been done a while back. Sakis will check/update the user guide about this.

**Comment by asdimitriadis** [comment]
The User Guide has been updated, the Hide/Unhide already exists in 1.4.0 and it was tested
