### ISSUE TITLE
Changes are loss if Hide Unuse is clicked b/f clicking Update 

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#768]
when I check some nodes in the BIE tree, if I click Hide Unused b/f saving  changes first the changes disappear.

@hakjuoh said he would change the client to issue update request when the Hide Unuse checkbox is clicked.

**Comment by hakjuoh** [comment]
@asdimitriadis You could check this using `release/v1.4.0` branch.

**Comment by asdimitriadis** [comment]
Tested. It works.
When the user clicks the "Hide unused" checkbox the BIE is automatically updated and so the changes are not lost.
