### ISSUE TITLE
Move the Hide Unused check box to the area where it doesn't move with the tree

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#769]

**Comment by hakjuoh** [comment]
@kbserm Now the menu contains 'Hide unused' checkbox is separated with the tree as the following image:

<img width="755" alt="Screen Shot 2020-04-03 at 1 30 19 AM" src="https://user-images.githubusercontent.com/16102116/78327398-c9afe900-754a-11ea-8767-1241c27bb71d.png">

**Comment by asdimitriadis** [comment]
Tested. This button works.
