### ISSUE TITLE
Blocking cookie 'SameSite=None' without 'Secure' in Chrome 80

### ISSUE THREAD

**Issue by hakjuoh** [OAGi/Score#771]
All requests are blocked in Chrome 80.0.3987.132 if the cookie has 'SameSite=None' property value, but without 'Secure'.

**Comment by hakjuoh** [comment]
@asdimitriadis Now Score stores user info in Local Storages instead of Cookies.

**Comment by asdimitriadis** [comment]
Tested using Chrome Version 80.0.3987.132 (Official Build) (64-bit).
No warning message is returned. Score works.
