### ISSUE TITLE
Implement exact search with double quote

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#774]
Hakju and Sakis will exchange the locations where they think this should impact.

**Comment by kbserm** [comment]
@asdimitriadis will update the user guide as well.

**Comment by hakjuoh** [comment]
@asdimitriadis Here's a list of fields that this issue will apply.

 - BIE
	- Property Term

- Code List
	- Name

- Context Category
	- Name
	- Description

- Context Scheme
	- Name

- Business Context
	- Name
	
- Core Component
	- DEN
	- Definition
	- Module

**Comment by asdimitriadis** [comment]
Underscore issue:
Could we include the underscore (_) in search fields as well?
Underscore is used in Code Lists and now if our keyword includes underscore then no result is returned.
To reproduce the issue.
1. Visit the Code List Page (Code List -> View/Edit Code List)
2. Enter the keyword oacl_UnitCode in the Name Field.
3. Click search button.

No code list is return.

=========================

Module search field issue:

The module search field does not work properly. This field is located in the 
-CC List page (Core Component -> View CC)
- Create BIE Page (the one in which we can select the top-level concept)
-append an ASCCP dialog
-append a BCCP dialog


In particular, if we give a part of a module path (e.g. ChangeAcknowledgeProductionOrder) nothing is returned. However, if we give the full path (e.g. Model\BODs\ChangeAcknowledgeProductionOrder) it works.

Note that if we use "ChangeAcknowledgeProductionOrde" (with double quotes - exact search) then it works.

**Comment by asdimitriadis** [comment]
Now, the DEN Field of the second page used to create BIE, namely "Create BIE: Select Top-Level Concept" does not work if I use spaces.
To reproduce the issue, use the term "ASN Reference". No results are displayed.

**Comment by kbserm** [comment]
the issue with the code list that @asdimitriadis mentioned would be an issue.

the behaviour of the module is OK at this point.

**Comment by asdimitriadis** [comment]
All the forenamed issues have been addressed. 
Tested.
