### ISSUE TITLE
Developer Code List Management

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#781]
This issue is created as the 5th stepping stone for issue #658 .

This issue covers editing, revising, and state management of Code List.

**Comment by kbserm** [comment]
I logged in as a developer, selected a release branch and still able to create a code list in that branch. This shouldn't be allowed.

**Comment by hakjuoh** [comment]
> I logged in as a developer, selected a release branch and still able to create a code list in that branch. This shouldn't be allowed.

Now the button would disappear in that case.
