### ISSUE TITLE
OAS Expression - remove GUID from generated path

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#782]
The BIE GUID is not appropriate as a path may have 1:m references to a schema object for different operations (GET, POST, DELETE, PUT, PATCH):

paths:
  /location/**oagis-id-0389f5287c9047debef204d69af52f4c:**
    summary: ""
    description: ""

Should be:
paths:
  /location
    summary: ""
    description: ""

**Comment by hakjuoh** [comment]
@kbserm The user can select multiple BIEs to generate schemas and there's no way to distinguish between the same name of BIEs.

**Comment by dubnemo** [comment]
@hakjuoh 
The guid is in the $ref to the schema object, so it is not needed in the path.  
There can be multiple schema objects per path, so it's currently invalid. 
A GET will have a response schema object while a POST could/will have a different schema object.

**Comment by kbserm** [comment]
@dubnemo maybe what @hakjuoh worried is, if the user select multiple BIEs of the same name, it will be difficult to differentiate which one is what. Might it be better to have that GUID there which is deleted by the user at a later stage?

**Comment by dubnemo** [comment]
We have to distinguish current state and future state.  The GUID absolutely makes no sense for path with multiple BIE profiles; e.g., POST, PATCH, GET.  In the future I will be able to reference different profiles before different operations under the same path as shown in the BPMN.  Currently I am manually removing the GUID under path as I do not want that in my publicly facing endpoint.

Plus the GUID is already in the **scheme/$ref** so its redundant (see below).  

paths:
  /batchCertificateOfAnalysis/oagis-id-**8db2fa815bf74427a75644696810ec97**:
    summary: ""
    description: ""
    post:
      summary: ""
      description: ""
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/post-batchCertificateOfAnalysis-oagis-id-**8db2fa815bf74427a75644696810ec97**"
      responses:
        "200":
          description: ""
          content:
            application/json: {}

**Comment by hakjuoh** [comment]
@dubnemo It would be great if you review this issue through [biopharma](http://biopharma.oagiscore.net/) instance that just deployed.

**Comment by dubnemo** [comment]
@hakjuoh perfect!  Thank you!
@kbserm
