### ISSUE TITLE
Item selection issue which may effect several pages

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#783]
The name of the BIE is appearing in the filename for a noun, but its not appearing for a component.

![image](https://user-images.githubusercontent.com/32434235/76530055-27b44980-6441-11ea-9c44-c14495ac1742.png)

The highlighted yml file was generated off biopharma.oagiscore.net, using Location BIE.

**Comment by hakjuoh** [comment]
@dubnemo It probably happened if you chose multiple BIEs for schemas. In this case, the filename would be randomly generated ID like that. The filename of a single BIE selection case is containing ABIE ID as a suffix and there was no such record with `oagis-id-05ba6907b1e041b3a964615bc261690` in DB.

**Comment by dubnemo** [comment]
@hakjuoh @kbserm 
You are right, there are multiple BIEs in the yml. (Location and WIPStatus)
HOWEVER, when I deselected both Location and WIPStatus BIEs, and hit generate button again (none selected), a new yml was created with both Location and WIPStatus in it.

It appears if I stay on the Express page, and try multiple expressions in sequence deselecting one of the BIE, its as if the checkbox was still enabled in memory.

Moving off the page to Edit, and going back it works.

**Comment by dubnemo** [comment]
Test: 1) select Location on Page 2, Express -- should be OK, 2) navigate to WIPStatus Page 3, select, should have oagis prefix, 3) deselect WIPStatus, navigate to Location, it no longer shows selected but **button is still enabled**.

**Comment by asdimitriadis** [comment]
Testes and it works.
