### ISSUE TITLE
When typeCode, unitCode or other qualifier is selected, "example" keyword should be on content for OAS 3.0.2

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#785]
Since there is not way to place Example on 'content' in the UI, and the example must be place under content during the expression.
![image](https://user-images.githubusercontent.com/32434235/76685108-215bd400-65df-11ea-91d1-3b29d66b74e2.png)

Generated, should be under content property:

                                      items:
                                        **example: "12.409"**
                                        type: "object"
                                        required:
                                        - "content"
                                        - "nameName"
                                        additionalProperties: false
                                        properties:
                                          content:
                                            $ref: "#/components/schemas/float"
                                          nameName:
                                            allOf:
                                            - $ref: "#/components/schemas/string"
                                            - description: "Name of the Test Result"
                                          typeCode:
                                            $ref: "#/components/schemas/token"
                                          unitCode:
                                            $ref: "#/components/schemas/token"

**Comment by dubnemo** [comment]
Should be (snip):

                                    resultValue:
                                      description: "Array of measure values of a given\
                                        \ properties for a specified test method/\
                                        \ procedure"
                                      type: "array"
                                      items:
                                        
                                        type: "object"
                                        required:
                                        - "content"
                                        - "nameName"
                                        additionalProperties: false
                                        properties:
                                          content:
                                            allOf:
                                            - $ref: "#/components/schemas/float"
                                            - example: "12.409"
                                          nameName:
                                            allOf:
                                            - $ref: "#/components/schemas/string"
                                            - description: "Name of the Test Result"
                                              example: "TestName"
                                          typeCode:
                                            $ref: "#/components/schemas/token"
                                          unitCode:
                                            allOf:
                                            - $ref: "#/components/schemas/token"
                                            - example: "PPM"

**Comment by hakjuoh** [comment]
@kbserm This came from a decision what we made through [Fix JSON schema and OAS schema object serialization](https://github.com/OAGi/Score/issues/753) issue. We also may need to move a position of `description` property under the content like
```
resultValue:
  type: "array"
  items:    
    type: "object"
    required:
    - "content"
    - "nameName"
    additionalProperties: false
    properties:
      content:
        allOf:
        - $ref: "#/components/schemas/float"
        - description: "Array of measure values of a given\
                \ properties for a specified test method/\
                \ procedure"
          example: "12.409"
      nameName:
        allOf:
        - $ref: "#/components/schemas/string"
        - description: "Name of the Test Result"
          example: "TestName"
      typeCode:
        $ref: "#/components/schemas/token"
      unitCode:
        allOf:
        - $ref: "#/components/schemas/token"
        - example: "PPM"
```

**Comment by kbserm** [comment]
@hakjuoh All you need to do is move the "example" keyword to "content" when there is a need for it. Leave description at the same place. Note that this applies to both array and singular cases. It should look like this.

    "resultValue" : {
                                        "description" : "Array of measure values of a given properties for a specified test method/ procedure",
                                        "type" : "array",
                                        "items" : {
                                          "type" : "object",
                                          "required" : [ "content", "nameName" ],
                                          "additionalProperties" : false,
                                          "properties" : {
                                            "content" : {
                                              "allOf" : [ {
												  "$ref" : "#/components/schemas/float",
												}, {
													"example" : "18.0"
													}
												]
                                            },
                                            "nameName" : {
                                              "$ref" : "#/components/schemas/string"
                                            },
                                            "typeCode" : {
                                              "$ref" : "#/components/schemas/token"
                                            },
                                            "unitCode" : {
                                              "$ref" : "#/components/schemas/token"
                                            }
                                          }
                                        }
                                      },

**Comment by hakjuoh** [comment]
> @hakjuoh All you need to do is move the "example" keyword to "content" when there is a need for it. Leave description at the same place. Note that this applies to both array and singular cases. It should look like this.
> 
> ```
> "resultValue" : {
>                                     "description" : "Array of measure values of a given properties for a specified test method/ procedure",
>                                     "type" : "array",
>                                     "items" : {
>                                       "type" : "object",
>                                       "required" : [ "content", "nameName" ],
>                                       "additionalProperties" : false,
>                                       "properties" : {
>                                         "content" : {
>                                           "allOf" : [ {
> 											  "$ref" : "#/components/schemas/float",
> 											}, {
> 												"example" : "18.0"
> 												}
> 											]
>                                         },
>                                         "nameName" : {
>                                           "$ref" : "#/components/schemas/string"
>                                         },
>                                         "typeCode" : {
>                                           "$ref" : "#/components/schemas/token"
>                                         },
>                                         "unitCode" : {
>                                           "$ref" : "#/components/schemas/token"
>                                         }
>                                       }
>                                     }
>                                   },
> ```

Don't forget `enum` and `default` properties :)

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis `content` might be wrapped by `oneOf` property if it's nillable as below.
```
"content" : {
  "oneOf" : [ {
    "type" : "null"
  }, {
    "allOf" : [ {
      "$ref" : "#/definitions/float"
    }, {
      "default" : "12.409",
      "examples" : [ "12.409" ]
    } ]
  } ]
},
```

**Comment by asdimitriadis** [comment]
Tested,

**Comment by asdimitriadis** [comment]
Tested again after the commit f416da0520c887f686a059b3d3ca9e513b9b43ed at the gateway.
It works.

**Comment by hakjuoh** [comment]
@dubnemo This change is applied on [biopharma](http://biopharma.oagiscore.net/) instance now, so @asdimitriadis will be able to close this issue after your confirm.

**Comment by dubnemo** [comment]
@hakjuoh GREAT!  I will take a look.  You just made my day!
@kbserm
