### ISSUE TITLE
Deprecate is_nillable column of the BCC table.

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#786]
Add a comment to the is_nillable column that it is deprecated. This was a mistake. XML schema only support nillable in the xsd:element and hence BCCP definition. So we shouldn't expose this column on the UI.

**Comment by kbserm** [comment]
Add comment to the column "This column is deprecated because nillable association (element reference) is not possible in XML schema. However, there may be a good reason to use this column again in the future."

**Comment by hakjuoh** [comment]
@asdimitriadis Now there is no `nillable` checkbox on UI and cannot access `is_nillable` property by APIs.
