### ISSUE TITLE
It seems like there is a supplementary component not correctly expressed.

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#791]
This occurs at least in the schema Object of the Open API. 

This has to do with the 'name' supplementary component. An example of this can be found in the ResultValue component. It was generated as "nameName", should be truncated with only "name".

**Comment by hakjuoh** [comment]
@kbserm That supplementary component has a same property value, `Name` for both `Property Term` and `Representation Term`. It sounds like we are going to add a sort of a conditional logic that the representation term will be ignored if its value is duplicated with the value of the property term. Correct?

**Comment by kbserm** [comment]
Yes

**Comment by kbserm** [comment]
This rule is already in place for the BCCP, isn't it? Need to be applied to SC too.

**Comment by kbserm** [comment]
@hakjuoh I'm taking it back....let me investigate further.

**Comment by kbserm** [comment]
We actually have already implemented the truncation rule in the XML schema serialization correctly, i.e., we don't serialize to nameName but just name. The catch is that there is an exception that we hardcoded for the BDTs that are derived from the BinaryObjectType b/c OAGIS happened to have filenameName which is inconsistent with others SCs with Name Representation term.

Truncation rules must have already been applied already also in JSON Schema and Open API serializations otherwise, we would have ended up with a number of duplicate tokens in property names. We seems to miss the truncation rule for when Name representation term, this maybe because we forgot that filenameName is just an exception that we had to hard code.

**Comment by hakjuoh** [comment]
@kbserm Here's the rules XML schema generation uses.

If `Representation Term` is `**Text**`, it only uses `Property Term`
Else if `name` is `preferredIndicator`, it would be `preferred` <- This should be removed because `preferred` SC is fixed since OAGIS 10.3.
Else if `Property Term` == `Representation Term`, it only uses `Property Term`
Else if `Representation Term` is `**Identifier**`, it would be `ID`.

Please review it again.

**Comment by kbserm** [comment]
So we figured out that the truncation should be done only at the token level. Since 'name' in 'filename' is not a separate token, it is not truncated. In other words, because the SC's property term is "Filename", the 'Name' representation term is not truncated. OTOH, if the SC's property term were 'File Name', the 'Name' representation would be truncated. The logic below should work (it should work for when PT = "Preferred Indicator" & RT ="Indicator" as this is the same case when PT = "File Name").

If RT is "Text" then RT ="";
else if RT = "Identifier" then RT = "ID" 
else {
  RT = " "+RT;
  if [PT ends with RT] then RT="";
}
attribute_name = lower-camel-case(PT + RT)

**Comment by hakjuoh** [comment]
@asdimitriadis Review this issue.

**Comment by asdimitriadis** [comment]
Tested and it works.

**Comment by hakjuoh** [comment]
@asdimitriadis @kbserm  I missed a rule to the camel-case that abbreviated words won’t be applied in XML while it will in JSON. For example, ‘List Agency Identifier’ would be ‘listAgencyID’ in XML, but ‘listAgencyId’ in JSON. Please let me know if you have any concern about this.

**Comment by kbserm** [comment]
@hakjuoh @asdimitriadis It is supposed to be 'listAgencyIdentifier' in JSON. The current version oagiscore.org is still generated like that.

@asdimitriadis Please generate schemas from the two version and compare to make sure that only expected differences exist.

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis Please take a look at all cases for both XML and JSON as below.

| Property Term | Representation Term | > | XML | JSON |
| -------------- | --------------------- | --- | ----- | ----- |
| Currency | Code |   | currencyCode | currencyCode |
| MIME | Code |   | mimeCode | mimeCode |
| Character Set | Code |   | characterSetCode | characterSetCode |
| Filename | Name |   | filenameName | filenameName |
| List | Identifier |   | listID | listIdentifier |
| List Agency | Identifier |   | listAgencyID | listAgencyIdentifier |
| List Version | Identifier |   | listVersionID | listVersionIdentifier |
| Time Zone | Code |   | timeZoneCode | timeZoneCode |
| Daylight Saving | Indicator |   | daylightSavingIndicator | daylightSavingIndicator |
| Scheme | Identifier |   | schemeID | schemeIdentifier |
| Scheme Version | Identifier |   | schemeVersionID | schemeVersionIdentifier |
| Scheme Agency | Identifier |   | schemeAgencyID | schemeAgencyIdentifier |
| Unit | Code |   | unitCode | unitCode |
| Language | Code |   | languageCode | languageCode |
| Multiplier | Value |   | multiplierValue | multiplierValue |
| Base Multiplier | Value |   | baseMultiplierValue | baseMultiplierValue |
| Base Unit | Code |   | baseUnitCode | baseUnitCode |
| Base Currency | Code |   | baseCurrencyCode | baseCurrencyCode |
| Format | Text |   | format | format |
| Encoding | Code |   | encodingCode | encodingCode |
| URI | Text |   | uri | uri |
| List Agency | Name |   | listAgencyName | listAgencyName |
| List | Name |   | listName | listName |
| Name | Text |   | name | name |
| Language | Identifier |   | languageID | languageIdentifier |
| List URI | Text |   | listURI | listUri |
| List Scheme URI | Text |   | listSchemeURI | listSchemeUri |
| Format | Code |   | formatCode | formatCode |
| Scheme | Name |   | schemeName | schemeName |
| Scheme Agency | Name |   | schemeAgencyName | schemeAgencyName |
| Scheme Data URI | Text |   | schemeDataURI | schemeDataUri |
| Scheme URI | Text |   | schemeURI | schemeUri |
| Sequence | Number |   | sequenceNumber | sequenceNumber |
| Expression Language | Text |   | expressionLanguage | expressionLanguage |
| Action | Code |   | actionCode | actionCode |
| Type | Code |   | typeCode | typeCode |
| Country | Code |   | countryCode | countryCode |
| Sequence Number | Number |   | sequenceNumber | sequenceNumber |
| Name | Name |   | name | name |
| Author | Text |   | author | author |
| Entry Date Time | Date Time |   | entryDateTime | entryDateTime |
| Status | Text |   | status | status |
| Unit Code List Version | Identifier |   | unitCodeListVersionID | unitCodeListVersionIdentifier |
| Preferred Indicator | Indicator |   | preferredIndicator | preferredIndicator |
| Type | Text |   | type | type |
| Code | Code |   | code | code |
| Interval | Text |   | interval | interval |
| Minimum | Text |   | minimum | minimum |
| Maximum | Text |   | maximum | maximum |
| Number Format | Value |   | numberFormatValue | numberFormatValue |
| Access | Code |   | accessCode | accessCode |
| Area | Code |   | areaCode | areaCode |
| Exchange | Value |   | exchangeValue | exchangeValue |
| Extension | Value |   | extensionValue | extensionValue |

**Comment by dubnemo** [comment]
@hakjuoh @kbserm @asdimitriadis 
These look good to me.  Everyone agree?

**Comment by asdimitriadis** [comment]
Tested and it works. 
If everyone agrees with the above-mentioned table, we can close this issue.

**Comment by kbserm** [comment]
The table looks fine.
