### ISSUE TITLE
We cannot edit a code list value if we do not change the Code field

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#795]
The issue is that if we want to edit a code list value, we should change the "Code" field of the value.
The expected behavior is that we can edit a code list value without having to edit the "Code" field. For instance, we can change only the Definition field.

Also, please change the "Edit" button of the dialog used to edit a code list value to "Save".

**Comment by kbserm** [comment]
@hakjuoh just try updating the detail of a code value w/o changing the code value itself. it doesn't work. the system thinks that the user tries to enter a duplicate code value and error out.

**Comment by hakjuoh** [comment]
@asdimitriadis You mean this should be able to edit for 'definition' (probably 'definition source' too) even if it's derived?

**Comment by asdimitriadis** [comment]
In other words, we cannot edit/update a code list value that we have added if we do not change the "Code" field/property of the value.
To reproduce the issue,
1. Create a code list 
2. Create a code list value and add it.
3. Open it again by clicking on its name
3. Edit/change the "Definition" field of value and click on the "Edit" button.

A message is returned saying that the code list value already exists.

**Comment by asdimitriadis** [comment]
The issue is partially fixed. 
To reproduce the issue, 
1. Open a Code List that can be extended.
2. "Click Derive Code List based on this" button.
3. Add a new value.
4. Open this new value in order to edit it.
5. Change its Description.
6. Try to save it by clicking the "Save" button. 

The value cannot be changed and the message "the value exist" is returned.

So we cannot edit a value when we are creating a new Code List based on another. 
However, we can edit values of the Code Lists that already exist/stored in the database.

**Comment by asdimitriadis** [comment]
Tested, it works.
