### ISSUE TITLE
We cannot restrict a value when we create a code list with base creation

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#796]
The issue is that when we choose to create a code list based another (Derive Code List), we cannot restrict the values of the base code list. 
The issue is related to issue #795

**Comment by hakjuoh** [comment]
@asdimitriadis Please explain more details about this issue and #795.

**Comment by kbserm** [comment]
Similar to #795, try to uncheck the Used box in the code value detail dialog. The system thinks the user try to add a duplicate code value.

**Comment by hakjuoh** [comment]
@asdimitriadis You can check this using `release/v1.4.0` branch.

**Comment by asdimitriadis** [comment]
The issue is partially fixed. 
To reproduce the issue, 
1. Open a Code List that can be extended.
2. "Click Derive Code List based on this" button.
3. Try to restrict a value.

The value cannot be extended and the message "the value exist" is returned.

So restriction does not work when we are creating a new Code List based on another. 
However, restriction works good in the Code Lists that already exist in the database.

**Comment by asdimitriadis** [comment]
Tested.
