### ISSUE TITLE
Change the label on disk icon to 'Save'

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#797]
Replace 'Edit' with 'Save' on this icon.

![image](https://user-images.githubusercontent.com/7863166/78583131-651fb300-7804-11ea-9236-a0e58e5d8c2d.png)

**Comment by asdimitriadis** [comment]
Fixed and Tested.

**Comment by asdimitriadis** [comment]
This is fixed in Code List.

Can we change the name of button (from Edit to Save) in the Context Scheme and Business Context values as well?

**Comment by hakjuoh** [comment]
@asdimitriadis It applied.

**Comment by asdimitriadis** [comment]
Fixed. Tested.
