### ISSUE TITLE
Confirmation dialog for all deletion operations

### ISSUE THREAD

**Issue by hakjuoh** [OAGi/Score#798]

**Comment by kbserm** [comment]
Check
- code list
- context scheme
- business context
- End user core component editing

**Comment by asdimitriadis** [comment]
In score 1.3.1.2 we should add this confirmation dialog when we delete:

1. A code list value. 
2. A context scheme value.
3. A business context value.

**Comment by hakjuoh** [comment]
@asdimitriadis Now, all confirmation dialog looks as below:

<img width="472" alt="Screen Shot 2020-04-21 at 8 20 51 AM" src="https://user-images.githubusercontent.com/16102116/79865366-08e29480-83a9-11ea-81c6-233dfc3aa43f.png">

**Comment by asdimitriadis** [comment]
Please add this confirmation dialog when we delete:

A code list value during a Code List creation (Create and Derive a Code List).
A context scheme value during a Context Scheme creation.
A business context value during a Business Context creation.

**Comment by hakjuoh** [comment]
> Please add this confirmation dialog when we delete:
> 
> A code list value during a Code List creation (Create and Derive a Code List).
> A context scheme value during a Context Scheme creation.
> A business context value during a Business Context creation.

@asdimitriadis Done.

**Comment by asdimitriadis** [comment]
Tested.
