### ISSUE TITLE
Update codes related to end user CC management

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#799]
This issue is created as a stepping stone for issue #658 .

**Comment by kbserm** [comment]
@dubnemo The end user CC (EUCC) management becomes very complex (as expected). Do you think it is reasonable to put a restriction that once EUCC is in Production state, it can no longer be amended? What this means is if you create a Distribution EUCC  
 within a release and perhaps a few other EUCCs used by the Distribution EUCC; once these are in Production state (which is when you can make BIEs out of them), and you want to make change (within the same release), you will have to create different copies of these EUCCs. Perhaps you would have to use unorthofox name like Distribution1.

If you already upgrade to a newer release, then you can use the same name again. 

It would great if you could think about this and we could discuss again on Thu.

**Comment by kbserm** [comment]
@hakjuoh Another approach is we could impose a simpler restriction, every time a BIE node is expended by the user, the system has to check whether the base CC is in a state other than Production (or Published). If not, the system respond that the BIE cannot be expanded because the underlying CC is not in the appropriate state. In this way, even if there is already existing BIE corresponding to that CC, there is no harm - as eventually the change has to be backwardly compatible with exist BIE data.

**Comment by dubnemo** [comment]
@kbserm @hakjuoh 
Can you provide a link to the Google document for EUCC?  This seems to indicate the name must be unique, and copy cannot have the same name.  Is that true?  Or am I misreading?  
If names don't have to be unique, I don't mind copies of production BIEs with the same name if I can see a remark to know the difference.

The whole concept of EUCC - at least for my uses - were _temporary_ CCs until I was able to submit the EUCC into the next OAGIS release.  As/if OAGIS releases move to a CI/CD build process (i.e., pull requests every two weeks), these concerns become non-issues; I would be able to extend and submit those extensions as a pull request in the next build.

Perhaps I am not understanding the concern.

**Comment by kbserm** [comment]
@dubnemo Yes, the EUCC will be important if OAGIS still don't have CI/CD or even if there is the company does not want to participate in CI/CD. E.g., Oracle E-Biz stuck with OAGIS 7.0 for a long long time. I could imagine companies like LM don't participate in CI/CD with OAGi either.

Now back to the specific question. Generally, Score can allow EUCC to be copied with the same name. Same name is fine when the EUCC is only to be used as top-level, but not when it is to be used in the Extension. Taking for example, if you add Distribution to Shipment Request Header Extension (as part of the Shipment Request top-level BIE). Even if you copy the Shipment Request top-level BIE, the new copy will still have Distribution in its Shipment Request Header Extension. So if you copy the Distribution EUCC into the same name because you want to make some changes to it, you can no longer add that new Distribution EUCC to the Shipment Request Header Extension because CC logic won't allow ASCCP with the same property term added to the (Shipment Request Header Extension) ACC. Or we have to relax this rule for EUCC. Or you would have to have a dubious name like Distribution1 as I mentioned earlier, which I thought should be ok b/c it is just a temporary CCs (but again this could be true only for org that participate in CI/CD).

You can read about EUCC in Test Suite 15 in the attached test case doc (note open Navigation Pane in MS Word to jump to Test Suite 15).
[Acceptance Test Cases 2.0 v1.docx](https://github.com/OAGi/Score/files/4968926/Acceptance.Test.Cases.2.0.v1.docx)

**Comment by kbserm** [comment]
@rekuku Please disable the Extension component type from the EUCC. End User CC should not contain any extension anymore.

**Comment by kbserm** [comment]
@rekuku Also we should not allow EUACC to have an association to any ASCCP that is a role of ACC that is an Extension component Type. 

We will need to also prevent the end user from creating an ASCCP that is a role of an ACC that is an Extension component type.

**Comment by rekuku** [comment]
@kbserm Oaky, I will put blocking logics to  EUACC,
But, what if sub-nodes contain extensions?
Should we check all-children dose not have the Extension acc?
Here is the example of biopharma.
<img width="1426" alt="Screen Shot 2020-08-12 at 7 37 27 PM" src="https://user-images.githubusercontent.com/10194354/90079902-35fbdf80-dcd7-11ea-8c65-c2ed0f73eff9.png">

**Comment by kbserm** [comment]
@rekuku Great  point. Thanks. We cannot block developer CCs that have extensions from being used in the EUACC. The BIE logic must block the end user from create Local/Global Extension within the Extension. I'm not sure if that is already there?

**Comment by kbserm** [comment]
@rekuku Think of it again, I think it doesn't matter. We don't have to block the end user from invoking Local/Global Extension within the Extension.

**Comment by rekuku** [comment]
@kbserm  Got it, If we can not make EUACC of extension type,
there is no need to check if there is an extension when appending EUCC to Local/Global Extension.

**Comment by kbserm** [comment]
@rekuku I think you still need to check b/c the user might happen to select a developer extension to be added.
