### ISSUE TITLE
Release management

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#802]

**Comment by kbserm** [comment]
This occurred after creating a release draft.

![image](https://user-images.githubusercontent.com/7863166/89422799-c6e52080-d703-11ea-9541-e2b44dd21573.png)

**Comment by kbserm** [comment]
Not sure why the field name in the red box is called 'Namespace List'. Should be 'Release Namespace'.

![image](https://user-images.githubusercontent.com/7863166/95019127-a701a880-0631-11eb-8a6b-5e0a6b77ec5e.png)

**Comment by kbserm** [comment]
Also, should show the URI in the field as well.

**Comment by kbserm** [comment]
Create release draft was unsuccessful. It said that CC can only be modified by owner.

**Comment by asdimitriadis** [comment]
Tested and it works good.
