### ISSUE TITLE
make sure that developer cannot extend BIE

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#803]

**Comment by dubnemo** [comment]
@kbserm 
Are you suggesting that once User Defined Core Components capability is available, we can no longer create an extension?  Quite often I add **existing** BCCPs as an extension.

**Comment by kbserm** [comment]
@dubnemo No Scott. Only if the user is a Developer user, he cannot extends BIE. Otherwise, we will have to add a flag or rely on other information to indicate whether core components are standard or extension. We want to rely on user role. And it seems make sense that (standard) developer shouldn't create extensions.

**Comment by kbserm** [comment]
Also if developer published BIEs, e.g., as the Agricultural Standard and an end user needs to customize or extends it, the end user should copy that BIE to create its own variation.
