### ISSUE TITLE
Business Context column blank when selecting BIE to copy

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#807]
It is not clear which BIE need to copy.  Context would help...

![image](https://user-images.githubusercontent.com/32434235/79611873-266de080-80c1-11ea-9ceb-2351545d8e59.png)

**Comment by hakjuoh** [comment]
@asdimitriadis Now it looks same as the BIE list page.

<img width="1396" alt="Screen Shot 2020-04-19 at 7 18 40 PM" src="https://user-images.githubusercontent.com/16102116/79702405-ac7d5900-8272-11ea-8855-018f99e8ac8d.png">

**Comment by dubnemo** [comment]
That works.  I would prefer less real estate, but clearly you are re-using the grid layout.

**Comment by hakjuoh** [comment]
@dubnemo It needed wider space to express those contents. A simple solution is to reduce a font size. However, it may cause poor visibility. @kbserm What do you think? 
If I remember correctly, you’ve been having a trouble with occasional scrolling to look at the pagination box. I’ll think more about that either.

**Comment by dubnemo** [comment]
@hakjuoh @kbserm I am good here.  thanks.

**Comment by asdimitriadis** [comment]
Tested.
