### ISSUE TITLE
Default all *Date Time BCCPs to 'date time' primitive

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#808]
It is not clear why we have token as the primitive for these date time BCCPs.  Having them set to 'date time' ahead of time will ensure proper expression, especially in JSON Schema and Open API specification with format keyword.  
Currently, I have to manual select each of these BCCPs, and change the primitive to serialize properly.
This could be a SQL UPDATE statement to correct this.

![image](https://user-images.githubusercontent.com/32434235/79878319-ea819680-83b2-11ea-94c8-c1ad3c522ec3.png)

@kbserm @hakjuoh

**Comment by hakjuoh** [comment]
`Open Date Time` type has a multiple primitive types as a union member as below, and `token` used to a default type of that. This is probably going to be OAGIS issue. @kbserm

```xml
<xsd:complexType name="OpenDateTimeType" id="oagis-id-38a0fb8fb7514a29b0597837faf2518d">
    <xsd:simpleContent>
        <xsd:extension base="DateTimeType">
            <xsd:attribute name="typeCode" type="xsd:token" use="optional" id="oagis-id-543b69ea686e44f4a470a332e18b1d91"/>
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>
<xsd:simpleType name="DateTimeType" id="oagis-id-dd0c8f86b160428da3a82d2866a5b48d">
    <xsd:restriction base="DateTimeType_AD9DD9"/>
</xsd:simpleType>
<xsd:simpleType name="DateTimeType_AD9DD9" id="oagis-id-a5cfd20385314a63afc1ffcf6357a08b" final="union">
    <xsd:annotation>
        <xsd:documentation xml:lang="en">
            <ccts_UniqueID>AD9DD9</ccts_UniqueID>
            <ccts_VersionID>1.0</ccts_VersionID>
            <ccts_DictionaryEntryName>Date Time. Type</ccts_DictionaryEntryName>
            <ccts_Definition>A date time identifies a date and time of day to various common resolutions: year, month, day, hour, minute, second, and fraction of second</ccts_Definition>
            <ccts_DataTypeTermName>Date Time</ccts_DataTypeTermName>
        </xsd:documentation>
    </xsd:annotation>
    <xsd:union memberTypes="xbt_DateHourMinuteType xbt_DateHourType xbt_DateTimeType xbt_DayHourMinuteType xbt_DayHourType xbt_DayOfWeekHourMinuteType xbt_DayOfWeekHourType xbt_DayOfWeekTimeType xbt_DayOfYearHourMinuteType xbt_DayOfYearHourType xbt_DayOfYearTimeType xbt_DayTimeType xbt_MonthDayHourMinuteType xbt_MonthDayHourType xbt_MonthDayTimeType xbt_WeekDayHourMinuteType xbt_WeekDayHourType xbt_WeekDayTimeType xbt_YearDayHourMinuteType xbt_YearDayHourType xbt_YearDayTimeType xbt_YearWeekDayHourMinuteType xbt_YearWeekDayHourType xbt_YearWeekDayTimeType xbt_DateType xbt_DayOfWeekType xbt_DayOfYearType xbt_DayType xbt_MonthDayType xbt_WeekDayType xbt_YearDayType xbt_YearWeekDayType xbt_DateHourMinuteUTCType xbt_DateHourUTCType xbt_DateTimeUTCType xbt_DayHourMinuteUTCType xbt_DayHourUTCType xbt_DayOfWeekHourMinuteUTCType xbt_DayOfWeekHourUTCType xbt_DayOfWeekTimeUTCType xbt_DayOfYearHourMinuteUTCType xbt_DayOfYearHourUTCType xbt_DayOfYearTimeUTCType xbt_DayTimeUTCType xbt_MonthDayHourMinuteUTCType xbt_MonthDayHourUTCType xbt_MonthDayTimeUTCType xbt_WeekDayHourMinuteUTCType xbt_WeekDayHourUTCType xbt_WeekDayTimeUTCType xbt_YearDayHourMinuteUTCType xbt_YearDayHourUTCType xbt_YearDayTimeUTCType xbt_YearWeekDayHourMinuteUTCType xbt_YearWeekDayHourUTCType xbt_YearWeekDayTimeUTCType xbt_DateHourMinuteUTCOffsetType xbt_DateHourUTCOffsetType xbt_DateTimeUTCOffsetType xbt_DayHourMinuteUTCOffsetType xbt_DayHourUTCOffsetType xbt_DayOfWeekHourMinuteUTCOffsetType xbt_DayOfWeekHourUTCOffsetType xbt_DayOfWeekTimeUTCOffsetType xbt_DayOfYearHourMinuteUTCOffsetType xbt_DayOfYearHourUTCOffsetType xbt_DayOfYearTimeUTCOffsetType xbt_DayTimeUTCOffsetType xbt_MonthDayHourMinuteUTCOffsetType xbt_MonthDayHourUTCOffsetType xbt_MonthDayTimeUTCOffsetType xbt_WeekDayHourMinuteUTCOffsetType xbt_WeekDayHourUTCOffsetType xbt_WeekDayTimeUTCOffsetType xbt_YearDayHourMinuteUTCOffsetType xbt_YearDayHourUTCOffsetType xbt_YearDayTimeUTCOffsetType xbt_YearWeekDayHourMinuteUTCOffsetType xbt_YearWeekDayHourUTCOffsetType xbt_YearWeekDayTimeUTCOffsetType">
        <xsd:annotation>
            <xsd:documentation xml:lang="en">
                <ccts_ContentComponentValueDomain>
                    <ccts_Definition>The particular point in the progression of date</ccts_Definition>
                    <ccts_DefaultIndicator>True</ccts_DefaultIndicator>
                    <ccts_PrimitiveTypeName>TimePoint</ccts_PrimitiveTypeName>
                </ccts_ContentComponentValueDomain>
            </xsd:documentation>
        </xsd:annotation>
    </xsd:union>
</xsd:simpleType>
```

**Comment by dubnemo** [comment]
@hakjuoh @kbserm 
Yes, the ask is changing the default for the Open Date Time type.  
I am not suggesting changing the underlying list; i.e., memberTypes.

<xsd:complexType name="OpenDateTimeType" id="oagis-id-38a0fb8fb7514a29b0597837faf2518d">
    <xsd:simpleContent>
        <xsd:extension base="DateTimeType">
            <xsd:attribute name="typeCode" **type="xsd:token"** use="optional" id="oagis-id-543b69ea686e44f4a470a332e18b1d91"/>
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

**Comment by kbserm** [comment]
I think @dubnemo suggestion is to default this on the BIE side. This should be okay as there is no change to the CC side.

**Comment by kbserm** [comment]
@hakjuoh I guess the rule is if Data Type Term is Date Time, set the primitive to dateTime upon creation of the BBIE/BBIEP.

**Comment by hakjuoh** [comment]
> @hakjuoh I guess the rule is if Data Type Term is Date Time, set the primitive to dateTime upon creation of the BBIE/BBIEP.

There are also `OpenTimeType`whose `Data Type Term` is `Time`, and it has a same issue. Do you want to make those exceptions for this issue without modifying `bdt_pri_restri` records? That would be working like this

```c++
if (bccp->bdt.dataTypeTerm is `Date Time`)
   then defaultPrimitiveRestriction := xbt.dateTime;
else if (bccp->bdt.dataTypeTerm is `Time`) 
   then defaultPrimitiveRestriction := xbt.time;
else 
   defaultPrimitiveRestriction won't change;
```

**Comment by sfohn** [comment]
Just had a couple of questions, 1-under the "Primitive Restriction" section on the UI, there is the term "Based Data Type Name"...should this be "Core Data Type"?   2-It seems from the pull down list under "Primitives", different Business Data Types are offered (for the related Core Data Type)...therefore, is this really "CoreDataType Restriction" (aka "BusinessDataType" specification? ..in which case "token" would not appear in the pull down list.

**Comment by kbserm** [comment]
@hakjuoh the rules look good to me.

@sfohn @hakjuoh Lable "Based Data Type Name" should be simply "Business Data Type".

@sfohn In pull down under "Primitives Type" , we just generically offer the user the option to assign code list or agency id list for any field. I.e., an implementation may still want to restrict some fields whose data types are not code to a list of value, e.g., employee identifier.

**Comment by sfohn** [comment]
@kbserm ...not sure that I understand...as the Date Time. Type is a Core Data Type ... and the selection list presented are all restrictions on the Core Data Type, i.e. Business Data Types.

![Screen Shot](https://user-images.githubusercontent.com/5239917/79919907-4113c280-83fd-11ea-9271-cf84690c8e1a.png)

**Comment by hakjuoh** [comment]
@asdimitriadis You can test this issue as follows:

1. Create BIE with 'Purchase Order Header. Purchase Order Header'.
2. Expand the tree.
3. Click any BCCP whose representation term is `Date Time`.

Then a default primitive type must be `date time`.

<img width="1031" alt="Screen Shot 2020-04-21 at 10 22 46 PM" src="https://user-images.githubusercontent.com/16102116/79933673-b17f0b80-841e-11ea-8e71-89bc07878845.png">

It also must be tested for BCCPs whose representation term is `Date` or `Time`.

One thing you may have to know is that this rule also applied to BBIE SC, and there are only one BDT SC, 'Entry Date Time', under `Note` BBIE SC.

<img width="1152" alt="Screen Shot 2020-04-21 at 10 20 42 PM" src="https://user-images.githubusercontent.com/16102116/79934031-91038100-841f-11ea-90d9-2fffb4a3e319.png">

**Comment by sfohn** [comment]
@hakjuoh , @kbserm ...regarding use of the term "Primitive" in the UI...PrimitiveTypes are: Binary, Boolean, Decimal, String, etc. The values in the selection list are BusinessDataTypes.  It seems to me that we are dealing with CoreDataTypes and BusinessDataTypes...therefore, "DataType Restriction".

From the Data Type Catalogue...Business Data Types are used with BBIE properties. Business Data Types are derived from Core Data Types, and have the same structure as their parent CDT. A BDT can be without restrictions on its parent CDT, or it can further refine the CDT through semantic restrictions in the form of Data Type Term qualifiers and context driven value domain restrictions. Value domain restrictions are expressed as either restrictions to the allowed facets of the primitive, or modifications to the scheme or list. (UN/CEFACT Core Components Data Type Catalogue Version 3.1, p17)

**Comment by kbserm** [comment]
@sfohn I would say pretty much everything on the detail pane of the BBIE/BBIEP node in the BIE tree is about Value Domain restriction. For simplicity, we just group value domain restriction using different primitives and enumeration under the Primitive Restriction. These are just different ways to do Value Domain Restriction that the application currently supports. Not sure if I have answer your question. We can talk more on the call.

**Comment by hakjuoh** [comment]
#809 MUST be done with this.

**Comment by asdimitriadis** [comment]
Tested.
