### ISSUE TITLE
Add `xsd:date` mapping to any BDT whose CDT is `TimePoint`

### ISSUE THREAD

**Issue by hakjuoh** [OAGi/Score#809]
Although `TimePoint` CDT had to have a XML mapping with `xsd:date`, the current data in `1.3.0` didn't have it. Testing model using `schematron` which we have been used missed that to catch, because exported schema files didn't contain CDT primitive restrictions.

**Comment by kbserm** [comment]
1. Put the xsd:Date in the Date CDT in cdt_awd_pri_xps_type_map table.
2. find all the bdts that has Date data type term.
3 add the reference to #1 for the bdts in #2 in the bdt_pri_restri table.

**Comment by hakjuoh** [comment]
@kbserm 
I found a fact that `dateTime` has mappings to both `xsd:dateTime` and `xsd:time`. I guess it should be removed from DB if we want to keep consistency that `dateTime` mapped to only `xsd:dateTime`.

So I'll do the following after your rules:

4. Remove xsd:time in the Date Time CDT in cdt_awd_pri_xps_type_map table.
5. Remove also all bdt_pri_restri records which indicate to removed record.
6. Switch bdt_pri_restri_id in BBIE records to point from xsd:time to xsd:dateTime.

**Comment by hakjuoh** [comment]
@asdimitriadis You test this issue with #808 after executing `misc/mig_1.3.0_to_1.4.0.sql` file on your local 1.3.0 repository.

**Comment by kbserm** [comment]
We also found that Date Time CDT is also missing the xsd:date in the cdt_awd_pri_xps_type_map table. So we also need to find all BDTs that has Date Time data type term and add reference to them in the the bdt_pri_restri table for those BDTs.

**Comment by hakjuoh** [comment]
@asdimitriadis 

- `Date Time` CDT case
<img width="1042" alt="Screen Shot 2020-04-29 at 11 33 54 PM" src="https://user-images.githubusercontent.com/16102116/80670190-44015980-8a74-11ea-9706-ee0d072dbc8c.png">

- `Date` CDT case
<img width="974" alt="Screen Shot 2020-04-29 at 11 50 30 PM" src="https://user-images.githubusercontent.com/16102116/80670201-48c60d80-8a74-11ea-9349-e142f95e0d61.png">

**Comment by asdimitriadis** [comment]
Tested.
