### ISSUE TITLE
The name of the BIE List page is not displayed.

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#811]
When we visit the BIE List page (BIE -> View/Edit BIE) the name of the page is not displayed.
Instead it is displayed "BIE_LIST.TITLE"

**Comment by asdimitriadis** [comment]
The same issue happens in the following pages:
1. Create BIE
2. Copy BIE
3. Express BIE
4. View Core Components (

**Comment by hakjuoh** [comment]
@asdimitriadis Would you try disable cache on your browser?

**Comment by asdimitriadis** [comment]
It was a cache issue. 
So I am closing it.
