### ISSUE TITLE
Update the user guide

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#816]
The user guide needs to be updated to include:

1. Information about the home page of SCORE
2. The "Component Type" filter located in the Core Component Page under the section "How to Search and Filter for a Core Component".

**Comment by hakjuoh** [comment]
@kbserm I had to add 'Component Type' filter on CC List page to support redirecting from Dashboard for UEG.

**Comment by asdimitriadis** [comment]
The "Transfer Ownership" has to be also checked for changes.

**Comment by kbserm** [comment]
@hakjuoh you can hide it right?

**Comment by asdimitriadis** [comment]
The user guide was updated.
