### ISSUE TITLE
Highlight the node the user is on in the BIE tree

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#817]
Also put the the full path to the node on the top of the right pane that is not effected by scrolling.

If the path is longer than the width truncate the front so that the end of the path visible.

@dubnemo Do you agree with this?

**Comment by dubnemo** [comment]
@kbserm lets call this the breadcrumb trail/ path, as it is independent of syntax.

I would start the root very close to the Hide Unused button, as paths could be long.  If too long, similar to many document management systems such as Sharepoint, ellipses (...) may be required depending on character length of the full breadcrumb path.

**Comment by dubnemo** [comment]
https://www.smashingmagazine.com/2009/03/breadcrumbs-in-web-design-examples-and-best-practices/
