### ISSUE TITLE
Update BIE code to work with the new Core Component data scheme and logic

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#818]

**Comment by kbserm** [comment]
Hakju is almost done. The extension functionality is left to implement.

**Comment by kbserm** [comment]
Show BIE DEN, release, state, owner somewhere on the top.

**Comment by kbserm** [comment]
I have thought about @hakjuoh comment that the BIE state names - WIP, QA, and Production - are not suitable for Developer. While I agree, I would leave them like that for now for the following reasons 1) the use case for Developer user to publish BIEs (as standard) is not clear. 2) It is not a matter of just name. It is the whole process. In the large scheme, this is like asking whether developer BIEs need all the states and life-cycle same as CCs. There is no release scheme associated with BIEs at this point; so right now it is like each BIE would be published by the developer individually. 

This is also related to publishing something like the OAGi SME WG content.

I'm wonder whether developer BIE management and end user BIE management share a lot of common line of codes?

**Comment by hakjuoh** [comment]
@kbserm Both developers and end-users share 99% of same codes for now

**Comment by kbserm** [comment]
In addition to checking state of the CC in the extension. We have to deal with the state of the end user code list as well. If end user code list state is not Production and Revision Number is 1, it cannot be used in the Code List drop down box - the code list should not be in the list. If rev is > 1, it can be included in the list in any state. It would be good to be able to flag in a way that it is not in Production state.

**Comment by hakjuoh** [comment]
> In addition to checking state of the CC in the extension. We have to deal with the state of the end user code list as well. If end user code list state is not Production and Revision Number is 1, it cannot be used in the Code List drop down box - the code list should not be in the list. If rev is > 1, it can be included in the list in any state. It would be good to be able to flag in a way that it is not in Production state.

For the extension, it always applied the latest one in Production state. Why don’t we follow the same rule for the end user code list.

**Comment by kbserm** [comment]
@hakjuoh Because there is no (official) record of the previous revision in the the DB, how would the application applies "the latest one in Production state"?

Actually, now I realized, code list is not the same as BIE. We lock BIE when an its CC is in flight, there is record of BIE according to the CC b/f the CC is amended. But not the case for code list.

But I guess you are keeping the a temp record of the end user CC and CL b/f they are amended, is that you are referring too? I think if that is possible it is good. And those temp record can be used to express BIE while the actual CCs are still in flight as well.
