### ISSUE TITLE
Add 'Find Usages' function

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#820]
The user is able to query about where a particular CC is use.

**Comment by kbserm** [comment]
@dubnemo 

If we want to find where an ASCCP or BCCP is used, we can search for ASCC or BCC on the CC page by using DEN field like this ". [ASCCP DEN]". For example, we can see where Party. Party ASCCP is used by input ". Party. Party" in the DEN field. Note that the double quotes should be included in the DEN field and make sure that ASCC and/or BCC is selected in the Type drop down.

If we want to find what are ASCCPs are available based on an ACC, we can use this input pattern in the DEN field. ". [Object Class Term" and make sure that only the ASCCP is selected in the Type drop down. For BCCP, use ". [Data Type Term]" and make sure that only BCCP is selected in the Type drop down.

These may return more results than wanted when the entity DENs include the search string but longer. E.g., searching for ASCCP based on Party ACC with ". Party" would also return "Supplier Party Reference**. Party** Reference"

What do think @dubnemo ? Are these trick sufficient for 'where use' at least for now? What other use cases you might envision?

**Comment by asdimitriadis** [comment]
It works well. 
To view the usages of a CC, the user opens the context menu of a CC node and clicks the "Find Usages" option.

**Comment by dubnemo** [comment]
What's the label for this in the UI?  'Where Used' is what was used in the X12 data dictionary, and what people are most familiar with.

**Comment by asdimitriadis** [comment]
I am reopening the issue since now the label is "Find Usages". 

![findusages](https://user-images.githubusercontent.com/37205288/130623864-328d43e4-8323-4cd5-96d7-29ffac5d9502.png)

**Comment by rekuku** [comment]
@asdimitriadis the label changed to 'Where Used'
![Screen Shot 2021-08-31 at 9 51 08 PM](https://user-images.githubusercontent.com/10194354/131598750-11546435-0324-4420-9c9a-1a232287046a.png)

**Comment by asdimitriadis** [comment]
The label has been changed and it works well.
