### ISSUE TITLE
Deprecate a BCCP while revising an extension

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#824]
The issue is that I cannot deprecate a BCCP association of a previous revision of an extension if I do not make any other change (the Update button is disabled).
To reproduce it:
1. Create a BIE
2. Extend it globally or locally
3. Append a BCCP
4. Publish the extension
5. Open the extension again (create a new revision)
6. Try to deprecate the BCCP of the previous revision (1). If you click "Deprecate" button the "Update" button remains disabled.
However, if you click Deprecate, make another change, e.g., add a definition then it works fine.

**Comment by hakjuoh** [comment]
@asdimitriadis Please test it again with the latest commit.

**Comment by asdimitriadis** [comment]
Fixed and Tested.
