### ISSUE TITLE
Comments in Core Components 

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#827]
The issue is that a developer (e.g., devx) can add a comment to a CC that is in WIP state and owned by another developer (e.g., devy). 
The expected behavior is a developer (e.g., devx) should only be able to view the comments made in a CC that is in WIP state and owned by another developer (e.g., devy) but he cannot make a new comment.

**Comment by rekuku** [comment]
It is possible to comment on all CCs in the tree and all state. If we cannot comment in the WIP state, should I make sure that the lower CCs are also not allowed even they are not WIP state?
And should we block editing and deleting comments? @kbserm @asdimitriadis

**Comment by kbserm** [comment]
@asdimitriadis @rekuku I have been thinking about this. Initially, I thought commenting on CC during WIP could be annoying b/c the owner is still making change. I did think whether this would worth the more complex logic. I don't mind simplifying this to allow comments at any time regardless of state. Let's do that. I will update the Test Case document. @asdimitriadis please go ahead and change the test script accordingly.

**Comment by asdimitriadis** [comment]
I have closed this issue since we changed the logic (it is simpler now). The related Test Assertions  of the Test Case  "Test Case 10.1	Core component access" have changed as well.
