### ISSUE TITLE
Change mat-icons to buttons for consistency purposes

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#833]
According to the last UI changes, the following mat-icons, which are used in previous Score versions, should be buttons now:
1. The "Update" mat-icon in the page where a user changes its password (setting->change password).
2. The "Create Account" mat-icon in the "Group" page.
3. The "Create Account" mat-icon in the "Permission" page.

**Comment by asdimitriadis** [comment]
The above mat-icons have been changed to buttons.
I will keep this issue open till I test the whole application.

**Comment by rekuku** [comment]
@asdimitriadis The Group and Permission are not planned to be applied yet, so now they are hidden.

**Comment by asdimitriadis** [comment]
The buttons were checked for changed and the changes adopted in the scripts. The only issue was related to the forenamed button. Therefore, I am closing this issue since we do not use Group and Permissions in Score 2.0
