### ISSUE TITLE
Cannot update a Context Category

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#835]
A context category cannot be updated. To reproduce the issue:
1. Create a context category
2. Visit the "Context Category" page and make some changes.
3. Click "Update" button.

**Comment by hakjuoh** [comment]
@asdimitriadis Could you repeat it with clean data? I couldn't get this.

**Comment by asdimitriadis** [comment]
Fixed by `82c41c54923a372191950ff089948852bf88468f` and tested.
