### ISSUE TITLE
Cannot delete a Business Context

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#837]
The issue is that we cannot delete a Business Context. To reproduce the issue:
1. Create a Business Context
2. Open this Business Context again
3. Try to delete it. (an error is returned).

Note that if you visit the Business Context page (i.e., the page where all business contexts are listed), select a business context and click on the Discard button, it works (i.e., the selected business context is deleted)

**Comment by hakjuoh** [comment]
@asdimitriadis Just made a commit. Please try it again.

**Comment by asdimitriadis** [comment]
It works. Tested.
