### ISSUE TITLE
Search function in Business Context page does not work properly

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#838]
The issue is that the search function in the business context page does not work like other pages. In particular, multiple words entered into the name search field are not treated as AND, namely the system does not return the Business Contexts that contain both of the multiple words entered. To reproduce the issue:
1. Create the Business Context "Business Context Process"
2. Search using the keywords "Business Process" (without the quotes).
3. The Business Context "Business Context Process" is not returned.

The expected behavior is that when we enter multiple words into the name search field, they should be treated as AND, namely the system should return the Business Contexts that contain both of the multiple words entered in any order.

**Comment by hakjuoh** [comment]
@asdimitriadis Please try this again with the latest commit, 8d85630.

**Comment by asdimitriadis** [comment]
Fixed and it works good.
