### ISSUE TITLE
Delete property from an extension

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#841]
The issue is that if I append a property to an extension, I cannot delete it. There is no button that I can use.
To reproduce the issue:
1. Login using an end user account
2. Create a BIE
3. Extend it (e.g. locally)
4. Append a BCCP
5. Try to delete this BCCP.

**Comment by rekuku** [comment]
@asdimitriadis It has fixed, so you can see the discard btn on extension tree.
Please test this.

**Comment by asdimitriadis** [comment]
Tested.
