### ISSUE TITLE
A developer cannot reuse a BIE

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#842]
The issue is that a developer cannot access this function, namely a developer cannot reuse a BIE under a top-level BIE. In Score 1.5.0 an end user can only reuse a BIE.

The expected behavior is that a developer can reuse a BIE as well (not only an end user).

**Comment by hakjuoh** [comment]
@asdimitriadis Developers cannot reuse BIEs because of a chance of exposing user extension groups to developers as we discussed earlier. Please let me know if I misunderstood about it.

**Comment by hakjuoh** [comment]
@rekuku 
```Developers can reuse only developers' BIEs``` We may need to add a filter of the account role in the BIE fetching API.

**Comment by rekuku** [comment]
@asdimitriadis Developer's BIE is allowed to reuse for developers.
Please check this.

**Comment by asdimitriadis** [comment]
Tested.
