### ISSUE TITLE
UEG must not be visible to the developers

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#843]
The issue is that if an end user extends a BIE, then this extension is visible to a developer.

The expected behavior is that UEGs must not be visible to the developers.

This issue was created according to our last discussion.

**Comment by rekuku** [comment]
@asdimitriadis Now developer can not see the nodes that extended by end-users.
Please check this.

**Comment by asdimitriadis** [comment]
Tested and it works.
