### ISSUE TITLE
Schema generated from BIE should include version information for the BIE version from the BIE meta data

### ISSUE THREAD

**Issue by joshklm** [OAGi/Score#844]
Current SCORE tool has an option to generate XSD with BIE OAGi/SRT Meta Data that creates the following section under root element.

`			<xsd:annotation>
				<xsd:documentation>
					<srt_Version>Version Info</srt_Version>
					<srt_Remark>Remark Info</srt_Remark>
				</xsd:documentation>
			</xsd:annotation>`

But the introduction of this `<xsd:annotation><xsd:documentation><srt_Version>` structure is not based on OAGIS spec. 

OAGIS Spec has a dedicated "versionID" attribute at the BOD top level for containing the version information for the BOD profile. Currently, a way to use this versionID is to type in (separately from the BIE vesion info) the Version Identifier as Fixed Value while profiling. 

It would be ideal for SCORE to take the BIE version information (the meta data for BIE), and automatically insert it as a fixed value for Version Identifier attribute, or provide the user an option to do it. This way, we could avoid separately maintaining the version for the BIE and the fixed value under Version Identifier (and manually keeping them in sync.)

**Comment by dubnemo** [comment]
@joshklm should be leverage the standard metadata as a component that can be serialized by choice,  similar to how we select metaHeader and pagination based on the chosen representation?

**Comment by dubnemo** [comment]
@joshklm @kbserm I suggest extracting the data from abie.version, abie.remark, abie.definition, abie.last_update_timestamp, abie.status to the new meta component

**Comment by kbserm** [comment]
Josh suggested having a checkbox next to the Version field of the top-level BIE when it is a BOD. When it is checked, the fix value is set on the Version Identifier node.  What is the best way to recognize that the top-level BIE is BOD? Perhaps, BOD/@releaseID should also be populated with the release number which the BIE is derived from.

What happen if the the Version Identifier is already checked?

When the BIE is not BOD, we talked about having all OAGIS components containing a version ID field in the future. Does it means all components should have release ID as well?

**Comment by sfohn** [comment]
Hi Serm.

Regarding the last point, "having all OAGIS components containing a version ID field ", it seems that any "type" definition (and property) should have a versionId...as shown in the CCTS model, where each is-a RegistryClass with both a uniqueId and versionId. 

Regarding the question, "What is the best way to recognize that the top-level BIE is BOD?", while I think there are other reasons for identifying the message, the message body...the need of a versionId, does not seem to be one of them (assuming all types and properties have a versionId, per above).

Regarding the last question, "Does it means all components should have release ID as well?"  In ISO 11179, every Administered_Item is registered by Registration_Authority (an Organization).  Every type and property in the library is in a "namespace" identifying the Registration_Authority and has a releaseId, specific to the Organization that released it (e.g. OAGIS as a Platform with an HR-Open release including HR-related types and properties.

**Comment by dubnemo** [comment]
@sfohn @kbserm 
The CCTS model was slightly out of sync with ebRIM, but since I was part of both 11179 Part 3 (working with ANSI X3 as the liaison from X12) and ebRIM (explicitly citing 11179), what is stated for versioning at the CC and property level is absolutely correct.  

However...
1) we imported the CCs from the OAGIS schemas and did not start with a registry.  Do we just pick a version/ release of the CC and call it a day?  We just don't have the history how these components were created, defined, rationale for the based-on references, etc.  I would LOVE to have this history, and information on WHO submitted this.
2) The 'namespace' aspect is an implementation specific approach of of the registration authority reference identifier.  IMHO CCTS became too XML implementation centric, vs. syntax neutral as originally conceived in UN/CEFACT TMWG.   I think since we ARE 'OAGi' this is an easy update.  
If we import MIMOSA or other semantic standards, and user defined components becomes available, then those components have different agency identifiers.  If user defined core components are submitted to OAGi with the new export/ import feature, they should (need to) have the **original agency id** and the new agency id (OAGi) to show lineage.

The next obvious question, which is core to @joshklm request,  is whether a BIE generated expression needs to have all the version, release, agency etc. identifiers at the CC level -- in the JSON schema or otherwise.  IMHO, the answer is only at the top_level_abie level, since all these components within a BIE are already associated to CC details through Score's associative tables.  These associative tables should also retain the version of the CC originally reference -- which would also allow alerting if the referenced CC is versioned.

**Comment by joshklm** [comment]
@sfohn @kbserm 
I agree with @dubnemo: "IMHO, the answer is only at the top_level_abie level, since all these components within a BIE are already associated to CC details through Score's associative tables."

**Comment by sfohn** [comment]
@dubnemo 

Regarding the question, "Do we just pick a version/ release of OAGIS and assign to the CC and call it a day?" ...while not reflecting the history, this may be are only option. This will serve as a baseline going forward and means the version are types and properties going forward.  Regarding, information on WHO "submitted" and WHO is "administering"...while this would be nice to have, I'm not suggesting this.  But I am suggesting that we know WHO the owner organization (i.e. Registration_Authority) ... OAGi,  etc.  This is inline with our namespace discussions and use of OAGIS as a Platform; I think, from your 2nd point, we in agreement on this.  I would think (IMHO), for the BIE _**expression**_...it is sufficient to have the versionId, releaseId at the top-level...as it represents the version of an aggregate.

**Comment by joshklm** [comment]
@dubnemo: Regarding, ".. leverage a standard meta component (perhaps a new one) that can be serialized by choice, similar to how we select metaHeader and pagination based on the chosen representation?" 
 and 
".. suggest extracting the data from abie.version, abie.remark, abie.definition, abie.last_update_timestamp, abie.status to the new meta component -- when the ABIE is a top_level_abie." ,
my suggestion is that we use the attributes that are part of OAGIS specification. So the versionID, and better with OAGIS releaseID as well, be part of the OAGIS compliant XSD schema output, so the XML instance generated based on the schema would be able to get validated. Extracting all the meta data with remark, definition and put them in a new meta component won't do it unless we update the OAGIS spec to include those new meta component.

**Comment by dubnemo** [comment]
@joshklm we would need new properties for certain, and Application Area would then be versioned to include those properties.  

The new component would be used for non-BOD BIEs that would mirror Application Area.  A new checkbox [x] would allow this component to be selected during serialization /expression of the BIE in a targeted syntax.

**Comment by joshklm** [comment]
@dubnemo @kbserm @sfohn Just want to be sure that we all understand where the versionID appears in XML instance for a BOD BIE when the versionID attribute is activated in SCORE. It's not an element or attribute under Application Area. 
 
Having the versionID activated in SCORE tool, the XSD generated from SCORE has the xsd:attribute name="versionID" line added at the top level for the BOD (line 5 below). 
```
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.openapplications.org/oagis/10" targetNamespace="http://www.openapplications.org/oagis/10" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:element name="ProcessItemMaster">
		<xsd:complexType>
                <xsd:sequence>...</xsd:sequence>
                <xsd:attribute name="versionID" type="xsd:normalizedString" use="optional" fixed="1.1"/>
		</xsd:complexType>
	</xsd:element>
```
The XML instance generated from that schema has that versionID value added here in the first line
```
<ns1:ProcessItemMaster xmlns:ns1="http://www.openapplications.org/oagis/10" xmlns:ns2="http://www.w3.org/2001/XMLSchema" versionID="1.1">
  <ns1:ApplicationArea>
...
```

**Comment by sfohn** [comment]
@joshklm Yes, agreed; version information is, as they say in ISO 11179, "administrative" data.  Therefore, should be treated separate from ApplicationArea.

**Comment by kbserm** [comment]
To be implemented as shown on the slide. 
[VersionID Score Issue 844.pptx](https://github.com/OAGi/Score/files/5045260/VersionID.Score.Issue.844.pptx)

**Comment by hakjuoh** [comment]
@kbserm 

Synchronizing 'Version' value with 'Version Identifier' only works when it checked as 'Used'.

<img width="604" alt="Screen Shot 2020-09-25 at 2 29 47 PM" src="https://user-images.githubusercontent.com/16102116/94303371-b00cbe80-ff3b-11ea-99f3-e3198a2ca3ea.png">

After changing 'Version' value, it triggers when the user clicks 'Version Identifier' on the tree.

<img width="439" alt="Screen Shot 2020-09-25 at 2 30 13 PM" src="https://user-images.githubusercontent.com/16102116/94303391-b6029f80-ff3b-11ea-8c0e-b4dabea1be61.png">

**Comment by kbserm** [comment]
from @joshklm Looks like the version number doesn’t get synced with the meta data update, unless you click on Version Identifier from the list after you’ve made a change to the version number on the right side. I think it should be synced when you hit the Update button, even if you didn’t hit the Version Identifier again. 

Without this fix, it can easily cause the BIE version for the BIE not matching the version info in the generated XSD. I’ve done some testing with Process Party Master.

See Process Party Master BIE that I’ve created in the test instance. I created the BIE and added version 0.1 in the meta and had that synced with Version Identifier once. Once I made the update and set the BIE version with 0.2, the Version Identifier didn’t get updated when I hit the Update button, and when I generated a new XSD from the BIE.

**Comment by kbserm** [comment]
@hakjuoh Looks like the second flowchart in the slide didn't get implemented. Is there a problem like you can not issue a sync just when the user leave the Version field of the top-level BIE?

Anyway, I updated the second flowchart a bit to remove an extra arrow and a little comment on a box.

[VersionID.Score.Issue.844 (1).pptx](https://github.com/OAGi/Score/files/5318200/VersionID.Score.Issue.844.1.pptx)

**Comment by asdimitriadis** [comment]
Now, it works good and the last two comments are incorporated. Fixed and tested.
