### ISSUE TITLE
Min and Max Cardinality cannot be change in a revision of a UEG

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#845]
The issue is that we cannot change the Min and Max Cardinality of old associations (ASCCs and BCCs) when we create a new revision of an extension.

An example to reproduce the issue is:
1. Create a BIE
2. Extend it Locally
3. Append an ASCCP
4. Set Min to 3 and Max to 25
5. Publish the extension
6. Create a new extension on the same extension point (i.e., revise the extension)
7. Try to change the Min and Max Cardinalities. They are disabled.

The expected behavior is that the Min and Max cardinalities of old associations should be disabled when:
1. Min is 0 (only the Min should be disabled)
2. Max is unbounded (only the Max should be disabled)
3. Min=0 and Max=unbounded (both of them should be disabled)

**Comment by rekuku** [comment]
@asdimitriadis It fixed. 
Please test this.

**Comment by asdimitriadis** [comment]
Tested and it works.
