### ISSUE TITLE
Min and Max cardinality of an association of an extension are not reflected to the BIE tree

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#846]
The issue is that if we set the Min and Max Cardinalities to 0 and unbounded respectively, then they are not disabled in the corresponding node in the BIE tree.

To reproduce the issue:
1. Create a BIE
2. Extend it locally
3. Append an ASCCP (e.g., ASCCP1)
4. Set Min to 0 and Max to unbounded
5. Publish the extension 
6. Open the BIE and expand its tree
7. Click on ASCCP1

You can see that you can change the Min and Max cardinalities. For instance you can set Min to 3 and Max to 9. 
The expected behavior is that they cannot be changes since they were set to 0 and unbounded.

**Comment by rekuku** [comment]
@asdimitriadis 
As far as I know,
CC's cardinalities are can be wider ( e.g. 5 and 10 can be 4 and 11 ).
BIE's cardinalities are can be change to narrower ( e.g 5 and 10 can be 6 and 9 ).
So the case what you mentioned ( CC 0 and -1 ) is  can be change to any values.
Isn't it right?

**Comment by asdimitriadis** [comment]
Yes it works good.
