### ISSUE TITLE
X-Frame-Options HTTP is not set in the Login Page

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#847]
The issue is that the X-Frame-Options HTTP response header is not set in the login page of Score. 

This issue is a manifestation of the weakness CWE-16, it is described in https://cwe.mitre.org/data/definitions/16.html and can lead to "click-jacking" attacks (also known as "user interface redressing"). 

In our case a click-jacking allows adversaries to render the login page of Score into their fake website and trick a user into providing his login credentials. The result is stolen credentials.

To address this issue, the X-Frame-Options header should be set. In particular, we can use either 
"X-Frame-Options: SAMEORIGIN", or
"X-Frame-Options: DENY".

Note that we use "X-Frame-Options: DENY" for the other pages of Score.

**Comment by asdimitriadis** [comment]
This header is not set for the following pages as well:
1. http://localhost:4200/context_management/business_context
2. http://localhost:4200/context_management/business_context/create

**Comment by hakjuoh** [comment]
@asdimitriadis Now 'X-Frame-Options' header is set for all responses. @kbserm Note that we need to test this on not only 'localhost', but also production.

<img width="303" alt="Screen Shot 2020-09-25 at 11 05 16 AM" src="https://user-images.githubusercontent.com/16102116/94283659-4979a780-ff1f-11ea-9b77-394a4239cafa.png">

**Comment by asdimitriadis** [comment]
Fixed and tested in both local docker and in production (beta.oagiscore.net)
