### ISSUE TITLE
X-Content-Type-Options HTTP header is not set in the login page 

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#848]
The issue is that the X-Content-Type-Options HTTP response header is not set in the login page of Score. 

This issue is a manifestation of the weakness CWE-16, it is described in https://cwe.mitre.org/data/definitions/16.html and can be lead to "Cross-Site Scripting (XSS) attacks" based on MIME-type confusion. 

Although we do not allow uploading files, to harden Score it is recommended to set the X-Content-Type-Options header in the login page. In particular, we can use
"X-Content-Type-Options: nosniff" along with "Content-Type: text/html".

Now that all other pages include the "X-Content-Type-Options: nosniff" along with the appropriate Content-Type (in most cases "application/json").

**Comment by asdimitriadis** [comment]
This header is not set for the following pages as well:
1. http://localhost:4200/context_management/business_context
2. http://localhost:4200/context_management/business_context/create

**Comment by hakjuoh** [comment]
@asdimitriadis Now 'X-Content-Type-Options' header is set for all responses. @kbserm Note that we need to test this on not only 'localhost', but also production.

<img width="303" alt="Screen Shot 2020-09-25 at 11 05 16 AM" src="https://user-images.githubusercontent.com/16102116/94283503-16371880-ff1f-11ea-9858-6450408635d7.png">

**Comment by asdimitriadis** [comment]
Fixed and tested in both local docker and in production (beta.oagiscore.net)
