### ISSUE TITLE
Property Term Filter Field does not exist in the reuse BIE dialog

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#849]
The issue is that the dialog where we can select a BIE to reuse it does not include the "Property Term" search field. 

The expected behavior is that this dialog should include a "Property Term" search field.

**Comment by rekuku** [comment]
@asdimitriadis 
reusable BIE list always has the same property term as the ASBIEP of choice. Therefore, in the list, nodes with different information but always the same ASCCP node's property terms are displayed.
Therefore, there is no need to search for Property Term.
<img width="1395" alt="Screen Shot 2020-07-22 at 12 14 37 PM" src="https://user-images.githubusercontent.com/10194354/88201343-545d4680-cc15-11ea-886e-c79c6b436cc0.png">

**Comment by asdimitriadis** [comment]
We have this Test Assertion "The pop-up dialog for choosing a top-level BIE must include the following details – State, Property Term, Business Term, Owner, Business Context, Remark, Version, Status, and Updated Date Time (Release is NOT needed, they must be in the same release as the reuse-target anyway). Filters shall be available for these columns."

However, there is no point for filtering BOM as you correctly mentioned. 
@kbserm shall we exclude the filtering based on the Property Term from the TA or we might have a case that will be needed?

**Comment by asdimitriadis** [comment]
As you correctly mentioned there is no need to include such filtering field.
