### ISSUE TITLE
The Context Definition of the ASBIE belonging to the reusing top-level BIE cannot be changed

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#850]
The issue is that the Context Definition of the ASBIE that belongs to the reusing top-level BIE cannot be changed.

The expected behavior is that the the Context Definition of the ASBIE that belongs to the reusing top-level BIE **can be** changed.

**Comment by rekuku** [comment]
<img width="1431" alt="Screen Shot 2020-07-22 at 12 07 42 PM" src="https://user-images.githubusercontent.com/10194354/88200311-fe3bd380-cc13-11ea-9a56-2de1fed10a91.png">

I was added a "context definition" field for ASBIE.

@asdimitriadis Please check this.

**Comment by asdimitriadis** [comment]
Tested. It works.
