### ISSUE TITLE
NullPointerException when viewing the nodes of a reused BIE

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#851]
The issue is that if I reuse a BIE **which I have not expanded a node of it before I reuse it** , I am getting a NullPointerException when I try to expand this node.
To put is simple, I think that If I want to view all the nodes of a reused BIE, I have to expand its whole tree before reusing it. 

One simple example to reproduce the issue is:
1. Login as a developer
2. Create the BIE "Resource Codes. Sequenced Codes"
3. Expand the top-level ASBIE (i.e., Resource Code)
4. Do not expand it further so that you can see the children of the "Code".
5. Publish it
6. Create the BIE "Change Acknowledge Project Accounting. Change Acknowledge Project Accounting"
7. Expand its tree (Change Acknowledge Project Accounting/Data Area/Project Accounting)
8. On the node "Resource Codes" reuse the BIE create on step 2.
9. Expand the reused BIE (i.e., "Resource Codes")
11. Expand the node "Code"
12. You will receive a "NullPointerException"

**Comment by rekuku** [comment]
@asdimitriadis Now it fixed.
Please check this.

**Comment by rekuku** [comment]
@asdimitriadis I was add another exception handling code for BBIE_SC. 
Please check this.

**Comment by asdimitriadis** [comment]
Tested. It works.
