### ISSUE TITLE
Remove unnecessary tables from developer's home page

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#852]
The tables with the red cross of the attached screenshot should be removed from the homepage of a **developer** user since developers cannot extend a BIE.

![screenext](https://user-images.githubusercontent.com/37205288/88409755-61a83b80-cda3-11ea-8669-4bb51e265964.jpg)

**Comment by rekuku** [comment]
@asdimitriadis It has applied. Please test this.

**Comment by asdimitriadis** [comment]
Tested. The forenamed tables have been removed when a developer is logged in.
