### ISSUE TITLE
Data truncation exception when extending a BIE

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#853]
The issue is that when the Property term of a BIE is too long, a data truncation exception is returned.

To reproduce the issue:
1. Create a BIE using the ASCCP "Acknowledge Hazardous Material Shipment Document. Acknowledge Hazardous Material Shipment Document"
2. Open the BIE
3. Expand "Acknowledge Hazardous Material Shipment Document"
4. Expand "Data Area"
5. Expand "Hazardous Material Shipment Document"
6. Expand "Hazardous Material Shipment Document Header"
7. Extend the BIE on the extension point located under the above node.

At this point a data truncation exception is returned.

**Comment by rekuku** [comment]
@asdimitriadis It has fixed,
As you mentioned, there are ACCs that has over 60 object_class_term of length.
It was a problem when making ASCCP with this ACC.
Now i gave 100 length to ASCCP.property_term that the same size as ACC.
Please test this after reset your database with mig_1.4.0_to_1.5.0.sql or oagi_1.5.0.sql in gateway project.

**Comment by asdimitriadis** [comment]
Tested. It works.
