### ISSUE TITLE
Context Definition is missing when we make BIE reusable

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#854]
The issue is that when we make a BIE reusable the value of the context definition is missing.

To reproduce the issue:
1. Create a BIE
2. Enable an ASBIE node of it and set its context definition field
3. Make this node reusable
4. Open the BIE list page and click to view this reusable BIE
5. The context definition is null

**Comment by rekuku** [comment]
As we discussed last,
A context definition that mid of BIE belongs to `ASBIE`.
The created reusable BIE does not get the context definition from origin, but has its own `ASBIEP` context definition.
So, the created reusable BIE only has `Biz Term` and `Remark`.
It looks working correctly. 
@asdimitriadis

**Comment by asdimitriadis** [comment]
The created reusable BIE does not get the context definition from origin, but has its own ASBIEP context definition.
