### ISSUE TITLE
Cannot make a BIE reusable if that BIE reuses another BIE

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#855]
The issue is that when an ASBIE node of a BIE contains a node that reuses a BIE, it cannot be made reusable.

To reproduce the issue:
1.Create the BIE "Resource Codes. Sequenced Codes"
2.Make some changes
3.Publish it
4.Create the BIE "Change Acknowledge Project Accounting. Change Acknowledge Project Accounting"
5.Expand its tree (Change Acknowledge Project Accounting/Data Area/Project Accounting)
6.On the node "Resource Codes" reuse the BIE create on step 2.
7.Make the node "Project Accounting" (Change Acknowledge Project Accounting/Data Area) reusable.

**Comment by rekuku** [comment]
@asdimitriadis It has fixed. Please check this.

**Comment by asdimitriadis** [comment]
Tested. It works.
Make a BIE reusable and Copy a BIE functions have been tested since they were affected by this issue. They both work good.
