### ISSUE TITLE
Cannot enable a BIE node if I do not enable its parent first.

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#856]
The issue is that if I enable a BIE node before enabling its parent node and click update the node still remains unused.

To reproduce the issue:
1. Create the BIE "Show Quote. Show Quote"
2. Click on the node Show Quote/Application Area/Scenario Identifier/Scheme Identifier
3. Click on the "Used" checkbox
3. Click Update
4. Open the BIE again
5. Go to this node. It remains unchecked/unused while its parent (i.e., Scenario Identifier) is checked/used

**Comment by rekuku** [comment]
@asdimitriadis This bug only occurred on the bbieSc node.
It fixed and please check this.

**Comment by asdimitriadis** [comment]
Tested. It works.
