### ISSUE TITLE
Routinely executed code to clean up potentially unfinished BIE content deletion during reuse

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#858]
In BIE reuse (#821), replaced BIE content needs to be deleted. However, for quick user response, the application does not put the deletion and replacement into the same DB transaction. The application replaces with the reused BIE first and delete existing BIE content later. This is because if BIE content that needs to be deleted may be sizable, the application has to traverse the BIE to gather all descendant BIE records that need to be deleted. This could take long. 

The best event that would trigger the execution of this code will have to be figured out.

We also talked about potential problem if the user reuse and remove reuse so quick that the deletion hasn't occurred or finished. But this is not a problem b/c @hakjuoh made sure that the replaced ASBIEP record got deleted b/f the rest of the process. It is just that its descendants are deleted later.

**Comment by rekuku** [comment]
This was already applied in 1.6
https://github.com/OAGi/Score/blob/release/v1.6.0/score-http/src/main/java/org/oagi/score/gateway/http/configuration/intializer/OrphanBIEAfterReusedCleanUpInitializer.java

But it is not ported to 2.0 yet.
@kbserm Can you me this issue to 2.0 or close it and create new issue in 2.0 milestone.
