### ISSUE TITLE
Code List Import in Context Scheme

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#860]
In 1.x, code list import function in the Context Scheme looks like it is linked to the context scheme, while in fact code list content is copied for the most part. The only exception is context scheme table maintains a foreign key to the code list; and that is how the code list name is displayed on the Context Scheme UI.

In 2.0, we should make it clear that there is no intention for to link them. I.e., code list revision won't update the context scheme. The function should look like code values are copied into context scheme values and the user is free to change or add more values. So in 2.0, after import, every field of the context scheme and context scheme values shall be editable after copied. The UI should not display the code list name (just put the definition "copied from" + code-list-name).

The user can import again but it would be like recreating the whole context scheme. OTOH, I think we don't need this, i.e., it is a one time deal, b/c once the context scheme has been used by a context, this reimport will be impossible. In other word, if the context scheme can still be deleted, then the user can just delete it and create a new one to import a code list again.

When selecting a code list to import, the user can select a release and then select a code list. Both production end user code list and published developer code list can be selected.

**Comment by dubnemo** [comment]
@kbserm we should create a REST API using the Code List component to POST, PATCH and GET the code list entries.

**Comment by kbserm** [comment]
@dubnemo can that be a separate issue?
