### ISSUE TITLE
Change the name of menu items related to property appending

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#863]
Append always means "add to the end/last". So menu items "Append Property Before" and "Append Property at First" do not make sense. They should be "Insert Property Before" and "Insert Property at First". "Append Property After" is also iffy, "Insert Property After" reads better. "Append Property at Last" is okay.

**Comment by hakjuoh** [comment]
@kbserm This is done in 2.0 because it's relatively easy issue.

**Comment by kbserm** [comment]
I believe this will effect @asdimitriadis test script. @asdimitriadis please take note. 

@hakjuoh the flashed up message that follows the Insert, still say Append though.

**Comment by asdimitriadis** [comment]
It works good now
