### ISSUE TITLE
v1.5 HTTP 500 error extending Shipped Item Instance with Results. Results component

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#865]
@hakjuoh @kbserm @rekuku @asdimitriadis 
This occurred yesterday in biopharma site.  I tried several times to append;, repeatable.  

![Trying To Append Results](https://user-images.githubusercontent.com/32434235/89782610-421b4d80-dadb-11ea-80cb-813472f786a0.png)

**Comment by hakjuoh** [comment]
@dubnemo We found that the migration script did not contain removing orphan records. So we updated it. Please try what you were doing last week again and let us know if you encounter the problem again.

**Comment by dubnemo** [comment]
@hakjuoh that worked.  I was able to add the Results. Results extension.
