### ISSUE TITLE
Copying an End User BIE by an OAGIS developer needs to ignore descendant BIEs in the EUEG

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#869]
Copying an End User BIE by an OAGIS developer needs to ignore descendant BIEs in the End User Extension Group because a developer BIE cannot have an extension.

@asdimitriadis We need to document this in a test case and also User Guide.

Also need to make sure that this is carried into [milestone 2.0.](https://github.com/OAGi/Score/milestone/29)

**Comment by hakjuoh** [comment]
If the requester's role is a developer, it deletes all BIEs in the EUEG in the target after copying completes.

**Comment by kbserm** [comment]
@hakjuoh Should we make a copy of this issue for 2.0?

**Comment by hakjuoh** [comment]
> @hakjuoh Should we make a copy of this issue for 2.0?

@rekuku Please take this issue for 2.0.

**Comment by asdimitriadis** [comment]
Fixed and works.
