### ISSUE TITLE
backslash character disappears in html version of the user guide

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#870]

**Comment by asdimitriadis** [comment]
In the docx format of the User Guide, we will use 2 backslahes in a row ( e.g., "Model\\Platform\\2_4\\Common"). Doing so, we will allow Sphinx to create an HTML file with 1 backslash (e..g. "Model\\Platform\\2_4\\Common").

Sphinx requires two backslashes in a row to represent a literal backslash (the first backslash "escapes" the second, preventing it being interpreted in an "escaping" role).

User Guide updated.
