### ISSUE TITLE
Internal Server when Expressing Catalogm POST with metaheader

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#871]
![image](https://user-images.githubusercontent.com/32434235/90820715-6ce57d00-e2f7-11ea-975d-e26e45318910.png)

**Comment by dubnemo** [comment]
Works with GET operation and metaheader enabled.

**Comment by kbserm** [comment]
@hakjuoh since this is already fixed, if @asdimitriadis can verify it, we can roll this into 1.6.

**Comment by asdimitriadis** [comment]
Tested and it works good.
