### ISSUE TITLE
Data Integrity Validation Exception when expanding a BIE

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#874]
The issue is that when we try to expand a BBIE that has "Date" bdt as default we get an data integrity violation exception.

To reproduce the issue:
1. Create the BIE "Accounting Period"
2. Try to expand it.

**Comment by rekuku** [comment]
The oagi1docker/srt-repo:1.5.0 image had missing information.
As a result of checking with the @hakjuoh , there is no problem with the migration-script.
It will not happen to existing users.
We uploaded the updated srt-repo:1.5.0 and srt-repo:1.6.0 images.
Please delete the local 1.5.0, 1.6.0 images and download a new one to check.
@asdimitriadis

**Comment by asdimitriadis** [comment]
Tested and it works.
