### ISSUE TITLE
Load value from code list in Context Scheme

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#876]
After clicking load from code list the message in the dialog should be "All existing values will be removed and replaced with values from the code list."

**Comment by hakjuoh** [comment]
<img width="621" alt="Screen Shot 2020-09-09 at 11 24 57 PM" src="https://user-images.githubusercontent.com/16102116/92678301-b2dca200-f2f3-11ea-96e3-ec3430e7c125.png">
