### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#877]
![image](https://user-images.githubusercontent.com/7863166/91994316-795cd300-ed04-11ea-922c-1aaf89d97cec.png)

Change to "Only the owner can access BIE in this state."

**Comment by hakjuoh** [comment]
<img width="300" alt="Screen Shot 2020-09-09 at 11 25 46 PM" src="https://user-images.githubusercontent.com/16102116/92678354-cee04380-f2f3-11ea-9644-fc9c5c037bb2.png">
