### ISSUE TITLE
SSO Improvements: Admin Ability to use SSO

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#879]
Currently the Single Sign On implementation only allows for non-admin users to sign on with SSO.  If possible, allowing the admins to use the SSO option as well would be a nice feature.  To enable the admins to use SSO currently, this would need to be done via a manual SQL query.

**Comment by kbserm** [comment]
@hakjuoh actually with the way SSO currently work, I think we can do this.

@smorgan19 keep in mind though one account can have only one role.

**Comment by hakjuoh** [comment]
@kbserm This change may also need updating the User Guide.

**Comment by asdimitriadis** [comment]
The user guide has been updated

**Comment by hakjuoh** [comment]
This change applied in 1.6
