### ISSUE TITLE
Change terminology in the primitive restriction area for BBIE and BBIE SC

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#881]
![image](https://user-images.githubusercontent.com/7863166/92018152-c354b180-ed22-11ea-9901-d293445515d5.png)

**Comment by hakjuoh** [comment]
@kbserm If the value domain type is 'Primitive' on the left-side, it should use 'Primitive' as a placeholder on the right-side like this.
<img width="470" alt="Screen Shot 2020-09-02 at 3 37 15 PM" src="https://user-images.githubusercontent.com/16102116/92028549-36b1ef80-ed32-11ea-906a-235b450aef02.png">

If not, it replaces 'Primitive' text with 'Value Domain'.
<img width="464" alt="Screen Shot 2020-09-02 at 3 40 24 PM" src="https://user-images.githubusercontent.com/16102116/92028885-bf309000-ed32-11ea-87d8-7e07c67dbd9f.png">

**Comment by kbserm** [comment]
the latter Hakju. It is simpler - always fix to Value Domain, regardless of type.

**Comment by hakjuoh** [comment]
It applied in 2.0

**Comment by kbserm** [comment]
@hakjuoh we misunderstood each other somehow.

But it looks like you have eliminated the Business Data Type info. I'm not sure if that's a good idea.

Second the values in the drop down box below should be "Primitive", "Code", "Agency ID".

![image](https://user-images.githubusercontent.com/7863166/92965425-c1d26a00-f443-11ea-9ade-071738b38d10.png)

Third, I would like the label in the red box below to always be "Value Domain" regardless of whether "Primitive", "Code", or "Agency ID" is selected.

![image](https://user-images.githubusercontent.com/7863166/92965600-14ac2180-f444-11ea-873e-e400f221cc24.png)

**Comment by kbserm** [comment]
There is a bug associated with Agency ID drop down box.

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis Please review it.
<img width="460" alt="Screen Shot 2020-09-16 at 10 51 57 AM" src="https://user-images.githubusercontent.com/16102116/93354166-b64bbe00-f80a-11ea-8f77-420b82851984.png">
<img width="462" alt="Screen Shot 2020-09-16 at 10 52 05 AM" src="https://user-images.githubusercontent.com/16102116/93354164-b64bbe00-f80a-11ea-89bd-2188b0c159d0.png">
<img width="458" alt="Screen Shot 2020-09-16 at 10 52 13 AM" src="https://user-images.githubusercontent.com/16102116/93354163-b64bbe00-f80a-11ea-8bee-34e69ea0520e.png">

**Comment by kbserm** [comment]
looks good from the images. Will look again when it is deployed.
