### ISSUE TITLE
Sort combo boxes alphabetically

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#889]
Most drop down box should be ordered alphabetically. As it is now, it is hard to find element in the combo box.

If you think there is a combo box that does not make sense to have the list ordered alphabetically, let me know.

**Comment by hakjuoh** [comment]
@asdimitriadis I apply sorting on drop-boxes for primitives, code, agency in value domain restriction box, owner/updater filters, and agency id list in code list detail page.
