### ISSUE TITLE
Namespace field of an end user CC cannot be clicked

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#891]
The issue is that I cannot choose a Namespace for a CC if I use an end user account.
To reproduce the issue:
1. Log in with an end user account
2. Create an ACC
3. Try to click the Namespace field.

It returns nothing.

**Comment by rekuku** [comment]
The End-user only able to use non-standard for namespace.
At the first there has no non-standard namespace in the Database.
So you can add non-standard( it created by end-user ) namespace, then you can choose Namespace on end-user CC detail.
@asdimitriadis

**Comment by asdimitriadis** [comment]
Yes indeed. I have not created a Namespace.
Thanks!
