### ISSUE TITLE
Enhancement: Account Lock Feature

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#892]
With growing number of user accounts, there is the need to have a way to designate inactive accounts that need to be removed or locked from external usage once the user is no longer active at the company.  

Proposed solution:  Adding an inactive or active user status to accounts.

**Comment by dubnemo** [comment]
I agree.  We talked about a delete user feature in the past, but there needs to be check to see of the user 'owns' any BIE.  If so, the user cannot be deleted, and potentially assigned to another user.

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis Now the account list has a 'Status' column.

<img width="904" alt="Screen Shot 2020-09-23 at 6 00 22 PM" src="https://user-images.githubusercontent.com/16102116/94074187-c5141100-fdc6-11ea-9fae-80ff0c7a3d6c.png">

and the admin can change user's status

to the enabled user
<img width="182" alt="Screen Shot 2020-09-23 at 6 02 08 PM" src="https://user-images.githubusercontent.com/16102116/94074286-fb519080-fdc6-11ea-8079-a134b24bc878.png">

, or to disabled user
<img width="194" alt="Screen Shot 2020-09-23 at 6 02 02 PM" src="https://user-images.githubusercontent.com/16102116/94074280-f8ef3680-fdc6-11ea-98ee-29cd74f9be0d.png"> 

The disabled user cannot see all pages except the following alert message.
<img width="477" alt="Screen Shot 2020-09-23 at 6 00 35 PM" src="https://user-images.githubusercontent.com/16102116/94074718-dc073300-fdc7-11ea-9f07-e95a4a787280.png">

**Comment by asdimitriadis** [comment]
Tested and it works.
