### ISSUE TITLE
A deleted Property (ASCCP or BCCP) can be appended to an ACC

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#895]
The issue is that if I create an end user ACC, I can append to it a Property (ASCCP or BCCP) that is in Deleted state.
An example to reproduce the issue is the following:
1. Log in as an end user
2. Create an ASCCP
3. Delete it
4. Create an ACC
5. Choose to append this ASCCP
6. In the dialog you can see this deleted ASCCP

Please also check the following screenshot. 

Note that this issue exists for developer users as well. 

![deletedProperty](https://user-images.githubusercontent.com/37205288/93919528-d2a09c80-fcdb-11ea-976d-b54403238b33.jpg)

**Comment by hakjuoh** [comment]
@asdimitriadis Explicitly took Deleted state out from the state list.
<img width="539" alt="Screen Shot 2020-09-22 at 9 28 08 PM" src="https://user-images.githubusercontent.com/16102116/93953967-89bc0880-fd1a-11ea-99ec-fdbacd17ef7f.png">

**Comment by asdimitriadis** [comment]
Fixed and tested.

**Comment by asdimitriadis** [comment]
According to our last discussion, we want to **revert back this issue** so that a user can append a deleted property to an ACC. 

Since Score allows for restoring a deleted CC, users should be able to append a deleted Property to an ACC and then restore it back.  In that way, we can prevent users from creating duplicate CCs.

**Comment by hakjuoh** [comment]
@asdimitriadis @kbserm I allow to select 'Deleted' CC property in the dialog, but initial states in the filter don't have 'Deleted' state, so that the user should explicitly select 'Deleted' one.

<img width="433" alt="Screen Shot 2020-09-24 at 10 45 47 PM" src="https://user-images.githubusercontent.com/16102116/94220778-ba857480-feb7-11ea-942b-4d4395e832ef.png">

**Comment by kbserm** [comment]
@hakjuoh I would not exclude the deleted state by default, because the user will think that it is not there.

**Comment by hakjuoh** [comment]
> @hakjuoh I would not exclude the deleted state by default, because the user will think that it is not there.

Okay, now it's reverted.

<img width="463" alt="Screen Shot 2020-09-25 at 4 53 10 PM" src="https://user-images.githubusercontent.com/16102116/94314950-9e351680-ff4f-11ea-9513-33d72b4f827b.png">

**Comment by asdimitriadis** [comment]
Fixed and tested.
