### ISSUE TITLE
Changing the position of the association in ACC

### ISSUE THREAD

**Issue by hakjuoh** [OAGi/Score#896]
@kbserm @asdimitriadis As below, we are going to handle put associations in the middle of the ACC sequence even the ACC is revised. The validation for this will happen during the release validation #471. Test assertions may need to change to adopt this.

<img width="1411" alt="Screen Shot 2020-09-24 at 11 41 03 AM" src="https://user-images.githubusercontent.com/16102116/94167741-ddce0680-fe5a-11ea-9e3e-1d3324e87893.png">

**Comment by rekuku** [comment]
It is applied, revised ASCC/BCC can be changed except the attribute BCCP.
And going to handle validations with #471 .
