### ISSUE TITLE
History is not kept when a revision is discarded

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#898]
The issue is that if we discard a revision of a CC, the history record is not kept regarding the revision.

The expected behavior is to keep history record for the revision and that it was discarded.

To reproduce the issue:
1. Open a published CC (e.g., BCCP)
2. Create a new revision of it.
3. Open the history to see the record added.
4. Discard the revision.
5. Open the history.

The history does not contain the record of the above step 3.

**Comment by hakjuoh** [comment]
@rekuku 'Discard Revision' button name should change to 'Cancel Revision'. Please see TC 10.21 Assertion 3.

**Comment by asdimitriadis** [comment]
You are correct and thanks for pointing it out. 

- A revision can be cancelled. The information about the revision should be removed from the table. Traces should exist in the history table.

**Comment by hakjuoh** [comment]
@asdimitriadis 
All button name are now 'Cancel Revision'.
<img width="370" alt="Screen Shot 2020-09-24 at 10 20 22 PM" src="https://user-images.githubusercontent.com/16102116/94219176-3382cd00-feb4-11ea-826a-6bd588514fdb.png">

and you can see the history when it cancels
<img width="404" alt="Screen Shot 2020-09-24 at 10 20 32 PM" src="https://user-images.githubusercontent.com/16102116/94219247-60cf7b00-feb4-11ea-8be3-1967389250ae.png">

**Comment by kbserm** [comment]
I note that I didn't expect that the history need to be kept for cancellation. that's why I used the word 'may'.

**Comment by kbserm** [comment]
issue with button name.

![image](https://user-images.githubusercontent.com/7863166/94341782-41cb0900-ffda-11ea-84b8-a9911e53715a.png)

**Comment by hakjuoh** [comment]
Changes it with 'Okay'.
<img width="525" alt="Screen Shot 2020-09-26 at 6 45 08 PM" src="https://user-images.githubusercontent.com/16102116/94351583-6fd73a00-0028-11eb-8ba7-5b61930117fc.png">

**Comment by kbserm** [comment]
We decided to do not keep cancellation history at this time. The revision number will look confusing. The cancelation will refer to a rev # that do not exist. And the new revision will have the same number as the canceled one.

Hakju said we need to get out of the reversion number and use a commit link list.

**Comment by kbserm** [comment]
Hakju will revert the code.

**Comment by hakjuoh** [comment]
@asdimitriadis Now 'Cancel' action does not keep history records. Please review the function and close this issue if it works.

**Comment by asdimitriadis** [comment]
It works good. The Cancelation of a revision or of an amendment does not keep any history records created after the revision or the amendment.
