### ISSUE TITLE
Revision/Amendment of Code List

### ISSUE THREAD

**Issue by hakjuoh** [OAGi/Score#903]
1. Name/Short name properties of the code list value existed in previous revision of code List cannot be modified.
2. The code list value existed in previous revision of code List cannot be deleted.

**Comment by rekuku** [comment]
1. Name/Short name properties of the code list value existed in previous revision of code List cannot be modified.
- #910 It is happened on revised specific release. it should be blocked.
2. The code list value existed in previous revision of code List cannot be deleted.
- fixed

**Comment by rekuku** [comment]
Cc list has same bug of 2. so fixed.
