### ISSUE TITLE
Deleted Code List does not show up by default

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#905]

**Comment by hakjuoh** [comment]
@kbserm Now it shows up.

<img width="492" alt="Screen Shot 2020-09-25 at 4 45 52 PM" src="https://user-images.githubusercontent.com/16102116/94314499-9c1e8800-ff4e-11ea-8f98-78a42edb92f2.png">

**Comment by asdimitriadis** [comment]
Now the deleted Code Lists are displayed like in CC list page.
