### ISSUE TITLE
Lost info if not clicking update b/f leaving the CC node.

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#906]
I was editing an ACC revision. I updated Definition of a BCC. Without clicking the Update button, I clicked another BCC node. Come back to the previous BCC, the updated Definition disappear. However, if I clicked Update, the definition comes back.

**Comment by kbserm** [comment]
This issue seems to occur in several places albeit with different behavior. On ACC editing page for example. If I changes some info and happens to click in a wrong place (I clicked on the ACC pane on the left thinking about adding an association). The previous entered info, e.g., object class, namespace etc. got lost. But in this case clicking Update didn't bring the info back.

**Comment by kbserm** [comment]
I confirm that it happened on ASCC node too similar to the case of BCC.

**Comment by hakjuoh** [comment]
@rekuku Utilize '[onbeforeunload](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload)' event.

**Comment by rekuku** [comment]
Now It fixed.

**Comment by kbserm** [comment]
Serm checked this manually.

**Comment by kbserm** [comment]
This still happens. It occurred when I create a new ACC. I add a bunch of info like obj cls, nmsp and def. Without clicking Update, I selected the menu Set Based ACC. Boom!, the filled in info is gone.

**Comment by kbserm** [comment]
work fine. now.
