### ISSUE TITLE
There is no state change button on ACC revising page

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#907]
![image](https://user-images.githubusercontent.com/7863166/94341925-79868080-ffdb-11ea-8bbf-da2ce7caebd5.png)

**Comment by kbserm** [comment]
In fact the state change button seems to disappear for all kinds of CCs

**Comment by hakjuoh** [comment]
@rekuku Note that the access privilege 'CanEdit' implies 'CanMove' either.

**Comment by hakjuoh** [comment]
It's fixed.
```typescript
// *ngIf="access === 'CanMove'
*ngIf="(access === 'CanMove' || access === 'CanEdit')"
```

**Comment by kbserm** [comment]
Looks okay now.
