### ISSUE TITLE
Fix incorrect OAGIS 10.6 data

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#913]
The fix is related to a sequence bug reported in https://github.com/OAGi/oagis/issues/146.

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis 
You can find the patch script for data upgraded from OAGIS 10.5 to 10.6 [patch_oagis_10.5_to_10.6.sql](https://drive.google.com/file/d/1dmetmZg4N33x99KBOiVQwBrPOe6MezWj/view?usp=sharing).

It consists of #857, changing sequences of `Test Equipment Class Usage Id` and `Test Equipment Class Usage ID`, deleting `Status` ASCC from `Carrier Route Base`, and upgrading BIEs derived from `Test Results Line Base`.
