### ISSUE TITLE
something wrong with the history

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#914]
I revised the status base ACC, adding an association. I checked the history, it showed that the prior version is based on Attachment Base ACC which is incorrect and inconsistent with info the 10.5 and 10.6 branches.

**Comment by kbserm** [comment]
a bunch of history entries also showed on an entity with no revision as well.

**Comment by rekuku** [comment]
This bug is an issue that occurred while merge 10_6 into 10_5. It does not occur on the current database.
