### ISSUE TITLE
When we restore an ACC, its deleted ASCCP and BCCP are not restored

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#915]
The issue is that if we restore a deleted ACC all its deleted associations should be restored back. 

To reproduce the issue:
1. Create an ACC
2. Create an ASCCP and a BCCP
3. Append the ASCCP and the BCCP of the Step2 to the ACC of the Step1
4. Open the ASCCP and BCCP and delete them
5. Open the ACC and delete it
6. Open again the ACC and restore it.

The ASCCP and the BCCP should be restored back as well.

**Comment by kbserm** [comment]
it is not a bug. Only the BCC and ASCC are supposed to be restored with the ACC. BCCP and ASCCP used by them are not restored with the ACC. However, this is a possible enhancement albeit could be a complicated one b/c deleted properties used by ACC can be at the lower level than the direct child.
