### ISSUE TITLE
Extension ASCCP is created w/o namespace.

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#916]
The same namespace as the ACC should be assumed.

**Comment by kbserm** [comment]
Also, it is odd as the Extension ASCCP is in Rev 1 but I cannot edit the namespace.

**Comment by kbserm** [comment]
I guessed you intentionally locked it b/c it is Extension component type. But b/c no nmspc, I can't move the state.

**Comment by hakjuoh** [comment]
Related to #886

**Comment by rekuku** [comment]
- Fix extension ASCCP created without namespace.
- Can edit properties of created Extensions except Component Type(b/c it can not go back to Extension after once it is changed.)

**Comment by kbserm** [comment]
Looks fine now.
