### ISSUE TITLE
Bug associated with BCC entity type

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#919]
When changing BCC entity type from Element to Attribute, the min/max must be set to 0 .. 1. Right now, max is still unbounded. This might have caused other unstable behaviors that I noticed after changing the entity types around a few time as well.

@asdimitriadis Add TA related to this to TC doc as well.

**Comment by hakjuoh** [comment]
> When changing BCC entity type from Element to Attribute, the min/max must be set to 0 .. 1.

The min/max also could be 1 ... 1 for use="required". So this issue only affects to the cardinality max.

**Comment by kbserm** [comment]
@hakjuoh the system needs to default both min and max to 0 and 1. the user can change the min, of course. The system cannot just change the max bc min might be something else like 5 before switching the entity type.

**Comment by hakjuoh** [comment]
Done

**Comment by asdimitriadis** [comment]
It is fixed and tested.
