### ISSUE TITLE
Ability to move states of several CCs in one shot on the view/edit CC page

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#920]

**Comment by kbserm** [comment]
Tested on CC page. Looks fine.

**Comment by kbserm** [comment]
I didn't test the transfer ownership. 

Tried it on end user CCs, working ok.

**Comment by asdimitriadis** [comment]
It works good. 

Testing included:
1. State transfer
2. Ownership transfer
3. Deleting CCs.
