### ISSUE TITLE
The value of the Remark Field of a Code List is not stored

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#921]
The issue is that if I add a value in the Remark field of a code list and click the Update button, the Remark field gets blank.

To reproduce the issue:
1. Create a Code List
2. Fill all its fields (including the Remark)
3. Click Update

The Remark field is blank.

**Comment by hakjuoh** [comment]
@asdimitriadis Done

**Comment by asdimitriadis** [comment]
Fixed
