### ISSUE TITLE
HTTP 500 error when we discard a namespace that is used by a CC

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#924]
The issue is that if we discard a namespace that is already used by a CC (i.e. has a reference), an HTTP internal server error is returned.

An example to reproduce the issue is:
1. Login in as a developer
2. Create a Namespace
3. Create an ACC and use that Namespace is the Namespace selector box.
4. Open the Namespace and click the Discard button.

Note that the issue exists for both Standards (developers) and Non-standard Namespaces (end users)

The expected behavior is to either disable the Discard button or provide a message that the Namespace cannot be deleted since it has references.

**Comment by rekuku** [comment]
![Screen Shot 2020-10-02 at 12 38 14 PM](https://user-images.githubusercontent.com/10194354/94947775-37ae7c00-04ac-11eb-84ae-3af09b8927b4.png)
Fixed @asdimitriadis

**Comment by asdimitriadis** [comment]
Fixed and tested.
