### ISSUE TITLE
Create BIE without Business Context

### ISSUE THREAD

**Issue by rekuku** [OAGi/Score#925]
![Screen Shot 2020-10-02 at 9 19 01 AM](https://user-images.githubusercontent.com/10194354/94928077-1c824300-0491-11eb-9813-951b32553d13.png)

BIE created without BizCtx information.

**Comment by hakjuoh** [comment]
@asdimitriadis @rekuku Fixed.

**Comment by asdimitriadis** [comment]
Fixed and tested.

The test includes the following steps:
1. Open Create BIE page
2. Select a Business Context
3. Click Next button
4. Search for "Get BOM" using the DEN field
5. Refresh the page using the browser's button
6. Select the ASCCP "Get BOM. Get BOM"
7. Click the Create button
8. Verify in the BIE List page that there is the BIE "Get BOM" with the selected Business Context. Open this BIE and verify that the Business Context is listed in the corresponding input area.
