### ISSUE TITLE
Routinely executed code to clean up potentially unfinished BIE content deletion during reuse

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#926]
same as #858 but for 2.0.

**Comment by rekuku** [comment]
It applied for 2.0.
There are no changes displayed on the screen.
I was test by DB change.

**Comment by kbserm** [comment]
@rekuku when is this clean code executed? or what would trigger it?

**Comment by kbserm** [comment]
This clean up occurs when the application server starts.
