### ISSUE TITLE
On the View/Edit CC page there is no way to open CC detail in a new tab

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#927]

**Comment by hakjuoh** [comment]
@kbserm I don't follow this issue. Because there is a menu in Edit CC page.

<img width="589" alt="Screen Shot 2020-10-08 at 5 13 15 PM" src="https://user-images.githubusercontent.com/16102116/95514236-99c62000-0989-11eb-8659-566a73b336a7.png">

**Comment by kbserm** [comment]
I mean in the View/Edit CC page. Not the CC detail page.

**Comment by hakjuoh** [comment]
Duplicated with #951
