### ISSUE TITLE
Could not add Context Value to a Business Context

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#929]
Got "Server Internal Error: Http failure response for https://test.oagiscore.net/api/context_categories?sortActive=undefined&sortDirection=asc&pageIndex=-1&pageSize=-1: 500 OK"

**Comment by kbserm** [comment]
Posted in an incorrect Repo.

**Comment by rekuku** [comment]
Fixed

**Comment by kbserm** [comment]
tested
