### ISSUE TITLE
Primitive restriction does not show up all values

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#933]
The issue is that the values of the Primitive Types are not displayed.

To reproduce the issue:
1. Create a BIE (e.g., Procedure Step)
2. Enable a node (e.g., Description)
3. Check that the values of the Primitive Type "Code" are not displayed.

**Comment by hakjuoh** [comment]
@asdimitriadis Could you explain steps in details? because I can see the list.

<img width="1338" alt="Screen Shot 2020-10-05 at 10 19 30 AM" src="https://user-images.githubusercontent.com/16102116/95091350-57d07c00-06f4-11eb-9085-ba58ea0e93de.png">

**Comment by hakjuoh** [comment]
@asdimitriadis Fixed

**Comment by asdimitriadis** [comment]
It works good and it has been tested.
