### ISSUE TITLE
update dialog when changing end user CC state to production to be consistent with other state change dialog

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#939]
![image](https://user-images.githubusercontent.com/7863166/95148774-2c7c7a00-0752-11eb-9473-621cabbd1d34.png)

**Comment by rekuku** [comment]
![Screen Shot 2020-10-07 at 12 46 24 PM](https://user-images.githubusercontent.com/10194354/95361766-26de7b80-089b-11eb-8201-f22896ea8524.png)
Fixed.

**Comment by kbserm** [comment]
verified.
