### ISSUE TITLE
A developer cannot add to a context scheme code list values from Production Code Lists

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#941]
The issue is that a developer cannot add to a context scheme, code list values from a Production Code List.

The expected behavior is that a developer can add to a context scheme, code list values from a Production Code List.

**Comment by rekuku** [comment]
![Screen Shot 2020-10-06 at 8 16 05 PM](https://user-images.githubusercontent.com/10194354/95273604-7b3d1900-0811-11eb-9b39-53e2050e4f98.png)
Add code list of Production state to context scheme create/detail page.

**Comment by asdimitriadis** [comment]
Tested and it works.
