### ISSUE TITLE
when create an ASCCP, default the property term to the same as ACC object class term

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#943]

**Comment by hakjuoh** [comment]
Now the initial property term sets to the object class term of the associated ACC.
<img width="759" alt="Screen Shot 2020-10-08 at 2 13 47 PM" src="https://user-images.githubusercontent.com/16102116/95497552-8064aa00-0970-11eb-8a34-65a7ae2ca00a.png">

**Comment by kbserm** [comment]
@asdimitriadis may need to adjust test script.

**Comment by asdimitriadis** [comment]
Done. Scripts adapted. It works good.
