### ISSUE TITLE
provide a context menu on the ACC to create an ASCCP

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#944]
the new ASCCP is opened up in a new tab afterward.

**Comment by hakjuoh** [comment]
@kbserm 
<img width="433" alt="Screen Shot 2020-10-07 at 10 33 35 AM" src="https://user-images.githubusercontent.com/16102116/95345335-9d25b280-0888-11eb-93d9-3585714745e1.png">

**Comment by kbserm** [comment]
Menu name "Create ASCCP from this" is enough.

**Comment by hakjuoh** [comment]
<img width="231" alt="Screen Shot 2020-10-08 at 8 27 58 AM" src="https://user-images.githubusercontent.com/16102116/95458468-319f1c00-0940-11eb-8177-9f40de416e24.png">
