### ISSUE TITLE
port the version id sync from #844

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#946]
port the version id sync implemented in 1.7 to 2.0 according to #844

**Comment by rekuku** [comment]
Ported please test this @asdimitriadis

**Comment by asdimitriadis** [comment]
@rekuku can you try the following scenario:
1. Create a Get BOM
2. Open it and set its version metadata field to 9.
3. Enable the Version Identifier node (it will be syncronized to Fixed Value = 9)
4. Change the fixed value of the Version Identifier node to 11.
5. Click update button.
6. Navigate to a different node and the return back to Version Identifier. (the changed value is still there. It is 11)
7. Open the BIE again
8. Go to the Version Identifier
9. The Fixed value is 9 not 11.

**Comment by rekuku** [comment]
https://github.com/OAGi/Score/issues/844#issuecomment-702717325
As follow this comment,
If you change the Version Identifier.fixed_value, the server is check once more and override it.
This can be confuse, So If Root Version is exist, Version Identifier.fixed_value is going to disabled. please check this @asdimitriadis

**Comment by asdimitriadis** [comment]
This works good. Tested.
