### ISSUE TITLE
odd page one BCC cardinality is displayed as -1

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#947]
on all other BCCs, the max cardinalities are displayed as unbounded fine. 

![image](https://user-images.githubusercontent.com/7863166/95274824-d7556c80-0814-11eb-8f15-1fcae794d051.png)

**Comment by hakjuoh** [comment]
@kbserm 'unbounded' filter that transforms '-1' to 'unbounded' wasn't applied to disabled input fields. It's now fixed.

<img width="1097" alt="Screen Shot 2020-10-06 at 10 04 42 PM" src="https://user-images.githubusercontent.com/16102116/95279150-f6a5c700-081f-11eb-9849-706f333eb99f.png">
