### ISSUE TITLE
bbie_sc does not store the value of the Business Term field

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#950]
The issue is that a BBIE_SC node does not hold the value of its business term field.

To reproduce the issue:
1. Create a BIE (e.g., Cancel Require Product)
2. Enable the node Cancel Require Product/Application Area/Scenario Identifier/Scheme
3. Set a value for the Business Term field
 In this step you can see the value is stored even if you navigate through the different nodes of the tree.
However, if you open the BIE again and go to this node then the value is not there.

**Comment by hakjuoh** [comment]
@asdimitriadis There was no logic to handle BizTerm for BBIE_SC, and now it's fixed.

**Comment by asdimitriadis** [comment]
Fixed and it works.
