### ISSUE TITLE
open CC in new tab

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#951]
Currently, if the user click on the ASCCP DEN on the ASCCP selection page during the BIE creation process , the CC is opened on the same tab. This perhaps was the reason the user had to click Back button to select the ASCCP.

In fact, I think on all pages that list CCs, it is better to always open the CC detail in a new tab.

**Comment by kbserm** [comment]
Perhaps the same thing for BIEs and  code lists

**Comment by kbserm** [comment]
@asdimitriadis Would this impact test scripts?

**Comment by asdimitriadis** [comment]
It is ok for me Serm. It will not impact them.

**Comment by kbserm** [comment]
@hakjuoh I knew you did make some changes. But I am still gonna keep this in 2.x. I don't want to think about this now. This is usability.

**Comment by hakjuoh** [comment]
@kbserm Previously, navigating to the core component was performed by the script, not a HTML tag. That's the reason 'Crtl'+click didn't work to open the link in a new tab. Now, it works.

**Comment by asdimitriadis** [comment]
It works well.
