### ISSUE TITLE
Weird behavior of the Value Constraint Field of BBIE_SC nodes

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#952]
The issue is that if I enable a bbies_sc node of a BIE (e.g., Cancel Require Product/Application Area/Scenario Identifier/**Scheme**)
and change the Value Constraint to Default value, it is locked.
If I repopen the BIE again and change it to Fixed value and set it to 3 is again locked.

**Comment by hakjuoh** [comment]
@asdimitriadis It was a bug. After second choose of constraints, some validator returns 'null'. Now it's fixed.

<img width="902" alt="Screen Shot 2020-10-08 at 1 45 08 PM" src="https://user-images.githubusercontent.com/16102116/95494810-7e005100-096c-11eb-9381-f65a26f9fa4b.png">

**Comment by asdimitriadis** [comment]
It works good now.
