### ISSUE TITLE
Value Domain Type cannot be set if I change it and the Value Domain can be left blank.

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#954]
The issue is that if I change the Value Domain Type, I cannot change it again. It goes back to primitive somehow. 
Some other times I can update it leaving the Value Domain field blank. 

Please see the screenshot attached.

![vdt](https://user-images.githubusercontent.com/37205288/95492964-cf5b1100-0969-11eb-9410-efca84de5b61.png)

I do not know if issue #762 is similar but I mentioned here if it helps.

**Comment by asdimitriadis** [comment]
The expected behavior is that the Value Domain cannot be left blank.

**Comment by hakjuoh** [comment]
@asdimitriadis If the value domain does not be set a value, now the error message has shown up if the user clicks 'Update.
<img width="907" alt="Screen Shot 2020-10-08 at 2 00 02 PM" src="https://user-images.githubusercontent.com/16102116/95496324-a5581d80-096e-11eb-9e7d-898411455302.png">

**Comment by asdimitriadis** [comment]
Tested and it works good.

**Comment by kbserm** [comment]
Fix the error message to this pattern "Value Domain is required in System Environment Code."

**Comment by hakjuoh** [comment]
@kbserm @asdimitriadis It's applied.

**Comment by asdimitriadis** [comment]
It has been changed according to the above comment.
