### ISSUE TITLE
Remove the angle brackets from the Definition field of the code list values 

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#955]
The definition field of the code list value contains angle brackets like <CodeName>, <ccts_Definition> etc.

There should not exist there and they should be removed.

Please see the screenshot below.

![brankss](https://user-images.githubusercontent.com/37205288/95498098-52cc3080-0971-11eb-9c93-81eb689e230c.jpg)

**Comment by hakjuoh** [comment]
@asdimitriadis This is not an application problem. When we populated OAGIS data, we didn't take into account this. You may see the same thing on the previous release. @kbserm or is there anything I don't know about this?

**Comment by kbserm** [comment]
My apology @asdimitriadis I misunderstood this. This is not a bug. It is expected.
