### ISSUE TITLE
Not all values are listed in the Value Domain field when the Value Domain Code is selected.

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#956]
The issue is that the Value Domain field does not list all values if the "Code" is selected.

To reproduce the issue:
1. Create a BIE (e.g., Acknowledge Maintenance Order)
2. Open it and enable the Node "Language Code"
3. Choose "Code" for Value Domain Type.
Although the oacl_LanguageCode is published, compatible code list in the same release as the BIE, it is not displayed. 

Please see the screenshot below:

![languagecode](https://user-images.githubusercontent.com/37205288/95498472-dab23a80-0971-11eb-83a6-26ea6bc1592b.png)

**Comment by hakjuoh** [comment]
@asdimitriadis There was a bug incorrectly retrieving the list of value domains. Now it's fixed.

<img width="507" alt="Screen Shot 2020-10-08 at 2 36 16 PM" src="https://user-images.githubusercontent.com/16102116/95499690-ab043200-0973-11eb-9386-ec5f32d54bad.png">

**Comment by asdimitriadis** [comment]
It works good. Tested.
