### ISSUE TITLE
Cannot transfer the ownership of a BIE

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#958]
The issue is that we cannot transfer the ownership of a BIE. 

To reproduce the issue:
1. Create a BIE as a devx
2. Try to transfer the ownership to another developer 
I am getting a message saying "Not found a target user". However the user exists in the database.

Also, the following icon used to transfer the ownership of a BIE does not work. When I click it nothing happens.
![iconown](https://user-images.githubusercontent.com/37205288/95505106-cd9a4900-097b-11eb-9b49-6613d81bce0d.png)

This menu icon, however, works.
![menuown](https://user-images.githubusercontent.com/37205288/95505114-d428c080-097b-11eb-8b8a-7e36d1c2048f.png)

**Comment by hakjuoh** [comment]
@asdimitriadis There was a mistake to handle this with null value. It's now fixed.

**Comment by asdimitriadis** [comment]
It works good.
