### ISSUE TITLE
System must block top-level BIE creation from ASCCP tied to a group ACC 

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#965]
At least need to block from the application logic. Telling the user that this is not allowed.

Optionally, also filter this out from the ASCCP selections during the BIE creation process.

**Comment by rekuku** [comment]
Fixed.
56 ASCCP has filtered out from the BIE creation page.

**Comment by kbserm** [comment]
@rekuku is it also checked and blocked on server side?

**Comment by asdimitriadis** [comment]
Tested in during BIE management testing. It works good. 
I am not closing the issue because of the above question.

**Comment by rekuku** [comment]
@kbserm 
Server side has blocked.
API users will be found this message.
'''Cannot create BIE of `ASCCP` with group `ACC`.'''
