### ISSUE TITLE
Change current field that say "Namespace List" on the Release initialization page 

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#966]
Change to "Release Namespace" and make it the field required.

![image](https://user-images.githubusercontent.com/7863166/95687897-6925f680-0bd4-11eb-8403-51d0ab7fc157.png)

**Comment by rekuku** [comment]
Fixed.
![Screen Shot 2020-10-11 at 11 27 18 PM](https://user-images.githubusercontent.com/10194354/95702111-64376600-0c19-11eb-9133-891f807757fa.png)

**Comment by kbserm** [comment]
@rekuku I haven't seen this on the test server but I'm just going to close it.
