### ISSUE TITLE
Global user extension includes a lot of same nodes

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#968]
The issue is that when I created a Global Extension, I show a lot of same nodes. 
Please see the attached screenshot.

Also note that I cannot view the local extensions anymore. That is, If I extend the BIE locally and then globally, I cannot view the local extension.

![globalext](https://user-images.githubusercontent.com/37205288/95776679-caac9a80-0c92-11eb-972a-16f54bc33b48.jpg)

**Comment by rekuku** [comment]
@asdimitriadis Fixed please check this.
There's one thing that changed.
The UEG rootNode displays two ACC details.
The first is ACC, the top group of UEGs.
The second ACC displayed is the ACC exposed to the top of the tree managed by the system.
Only first Acc is owned by user and can change the namespaceId.

**Comment by asdimitriadis** [comment]
It works good now. Tested.
