### ISSUE TITLE
The links of the User Extension Tab of the HomePage do not work properly

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#969]
The issue is the links exist in the User Extension Tab of a developer user do not work properly.

To reproduce the issue:
1. Create some UEG CCs as an end user
2. Login as a developer
3. Visit the Homepage and click on the User Extension Tab
4. Click on the WIP div
The Core Component page is returned but nothing is listed since the Working release is selected.

**Comment by rekuku** [comment]
Fixed.

**Comment by asdimitriadis** [comment]
@rekuku can you try to click the links in the "User Extensions by users and states".
For instance, when I click on the Number of the UEG in WIP state, it opens the CC list page but the mat-progress-spinner do not disappear. 

Also, in the previous release there was a field by which we could filter the users of the UEGs.

**Comment by rekuku** [comment]
@asdimitriadis the user search box restored.
And i can not found the case you mentioned  

` it opens the CC list page but the mat-progress-spinner does not disappear.`

Can you let me know when it happened or just give me a DB dump if you have.

**Comment by asdimitriadis** [comment]
Indeed it was fixed. Thanks.
