### ISSUE TITLE
Add the Commonly Used flag to the DT table.

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#975]
Set this flag to true on all DTs currently used in 10.6.

When creating a new BCCP, default the type filter to this flag.

**Comment by hakjuoh** [comment]
@kbserm `commonly_used` column is added on `dt` table. The following screenshot shows how the filter looks like
<img width="1127" alt="Screen Shot 2020-10-13 at 10 43 09 AM" src="https://user-images.githubusercontent.com/16102116/95876324-eff7e200-0d40-11eb-9482-aa4e640181b7.png">

**Comment by asdimitriadis** [comment]
The suggestions are incorporated:
```
Type = Clear
Commonly Used selector = true.
```

Works good.
