### ISSUE TITLE
Deprecation of code values in a brand new code list shouldn't be allowed 

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#978]
What happened was. It wasn't allowed when I first created the value in the brand new code list. But when I edited the value, the UI allowed that.

**Comment by kbserm** [comment]
Similarly, new code values added to a revised code list can be deprecated if I added the value and then edit it. This shouldn't be the case.

**Comment by rekuku** [comment]
Fixed and deployed.

**Comment by asdimitriadis** [comment]
Deprecation is not allowed in brand new code list. Neither in case of new added values in a revised code list.

It works good.
