### ISSUE TITLE
Code related to issue 808 has not been incorporated 

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#982]
The issue is that the code which fixed the issue #808 has not been incorporated to version 2.0

To reproduce the issue follow the comment Hakju made on Apr 21
 1. Create BIE with 'Purchase Order Header. Purchase Order Header'.
 2. Expand the tree.
 3. Click any BCCP whose representation term is Date Time

**Comment by hakjuoh** [comment]
@asdimitriadis 
<img width="1172" alt="Screen Shot 2020-10-13 at 12 45 58 PM" src="https://user-images.githubusercontent.com/16102116/95890741-25f19200-0d52-11eb-9f78-342437d342ad.png">
<img width="1137" alt="Screen Shot 2020-10-13 at 12 46 29 PM" src="https://user-images.githubusercontent.com/16102116/95890747-28ec8280-0d52-11eb-8dca-3d72ca14e909.png">

**Comment by asdimitriadis** [comment]
Tested. It works good.
