### ISSUE TITLE
When revise a developer code list the Version field should be defaulted to the previous revision value + "_New"

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#984]

**Comment by hakjuoh** [comment]
@kbserm This potentially causes an exceeding length problem because `version_id` column has defined 10-byte varchar. For example, the first revised CL has '1_New' and second one has '1_New_New', so on. For now, we change it to 100-byte, but it's not ultimate solution for this.

**Comment by kbserm** [comment]
I'm not sure if the value get inserted into the DB right away after creation is invoked. Is there a guard condition b/f exceeding 100 byte? E.g., when that is going to happen, replace the whole thing with 'New'.

**Comment by kbserm** [comment]
We decided to just rely on the uniqueness validation.
