### ISSUE TITLE
Process Item Master and BOM Reuse Issue

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#985]
We are seeing a error expressing a published process item master and bom BIEs.  In this case we have a BOM and Item Master Reuse BIE, when the reuse BIEs are enabled inside of the Process Item Master or Process BOM the following error occurs:

Server Internal Error: Http failure response for https://.../api/profile_bie/generate?data=dG9wTGV2ZWxBc2JpZXBJZHM9NTkmYmllRGVmaW5pdGlvbj10cnVlJmV4cHJlc3Npb25PcHRpb249WE1MJnBhY2thZ2VPcHRpb249QUxMJm9wZW5BUElFeHByZXNzaW9uRm9ybWF0PVlBTUw=: 500 OK 

We are still able to export the Item Master or BOM Reuse BIEs individually that are being used inside of the Process Item Master and Process BOM.  In addition, other reuse BIEs are working inside of the Process BOM or Process Item Master, when the Item Master or BOM Reuse BIE is not enabled.  This error is occurring in 1.6 and 1.7.

**Comment by kbserm** [comment]
This seems to occur when there is a nested reuse. @smorgan19 Could you check whether there is nested reuse in Process Item Master and Process BOM, e.g., the reused BOM reuses another BIE inside.

**Comment by smorgan19** [comment]
In both cases there is another reused bie inside the BOM and Item Master.  In the case of the BOM its BOM Item Data, which is reused twice and in Item Masters its Location Item Master

**Comment by hakjuoh** [comment]
@asdimitriadis You can reproduce this issue by the following steps,

1. Create 'BOM Item Data' BIE. Make some changes and publish it.
2. Create 'BOM' BIE. Expand the tree and reuse 'BOM Item Data' using the published BIE in the step 1. Make some changes and publish it.
3. Create 'Get BOM' BIE. Expand the tree and reuse 'BOM' using the published BIE in the step 2. At this point, you'll see the nested reuse BIEs case like this.

<img width="371" alt="Screen Shot 2020-10-16 at 10 18 25 AM" src="https://user-images.githubusercontent.com/16102116/96270009-16b05580-0f99-11eb-836a-fcb13a84a96b.png">

4. Check the XML/JSON Schema expression.

**Comment by asdimitriadis** [comment]
It works good. Tested.
