### ISSUE TITLE
Cannot change property term of a used BCCP

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#987]
The issue is that we cannot change the property term of a BCCP is it is used by an ACC

To reproduce the issue:
1. Create a BCCP
2. Create an ACC
3. Insert/append the BCCP to the ACC
4. Open the BCCP and try to change its property term field.
An error is returned.

**Comment by hakjuoh** [comment]
@asdimitriadis Please try it again. It's fixed.

**Comment by asdimitriadis** [comment]
It works good. Tested.
