### ISSUE TITLE
Create Open Document Format expression capabilities to handle large volumes of data in Comma Separated Value (CSV) format as well as supporting needs of Small, Medium-sized Enterprises

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#992]
Express the Property Term BCCP and associated supplemental component names in sequence by their hierarchy, from left to right as the first row, so names can be imported / exported by Low Code tools, PowerApps, systems used by Small and Medium-sized business, middleware tools, MS Access, and other technologies.

The OASIS Open Document Format (ODF), specifically the .ods extension, should be our target expression.  The first sheet would contain a 'template' for the intended CSV, and the second sheet would provide the 'specification' for the first sheet.  

The first sheet 'template' first row would contain human understandable column names.  Ideally, the column names would qualify the Property Term names by parent Property Term(s) if /as required, _until each property has a unique name expressed_.  This would avoid collisions when generic Property Terms such as 'Name' or 'Description' are included in the BIE.

The second sheet 'specification' would provide guidance to implementers and include:
- the full paths to the bccp and related supplemental components (as those relate to actual cell in the first sheet, and instances would hold actual values),
- the context definition entered by the user in Score for the bccp or supplemental component,
- data types targeted to ODF specifications, and,
- example data entered by the user in Score for each bccp and supplemental component.

**Comment by dubnemo** [comment]
I would suggest this take priority over Protobuf expression capabilities, as this is a more common file format.

**Comment by kbserm** [comment]
is there a schema for this or u r just talking about the example instance.

**Comment by dubnemo** [comment]
Here are the schemas for ODF 1.3:
[OpenDocument-v1.3-cs01.zip](https://github.com/OAGi/Score/files/7137540/OpenDocument-v1.3-cs01.zip)

**Comment by dubnemo** [comment]
Example XML file ODS format.
All style information has been removed, stripped down to MVP.

[ScoreODSExpressionExample.fods](https://github.com/OAGi/Score/files/7156594/ScoreODSExpressionExample.fods)

**Comment by dubnemo** [comment]
[ScoreODSExpressionExample.ods](https://github.com/OAGi/Score/files/7180778/ScoreODSExpressionExample.ods)

**Comment by dubnemo** [comment]
The ods file is clearly a zip file, and the contents in the content.xml which is the OASIS office:document/office:body/office:spreadsheet document.

![image](https://user-images.githubusercontent.com/32434235/133682040-726c74aa-a79a-486b-ad35-e321a57ba812.png)

**Comment by hakjuoh** [comment]
@dubnemo @kbserm 
To generate unique column names, I wrote the following logic (pseudo C-like code used):
```
struct Row {
    columnName: string,
    fullPath: string,
    ...
}

void fillColumnNames(rows: Row[], depth: int = 1) {
    rowMap: Map<string, Row[]>;
    forEach (const row of rows) {
        string[] paths = split(row.fullPath, '.');
        // truncate paths with number of parts by given 'depth' from the last part.
        string[] subPaths = sub_list(paths, beginIdx = (paths.length - depth), endIdx = paths.length);
        row.columnName = join(subPaths, '.');
        rowMap.put(row.columnName, ...row);
    }
    forEach (rowEntry of rowMap) {
        if (rowEntry.value.length > 1) { // found duplicate
            fillColumnNames(rowEntry.value, depth + 1); // recursive call with depth + 1
        }
    }
}
```

Here's a sample MoveInventory CSV, and a screenshot.
[MoveInventory.csv](https://github.com/OAGi/Score/files/9096091/MoveInventory.csv)

<img width="1052" alt="Screen Shot 2022-07-12 at 3 08 40 PM" src="https://user-images.githubusercontent.com/16102116/178574765-dfeb3034-842c-4eea-979b-ecb9852d39a1.png">

We could change CSV to ODF later.

**Comment by dubnemo** [comment]
Yes, that would be the definition sheet, second sheet in the ODF that
describes the columns in the first sheet that gets used by most import
'wizards'.
Great progress!

**Comment by kbserm** [comment]
@hakjuoh @dubnemo 

I am going to have to request @dubnemo to verify this.  @hakjuoh please work with @dubnemo directly on this. 

@dubnemo I think there should be a specification document from OAGi SME WG that clearly specifies this serialization.

@hakjuoh I think this should be move to another milestone, given that we want to finish this milestone with the opensource documentation.

**Comment by dubnemo** [comment]
Pivot from rows to columns.  Then tools that First row as Header will work with this:
![image](https://user-images.githubusercontent.com/32434235/179089100-91a30906-8fda-43cf-b45e-dcfbdc5d2632.png)

**Comment by hakjuoh** [comment]
@dubnemo Please review this again. Pivoting applied.
[MoveInventory.fods.zip](https://github.com/OAGi/Score/files/9116009/MoveInventory.fods.zip)

**Comment by dubnemo** [comment]
> @dubnemo Please review this again. Pivoting applied. [MoveInventory.fods.zip](https://github.com/OAGi/Score/files/9116009/MoveInventory.fods.zip)

@hakjuoh - perfect!  Is there a reason it is in a zip file now?  Less is more. ;-)

**Comment by dubnemo** [comment]
@kbserm lets remove the CSV topic from the Aug agenda.

**Comment by hakjuoh** [comment]
> @hakjuoh - perfect! Is there a reason it is in a zip file now? Less is more. ;-)

I don't know exact reason, but it doesn't support to upload this type of files on my browser, even though the github says it has supported. :(

**Comment by dubnemo** [comment]
@hakjuoh Got it!!  It was only to upload to GitHub, whereas Score would output in .fods.  

Getting back to the Expression page, can you label from CSV to "Open Document Spreadsheet (supports CSV)".   We can add a usage note in the Help that states 

"The Open Document Format is an OASIS standard that includes the representation of a spreadsheet.  The first sheet in the FODS file, when opened in Microsoft Excel, OpenOffice or Libre' Office, is the template that business users can provide to Small, Medium-sized Enterprises whose software applications support importing comma-separated-value (CSV) files or spreadsheets, where the first row is the header. describing the column names.   These utilities often allowing storing the template for processing of CSV files in on a regular basis.   The second sheet of the FODS file provides the specification of the header definitions, including the context definition and example data entered into Score."

**Comment by dubnemo** [comment]
@kbserm @hakjuoh 
FYI we have a use case that can be implemented ASAP for AgLeader SMS for our AgGateway WG01 In-Field Product Identification project.  SMS would import shipping information sent by Retailers using `application/csv `media type, even though the Retailer sent the shipping information in JSON using the Shipped Item Instance BIE in oagiscore.net. 

This is a landmark deliverable.

**Comment by dubnemo** [comment]
@hakjuoh  is this in test.oagiscore.net.  I have few examples where the BIE has the same component enable (reused) at different levels (e.g., Catalog with registrationStatus under item.substance and item.itemTreatment.substance

**Comment by hakjuoh** [comment]
> @hakjuoh is this in test.oagiscore.net? I have few examples where the BIE has the same component enabled (reused in fact) at different levels (e.g., Catalog with registrationStatus under item.substance and item.itemTreatment.substance).

Yes, and it looks like below for now.

<img width="830" alt="Screen Shot 2022-07-17 at 11 21 33 AM" src="https://user-images.githubusercontent.com/16102116/179405101-067dc3db-254a-4464-b2ef-34758d5125ae.png">

**Comment by dubnemo** [comment]
@hakjuoh @kbserm I do see the use case where the Example data is mapped to the second row of the template.  This serves as a test record for anyone configuring the import or export utilities, proving their configurations were successful.  Great time saver.  
Our example data often would provide clear identification for deletion of the test record after configuration.  

What do you think?

**Comment by dubnemo** [comment]
@hakjuoh Please remove 'Flat XML' as minimum.  People don't need to know that ODF is specified in XML.  TMI.  
I do recommend that there a parenthetical reference to CSV though, as most utilities have CSV in their names.
Options:
(for CSV)
(enabling CSV)
(supports CSV)

More user friendly and adapting to current practices.

**Comment by dubnemo** [comment]
@kbserm @hakjuoh one catch I just found.
We only should be expressing the BCCPs only, as per the original description.
The yellow highlighted columns should NOT have been generated.

![image](https://user-images.githubusercontent.com/32434235/181105409-d1ba282a-5c0b-46dd-af0d-988c6f16946a.png)

**Comment by hakjuoh** [comment]
@dubnemo Now, it's expressing only BBIEs and BBIE_SCs.

<img width="1175" alt="Screen Shot 2022-07-26 at 10 26 53 PM" src="https://user-images.githubusercontent.com/16102116/181147357-4aee4d2b-6408-4606-b2cd-0ccd7bb16e0a.png">

**Comment by dubnemo** [comment]
@hakjuoh Exactly.  
@kbserm 
For a spreadsheet, MaxCardinality will be valuable for the user role when creating the BIE, as a CSV expression needs to be 'flat' with all MaxCardinality = 1.
@joshklm expressed interest in this too yesterday.

**Comment by dubnemo** [comment]
@kbserm @hakjuoh @jim-wilson-kt 
Discussion at Land O'Lakes revolved around that Excel does not open the FODS file directly, however ODS binary is supported.

Pro/ Cons
| Approach | Pro | Con |
| :---        |    :----   |  : --- |
| Find library in LibreOffice that converts to ODS | Takes advantage of work to day, Leverages OASIS standard | still requires export to CSV   |
| Export to Excel xlsx file instead | Takes advantage of Excel as defacto standard |  still requires export to CSV, lost work to date  |
| Export to CSV and Specification. PDF files | No additional step to get to CSV, retains specification detail |  lost work to date    |

**Comment by dubnemo** [comment]
Since there is a --convert-to command line option, with ODS as an option for the output file, there is likely a SDK for this.
https://help.libreoffice.org/latest/he/text/shared/guide/convertfilters.html

ODF Spreadsheet | "calc8" | application/vnd.oasis.opendocument.spreadsheet (ods)
-- | -- | --

**Comment by hakjuoh** [comment]
@dubnemo I added a format option for 'ODS' and 'XLSX'.

<img width="372" alt="Screen Shot 2022-08-16 at 5 18 55 PM" src="https://user-images.githubusercontent.com/16102116/184987289-eb2cffd8-314b-4249-9c19-1dae55366026.png">

See generated files in [MoveInventory.zip](https://github.com/OAGi/Score/files/9354765/MoveInventory.zip).

**Comment by dubnemo** [comment]
@hakjuoh Excellent!  Was there a jar that you were able to use from LibreOffice?
