### ISSUE TITLE
Beta.oagiscore.net - when a component change is 'undone' status is not recognized as its previous state of Published

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#994]
In OAGIS repo, see https://github.com/OAGi/oagis/issues/164

Version Identifier was added to Catalog Header Base. Details, then removed after realizing that Revision Identifier already existed on Document Identification Base. Details.
The component is back to its original structure, sitting in Candidate state.
Similar to BIE behavior, I would have expected the component to be back in its original published state.

I am not sure if I put it in WIP Status prior to removing it.

**Comment by kbserm** [comment]
@dubnemo you need to put it back to WIP status and Cancel revision. Then it will go back to Published state with the previous Rev. number.

**Comment by dubnemo** [comment]
@kbserm perfect.  Closing.
