### ISSUE TITLE
Context Scheme creation leads to duplicate Context Category

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#995]
The issue is that when I create a Context Scheme, the selected Context Category of the Context Scheme is created again leading to duplicate context categories.

To reproduce the issue:
1. Create a Context Category (lets use the name ConCategory1)
2. Open the Context Category List page. You can see the ConCategory1listed.
2. Create a Context Scheme using the ConCategory1
3. Open the Context Category List page. Now, you can see the ConCategory1 listed two times.

**Comment by rekuku** [comment]
According to 4.6.1 of the Design document,

Warning dialog when another ContextScheme with same Scheme ID, Agency ID but different Name, Version exists.
![Screen Shot 2020-10-21 at 11 48 23 AM](https://user-images.githubusercontent.com/10194354/96744734-5c06c580-1393-11eb-971c-239b46c9a91b.png)

Error dialog when another ContextScheme with Same Scheme ID, Agency ID, Version exists.
![Screen Shot 2020-10-21 at 11 48 11 AM](https://user-images.githubusercontent.com/10194354/96744739-5d37f280-1393-11eb-9a26-c612da98029d.png)


Please check this @asdimitriadis

**Comment by rekuku** [comment]
@asdimitriadis 
I misunderstood.
The Context Category has been modified so that it does not appear as duplicates.

**Comment by asdimitriadis** [comment]
It is fixed. Tested.
