### ISSUE TITLE
Browser displayed cached data after cancel revision

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#997]
After cancel revision of an ACC, the browser still display the ACC with the same info. The user has to refresh the browser.

**Comment by asdimitriadis** [comment]
Yes indeed. The issue exists in Score 2.0
When we revise a CC and click to Cancel the revision, then the browser still displays the cached data.
However, if we refresh the page using the browsers button, we can see the expected values in the fields of the CC.

**Comment by asdimitriadis** [comment]
Actually, I noticed that the issue happens only when you cancel the revision of an ASCCP or BCCP. Not in ACCs.

**Comment by dubnemo** [comment]
@kbserm @asdimitriadis  I would close the other #996 bug then.

**Comment by rekuku** [comment]
Add code to clear cache after Cancel action.
@asdimitriadis please test this.

**Comment by asdimitriadis** [comment]
It works fine now.
