### ISSUE TITLE
search by business context on BIE view/edit page shows only one result

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#998]
The user has to click on show 50 per page for all the results to show.

**Comment by asdimitriadis** [comment]
In the Score 2.0, I could not reproduce the issue.

**Comment by dubnemo** [comment]
@asdimitriadis @kbserm 
It exists on oagiscore.net.  It only searches the current scoped paginated collection that is displayed.  

Go to view BIE, search 'Express Pack' business context.

**Comment by kbserm** [comment]
This seems to be 1.x issue and we won't go back and fix it.
