### ISSUE TITLE
The version of the revised code list should include "_New".

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#999]
The issue is that when a developer revises a code list, the version field remains the same and does not change to include the value "_New" after the previous one.

To reproduce the issue:
1. Login as a developer
2. Open the code list oacl_ProcessConfirmationCode
3. Click "Revise" button

At this point the Version remains "1". It should be changed to "1_New" according to TC.

**Comment by asdimitriadis** [comment]
Also, when an end user amends a Code List the Version field should be set to "pre-amendment + “_New”"

**Comment by hakjuoh** [comment]
@asdimitriadis @kbserm As we talked earlier, this approach has a drawback due to the length of `version` column. The test document may need to be updated.

**Comment by kbserm** [comment]
@asdimitriadis I think you can remove that requirement. The uniqueness constraint will take care of that anyway.

**Comment by hakjuoh** [comment]
This issue related with #984, so we would handle this in 2.x.

**Comment by kbserm** [comment]
@asdimitriadis could you change the TA to not require this and then just close this issue.

**Comment by asdimitriadis** [comment]
Changed. There is no such requirement anymore. 
I am closing the issue.
